.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/question.md, .github/SUPPORT.md, index.html, package.json
Replace instances of `Carbon Design System` with `IBM.com Library`
**Changed**
- Change `Carbon Design System` to `IBM.com Library`
- Update repository path `IBM/carbon-addons-dotcom` → `carbon-design-system/dotcom-library`
=> chore(docs): update copy for IBM.com Library

packages/react/.gitignore, packages/react/.storybook/.babelrc.js, packages/react/babel.config.js, packages/react/jest.config.js, packages/react/package.json, packages/services/.env.example, packages/services/.gitignore, packages/services/babel.config.js, packages/services/config/jest/setup.js, packages/services/jest.config.js, packages/services/package.json, packages/services/src/index.js, packages/services/src/services/MarketingSearch/MarketingSearch.js, packages/services/src/services/MarketingSearch/__tests__/MarketingSearch.test.js, packages/services/src/services/MarketingSearch/__tests__/data/response.json, packages/services/src/services/MarketingSearch/index.js, packages/services/src/services/SearchTypeahead/SearchTypeahead.js, packages/services/src/services/SearchTypeahead/__tests__/SearchTypeahead.test.js, packages/services/src/services/SearchTypeahead/__tests__/data/response.json, packages/services/src/services/SearchTypeahead/index.js, packages/utilities/.gitignore, packages/utilities/babel.config.js, packages/utilities/jest.config.js, packages/utilities/package.json
Closes #
https://github.ibm.com/webstandards/digital-design/issues/779
This adds the initial search classes for typeahead search. These have been separated out into two classes, as the marketing and regular searches are two completely different endpoints and are treated as such. The host and versions have been set as environment variables, which we will need to set up in CircleCI.
Will need to set up a separate utility class for getting locale/country.
Coverage Report:
JSDoc available in Netlify preview:
https://deploy-preview-39--ibmdotcom-services.netlify.com
**New**
- SearchTypeaheadAPI
- MarketingSearchAPI
=> feat(search): adding initial search services

packages/eslint-config-ibmdotcom/CHANGELOG.md, packages/eslint-config-ibmdotcom/package.json, packages/react/CHANGELOG.md, packages/react/package.json, packages/services/CHANGELOG.md, packages/services/package.json, packages/stylelint-config-elements/CHANGELOG.md, packages/stylelint-config-elements/package.json, packages/styles/CHANGELOG.md, packages/styles/package.json, packages/utilities/CHANGELOG.md, packages/utilities/package.json
Bump minor version from `v0.2.0-RC.0` to `v0.2.0`
**Changed**
- `eslint-config-ibmdotcom`, `react`, `services`, and `styles` packages bumped from `v0.2.0-RC.0` to `v0.2.0` (kennylam@0c749eada394b25d773855d94180542112f779d2)
=> chore(release): bump from RC to release version

docs/stable-selectors.md
https://github.ibm.com/webstandards/digital-design/issues/1242
This adds in documentation on how to implement stable selectors to the
components and patterns being created in the IBM.com Library. With this,
we can remove the documentation from Box as well as share this out to
adopters.
**New**
- Documentation on stable selectors
=> docs(stableselectors): adding documentation on stable selectors

packages/eslint-config-ibmdotcom/index.js
By default the eslint configurations are on for AirBNB:
- [react/prefer-es6-class](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/prefer-es6-class.md)
- [react/prefer-stateless-function](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/prefer-stateless-function.md)
This is described in the following documentation:
https://github.com/airbnb/javascript/tree/master/react#class-vs-reactcreateclass-vs-stateless
Essentially, if a component is not managing internal state, lifecycles, or refs, it should be created as stateless for performance.
**Changed**
- Added additional react eslint checks
=> fix(eslint): adding additional eslint checks for react components

packages/patterns-react/docs/feature-flags.md, packages/react/docs/feature-flags.md, packages/react/src/components/Footer/LocaleButton.js, packages/utilities/src/utilities/featureflag/__tests__/featureflag.test.js, packages/utilities/src/utilities/featureflag/featureflag.js, packages/utilities/src/utilities/featureflag/index.js
https://github.com/carbon-design-system/ibm-dotcom-library/pull/75#discussion_r323477375
This pull request cherry-picked one or two commits from #75 so we can deploy it to alpha faster for further testing, and leveraging. It basically adds a feature flag utility that determines if a feature flag is turned on and decides to render the jsx or not.
**New**
- feature flag utility
=> Feature Flag Utility

packages/styles/scss/components/accordion/_accordion-expressive.scss, packages/styles/scss/components/footer/index.scss, packages/styles/scss/components/link/_link-expressive.scss, packages/styles/scss/components/masthead/_masthead-l1.scss, packages/styles/scss/components/masthead/_masthead.scss, packages/styles/scss/globals/_imports.scss, packages/styles/scss/globals/_vars.scss
#89 
CSS vendor imports are failing with the `includePath (~)` missing.
**Changed**
- add `~` for all css vendor imports [[5ee25ed](https://github.com/carbon-design-system/ibm-dotcom-library/commit/5ee25edc9d0f7dc59a987ef96795fed3cc8b832c)]
=> chore(fix): fix css loaders; fixes #89

packages/services/package.json
https://github.com/carbon-design-system/ibm-dotcom-library/issues/92
This switches `axios` from a devDependency to an actual dependency.
**Changed**
- Changed `axios` dependency in package.json
=> fix(services): added axios as a dependency

packages/react/src/components/Footer/README.md, packages/react/src/components/Masthead/README.md
No related tickets
I added quick documentation on setting up a CORS proxy for the components that will need it in order to function properly. 
**Changed**
- Masthead/footer README files
=> docs(cors): adding cors proxy documentation for the masthead/footer

packages/react/src/components/index.js
#94 
`DotcomShell` not being imported. This fixes that.
**New**
- `DotcomShell` exported
=> fix(react): exports DotcomShell

packages/react/.storybook/manager-head.html
https://github.ibm.com/webstandards/digital-design/issues/1131
This adds the global analytics tag for IBM to Storybook.
**New**
- Analytics script for Storybook
=> feat(analytics): adding base IBM analytics tag to storybook

.lintstagedrc, jest.config.js, tasks/jest/setupafter.js
[lint-stage "yarn test" failing even though running manually passes #1701](https://github.ibm.com/webstandards/digital-design/issues/1701)
filter out any `act()` errors to unblock the `yarn test` script in pre-commit hook 
**New**
- add jest setup file for after `setupFilesAfterEnv`
=> fix(jest): silence act errors from testing to unblock pre-commit hook

.lintstagedrc, packages/patterns-react/src/patterns/LeadSpace/LeadSpace.js, packages/react/jest.config.js, packages/react/src/components/Footer/FooterNav.js, packages/react/src/components/Footer/FooterNavGroup.js, packages/react/src/components/Footer/LegalNav.js, packages/react/src/components/Footer/__tests__/Footer.test.js, packages/react/src/components/Footer/__tests__/LegalNav.test.js, packages/react/src/components/Masthead/MastheadL1.js, packages/react/src/components/Masthead/MastheadLeftNav.js, packages/react/src/components/Masthead/MastheadProfile.js, packages/react/src/components/Masthead/MastheadSearchSuggestion.js, packages/react/src/components/Masthead/MastheadTopNav.js, packages/react/src/components/__tests__/__snapshots__/storyshots.test.js.snap
This fixes a number of jest test issues. With most of them, the footer nav links did not account for the additional placeholder element for the truste module so incremented it by 1.
The other thing is to remove the required PropTypes for the various footer components. I felt it wasn't necessary since the component itself already renders null if no items are passed in, and the shape of the props are already covered and should throw console logs accordingly.
**Changed**
- Jest fixes for the footer
=> fix(jest): multiple jest fixes for the footer

.lintstagedrc, packages/react/.env.example, packages/react/.storybook/manager-head.html, packages/react/.storybook/preview-head.html, packages/react/src/components/DotcomShell/DotcomShell.js, packages/react/src/components/Masthead/Masthead.js, packages/react/src/global.js, packages/services/.env.example, packages/services/src/services/Analytics/Analytics.js, packages/services/src/services/Analytics/index.js
[Analytics: Add event triggers for scroll tracking #1602](https://github.ibm.com/webstandards/digital-design/issues/1602)
- Add event trigger for scrolling. Fires every 400px interval (only at the deepest scroll depth - does not fire if user scrolls back up)
**New**
- add scroll event listener
- add `RegisterAnalyticsEvent` in `services` package
**Changed**
- move analytics script to the `preview-head.html` file so that the `ibmStats` object is exposed to the iframe
=> feat(analytics): scroll tracking

packages/react/src/components/DotcomShell/DotcomShell.js
No related tickets
This is a minor fix that changes the DotcomShell imports of the Masthead and Footer to be relative imports instead of the published components.
**Changed**
- DotcomShell imports
=> fix(shell): fixed dotcom shell imports

packages/styles/scss/components/accordion/_accordion-expressive.scss, packages/styles/scss/components/footer/_footer-nav.scss
closes #170 
This pull request is simple and adds an `overflow: hidden` to the accordion. It's needed because the accordion items currently aren't hidden and so there is empty space added after the footer, and is noticeable when it's near the bottom of the page where page content doesn't create enough height for it to hide.
**New**
- accordion overflow hidden
**Removed**
- Removed default css multi-column gutter missed originally
=> fix(footer): added overflow:hidden to accordion

.github/stale.yml
No related tickets
This updates the stalebot config to 30 days instead of 15 days.
**Changed**
- Updated stale.yml file
=> Updating stalebot config to 30 days

packages/react/src/components/Masthead/__tests__/MastheadSearch.test.js
This fixes MastheadSearch.test.js failing due to outdated prefix.
**Changed**
- change Carbon `prefix` to Dotcom's `stablePrefix`
=> fix(jest): fixes stable selector prefix

README.md, packages/patterns-react/src/patterns/LeadSpace/__stories__/LeadSpace.stories.js, packages/react/src/components/CardLink/__stories__/Card.stories.js
This is a quick PR to hide experimental features from the production storybook output. There were a couple of features behind feature flags that were rendering blank storybook stories. This adds the feature flag around the story itself to only render if the flag is set to true.
I also added the entry for vanilla package in the base README.
**Changed**
- Added feature flags around experimental storybook stories
- Updates to main README
=> fix(featureflag): hiding experimental stories from production

packages/react/src/components/index.js, packages/styles/scss/components/link-with-icon/_link-with-icon.scss
This pull request quickly fixes a bug with the `LinkWithIcon` component.
**New**
- exporting `LinkWithIcon`
**Changed**
- fills to `currentColor`
**Removed**
- removed unecessary fills
=> Fix link with icon

packages/styles/scss/components/masthead/_masthead-search.scss
fixes: #588 
fixes: #135
This pull request adds the highlighting to the search suggestion as you key down and up arrows on your keyboard.
**New**
- Added `.bx--container-highlight-class` to adopt focus state
=> Search dropdown highlight fix

packages/react/src/components/Masthead/MastheadSearchSuggestion.js
#589 
This adds in a visual space for the typeahead suggestion item, as there were no spaces getting added with the way the content was currently structured.
**Changed**
- Masthead search suggestion item visual fix
=> fix(masthead): adds space for suggestion item

packages/react/.env.example, packages/react/src/components/Masthead/Masthead.js, packages/react/src/components/Masthead/MastheadSearch.js, packages/react/src/components/Masthead/MastheadSearchInput.js, packages/react/src/components/Masthead/README.md, packages/react/src/components/Masthead/__stories__/Masthead.stories.js, packages/react/src/internal/FeatureFlags.js, packages/services/src/services/Locale/Locale.js
#587, #593 
This addresses a few items in the Masthead:
- Pressing enter should trigger a search in the search field
- Clicking the search icon will trigger a search if the search bar is open
- Added the prop `searchOpenOnload` that will open the search field by default
- Added environment variable `SEARCH_REDIRECT_ENDPOINT` for changing the search redirect url if needed
- Added `MASTHEAD_L1` feature flag
**New**
- `MASTHEAD_L1` feature flag
- `SEARCH_REDIRECT_ENDPOINT` environment variable
**Changed**
- Fixes for the masthead search
- Hiding Masthead L1 behind a feature flag
- Option to open search on load
=> feat(masthead): flag to open masthead search by default, multiple fixes

packages/react/src/components/Masthead/MastheadSearch.js, packages/react/src/components/Masthead/MastheadSearchInput.js
Fixes: #597 
This is a fix for the search field not closing. The overall fix was to get rid of `useState` and just use `useReducer` for all of the interactions.
**Changed**
- Fixed handling of states in the Masthead search
=> fix(masthead): fix to search input not closing

packages/react/src/components/Masthead/MastheadSearch.js
Fixes #607 
This quick-fix prevents the search input field from being closed when you navigate away from the input field if it's been opened by default.
**Changed**
- Check for `!searchOpenOnload` before closing on blur
=> fix(react): open by default blur shouldnt close search

packages/react/src/components/Masthead/MastheadSearch.js
fixes #620 
We're setting some values outside of the component's function. In storybook, in particular, this is causing problems especially when we use the object. Once the open by default is set as the initial state it's defined for all the stories. Almost like setting it in a global scope.
**Changed**
- moved `_initialstate` into component
=> fix(react): moved initial state inside component func

packages/react/src/components/Masthead/MastheadSearchInput.js, packages/react/src/components/__tests__/__snapshots__/storyshots.test.js.snap, packages/styles/scss/components/masthead/_masthead-search.scss, packages/styles/scss/components/masthead/_masthead.scss
fixes #627
This pull request removes invisible items from the tabbing order, applies focus onto the search button after it's closed, and removes the default outline from the logo.
**New**
- Focuses search button after the search is closed
**Removed**
- Removed search input and search close button from tabbing index
- Removed default browser outline from IBM logo on focus
=> Fix masthead tabbing and focus

packages/react/src/components/Masthead/MastheadSearch.js, packages/services/src/services/Locale/Locale.js
[Carbon footer is not using lang from html to localize footer links and labels #632](https://github.com/carbon-design-system/ibm-dotcom-library/issues/632)
Return the `lang` object when detected from the html `lang` attr so that it can be used for the network call.
You can easily test by setting the `lang` html attribute for the iframe in storybook like so
Toggle between components and then switch back to `DotcomShell` or `Masthead` or `Footer` and you will see the components will be translated according to the `lang` attr.
**Note** For some languages like mexico spanish (es-MX) the masthead will break - that is a separate issue that we have a ticket for ([Masthead (and DotcomShell) briefly renders and disappears #634](https://github.com/carbon-design-system/ibm-dotcom-library/issues/634)) …
=> fix(translation): set footer and masthead pull from html lang attr

packages/react/src/components/Masthead/MastheadSearch.js
[Carbon footer is not using lang from html to localize footer links and labels #632](https://github.com/carbon-design-system/ibm-dotcom-library/issues/632)
Set the values in the correct state keys (`cc` & `lc`)
otherwise user will first see the lc/cc populate the input when they open the search bar
**Changed**
- set corresponding state keys in reducer instead of using the `val` key
=> fix(search-input): set correct key in masthead search reducer

packages/react/src/components/Masthead/Masthead.js, packages/react/src/components/Masthead/README.md, packages/react/src/components/Masthead/__stories__/Masthead.stories.js
#631 
Exposes prop for Search placeholder value. In the future we can get this value from localized json.
**New**
- `<Masthead />` now accepts `placeHolderText` prop to change value of search input.
**Changed**
- update `Masthead` story and README
=> feat(search): expose search placeholder prop

packages/services/src/services/Locale/Locale.js, packages/services/src/services/Locale/__tests__/Locale.test.js, packages/services/src/services/SearchTypeahead/SearchTypeahead.js
This is a quick fix to dynamically set the lc/cc combination for the search typeahead service.
**Changed**
- Set lc/cc from LocaleAPI.getLang in SearchTypeaheadAPI
=> fix(typeahead): dynamically set lc/cc from getLang for search typeahead

.prettierignore, packages/react/src/components/Layout/Layout.js, packages/react/src/components/Layout/__stories__/Layout.stories.js, packages/react/src/components/Masthead/MastheadL1.js
This is a bug that was picked up while working through the TableofContents component. The sticky column was not remaining sticky in mobile views.
**Changed**
- Added sticky modifier class for parent div for mobile breakpoints
- Fixed lint issues with MastheadL1
- Fixed prettierignore to ignore the examples folder
=> fix(layout): properly set mobile columns to be sticky if set

packages/styles/scss/components/masthead/_masthead.scss
#719 
This addresses incorrect masthead width, as well as IBM logo padding for various breakpoints.
**Changed**
- `Masthead` width increased
- IBM logo now correctly left-aligns with content in all breakpoints
=> fix masthead/logo responsive css

packages/styles/scss/patterns/leadspace/_leadspace.scss
Forgot to set background color to transparent in the `themed-items` mixin
AFTER:
**Changed**
- set background-color to transparent when setting gradient color
**Removed**
- remove repetitive styles already in the `themed-items` mixin
=> fix(leadspace): leadspace theme modifier background color

packages/patterns-react/src/patterns/CardsWithoutImages/__stories__/CardsWithoutImages.stories.js, packages/patterns-react/src/patterns/LeadSpace/__stories__/LeadSpace.stories.js, packages/patterns-react/src/patterns/ListSection/ListSection.js, packages/patterns-react/src/patterns/ListSection/__stories__/ListSection.stories.js, packages/styles/scss/patterns/listsection/README.md, packages/styles/scss/patterns/listsection/_listsection-item.scss, packages/styles/scss/patterns/listsection/_listsection.scss, packages/styles/scss/patterns/listsection/index.scss
[[ListSection] Update styles to apply color theme as a container modifier #735](https://github.com/carbon-design-system/ibm-dotcom-library/issues/735)
Add theme modifier class to ListSection pattern
**Changed**
- pass `theme` as prop to ListSection pattern
- set `themed-items` mixin for styles that are using color tokens
=> fix(listsection): add theme modifier to ListSection pattern

packages/react/examples/create-react-app/package.json, packages/react/examples/create-react-app/yarn.lock
This addresses a security vulnerability found in `serialize-javascript`, a sub-package in `terser-webpack-plugin` within the `create-react-app` example.
Details: https://github.com/carbon-design-system/ibm-dotcom-library/network/alert/packages/react/examples/create-react-app/yarn.lock/serialize-javascript/open
**Changed**
- dependency update in CRA
=> chore(security): update for serialize-javascript for security patch

packages/patterns-react/.storybook/webpack.config.js, packages/react/.storybook/webpack.config.js
This will configure custom properties by the `carbon-expressive` flag for the storybook webpack configs for `patterns-react` and `react`.
**Changed**
- Webpack configuration changes for style feature flags
=> fix(storybook): configure custom properties from carbon expressive flag

packages/react/src/components/Footer/LocaleButton.js, packages/react/src/components/Footer/__tests__/LocaleButton.test.js, packages/react/src/internal/FeatureFlags.js, packages/utilities/src/utilities/featureflag/featureflag.js
#506, #507
This removes the feature flag from the footer to always show the locale selector CTA.
**Removed**
- Removed `DDS_FOOTER_LOCALE_BUTTON`
=> feat(footer): removal of feature flag for the locale selector in footer

packages/services/src/services/Locale/Locale.js, packages/services/src/services/Locale/__tests__/Locale.test.js
This is an additional method to get the display name of the locale/language combination based on getLang
**New**
- getLangDisplay method in LocaleAPI
=> feat(locale): method for getting the language/locale display name

README.md, docs/building-for-ibm-dotcom.md
[Add metadata and DDO content cards to the Resources page](https://github.com/carbon-design-system/carbon-for-ibm-website/issues/128)
Adding documentation regarding DDO and page meta data for building on IBM.com 
**New**
- documentation page on building for ibm.com
=> docs(authoring): adding content for building pages on ibm.com

.circleci/config.yml
#722 
This adds a scheduled cron job to kick off a nightly release of our packages to npm
**New**
- New cron job and nightly release command in circleci.yml
=> feat(circleci): adding nightly releases

packages/styles/scss/components/tableofcontents/_tableofcontents.scss
#819 
In mobile viewports there is a 1px gap above the section selector. Content is visible through this gap when scrolling.
**Removed**
- remove 1px height of empty element
=> fix(css): remove 1px space above TOC select

packages/react/src/components/ButtonGroup/__stories__/ButtonGroup.stories.js, packages/react/src/components/ButtonGroup/__stories__/index.scss, packages/react/src/components/DotcomShell/__stories__/DotcomShell.stories.js, packages/react/src/components/DotcomShell/__stories__/index.scss, packages/react/src/components/ExpressiveModal/__stories__/ExpressiveModal.stories.js, packages/react/src/components/ExpressiveModal/__stories__/index.scss, packages/react/src/components/HorizontalRule/__stories__/HorizontalRule.stories.js, packages/react/src/components/HorizontalRule/__stories__/index.scss, packages/react/src/components/Layout/__stories__/Layout.stories.js, packages/react/src/components/Layout/__stories__/index.scss, packages/react/src/components/LinkWithIcon/__stories__/LinkWithIcon.stories.js, packages/react/src/components/LinkWithIcon/__stories__/index.scss, packages/react/src/components/Masthead/__stories__/Masthead.stories.js, packages/react/src/components/Masthead/__stories__/index.scss, packages/react/src/components/TableOfContents/__stories__/TableOfContents.stories.js, packages/react/src/components/TableOfContents/__stories__/index.scss
Removes individual imports of css in Storybook in favor of a single `index.scss`. This prevents styles from being overwritten. This does not address #409 
**Changed**
- Storybook story css imports consolidated into a single `index.scss`
=> fix(css): move storybook css out of story file into local index.scss

packages/react/src/components/LocaleModal/LocaleModalCountries.js, packages/react/src/components/LocaleModal/LocaleModalRegions.js, packages/styles/scss/components/masthead/_masthead.scss
[LocaleSelector] Mobile issues for region selector view #835
[LocaleSelector] Cannot go back when in country/language selection mode #836
[LocaleSelector] Change placeholder text to "Search by location or language" #837
Change default placeholder text to "Search by location or language"
Have modal take entire height of screen on mobile and align the region divs to take entire width
**Changed**
- Change `z-index` of Masthead
- Change modal placeholder prop default search text
=> fix(locale-selector): various fixes to the locale modal

.circleci/config.yml
#722 
Publishing as alpha for some reason throws an error `E403 You cannot publish over the previously published versions`. Switching the `preid` to `nightly` should avoid this, and also should make it easier to identify what versions were nightlies.
**Changed**
- changed preid to nightly builds
=> fix(circleci): added preid for nightly builds to avoid version conflicts

packages/react/src/components/LocaleModal/LocaleModal.js, packages/react/src/components/LocaleModal/LocaleModalCountries.js, packages/react/src/components/LocaleModal/LocaleModalRegions.js
[LocaleSelector] State of search view doesn't clear after closing the modal or going back #839
Reset the search results when user closes the modal or clicks the back to region button
**Changed**
- add `clearResults` flag to determine whether to remove `${prefix}--locale-modal__locales-hidden` class and styling.
=> fix(locale-selector): reset country search results when clicking close icon or back to region button

packages/styles/scss/components/locale-modal/_locale-modal.scss
#845 
Locale modal region buttons now scrollable when viewport is too short
**Changed**
- locale modal regions now scrollable
=> fix(css): locale region buttons now scroll when cut off

.circleci/config.yml
This addresses two things:
1) Only publishes nightlies if there are changes detected
2) Only publish nightlies and canaries if an NPM_TOKEN is set in CircleCI
**Changed**
- Circleci yml updates
=> fix(circleci): fixed nightlies and ignore publish if token is not set

packages/styles/scss/components/footer/_footer-nav.scss, packages/styles/scss/components/footer/_footer.scss, packages/styles/scss/components/footer/_locale-button.scss
Footer Accordion Theme Slightly Off #876
Footer – secondary button theme is incorrect #877
import the carbon styles for accordion and button and stick them within the theme mixins
**Changed**
- add carbon accordion and button under the theme mixin
=> fix(footer): theme bugs

packages/react/examples/nextjs/package.json, packages/react/examples/nextjs/yarn.lock
This updates the dependency `serialize-javascript` to address a security issue.
**Changed**
- serialize-javascript version to 2.1.2
=> chore(security): updating serialize-javascript in nextjs example

packages/utilities/src/utilities/markdownToHtml/__tests__/markdownToHtml.js
I was getting an error pointing that the imports for this test should be sorted alphabetically, as this was keeping me from commiting my changes once I based one of my branchs I've decided to fix this.
**Changed**
- Imports sorted
=> fix(lint): imports sorted alphabetically

packages/styles/scss/patterns/leadspace/_leadspace.scss
Button width for <CardArray /> pattern too wide #921
Need to scope min-width button style to within Leadspace only as it will affect other patterns.
**Changed**
- scope min-width style
=> fix(button): scope button min width style to leadspace

packages/react/src/components/LightboxMediaViewer/LightboxMediaViewer.js, packages/react/src/components/LightboxMediaViewer/__stories__/LightboxMediaViewer.stories.js
As I was receiving linting issues after rebasing one of my branches to master, I've fixed the errors by sorting the imports for the Lightbox component.
**Changed**
- Sorted imports alphabetically
=> fix(lint): fixed alphabertic imports on lightbox

packages/styles/src/carbon-stories/ComboBox/ComboBox-story.js
ComboBox story isn't currently showing as the config file is loading stories with files ending in 
`-story.js` 
Commenting out `docgen` for now as it is causing issues with rendering the story.
**Changed**
- Renamed ComboBox story file to match what the config is expecting
- commented out `docgen` code
=> fix(expressive): rename combobox file to match config syntax

packages/utilities/src/utilities/markdownToHtml/__tests__/markdownToHtml.js, packages/utilities/src/utilities/markdownToHtml/markdownToHtml.js
Make markdown-to-html converter have markdown syntaxes parameters be opt-out instead of opt-in
**Changed**
- Make markdown-to-html utility function have default markdown syntaxes parameters as `true` and have it be manually turned of if needed by the user.
=> fix(markdown-utility): make converter be opt-out

packages/styles/scss/themes/expressive/components/_search.scss, packages/styles/scss/themes/expressive/index.scss
Expressive theme – Search #956
increase search bar icons to fit expressive theme
**Changed**
- set icons to 20x20 and increase search input bar height
=> feat(expressive): search expressive theme

README.md, packages/patterns-react/README.md, packages/patterns-react/manifest-experimental.yml, packages/patterns-react/manifest.yml, packages/react/README.md, packages/react/manifest-experimental.yml, packages/react/manifest.yml, packages/services/README.md, packages/services/manifest.yml, packages/styles/README.md, packages/styles/manifest.yml, packages/utilities/README.md, packages/utilities/manifest.yml, packages/vanilla/manifest.yml
#966 Moving master builds to IBM Cloud
This adds a number of manifest files necessary for the deployments of master branch to IBM Cloud.
**New**
- IBM Cloud manifest files 
**Changed**
- Updates to URLs from Netlify for the Cupcake website
=> feat(cloud): adding cloud foundry manifest files

packages/patterns-react/src/patterns/CardSection/CardSection.js, packages/patterns-react/src/patterns/CardSection/README.md, packages/patterns-react/src/patterns/CardSection/__stories__/CardSection.stories.js, packages/styles/scss/patterns/card-section/_card-section.scss, packages/styles/scss/patterns/logo-grid/_logo-grid.scss
Related to ticket #976
Added the grid condensed property in cardSection pattern which will help to create spacing between cards. And restructure the JSX little bit to match the CSS changes.
And also added margin in logo_grid CSS to look nicer.
**Changed**
CardSection - js and scss
logGrid - scss
=> fix(pattern): fixed gutter between cards using gridCondensed property

packages/styles/src/carbon-stories/DataTable/DataTable-story.js
Review Data table #940
`default` story for DataTable carbon component was commented out. Uncommenting and adding related README.
**Changed**
- uncommented `default` story and added associate readme
=> fix(expressive): uncomment default DataTable story

packages/patterns-react/src/patterns/FeaturedLink/__stories__/FeaturedLink.stories.js, packages/react/src/components/Image/__stories__/Image.stories.js
The `Image` component in storybook was missing the README, this fixes this.
**Changed**
- README added to `Image` storybook
=> fix(image): properly linking the Image README to storybook

packages/patterns-react/src/patterns/CardArray/__stories__/CardArray.stories.js, packages/patterns-react/src/patterns/CardSection/__stories__/CardSection.stories.js, packages/patterns-react/src/patterns/CardSection/__stories__/data/cards.json, packages/patterns-react/src/patterns/FeaturedLink/__stories__/FeaturedLink.stories.js, packages/patterns-react/src/patterns/LeadSpace/__stories__/LeadSpace.stories.js, packages/patterns-react/src/patterns/LeadSpaceCentered/__stories__/LeadSpaceCentered.stories.js, packages/patterns-react/src/patterns/ListSection/__stories__/ListSection.stories.js, packages/patterns-react/src/patterns/LogoGrid/__stories__/LogoGrid.stories.js, packages/patterns-react/src/patterns/LogoGrid/__stories__/data/logos.json, packages/patterns-react/src/patterns/PictogramArray/__stories__/PictogramArray.stories.js, packages/patterns-react/src/patterns/SimpleBenefits/__stories__/SimpleBenefits.stories.js, packages/patterns-react/src/patterns/SimpleLongForm/__stories__/SimpleLongForm.stories.js, packages/patterns-react/src/patterns/SimpleOverview/__stories__/SimpleOverview.stories.js, packages/patterns-react/src/patterns/UseCases/__stories__/UseCases.stories.js, packages/patterns-react/src/patterns/overview.js
This is a slight modification to Storybook where we can break out our stories into sections. I think it will be easier to navigate through the patterns now that we're thinking about the hierarchy of these patterns and separating them out as such in Storybook (sections vs blocks vs sub-patterns).
**Changed**
- Adding separators/sections in Patterns storybook
=> feat(storybook): breaking out sections in storybook

tasks/publish.sh
This separates out `tag-release.sh` from `publish.sh` as separate commands.
**Changed**
- Separated publishing script
=> fix(release): separating tag-release.sh from publish.sh

README.md, packages/styles/README.md
Remove Netlify from documentation as it is no longer being used.
**Changed**
- Netlify references
**Removed**
- Netlify references in documentation
=> fix(docs): remove netlify references from documentation

packages/react/src/components/LocaleModal/__stories__/LocaleModal.stories.js
move locale modal knob within story otherwise it appears as a global knob
**Changed**
-move locale modal knob within story
=> fix(storybook): move localemodal knob within story

packages/services/src/services/Locale/Locale.js
#1300 
Fixes fallback when translation response fails. 
**Changed**
- `us-en` is now always called in addition to user `cc-lc`, as opposed to only calling if user `cc-lc` fails.
=> fix(locale): fixes fallback when translation response fails; fixes #1300

packages/react/src/__tests__/__snapshots__/storyshots.test.js.snap, packages/react/src/components/LocaleModal/LocaleModalRegions.js, packages/react/src/patterns/blocks/ContentGroupCards/ContentGroupCards.js, packages/react/src/patterns/blocks/FeaturedLink/FeaturedLink.js, packages/react/src/patterns/blocks/SimpleLongForm/SimpleLongForm.js, packages/react/src/patterns/blocks/UseCases/UseCasesGroup.js, packages/react/src/patterns/sections/CardSection/CardSection.js, packages/react/src/patterns/sub-patterns/CardLink/CardLink.js, packages/react/src/patterns/sub-patterns/CardLink/README.md, packages/react/src/patterns/sub-patterns/CardLink/__stories__/Card.stories.js, packages/react/src/patterns/sub-patterns/CardLink/__tests__/CardLink.test.js
#1268
Based on the work happening in #1268 we realized we had a couple different techniques when allowing the user to pass in an icon into a component. ButtonGroup stood out initially requiring the variable to be passed in instead of a JSX component, but looking at that code Carbon was dictating this and we were just passing it through. Lookiing to simplify some of the CTA logic we thought we should unify the technique across the board. It appears `CardLink` was the only component that was out of sync, but do let me know if I missed one.
**Changed**
- Pass in icon to `CardLink` via `ArrowRight20` vs. `<ArrowRight20 />`
- Updated documentation
- Updated other components dependent on `CardLink
=> Consistent Passing of Carbon Icons

packages/styles/scss/patterns/sub-patterns/content-group/_content-group.scss
Content group – text is not fluid between breakpoints #1334
Set the content group heading to scale
**Changed**
- pass in `true` to `carbon--type-style` mixin to allow the heading to scale
between sm, med and lg breakpoints
between xl and max breakpoints
=> fix(content-group): set expressive heading to scale

packages/services/src/services/Analytics/Analytics.js, packages/services/src/services/Locale/Locale.js, packages/services/src/services/MarketingSearch/MarketingSearch.js, packages/services/src/services/Profile/Profile.js, packages/services/src/services/SearchTypeahead/SearchTypeahead.js, packages/services/src/services/Translation/Translation.js, packages/utilities/src/utilities/geolocation/geolocation.js
Issue incoming
This adds a null check for `process` in case adopters are not compiling on their end for the environment variables.
**Changed**
- additional null checks for `process`
=> fix(vanilla): adding process null check for vanilla

packages/services/src/services/Locale/Locale.js
#1347
This fixes an issue for determining locale when country has multiple languages.
**Changed**
- `getLangDisplay` correctly filters all country languages
=> fix(locale): fixes locale for multiple langs; fixes #1347

packages/react/src/patterns/sub-patterns/Card/Card.js, packages/react/src/patterns/sub-patterns/Card/__stories__/Card.stories.js
Other patterns using the Card component are breaking as they are passing `icon` as its own prop instead of within `cta` object. Quick fix for now until I look at all the func specs
**New**
**Changed**
**Removed**
=> fix(card): have icon outside of cta object

packages/styles/scss/patterns/sub-patterns/card/index.scss
#1336 
#1383 
I've changed the import order in the `Card` scss, in order to correct a bug where the outline was display thinner than intended.
**Changed**
- SCSS imports
=> fix(scss): Fixed card outline issues

packages/react/src/patterns/sub-patterns/TableOfContents/TOCMobile.js
#1381 
I've fixed the issues we had with IOS 12, replacing the instances of `intersectionObserver`. It's working properly now.
**Changed**
- Replaced `intersectionObserver`.
=> fix(pattern): scroll fixed for IOS 12 Safari

packages/react/src/patterns/blocks/FeatureCard/__stories__/FeatureCard.stories.js, packages/styles/scss/globals/utils/_hang.scss, packages/styles/scss/patterns/blocks/feature-card/_feature-card.scss
Feature card: Card Needs to Hang #1067
Set card in the `FeatureCard` component to hang into the gutters as per [design specs](https://ibm.ent.box.com/file/608050432455)
**New**
- add `hang` mixin to global utils folder
**Changed**
- set the content group title in `FeatureCard` to full width
- in `md` breakpoint and higher, have the card hang
=> fix(feature-card): set card to hang into gutters

packages/styles/scss/patterns/sections/card-section/_card-section.scss
Pattern: Card Section Simple - Card font text is not readable, while theme (g90 and g100) is changed. #1479
`Card` className for copy changed to `--card__copy` instead of `--card__content`. Updating and adding `eyebrow` class as well to ensure the text is visible in darker themes
**Changed**
- update card classes in `card-section`
=> fix(card-section): add card class to themed items in cardsection scss

packages/styles/scss/patterns/blocks/content-group-pictograms/_content-group-pictograms.scss
#1476 
I've updated the bottom padding of the `ContentGroupPictograms` pattern in order to better match with the design specs.
**Changed**
- Added bottom padding on the pattern
=> fix(scss): adjusted bottom padding of content-group-pictograms

packages/react/src/patterns/sections/CardSection/CardSection.js
Related issue: #1504 
Fixed alignment of the cards when heading is big, 
**Changed**
-  Invoking sameHeight util for eyebrow.
=> fix(alignment): added sameheight for eyebrow to fix alignment

packages/react/src/patterns/sub-patterns/TableOfContents/__stories__/TableOfContents.stories.js
`menuLabel` global variable in `TableOfContents` story is being picked up by all component stories.
This localises the variable to `TOC` story only.
**Changed**
- localise `menuLabel` variable so it is not used by all component stories.
=> fix(storybook): fix storybook var for TOC

packages/styles/scss/components/masthead/_masthead.scss
#1604 
Adds background color to full width of `Masthead` to prevent issues like this
**Changed**
- add `background-color` to `Masthead` container
=> fix(css): add white bg to masthead header

packages/react/src/patterns/blocks/ContentBlockSimple/__stories__/ContentBlockSimple.stories.js
#1516 
Adds Storybook knob to toggle the optional image in `ContentBlockSimple` to show the pattern with no image.
**Changed**
- add image toggle to `ContentBlockSimple` story
=> chore(docs): update ContentBlockSimple story; fixes #1516

packages/styles/scss/patterns/blocks/content-block-media/index.scss, packages/styles/scss/patterns/sub-patterns/content-block/_content-block.scss
#1592 
Adds missing CSS imports to `ContentBlock` and `ContentBlockMedia`
**Changed**
- add `ContentGroup` css to `ContentBlockMedia`
- add `FeatureCard` css to `ContentBlock`
=> fix(css): add missing css imports

packages/styles/scss/patterns/blocks/content-block-mixed/index.scss, packages/styles/scss/patterns/blocks/content-block-segmented/index.scss
#1608 
Adds missing CSS imports for `ContentBlockMixed` and `ContentBlockSegmented`
**Changed**
- adds missing css imports
=> fix(css): add missing pattern css imports

packages/react/src/patterns/sections/CardSection/CardSection.js, packages/react/src/patterns/sections/CardSectionImages/CardSectionImages.js, packages/react/src/patterns/sections/CardSectionSimple/CardSectionSimple.js, packages/react/src/patterns/sub-patterns/ContentSection/ContentSection.js
Card Section Simple has a generic data-autoid #1621
make autoid for card section patterns more specific.
**Changed**
- pass `autoid` prop to `CardSection` and `ContentSection` components
=> fix(autoid): make autoids more specific for card section

packages/styles/scss/patterns/sections/card-section/_card-section.scss
Card Section Simple Pattern seems to be missing CSS #1624
import the content-section styles within `card-section.scss` as the card section pattern is missing grid styles defined in `content-section.scss`
**Changed**
- import `content-section` styles
=> fix(import): import content section styles in card section

packages/styles/scss/components/masthead/_masthead.scss
https://github.com/carbon-design-system/ibm-dotcom-library/issues/1628
The table of contents was overlapping the masthead dropdown
Updated image: 
**Changed**
Z index of the masthead
=> fix(toc): fixes toc overlapping the masthead dropdown

packages/react/src/patterns/blocks/ContentGroupPictograms/README.md, packages/react/src/patterns/sub-patterns/PictogramItem/README.md
Fixed wrong property name on `PictogramItem` and `ContentGroupPictograms` docs
=> chore(docs): fixed wrong property name on documentation for pictograms

packages/react/src/patterns/sub-patterns/Card/__stories__/Card.stories.js
#1562 
The aspect ratio knobs have been removed, so we fix a bug on storybook where content would go out of the cards in certain aspects.
=> chore(story): removed aspect-ratio on card pattern storybook

packages/styles/scss/patterns/sub-patterns/link-list/_link-list.scss
#1601
I've fixed the `LinkList` hover state, so it fits the whole pattern.
=> fix(scss): hover now fits the whole width

packages/styles/scss/patterns/sub-patterns/link-list/_link-list.scss
#1667 
I've added padding for both top and bottom to the `Link-list` pattern.
**New**
- Padding added on scss
=> fix(scss): added padding for link-list

packages/styles/scss/patterns/sub-patterns/link-list/_link-list.scss, packages/styles/scss/patterns/sub-patterns/tableofcontents/_tableofcontents.scss
#1733 
I've updated the selectors for `LinkList` and `TableOfComponents` so they are more specific to the patterns.
**Changed**
- SCSS Selectors
=> fix(scss): reinforced link-list pattern styling selectors

packages/react/src/patterns/sections/CardSection/__stories__/data/cards.json, packages/styles/scss/globals/utils/_ratio-base.scss, packages/styles/scss/patterns/sections/card-section/_card-section.scss
closes #1721 
https://cognitive-app.slack.com/archives/CNEG9HNBW/p1584549707073900
Having issues where the card section image ratios aren't working properly. This pull request fixes that.
**Changed**
- shifted where the ratio was applied
- updated ratio base with a overflow hidden / fixed option.
- updated storybook with a variety of aspect ratios.
=> fix(cardsection): fixed the aspect ratio on images

packages/styles/scss/patterns/sub-patterns/layout/_layout.scss
#1725 
In order to fix an issue where the top menu of the `TableOfContents` pattern disappeared after scrolling using the menu
**New**
- transform3d added to the menu
=> fix(scss): force gpu acceleration rendering for table of contents on ios

packages/react/src/patterns/sub-patterns/TableOfContents/TOCDesktop.js
#1395 
I've reimplemented the previous focus change function.
**New**
- Focus now changes to the heading when a section is selected
=> fix(accessibility): focus now change to the content heading on toc

packages/styles/scss/components/link-with-icon/_link-with-icon.scss
https://github.com/carbon-design-system/ibm-dotcom-library/issues/1455
The link with icon component was using the wrong type size. Affecting all components using this component. Adjusted to use the correct type size
=> fix(link-with-icon): fixed type size

packages/react/src/components/LightboxMediaViewer/LightboxMediaViewer.js, packages/react/src/components/LightboxMediaViewer/__stories__/LightboxMediaViewer.stories.js, packages/react/src/components/VideoPlayer/VideoPlayer.js, packages/styles/scss/components/lightbox-media-viewer/_lightbox-media-viewer.scss
Enable the Lightbox media viewer to render the Kaltura embedded video player #1109
Render the Kaltura video player within the LightBox Media Viewer component.
**Changed**
- changed props to somewhat match what was listed in the lightbox viewer func specs (`media` prop is an `object` instead of `array` as we're not supporting carousel right now)
- render the `VideoPlayer` component when media type is video.
=> feat(video-player): embed video player within lightbox component 

packages/styles/scss/patterns/sub-patterns/tableofcontents/_tableofcontents.scss
https://app.zenhub.com/workspaces/ibmcom-library-5d449f3642eb1962336cbe52/issues/carbon-design-system/ibm-dotcom-library/1622
feature card within TOC is unreadable since its theme css is being overridden. remove hardcoded TOC css header styles so feature card styling can be done on pattern level.
```
.#{$prefix}--tableofcontents__content {
h2,
h3,
h4 {
color: $text-01;
}
}
```
=> fix(issue-1622): remove TOC header text color

packages/react/src/patterns/sections/CardSection/CardSection.js
Pattern: CardSection Images - Cards are misaligned, when the heading is large. #1867
Take `eyebrow` element into account when adjusting height for card section
**Changed**
- add `eyebrow` to `sameHeight` utility
=> fix(card-section-images): account for eyebrow in sameheight utility

packages/react/src/components/Image/Image.js, packages/react/src/components/Image/__stories__/Image.stories.js
#1868 
This change removes the `decodeString` utility from the `Image` component. The original intent of this was to override (when necessary) React's default escaping of strings, which in this case was the `src` attribute for images.
As this utility utilized the `DOMParser` API, it introduced a breaking change to server-side rendering where this API does not exist (such as our own `nextjs-test`).
Additionally since this change would only affect image source attributes with query parameters, which is rare, I don't see an immediate need for this utility. For now I will remove its usage from `Image` and possibly removing the entire utility in the future. When needed perhaps component-level `encode/decode -URIComponent` will be sufficient.
If a server-side DOM API is necessary in the future, …
=> fix(util): remove decodeString util from Image

packages/react/src/components/Masthead/Masthead.js
#1332 
This forces the profile menu position to `fixed` to prevent it from scrolling.
**New**
- use native component method `onOpen` to set profile menu position to `fixed` to prevent scrolling
=> fix(profile): stops profile menu scroll

packages/react/src/patterns/blocks/ContentGroupCards/ContentGroupCards.js
#1382 
As the last proposed fix didn't helped the screen-readers to identify the card links, after researching I've come up with this possible solution for the issue.
**Changed**
- Moved role region from `Card` to the wrapping `div`
=> fix(accessibility): added region to wrapping div of card

packages/react/src/patterns/sections/CardSection/CardSection.js
#1880 
A bug was fixed, which was happening when the `Top Level Card` was the only card on the second row
=> fix(pattern): fixed same height usage for the top-level card-link

packages/react/examples/create-react-app/package.json, packages/react/examples/create-react-app/yarn.lock
This addresses the security patch for `kind-of` in the create-react-app example.
**Changed**
- resolution for `kind-of` to be `>=6.0.3`
=> chore(security): security patch for "kind-of" in CRA example

packages/react/src/components/LightboxMediaViewer/__stories__/index.scss, packages/react/src/patterns/sub-patterns/ButtonGroup/__stories__/index.scss, packages/react/src/patterns/sub-patterns/Card/__stories__/index.scss, packages/react/src/patterns/sub-patterns/Layout/__stories__/index.scss, packages/styles/scss/components/locale-modal/_locale-modal.scss, packages/styles/scss/globals/_imports.scss, packages/styles/scss/patterns/blocks/content-group-cards/index.scss, packages/styles/scss/patterns/blocks/content-group-simple/index.scss, packages/styles/scss/patterns/sub-patterns/link-list/index.scss, packages/styles/scss/patterns/sub-patterns/pictogram-item/_pictogram-item.scss, packages/styles/scss/patterns/sub-patterns/tableofcontents/_tableofcontents.scss
This was originally an issue where the grid classes were not getting loaded for the locale modal when pulled in discretely. When discussing, it made more sense to load in the grid classes by default for the global import instead.
**Changed**
- Changed global import to include the grid classes
- removed multiple pattern/component/story level grid imports
=> fix(grid): adding grid classes by default in global import

packages/styles/scss/components/lightbox-media-viewer/_lightbox-media-viewer.scss
https://github.com/carbon-design-system/ibm-dotcom-library/issues/1985
Fixes linting error within the lightbox-media-viewer.scss file
=> fix(lightbox-media-viewer): fixed linting error

packages/styles/scss/themes/expressive/components/_tabs.scss
https://github.com/carbon-design-system/ibm-dotcom-library/issues/1356
Fixed issue where text is moving location when you select a tab. Below is how it used to look
=> fix(tabs): fixed padding for selected tabs

packages/styles/scss/components/video-player/_video-player.scss
#1971 
Added `max-width` for the description of the `VideoPlayer` component.
=> fix(scss): added max-width to video-player description

packages/react/src/patterns/sub-patterns/ContentGroup/ContentGroup.js, packages/react/src/patterns/sub-patterns/ContentGroup/README.md
#1747 #1884
Adds `data-autoid` to `ContentGroup`'s optional CTA
**New**
- `data-autoid` to `ContentGroup` CTA
=> fix(autoid): add autoid to ContentGroup CTA

packages/react/src/patterns/sections/LeadSpace/__stories__/LeadSpace.stories.js, packages/styles/scss/components/dotcom-shell/_dotcom-shell.scss
#1780 
The `Dotcom-Shell` scss was updated, so it have the default `max-width` based on the masthead, in addition to that, the `Dotcom-Shell` has been added to the `Leadspace` story.
=> fix(scss): added max-width to dotcom-shell content

packages/react/src/patterns/sub-patterns/ContentBlock/ContentBlock.js, packages/react/src/patterns/sub-patterns/ContentBlock/__stories__/ContentBlock.stories.js, packages/styles/scss/patterns/sub-patterns/content-block/_content-block.scss
Linklist is rendering too high on a pattern #1920
wrap `ContentBlock` content and heading in `Layout` component to ensure the `LinkList` aligns properly with the copy.
**Changed**
- wrap the `heading` and `content` in `Layout` component if `LinkList` is passed in
=> fix(content-block): render optional linklist in layout

packages/styles/scss/themes/expressive/components/_select.scss
https://github.com/carbon-design-system/ibm-dotcom-library/issues/1355
The inline select labels and helper text were moving position when the invalid state is activated.
=> fix(select): fixed inline select when invalid

packages/styles/scss/components/masthead/_masthead.scss
#2065 
Fixes profile menu height
**Changed**
- profile menu item height changed to 48px
=> fix(css): fix profile menu item height

packages/styles/scss/components/masthead/_masthead-search.scss, packages/styles/scss/components/masthead/_masthead.scss
#2066 
Fixes `Masthead` platform and logo hover color
**Changed**
- platform and logo hover color to `$hover-ui`
=> fix(css): masthead platform hover color

packages/styles/scss/patterns/sub-patterns/layout/_layout.scss
#1193 
The border for the `Layout` pattern was updated on `md`, `lg`, `xlg` and `max` breakpoints, so it better fits the design specs.
=> fix(scss): fixed border size for layout pattern

packages/styles/scss/components/footer/_footer.scss
#2048 
Fixes hover color for visited footer links.
**Changed**
- footer link styles for `visited:hover`
=> fix(css): fix footer visited link hover color

packages/styles/scss/components/lightbox-media-viewer/_lightbox-media-viewer.scss
#1931 
Fixed a bug that happened when the image was bigger than the lightbox, so it would add scroll instead of resize to fit the container
=> fix(scss): lightbox video now fills the whole container height

packages/styles/scss/components/lightbox-media-viewer/_lightbox-media-viewer.scss
#2125 
Removes persistent scrollbars on content container, which are visible even when the content does not require scrolling.
**Changed**
- `LightboxMediaViewer` content overflow to `auto`.
=> fix(css): fix lightbox content overflow

packages/react/src/__tests__/__snapshots__/storyshots.test.js.snap, packages/react/src/patterns/sections/LeadSpace/LeadSpace.js, packages/react/src/patterns/sections/LeadSpace/README.md, packages/react/src/patterns/sections/LeadSpace/__stories__/LeadSpace.stories.js, packages/react/src/patterns/sub-patterns/ButtonGroup/__stories__/ButtonGroup.stories.js
I can't seem to find the issue that this was related to, but wondering if this should get patched in. The Leadspace is pointing to `image.default` and not `image.defaultSrc`. 
**Changed**
- Fix to Leadspace to properly point to `defaultSrc`
=> fix(leadspace): properly point to defaultSrc for the Image

packages/styles/scss/themes/expressive/components/_text-area.scss, packages/styles/scss/themes/expressive/index.scss
https://github.com/carbon-design-system/ibm-dotcom-library/issues/1358
Updates text area invalid icon to 20x20
=> fix(textarea): updated invalid icon to expressive sizing

.yarnrc
#2134 
Best workaround at the moment is to downgrade Yarn until this is fixed on the Yarn side. This PR downgrades the repo to 1.19.0.
**Changed**
- Downgrade Yarn to 1.19.0
=> fix(yarn): downgrading yarn to 1.19.0 for install issues

packages/styles/scss/themes/expressive/components/_file-uploader.scss, packages/styles/scss/themes/expressive/components/_tooltip.scss
https://github.com/carbon-design-system/ibm-dotcom-library/issues/1274
Updated tooltip link to expressive size.
=> fix(tooltip): fixed tooltip link fontsize

packages/react/src/__tests__/__snapshots__/storyshots.test.js.snap, packages/react/src/patterns/blocks/ContentBlockMedia/__stories__/ContentBlockMedia.stories.js, packages/react/src/patterns/blocks/ContentBlockMixed/__stories__/ContentBlockMixed.stories.js, packages/react/src/patterns/blocks/ContentBlockSegmented/__stories__/ContentBlockSegmented.stories.js, packages/react/src/patterns/blocks/ContentBlockSimple/__stories__/ContentBlockSimple.stories.js, packages/react/src/patterns/sub-patterns/ContentBlock/__stories__/ContentBlock.stories.js, packages/styles/scss/patterns/sub-patterns/content-block/_content-block.scss, packages/styles/scss/patterns/sub-patterns/link-list/_link-list.scss
Pattern: Content Block(with aside elements):- Copy text and linklist section are not getting displayed properly on mobile devices. #2142
Needed to add grid class for mobile breakpoint for `ContentBlock` and `ContentBlockMedia`, `ContentBlockSegmented`, `ContentBlockSimple`, `ContentBlockMixed`.
Also needed to add left and right padding to the linklist component for mobile breakpoint
NOW:
**New**
- add small grid class
- added padding to linklist card wrapper
- set `margin-right: -1rem` for linklist in `ContentBlock`
=> fix(storybook): add grid classes for mobile content block

packages/react/src/patterns/sub-patterns/ContentSection/__stories__/index.scss
[Content Section: Theme issue in Storybook: On applying g100, g90 , g10 text in children section is not visible #1656](https://github.com/carbon-design-system/ibm-dotcom-library/issues/1656)
The themes were not being applied correctly. This problem seems to related only with the storybook appearance.
**Changed**
- `packages/react/src/patterns/sub-patterns/ContentSection/__stories__/index.scss`
=> style(content-section): fixing theme error on storybook

packages/services/src/services/VideoPlayer/VideoPlayer.js, packages/styles/scss/components/lightbox-media-viewer/_lightbox-media-viewer.scss
If description or title was too short, the video player would shrink
BEFORE: 
AFTER: videoplayer doesn't shrink even if there is no title or description
**Changed**
- override carbon's `padding-right: 20%` on the `modal-content`
**Removed**
- styles setting media to the top of the modal, media should be vertically centered
=> fix(lightbox): display videoplayer and desc copy without distortion

packages/react/src/components/carbon-components-react/UIShell/SideNavMenu.js
Fix PropType type
**New**
- `isbackbutton` PropType changed to `string`
=> fix(props): fix proptype type

packages/styles/scss/components/locale-modal/_locale-modal.scss
#1764 
Adds a vertical breakpoint media query for mobile devices in landscape orientation to allow scrolling of locale list
**New**
- media query for max-height of LocaleModal container
=> fix(locale): fix locale scroll on mobile landscape

packages/react/src/__tests__/__snapshots__/storyshots.test.js.snap, packages/react/src/patterns/blocks/ContentBlockMedia/__stories__/ContentBlockMedia.stories.js, packages/react/src/patterns/blocks/ContentBlockMixed/__stories__/ContentBlockMixed.stories.js, packages/react/src/patterns/blocks/ContentBlockSegmented/__stories__/ContentBlockSegmented.stories.js, packages/react/src/patterns/blocks/ContentBlockSimple/__stories__/ContentBlockSimple.stories.js
Story book:- Patterns related to contents showing error message on selecting render aside element #2178
When turning on the aside knob in storybook for content block decorator patterns and opening new tab, it breaks.
Current workaround in this PR is to place the aside elements in a separate story
**Changed**
- put aside elements in separate story for content block decorators
=> fix(storybook): put aside elements in separate story for content block decorators

packages/styles/src/carbon-stories/ComboBox/ComboBox-story.js, packages/styles/src/carbon-stories/InlineLoading/InlineLoading-story.js
[Inline Loading UX example page is giving an error message #1309](https://github.com/carbon-design-system/ibm-dotcom-library/issues/1309)
Removed all the references to the `__docgeninfo` property since we're not using it. This prevents the `InlineLoading` component from continuing to break.
**Removed**
- all the references to the `__docgeninfo` property
=> fix(expressive-theme): removing __docgenInfo references

packages/styles/scss/components/locale-modal/_locale-modal.scss
[Locale selector: eyebrow link missing underline #2076](https://github.com/carbon-design-system/ibm-dotcom-library/issues/2076)
Underline added to the eyebrown link at the `LocaleModal` on hover.
**Changed**
- underline at the eyebrow link in the `LocaleModal`;
=> style(locale-modal): underline added to the eyebrow link

packages/react/src/components/carbon-components-react/UIShell/HeaderMenu.js, packages/styles/scss/components/masthead/_masthead-l1.scss
#2069 
Fixes chevron size in masthead navigation.
**Changed**
- update masthead chevron to use `ChevronDown20` from `@carbon/icons-react`
=> fix(masthead): update masthead nav chevron size

packages/styles/scss/components/locale-modal/_locale-modal.scss
Locale selector: locale list is using the wrong type size #1978
Applyied the correct type size to the locale-selector. 
**Changed**
- Now the text at the locale list follows the `$body-short-02` `scss` token.
=> style(locale-modal): applying correct type size

packages/react/src/__tests__/__snapshots__/storyshots.test.js.snap, packages/react/src/components/DotcomShell/DotcomShell.js, packages/react/src/components/DotcomShell/README.md, packages/react/src/components/DotcomShell/__stories__/DotcomShell.stories.js, packages/react/src/components/Footer/LanguageSelector.js, packages/react/src/components/Footer/__stories__/Footer.stories.js, packages/react/src/components/Masthead/Masthead.js, packages/react/src/components/Masthead/README.md, packages/react/src/components/Masthead/__stories__/Masthead.stories.js
https://github.com/carbon-design-system/ibm-dotcom-library/issues/2254
Made a number of fixes to the prop handling, storybook prop descriptions, and also generally how the footer props are passed through the `DotcomShell`. This is a breaking change for DotcomShell users, so will need to note this in release notes for `1.7.0`.
**Changed**
- Passing props for footer through the `DotcomShell`
- Various storybook descriptions
- README updates
=> fix(dotcomshell): passing additional footer props through dotcomshell

packages/styles/scss/components/lightbox-media-viewer/_lightbox-media-viewer.scss
Adds missing styles to `LightboxMediaViewer`
**New**
- `VideoPlayer` styles added to `LightboxMediaViewer`
=> fix(css): add videoplayer styles

packages/react/src/__tests__/__snapshots__/storyshots.test.js.snap, packages/react/src/components/Footer/Footer.js, packages/react/src/components/LocaleModal/LocaleModalCountries.js
https://github.com/carbon-design-system/ibm-dotcom-library/issues/2250
This properly sets the ipcinfo cookie within the locale modal.
**Changed**
- fixed the cookie set method trigger for changing language/locale
=> fix(ipcinfo): properly set the ipcinfo cookie in the locale modal

packages/styles/scss/components/locale-modal/_locale-modal.scss
#2279 
Removes country list container scrollbar when vertical media query active.
**Removed**
- vertical scrollbar in `LocaleCountry` list when vertical media query active
=> fix(locale): remove scroll on vertical media query

packages/react/src/patterns/sections/CardSectionImages/README.md, packages/react/src/patterns/sections/CardSectionSimple/README.md, packages/react/src/patterns/sub-patterns/CardGroup/README.md
Update documentation for `CardGroup`, `CardSectionSimple`, and `CardSectionImages`.
**New**
- good docs
**Removed**
- bad docs
=> chore(docs): update card docs

packages/react/src/patterns/blocks/index.js, packages/react/src/patterns/sections/CardSectionImages/README.md, packages/react/src/patterns/sections/CardSectionSimple/README.md, packages/react/src/patterns/sub-patterns/index.js, packages/styles/scss/ibm-dotcom-styles.scss, packages/styles/scss/patterns/sections/card-section-images/_card-section-images.scss, packages/styles/scss/patterns/sections/card-section-simple/_card-section-simple.scss
https://github.com/carbon-design-system/ibm-dotcom-library/issues/2322, https://github.com/carbon-design-system/ibm-dotcom-library/issues/2324
This adds in the discrete style imports for `CardSectionSimple` and `CardSectionImages`
**New**
- style imports for card section
=> fix(card-section): adding style imports for cardsection patterns

packages/react/src/__tests__/__snapshots__/storyshots.test.js.snap, packages/react/src/patterns/blocks/ContentBlockSimple/ContentBlockSimple.js, packages/react/src/patterns/blocks/ContentBlockSimple/README.md, packages/react/src/patterns/blocks/ContentBlockSimple/__stories__/ContentBlockSimple.stories.js, packages/styles/scss/patterns/blocks/content-block-simple/_content-block-simple.scss
https://github.com/carbon-design-system/ibm-dotcom-library/issues/2212
Adds the inverse theme for Content Block Simple
=> feat(contentblocksimple): added inverse theme to contentblocksimple

packages/react/src/components/DotcomShell/DotcomShell.js, packages/react/src/patterns/blocks/CalloutWithMedia/CalloutWithMedia.js, packages/react/src/patterns/sections/LeadSpace/LeadSpace.js, packages/react/src/patterns/sub-patterns/CardGroup/CardGroup.js, packages/react/src/patterns/sub-patterns/ContentItem/ContentItem.js
Fixes #2347.
This change attempts to fix React prop type warnings for prop type definitions for props that are passed along to child components.
**Changed**
- Prop type definitions for:
- `footerProps`/`mastheadProps` in `<DotcomShell>`
- Ones in `<CalloutWithMedia>`
- `image` in `<LeadSpace>`
- `cta` in `<CardGroup>`
- `cta` in `<ContentItem>`
=> chore(components): fix prop types

packages/react/.storybook/_container.scss
#2353 
This removed the floating cookie preferences button, which is causing some false positives.
**Changed**
- Added class to suppress cookie button in percy
=> fix(percy): hiding cookie preferences in percy output

packages/react/.storybook/_container.scss
#2353 
Still noticing the cookie link appearing. This also will suppress the cookie link in the footer as it seems to switch between "Cookie Preferences" and "Cookie Preferences and Do Not Share My Info".
**Changed**
- Hiding cookie link in Percy
=> fix(percy): hiding cookie preferences in footer in percy output

packages/styles/scss/components/masthead/_masthead-l1.scss
Refs #2198.
This change attempts to fix the build error that is observed by incorporating the full set of masthead styles. The issue is observed by creating code with `@import '@carbon/ibmdotcom-styles/scss/components/masthead/index'` (Replacing code importing `masthead.scss` in `styles.scss` in https://github.com/carbon-design-system/ibm-dotcom-library/compare/master...asudoh:codesandbox), which yields to a Sass build error.
**Changed**
- Add back a missing selector surrounding `display: none`, in `_masthead-l1.scss`.
=> fix(masthead): fix build error

packages/react/src/patterns/sub-patterns/ContentBlock/ContentBlock.js
Pattern: Change the Content block based on the Solution page designs and updated functions specs #1847
Turning the `ContentBlock` proptypes declaration for the `CTA` component more specific.  
**Changed**
- `ContentBlock` proptype from `cta: PropTypes.object` to `cta: PropTypes.shape(CTA.propType)`;
=> chore(content-block): specifying CTA prop in the pattern

packages/styles/scss/components/image-with-caption/image-with-caption.scss
Component: Image with Caption:- On mobile and tablet image is displayed in oval shape #2444
Seems like the default browser border styles for buttons is being applied - overwriting that and setting border to none
ISSUE:
AFTER:
**New**
- set `border` to `none`
=> fix(image-with-caption): set button border style to none to resolve rounding in mobile

packages/react/src/components/Masthead/Masthead.js
Learn page - User clicks on the profile icon, drop down is not displayed. #2168
The problem related in the ticket above was happening in the `DotcomShell` component as well. The profile-list was being set to position fixed, but without the `top` property being specified, which was causing it to render out of the screen limits according the user scroll down.  
**New**
- `top: 48px` property set at the style object in the `setProfileListPosition` function in the `Masthead` component;
=> fix(masthead):  added top property to profile-list

packages/react/src/components/CTA/README.md
Update documentation with `download` type
**New**
- add `download` type to README
=> chore(docs): update docs with download type

packages/styles/scss/components/masthead/_masthead-l1.scss, packages/styles/scss/components/masthead/_masthead-leftnav.scss, packages/styles/scss/components/masthead/_masthead-search.scss, packages/styles/scss/components/masthead/_masthead.scss
#2203 
This fixes `masthead` styles to address layout issues when platform name is included in the nav.
**Changed**
- fix masthead styles for when platform name is displayed
- update license text
=> fix(css): fix masthead nav styles

packages/react/src/__tests__/__snapshots__/storyshots.test.js.snap, packages/react/src/components/CTA/TextCTA.js, packages/react/src/patterns/blocks/CalloutQuote/CalloutQuote.js, packages/react/src/patterns/blocks/ContentBlockMedia/__stories__/ContentBlockMedia.stories.js, packages/react/src/patterns/blocks/ContentBlockMixed/__stories__/ContentBlockMixed.stories.js, packages/react/src/patterns/blocks/ContentBlockSegmented/__stories__/ContentBlockSegmented.stories.js, packages/react/src/patterns/blocks/ContentBlockSimple/__stories__/ContentBlockSimple.stories.js, packages/react/src/patterns/blocks/ContentGroupHorizontal/README.md, packages/react/src/patterns/blocks/ContentGroupHorizontal/__stories__/data/items.json, packages/react/src/patterns/sub-patterns/ContentBlock/__stories__/ContentBlock.stories.js, packages/react/src/patterns/sub-patterns/ContentItemHorizontal/ContentItemHorizontal.js, packages/react/src/patterns/sub-patterns/ContentItemHorizontal/__stories__/ContentItemHorizontal.stories.js, packages/react/src/patterns/sub-patterns/LinkList/LinkList.js, packages/react/src/patterns/sub-patterns/LinkList/README.md, packages/react/src/patterns/sub-patterns/LinkList/__stories__/LinkList.stories.js, packages/styles/scss/patterns/sub-patterns/content-item-horizontal/_content-item-horizontal.scss, packages/styles/scss/patterns/sub-patterns/link-list/_link-list.scss, tasks/tag-release.sh
#1850 
This adds `horizontal` and `vertical` layout options to `LinkList`.
**New**
- `horizontal` and `vertical` styling options added to `LinkList`
**Changed**
- various `ContentBlock` patterns updated with `LinkList`
- `ContentItemHorizontal` updated to use `LinkList` instead of `CTA`
=> feat(linklist): add linklist variations

packages/react/src/__tests__/__snapshots__/storyshots.test.js.snap, packages/react/src/components/Footer/__stories__/Footer.stories.js
This splits the Footer storybook story from a single story into two separate stories. The default shows the tall footer, and there is now a second story for the "short" footer.
**Changed**
- Footer storybook stories
=> chore(footer): splitting the footer story into two

packages/react/src/patterns/blocks/index.js
Restored the exports for `blocks` folder.
=> chore(exports): restored exports from blocks

packages/styles/scss/patterns/sub-patterns/buttongroup/_buttongroup.scss, packages/styles/scss/patterns/sub-patterns/callout/_callout.scss, packages/styles/scss/patterns/sub-patterns/card-group/_card-group.scss, packages/styles/scss/patterns/sub-patterns/card/index.scss, packages/styles/scss/patterns/sub-patterns/content-item-horizontal/_content-item-horizontal.scss, packages/styles/scss/patterns/sub-patterns/feature-card/_feature-card.scss, packages/styles/scss/patterns/sub-patterns/layout/_layout.scss, packages/styles/scss/patterns/sub-patterns/link-list/_link-list.scss, packages/styles/scss/patterns/sub-patterns/link-list/index.scss, packages/styles/scss/patterns/sub-patterns/pictogram-item/_pictogram-item.scss, packages/styles/scss/patterns/sub-patterns/quote/_quote.scss, packages/styles/scss/patterns/sub-patterns/tableofcontents/_tableofcontents.scss, packages/styles/scss/patterns/sub-patterns/tableofcontents/index.scss
https://github.com/carbon-design-system/ibm-dotcom-library/issues/2576
This adds back a breadcrumb to import the new location of the subpattern style files.
**New**
- sub-pattern style imports with deprecation notice
=> fix(sub-patterns): adding deprecation and breadcrumb imports

packages/react/.storybook/preview-head.html
https://github.com/carbon-design-system/ibm-dotcom-library/issues/2595
We have been getting a lot of false positives with the video link in
LinkList, so going to add this to suppress that item entirely instead.
**Changed**
- Modified elements hidden in percy for LinkList
=> chore(percy): hiding video link in linklist for percy tests

packages/react/.storybook/preview-head.html, tasks/beta-releases.js
https://github.com/carbon-design-system/ibm-dotcom-library/issues/2514
This is a script that will find the diff between the previous tag and
latest, then will generate a new release on the new tag. Right now,
it will only add features and fixes and sort accordingly.
Once this is merged in, I will set up on the CI side.
**New**
- beta release creation script
=> feat(beta-releases): adding beta release creation script

packages/react/src/__tests__/__snapshots__/storyshots.test.js.snap, packages/react/src/components/Masthead/__stories__/Masthead.stories.js
Component- Masthead- Platform name is not getting displayed on mobile devices when opened in new page. #2143
The problem here is that we have a bug within the storybook iframe happening with some of our stories when we change a `prop` in the knobs pannel and then open the component in the iframe. Since we cannot fix it in our end, a workaround is to create a new story with the properties we want to see.
**New**
- Story for the `Masthead` component, with the platform as the default.
**Removed**
- `platform` knob from the `Masthead` default story.
=> fix(storybook): bug happening in the masthead iframe view

packages/styles/scss/patterns/blocks/feature-card-block-large/_feature-card-block-large.scss
Pattern: Feature Card Block Large: Spacing fixes #2410
Fixes:
✅  Internal card spacing for large breakpoint;
✅  Extra padding above the feature card for small, medium, and large breakpoints;
✅  Extra space above the eyebrow on small breakpoint.
**Changed**
- `FeatureCardBlockLarge` pattern styles;
=> style(pattern): fix feature-card-block-large styles

packages/styles/scss/patterns/blocks/feature-card-block-large/_feature-card-block-large.scss
https://app.zenhub.com/workspaces/ibmcom-library-5d449f3642eb1962336cbe52/issues/carbon-design-system/ibm-dotcom-library/2400
CTA Icon font size corrected
**Changed**
Font size of CTA Icon changed from 20px to 32px
=> fix(pattern): icon size in FeatureCardBlockLarge corrected

packages/react/src/__tests__/__snapshots__/storyshots.test.js.snap, packages/react/src/components/Image/Image.js
Refs #2387.
This change fixes invalid `aria-describedby` value, which was an empty string. Seems that it happens in a condition that there should be no valid target for `aria-describedby`, and thus fixed it by simply removing the attribute.
**Removed**
- `aria-describedby` from `<Image>` in a condition where the attribute is not needed.
=> fix(Image): fix invalid aria-describedby

packages/react/src/internal/hooks/useVideoData/useVideoData.js
This change fixes an issue where `getVideoData()` is called in the corresponding variable's temporal dead zone. This is revealed in a Babel configuration where `const` is not transpiled to `var.
**Changed**
- `getVideoData()` in `useVideoData()` so that `getVideoData()` is not called in TDZ.
=> fix(useVideoData): fix a call in TDZ

tasks/beta-releases.js
#2514 
This is a minor fix to remove the delimiter from appearing in the last changelog item in the script.
**Changed**
- Beta release script tweak
=> fix(beta-releases): minor fix to remove the delimiter

packages/react/.storybook/preview-head.html
I believe the false positives being created is the sporadic rendering
of the privacy link. This will suppress it entirely rather than setting
the visibility to hidden.
**Changed**
- Setting to completely suppress the privacy link in the footer in Percy
=> chore(percy): removing percy false positives in footer

packages/styles/scss/components/tableofcontents/_tableofcontents.scss
Reverted some unintentional changes to the `TableOfContents` side navigation.
=> chore(scss): reverted table-of-contents side nav vertical positioning;

packages/react/.storybook/Container.js
https://github.com/carbon-design-system/ibm-dotcom-library/issues/2653
The "rtl" setting does not seem to be properly set in dev environments,
but is ok for static builds of storybook. This is an additional change
so that when running storybook in dev mode, this is set correctly.
**Changed**
- storybook container explicitly setting `dir="rtl"` in the html element
=> chore(rtl): fixing rtl attribute for dev environments

packages/react/src/__tests__/__snapshots__/storyshots.test.js.snap, packages/react/src/components/CardLink/CardLink.js
https://github.com/carbon-design-system/ibm-dotcom-library/issues/2610
We went through this one in the QA standup, a few minutes ago
**Removed**
- `role=region` from `CardLink`
=> fix(accessibility): lifting up role=region from anchor tag in CardLink

packages/services/src/services/DDO/DDO.js, packages/services/src/services/DDO/__tests__/DDO.test.js, packages/services/src/services/global/__tests__/global.test.js, packages/services/src/services/global/global.js, packages/vanilla/src/components/footer/footer.js, packages/vanilla/src/components/masthead/masthead.js
This change fixes swallowed promise rejections found in several places during manual test of vanilla CodeSandbox examples.
Such swallowed promise rejection was thrown from `DDOAPI.isReady()`, where a couple additional things were found (and fixed):
1. When `DDOAPI.isReady()` was called multiple times in a short amount of time, the "time elapsed" counter increases every time `DDOAPI.isReady()` is called, which causes `DDOAPI.isReady()` yield to a rejected promise at the 50th call, even before the actual timeout (`5s`) happens.
2. It was hard to trace the series of problem because the rejected promise was not created with an error object. It made investigation of integration test failure hard.
**Changed**
- Fixed swallowed promise rejections in various places.
- Made sure the promise …
=> fix(services): fix uncaught rejections

packages/utilities/src/utilities/decodeString/decodeString.js
While creating a new `Next.js` page, I've noticed that `DomParser` is not supported on a server side rendered page, this updates change the implementation of `decodeString` to fix this issue.
=> fix(decodeString): updated decode-string to work on server-side rendering

packages/react/config/jest/__mocks__/LocaleAPI.js, packages/react/config/jest/__mocks__/VideoPlayerAPI.js, packages/react/config/jest/setup.js, packages/react/src/__tests__/__snapshots__/storyshots.test.js.snap, packages/react/src/components/CTA/CardCTA.js, packages/react/src/components/LinkList/LinkList.js, packages/react/src/components/VideoPlayer/VideoPlayer.js, packages/styles/scss/components/link-list/_link-list.scss, packages/utilities/src/utilities/smoothScroll/smoothScroll.js
Refs #2688 
The CI checks were running with obfuscated Kaltura IDs since they are
passed in as environment variables, so this is setting up a mock for
the VideoPlayerAPI service to return back mocked data instead.
**Changed**
- Created jest mock for `@carbon/ibmdotcom-services` in React package
=> fix(VideoPlayer): fix for mocking VideoPlayerAPI in storyshots

packages/styles/scss/components/tableofcontents/_tableofcontents.scss
#2572 
Added `width` so the select text don't overlap the icon on mobile view
=> fix(table-of-contents): added max-width for select text on mobile view

packages/react/.storybook/_container.scss, packages/styles/.storybook/_container.scss, packages/vanilla/.storybook/_container.scss
Refs #2725.
This change removes our CSS override for `.bx--visually-hidden` class that is defined in our Storybook environment.
Setting `display:none` to that class makes the DOM element no longer keyboard focusable that is against its purpose, which is, "hidden visually, but navigable with screen readers".
Carbon modal's focus wrap behavior relies on elements with `.bx--visually-hidden` keyboard-focusable to detect changes in focused element that goes out of modal.
**Removed**
- Our CSS override in Storybook for `.bx--visually-hidden`.
=> chore(devenv): remove `.bx--visually-hidden` override

packages/react/.storybook/config.js, packages/react/src/__tests__/__snapshots__/storyshots.test.js.snap, packages/react/src/components/Card/__stories__/Card.stories.js, packages/react/src/components/ExpressiveModal/__stories__/ExpressiveModal.stories.js, packages/styles/scss/components/card-group/_card-group.scss, packages/styles/scss/components/footer/_footer-logo.scss, packages/styles/scss/components/footer/_footer-nav-group.scss, packages/styles/scss/components/footer/_footer-nav.scss, packages/styles/scss/components/footer/_footer.scss, packages/styles/scss/components/footer/_language-selector.scss, packages/styles/scss/components/footer/_legal-nav.scss, packages/styles/scss/components/footer/_locale-button.scss, packages/styles/scss/components/tableofcontents/_tableofcontents.scss, packages/styles/scss/internal/content-section/_content-section.scss, packages/styles/scss/patterns/blocks/content-block-media/_content-block-media.scss, packages/styles/scss/patterns/sections/ctasection/_ctasection.scss, packages/styles/scss/patterns/sections/leadspace/_leadspace.scss, packages/styles/scss/patterns/sections/simplebenefits/_simplebenefits.scss
(Please use gear icon - Hide whitespace changes for reviewing)
Refs #2733.
This change makes the theme zoning code in several components, notably footer, work with a theme set outside footer via CSS custom properties. It means that, with this fix, footer remains in `g90` color even if `white` theme is applied in `<body>` with CSS custom properties.
This change also:
* Implements a logic to reset the theme to default for stories that disable theme chooser. This logic is implemented in Storybook configuration code so that our theme chooser add-on focuses on its UI and ensures its re-usable in a way ibmdotcom library-specific requirements not baked in
* Disables theme chooser for expressive modal, too
**New**
- Support for CSS custom properties in our theme zoning code (notably footer).
- A …
=> feat(styles): support CSS custom properties in theme zoning

packages/styles/scss/components/masthead/_masthead.scss
Refs #1744
This is a fix for properly setting the profile menu dropdown in the
masthead. This uses rtlcss, and unfortunately will need to set as
!important for now until we can find a more elegant solution.
**Changed**
- Added positioning fix for RTL
=> fix(Masthead): fix for rtl masthead profile menu

packages/react/.storybook/Container.js
This change fixes broken `font-family` in our React Storybook environemnt in RTL mode. It was caused by redundant Carbon `.bx--body` class that sets `font-family: inherit` that overrides Carbon `font-family` definition for `<body>` tag.
**Removed**
- `.bx--body` class that was set in RTL environment of our React Storybook environment, that was not needed.
=> chore(devenv): fix font-family in RTL environment

packages/react/src/components/LocaleModal/LocaleModalCountries.js
Restores prop block comments removed in https://github.com/carbon-design-system/ibm-dotcom-library/pull/2786.
**New**
- block comments for `LocaleModalCountries` props
=> chore(lint): add block comments to props

packages/styles/scss/components/masthead/_masthead-search.scss
#2794
Change search icon `z-index` only when search is active to prevent persistent visibility.
**Changed**
- search icon `z-index` when search active
=> fix(Masthead): search icon z-index

packages/react/src/__tests__/__snapshots__/storyshots.test.js.snap, packages/react/src/components/Footer/LanguageSelector.js
Footer language selector "The prop `placeholder` is marked as required in `ComboBox`, but its value is `undefined`." #2657
Added an empty string as a placeholder for the `LanguageSelector` ComboBox, just to avoid the console errors about prop types validation. Since the Combobox will always contain the selected language a placeholder is not necessary.
=> fix(LanguageSelector): placeholder prop added

packages/styles/scss/components/buttongroup/_buttongroup.scss, packages/styles/scss/components/card/README.md, packages/styles/scss/components/card/index.scss, packages/styles/scss/components/link-with-icon/_link-with-icon.scss, packages/styles/scss/patterns/blocks/leadspace-block/_leadspace-block.scss, packages/styles/scss/patterns/sections/ctasection/_ctasection.scss
Fix missing ButtonGroup style import for LeadSpaceBlock and CTASection #2838
Various components are missing style imports for associated components. Importing `buttongroup`  and `lightbox-media-viewer` styles to related component styles.
**New**
- import `buttongroup` and `lightbox-media-viewer` styles
=> fix(styles): import missing styles to various components

packages/styles/scss/components/quote/_quote.scss
Pattern: CalloutQuote - Mobile - Left side padding is not as per visual specs. #2385
**Previous**
**Current**
**New**
- new absolute position to the quotation mark at small breakpoint.
=> fix(Quote): quotation mark spacing adjusted 

packages/styles/scss/components/card-link/_card-link.scss
Add missing css import to `CardLink`
**New**
- import `Card` styles
=> fix(CardLink): add missing css

packages/styles/scss/components/pictogram-item/_pictogram-item.scss
Add missing css import to `PictogramItem`
**New**
- import `ContentItem` and `LinkWithIcon` styles
=> fix(PictogramItem): add missing style import

packages/react/src/__tests__/__snapshots__/storyshots.test.js.snap, packages/react/src/components/LinkWithIcon/LinkWithIcon.js, packages/react/src/components/LinkWithIcon/__stories__/LinkWithIcon.stories.js, packages/react/src/components/LinkWithIcon/__tests__/LinkWithIcon.test.js, packages/styles/scss/components/link-with-icon/_link-with-icon.scss
#2295 
The `inverse` prop was added to `LinkWithIcon`, so we can toggle the inverse theming.
=> feat(LinkWithIcon): enabled inverse theming

packages/styles/scss/internal/content-block/_content-block.scss
https://github.com/carbon-design-system/ibm-dotcom-library/issues/2501
Updates content block copy token
=> fix(content-block): updated copy token to match updated designs

packages/react/src/__tests__/__snapshots__/storyshots.test.js.snap, packages/styles/scss/components/link-list/_link-list.scss
Pattern: ContentBlock Segmented - On iPad, all sub section are not stretched to full screen size as per specs. #2570
In the `md` breakpoint the `ContentBlockMixed` and `ContentBlockSegmented` patterns had it's `LinksList` fulfilling the entire screen when they were supposed to have a max-width of 640px.
**New**
- `max-width: carbon--mini-units(80);` in the LinksList style
=> fix(LinkList): added 640px max-width for the card type

packages/styles/scss/patterns/blocks/content-block-segmented/_content-block-segmented.scss
Pattern: ContentBlock Segmented - No spacing between bottom section and the border line. #2603 
Added padding between bottom section and border starting on large breakpoint. For `sm` and `md` the padding is already being applied correctly. 
**New**
- Added CSS to provide padding between border and section when border is set to `true` in border options
=> fix(ContentBlockSegmented): added padding between bottom border and content

packages/react/src/__tests__/__snapshots__/storyshots.test.js.snap, packages/react/src/components/Masthead/Masthead.js, packages/react/src/components/Masthead/MastheadLeftNav.js
#2769 
A bug was fixed where the platform name was not passed as a prop to `MastheadLeftNav`, causing the platform to not be shown on mobile devices.
=> fix(masthead): fixed missing platform on masthead

packages/react/src/__tests__/__snapshots__/storyshots.test.js.snap, packages/react/src/components/DotcomShell/__stories__/DotcomShell.stories.js, packages/react/src/components/DotcomShell/__stories__/data/content.js, packages/react/src/components/TableOfContents/__stories__/TableOfContents.stories.js, packages/react/src/components/TableOfContents/__stories__/data/DataContent.js, packages/react/src/components/TableOfContents/__tests__/TableOfContents.test.js
Refs #2693.
This change makes React component/element instances defined as module export (variable)s for some stories to functions that return React component/element, and thus they are React (function) components.
Doing so avoids React prop type warnings shown as orphaned React component/element tree, shown even in stories that don't use that React component/element tree.
This change also fixes some imports in `<Dotcomshell>` story referring to build artifacts. To see our changes live in storybook, we need to refer to the source.
**Changed**
- Made React component/element instances defined as module export (variable)s for some stories to functions that return React component/element, and thus they are React (function) components.
- Fixes some imports in `<Dotcomshell>` story referring to …
=> chore(Dotcomshell): avoid side effect in story module

packages/styles/scss/patterns/blocks/content-block-segmented/_content-block-segmented.scss
Patterns: ContentBlock Segmented - spacing variations between sub section on desktop and mobile view. #2567
The paddings were set incorrectly between content groups in `ContentBlockSegmented`. I fixed them based on `Visual Specs`: https://ibm.ent.box.com/file/662609167728
Please note I did other changes in the same file in this PR: https://github.com/carbon-design-system/ibm-dotcom-library/pull/2899
**Changed**
- Increased padding on top and bottom for content group components in `ContentBlockSegmented`
=> fix(ContentBlockSegmented): fixing sections padding for all breakpoints

packages/react/src/__tests__/__snapshots__/storyshots.test.js.snap, packages/react/src/components/ExpressiveModal/ExpressiveModal.js, packages/react/src/components/Footer/Footer.js, packages/react/src/components/HorizontalRule/HorizontalRule.js, packages/react/src/components/Layout/Layout.js, packages/react/src/components/Quote/Quote.js, packages/react/src/components/TableOfContents/TOCDesktop.js, packages/react/src/components/TableOfContents/TableOfContents.js, packages/react/src/internal/components/ContentSection/ContentSection.js, packages/react/src/patterns/sections/CTASection/CTASection.js, packages/react/src/patterns/sections/CardSectionImages/CardSectionImages.js, packages/react/src/patterns/sections/CardSectionSimple/CardSectionSimple.js, packages/react/src/patterns/sections/LeadSpace/LeadSpace.js
(Please use gear icon - Hide whitespace changes for reviewing)
Refs #2693.
This change attempts to better utilize `classnames` library's feature of setting/unsetting CSS class names conditionally.
Doing so avoids the need for:
* Sending a pseudo value to `marginTop`/`marginBottom` prop in `<Layout>` (e.g. `none`) that is not explicitly defined and caused prop type warnings. Such pseudo value seem to have been used to use e.g. `bx--layout--top-none` class to unset styles that e.g. `bx--layout--top-layout-01` defines, given `bx--layout--top-none` doesn't seem to be defined at: https://github.com/carbon-design-system/ibm-dotcom-library/blob/v1.8.0/packages/styles/scss/components/layout/_layout.scss#L29-L41
* Utility functions that attempts to achieve the feature of setting/unsetting CSS …
=> chore(react): better support conditional class names

.github/PULL_REQUEST_TEMPLATE.md, packages/web-components/.eslintignore, packages/web-components/package.json
Refs #2810 
This adds static builds of storybook, which will be needed for test deployments.
The PR template has also been updated to include the web components label in the instructions.
**Changed**
- `package.json` updated in web components package to include storybook static builds
- pull request template updated
=> chore(storybook): adding build static storybook for web components

packages/services/src/services/Translation/__tests__/Translation.test.js
#2081 
Increased testing coverage by checking else of `getTranslation()` 
**New**
- added empty object
=> test(TranslationAPI): increase coverage

packages/react/src/__tests__/__snapshots__/storyshots.test.js.snap, packages/react/src/components/VideoPlayer/VideoPlayer.js
Inline and Linklist Video Player error #2502
Use the `uniqueid` util to create unique videoplayer ids. This way the `VideoPlayerAPI` knows where to embed the video properly even if there are multiple of the same video in the same page.
**Changed**
- use `uniqueid` util to concatenate a unique id to the videoplayer id
=> fix(VideoPlayer): create distinct videoplayer ids in order to place multiple of the same video

packages/react/src/__tests__/__snapshots__/storyshots.test.js.snap, packages/react/src/patterns/blocks/ContentBlockSegmented/__stories__/ContentBlockSegmented.stories.js
https://github.com/carbon-design-system/ibm-dotcom-library/issues/2638
This issue was previously fixed but was non testable in storybook because there wasn't a copy knob. This adds an optional copy knob so the QA folks can test this within storybook. PR is changing in the application
=> fix(contentblocksegmented) added copy knob for storybook

packages/react/src/__tests__/__snapshots__/storyshots.test.js.snap, packages/react/src/patterns/blocks/LogoGrid/LogoGrid.js
Remove class name from `autoid`.
**Removed**
- rogue class name in `autoid`
=> chore(autoid): remove class name from stable prefix

packages/react/src/__tests__/__snapshots__/storyshots.test.js.snap, packages/react/src/components/ButtonGroup/ButtonGroup.js
Refs #2693.
This change fixes React key put in a wrong place. Given we made the child item there a React fragment, we need to put `key` there.
**Changed**
- Fix a React prop type warning in `<ButtonGroup>`.
=> fix(ButtonGroup): put React key in the right place

packages/styles/scss/patterns/blocks/content-block-mixed/index.scss
This change fixes a `@import` path in `content-block-mixed/index.scss`.
This was found during my test against CodeSandbox example of `<ContentBlockMixed>`.
**Changed**
- Fix a `@import` path in `content-block-mixed/index.scss`.
=> fix(contentblockmixed): style path fix

packages/react/src/patterns/blocks/index.js
Added CalloutData export to index.js in Blocks patterns
Pattern: CalloutData - Is not being exported properly #2998
According to the issue mentioned above, we detected the `CalloutData` wasn't being exported properly, so it was impossible to use it in external projects.
**New**
- Added export syntax for `CalloutData` in `index.js` from Blocks patterns
=> fix(CalloutData): exporting pattern properly

.github/workflows/automerge-pr.yml
Refs #3018 
The merge retry needed to be tweaked since the CI checks take longer than the GH action can wait with the default settings.
**Changed**
- `MERGE_RETRIES` and `MERGE_RETRY_SLEEP` updated
=> chore(automerge): tweak to automerge configuration

packages/react/src/patterns/blocks/LogoGrid/README.stories.mdx, packages/react/src/patterns/blocks/LogoGrid/__stories__/LogoGrid.stories.js
Pattern: Logo grid: Carbon theme #2829
Added a description in the docs explaining that this pattern is available only under the Carbon white theme. 
**Removed**
- Carbon Themes addon from `LogoGrid` pattern story.
=> fix(LogoGrid): removed Carbon Themes addon

packages/vanilla/src/components/footer/footer.template.js
Refs #3047.
This change divides legal nav contents to chunks of columns, as our React variant does.
**Changed**
- A change divides legal nav contents to chunks of columns.
=> fix(footer): divide legal nav to chunks

packages/web-components/docs/developer.md
This change fixes broken link to coding conversion developer doc for Web Components.
**Changed**
- Fix broken link to `packages/web-components/docs/coding-conventions.md`.
=> docs(developers): fix broken link

packages/react/src/components/Masthead/Masthead.js, packages/react/src/components/Masthead/MastheadL1.js, packages/react/src/components/Masthead/__stories__/Masthead.stories.js, packages/styles/scss/components/masthead/_masthead-l1.scss
- Added validation to `eyebrownLink` and `eyebrowText`. Now If both props don't exist it shows nothing;
- Increased `max-width` from `MastheadL1`. Now the `MastheadL1` has a more accurate sizing at the `max` breakpoint;
- Added a `titleLink` prop. This prop is optional.
Now the "Stock Charts" can be clickable
=> fix(MastheadL1): increased max-width, eyebrow validation and new prop

packages/styles/scss/components/footer/_footer.scss
Refs #3068.
Changes `:visited:hover` color of footer link from `$text-02` to `$text-01`.
**Changed**
- `:visited:hover` color of footer link from `$text-02` to `$text-01`.
=> fix(footer): change color for visited and hover state

packages/react/src/patterns/sections/CardSectionImages/__stories__/CardSectionImages.stories.js
#2954 
Removes object knobs from story.
**Removed**
- all JSON knobs
=> chore(CardSectionImages): remove object knobs from story

packages/styles/gulp/tasks/sass.js, packages/styles/package.json, packages/styles/scss/components/card-group/_card-group.scss
Refs #3113 
The `gulp-sass` task was throwing out of memory errors. This is a step to mitigate the build times for the overall css artifact. To our knowledge, no adopters are using the main entry point and built artifact (nor should they), so for now this is removing sourcemaps ~as well as gulp-clean-css~ from the build pipeline until this can get sorted out.
**Changed**
- Reduced complexity of gulp-sass runner (removed sourcemaps ~and cleanCss~)
=> fix(styles): optimization fixes for gulp-sass in styles package

packages/styles/scss/components/quote/_quote.scss
https://github.com/carbon-design-system/ibm-dotcom-library/issues/2788
Padding between the CTA and the bottom of the page was 2rems. The updated correct padding is 4rems.
=> fix(calloutquote): fixed bottom padding

packages/react/src/__tests__/__snapshots__/storyshots.test.js.snap, packages/react/src/components/Card/Card.js, packages/styles/scss/components/card/index.scss
[Card] Add link text #2196
Reduce the bottom margin for Card when there is text in the link so that it is 16px from bottom of cta icon to bottom of card
Issue: (should be 16px from icon to bottom of card)
**Changed**
- set -2px margin when there is cta text
=> fix(Card): reduce bottom margin when link has text

packages/react/src/__tests__/__snapshots__/storyshots.test.js.snap, packages/react/src/components/CardGroup/__stories__/CardGroup.stories.js
#2949 
Separate `CardGroup` into individual stories
**Changed**
- separate `CardGroup` variations into individual stories
=> chore(CardGroup): separate CardGroup knobs into stories

packages/web-components/src/components/lightbox-media-viewer/__stories__/README.stories.mdx, packages/web-components/src/components/lightbox-media-viewer/lightbox-video-player.ts, packages/web-components/tests/snapshots/dds-lightbox-video-player.md
Refs #3153.
This change adds stable selectors to `<dds-lightbox-media-viewer>`.
This change also adds [`part` attribute](https://developer.mozilla.org/en-US/docs/Web/CSS/::part) there for better styling flexibility.
**New**
- `part` attribute to `<dds-lightbox-media-viewer>`.
- `data-autoid` to `<dds-lightbox-media-viewer>`.
=> chore(lightbox-media-viewer): add stable selector

packages/web-components/package.json
Refs carbon-design-system/carbon-custom-elements#443.
This change adds [`exports` field](https://nodejs.org/dist/latest-v14.x/docs/api/esm.html#esm_package_entry_points) in `package.json`.
Doing so enables several CDNs that support module path mapping.
**New**
- `exports` field in `package.json`.
=> chore(build): add exports field

packages/styles/scss/components/ctasection/_ctasection.scss
https://github.com/carbon-design-system/ibm-dotcom-library/issues/3017
**Changed**
- cta section bottom spacing :
Lg and above -160px
Sm - 64px
=> Fix(ctasection): Bottom spacing

packages/react/src/__tests__/__snapshots__/storyshots.test.js.snap, packages/react/src/components/CTA/CardCTA.js, packages/react/src/components/Card/Card.js, packages/react/src/components/CardLink/CardLink.js, packages/react/src/components/CardLink/README.stories.mdx, packages/react/src/components/CardLink/__stories__/CardLink.stories.js, packages/styles/scss/components/card-link/_card-link.scss
#3229 
Fix disabled state for `CardLink`
**Changed**
- move `disable` prop inside `card` object
**Removed**
- `otherProps` from `CTA: Card` story to fix url rendering null
=> fix(CardLink): disabled state

packages/web-components/src/components/lightbox-media-viewer/__stories__/lightbox-media-viewer.stories.ts
#3242 
The issue here is that the video player is throwing false positives
in percy. Because we don't have an image in lightboxmediaviewer
yet, going to have this configured to be skipped for now until we
have that in place.
**Changed**
- Hide lightboxmediaviewer in percy for web components
=> chore(percy): hide web components lightboxmediaviewer in percy

packages/react/src/components/ContentBlockCards/__stories__/ContentBlockCards.stories.js, packages/react/src/components/ContentBlockSegmented/__stories__/ContentBlockSegmented.stories.js, packages/react/src/components/ContentBlockSimple/__stories__/ContentBlockSimple.stories.js
The video player is throwing false positives in percy for React.
This will suppress the stories in percy that includes
videos.
**Changed**
- Adding percy `skip: true` configuration for video related stories
=> chore(percy): hide stories with videos

packages/web-components/README.md
This change updates basic usage section in Web Components variant's README, to add an example with no toolstack. Also updates existing example, replacing `<dds-link-with-icon>` with `<dds-modal>`.
**Changed**
- Updated basic usage section in Web Components variant's README, to add an example with no toolstack.
- Updated existing example, replacing `<dds-link-with-icon>` with `<dds-modal>`.
=> docs(readme): update for WC

packages/react/src/__tests__/__snapshots__/storyshots.test.js.snap, packages/react/src/components/CTASection/CTASection.js, packages/react/src/components/CTASection/__stories__/CTASection.stories.js, packages/react/src/components/ContentBlockHeadlines/ContentBlockHeadlines.js
`CTASection` content items should be set to the same height.
**Changed**
- set `sameHeight` for content items
=> fix(CTASection): add sameHeight to content items

packages/styles/scss/components/footer/_legal-nav.scss
https://github.com/carbon-design-system/ibm-dotcom-library/issues/2771
Fixes the padding between the legal nav list on mobile
=> fix(footer): fixed spacing of the legal nav list

packages/styles/scss/components/footer/_components.scss, packages/styles/scss/components/footer/index.scss
Refs #3126.
According to @jeffchew, our users are using our footer as an "entry point" where they tend to expect including footer will provide everything they need from our library.
To support such use case, this change adds the whole expressive theme to `packages/styles/scss/components/footer/index.scss`.
**Changed**
- `packages/styles/scss/components/footer/index.scss` to include the whole expressive theme code.
=> chore(footer): add expressive theme

packages/styles/scss/components/card/index.scss, packages/styles/scss/components/content-item-horizontal/_content-item-horizontal.scss, packages/styles/scss/components/image-with-caption/image-with-caption.scss, packages/styles/scss/components/locale-modal/_locale-modal.scss, packages/styles/scss/components/logo-grid/_logo-grid.scss, packages/styles/scss/components/masthead/_masthead-leftnav.scss, packages/styles/scss/components/video-player/_video-player.scss, packages/styles/scss/themes/expressive/_tokens.scss, packages/web-components/src/components/button/button.scss, packages/web-components/src/components/link-with-icon/link-with-icon.scss
**Changed**
- Rename `@include carbon-productive-tokens-custom-properties` to `@include use-carbon-productive-tokens`.
- Rename `@include carbon-expressive-tokens-custom-properties` to `@include use-carbon-expressive-tokens`.
=> chore(styles): rename type token zone mixin names

packages/web-components/README.md
Refs #2916.
Makes the following changes to Web Components `README`:
* Replaces the link to Canary version of our storybook to the released version
* Adds instruction of style customization
**Changed**
Makes the following changes to Web Components `README`:
* Replaces the link to Canary version of our storybook to the released version
* Adds instruction of style customization
=> chore(readme): update Web Components README

package.json, tasks/beta-releases.js
The script was not generating the beta release notes
for some reason. Turns out it was a CI configuration, but
in the process ended up switching to `node-fetch` instead
and cleaning up the script a bit.
**Changed**
- `beta-release.js` switched to `node-fetch`
=> chore(beta-release): fixing beta release script

packages/web-components/examples/codesandbox/components/locale-modal/.babelrc, packages/web-components/examples/codesandbox/components/locale-modal/.gitignore, packages/web-components/examples/codesandbox/components/locale-modal/index.html, packages/web-components/examples/codesandbox/components/locale-modal/package.json, packages/web-components/examples/codesandbox/components/locale-modal/sandbox.config.json, packages/web-components/examples/codesandbox/components/locale-modal/src/index.js, packages/web-components/src/components/locale-modal/__stories__/README.stories.mdx, packages/web-components/src/components/locale-modal/__stories__/locale-modal.stories.ts, packages/web-components/src/components/locale-modal/locale-modal-composite.ts, packages/web-components/src/components/locale-modal/locale-modal-container.ts
Refs #2883.
**New**
- CodeSandbox example for locale modal.
**Changed**
- Fix in `<dds-locale-modal-composite>`, to add missing capability to load `langDisplay` from `@carbon/ibmdotcom-services`.
=> docs(locale-modal): add CodeSandbox example

packages/react/src/components/Footer/Footer.js, packages/react/src/components/Masthead/Masthead.js, packages/services/src/services/Translation/Translation.js, packages/vanilla/babel.config.js, packages/vanilla/src/components/footer/footer.js, packages/vanilla/src/components/footer/footer.template.js, packages/vanilla/src/components/masthead/masthead.js, packages/web-components/src/components/masthead/masthead-container.ts
Refs #3382.
This change ensures the following things when there is an error in services layer:
* The error is caught and logged in browser console
* Vanilla template is still (partially) rendered
**Changed**
- `TrasnlateAPI.getTranslation()` to avoid rejecting with `undefined`. Vanilla/React code use it for logging the error.
- Web Components' service interface code so uncaught exception won't be logged. (The error itself is logged in Redux layer)
- Vanilla template so missing data of masthead nav links, masthead profile links and footer nav links won't prevent entire footer from rendered.
=> chore(services): better error handling

packages/react/src/components/Masthead/MastheadSearch.js
Refs #2896.
This change implements a mini-polyfill of `AbortController` that's not implemented in UC browser, our tier-2 supported browser.
**Changed**
- `<MastheadSearch>` to mini-polyfill `AbortController` for UC browser.
=> fix(MastheadSearch): fix UC browser

.lintstagedrc
Newer version of `lint-staged` doesn't require `git add` in `.lintstagedrc`, and thus they are removed.
**Removed**
- `git add` in `.lintstagedrc`
=> chore(lint): update .lintstagedrc

packages/web-components/src/components/lightbox-media-viewer/__tests__/lightbox-media-viewer-container.test.ts, packages/web-components/src/components/video-player/__tests__/video-player-container.test.ts, packages/web-components/src/components/video-player/video-player-container.ts, packages/web-components/tests/snapshots/dds-lightbox-video-player-container.md, packages/web-components/tests/snapshots/dds-video-player-container.md
This change makes `VideoPlayerAPI.embedVideo()`'s mock in Web Components' test in sync with the change made to the actual implementation in #3427.
**Changed**
- A change to make `VideoPlayerAPI.embedVideo()`'s mock in Web Components' test in sync with the change made to the actual implementation in #3427.
=> test(video-player): update mock

packages/web-components/src/components/cta/__tests__/cta-container.test.ts, packages/web-components/src/components/cta/cta-container.ts, packages/web-components/src/globals/internal/link.ts
Refs #3440.
This change
**Changed**
- A fix to ensure lightbox won't open upon clicking link unless the CTA type is video.
=> fix(cta): prevent lightbox from opening for non-video

packages/styles/scss/components/masthead/_masthead-megamenu.scss
Mega menu desktop – CTA focus state #3498
Make sure padding is applied on focus state of the view all ctas
**Changed**
- add padding to :focus pseudo class
=> fix(MegaMenu): add padding to the view all cta focus state

packages/styles/scss/components/expressive-modal/_expressive-modal.scss, packages/styles/scss/components/lightbox-media-viewer/_lightbox-media-viewer.scss, packages/web-components/src/components/lightbox-media-viewer/__stories__/lightbox-media-viewer.stories.ts, packages/web-components/src/components/modal/modal.scss, packages/web-components/src/components/modal/modal.ts, packages/web-components/tests/snapshots/dds-lightbox-video-player-container.md, packages/web-components/tests/snapshots/dds-locale-modal.md, packages/web-components/tests/snapshots/dds-modal.md
Refs #3349.
This change fixes the size of lightbox media viewer by making sure the correct attribute of `<dds-modal>` is used.
This change also does:
* Making sure lightbox media viewer is vertically scrollable when screen real estate is big horizontally, but small vertically.
* Attempt to best reuse CSS between React and Web Components versions of modal and lightbox media viewer, by eliminating BEM concatenation.
**Changed**
- A fix to the size of lightbox media viewer.
- A change to make sure lightbox media viewer is vertically scrollable when screen real estate is big horizontally, but small vertically.
- Attempts to best reuse CSS between React and Web Components versions of modal and lightbox media viewer, by eliminating BEM concatenation.
=> fix(lightbox-media-viewer): fix the size

packages/react/src/components/CTASection/README.stories.mdx, packages/react/src/components/CalloutWithMedia/README.stories.mdx, packages/react/src/components/CardSectionImages/README.stories.mdx, packages/react/src/components/CardSectionSimple/README.stories.mdx, packages/react/src/components/ContentBlockCards/README.stories.mdx, packages/react/src/components/ContentBlockMedia/README.stories.mdx, packages/react/src/components/ContentBlockMixed/README.stories.mdx, packages/react/src/components/ContentBlockSegmented/README.stories.mdx, packages/react/src/components/ContentBlockSimple/README.stories.mdx, packages/react/src/components/ContentGroupCards/README.stories.mdx, packages/react/src/components/ContentGroupHorizontal/README.stories.mdx, packages/react/src/components/ContentGroupPictograms/README.stories.mdx, packages/react/src/components/ContentGroupSimple/README.stories.mdx, packages/react/src/components/FeatureCardBlockLarge/README.stories.mdx, packages/react/src/components/FeatureCardBlockMedium/README.stories.mdx, packages/react/src/components/LeadSpace/README.stories.mdx, packages/react/src/components/LeadSpaceBlock/README.stories.mdx, packages/react/src/components/LogoGrid/README.stories.mdx
#3541 
Fixed codesandbox links on docs that were pointing to the patterns folder.
=> fix(docs): fixed codesandbox links pointing to old folders

packages/styles/scss/components/masthead/_masthead-megamenu.scss
Component: Mega Menu - greyed out Horizontal scroll bar is visible on all 5 menu drop down list. #3543
`overflow-y` should be set to scroll instead of `overflow-x` which was causing uneccessary horizontal scroll for megamenu to appear.
Occurs in windows chrome
BEFORE:
AFTER:
**Changed**
- set `overflow-y` to scroll instead of `overflow-x`
=> fix(MegaMenu): change overflow scroll style from x to y

packages/react/src/__tests__/__snapshots__/storyshots.test.js.snap, packages/react/src/components/LocaleModal/LocaleModal.js, packages/styles/scss/components/locale-modal/_locale-modal.scss
Component: Locale Modal (React) - Spacing issues on the modal. #3329
Adjustments based on the visual specs. 
**Changed**
- Icon `EarthFilled20` to `EarthFilled16`;
- Icon left margin from `8px` to `4px`;
=> fix(LocaleModal): changing icon size and margin

packages/services/src/services/Locale/Locale.js, packages/services/src/services/Locale/__tests__/Locale.test.js, packages/services/src/services/Translation/Translation.js
This change introduces an in-memory cache for in-flight requests of `LocaleAPI.getList()` and `TrasnlationAPI.getTranslation()` APIs.
It prevents multiple requests from getting in-flight, especially when multiple request of those happens in a short amount of time. In other words, without this change, the cache in `sessionStorage` from the 1st call of `LocaleAPI.getList()` hasn't been populated when 2nd call of `LocaleAPI.getList()` happens, given the response of the 1st call hasn't come.
**New**
- In-memory cache for in-flight requests of `LocaleAPI.getList()` and `TrasnlationAPI.getTranslation()` APIs.
=> chore(services): introduce REST cache

packages/react/src/__tests__/__snapshots__/storyshots.test.js.snap, packages/react/src/components/Masthead/MastheadLeftNav.js, packages/react/src/components/Masthead/__tests__/MastheadLeftNav.test.js, packages/react/src/components/carbon-components-react/UIShell/SideNavMenuWithBackForward.js
Add autoids to megamenu #3381
Fix format of mobile megamenu data-autoids.
**Changed**
- change position of `sidenav` in autoid: `dds--masthead-default__l0-sidenav` to `dds--masthead-default-sidenav__l0`
- ensure all instances of `<<SideNavMenuWithBackFoward />` get passed in `navType`
=> fix(MegaMenu): tweak data-autoids for the mobile navigation

packages/services/src/services/DDO/DDO.js, packages/web-components/.storybook/preview-head.html
Refs #3575.
This change adds `ibm-common.js` to Web Components' storybook, that populates DDO.
This fixes a bug of slow loading of masthead menu data caused by `DDOAPI.getAll()` polling for `window.digitalData` until its timed out.
**New**
- `ibm-common.js` to Web Components' storybook, that populates DDO.
=> fix(devenv): use ibm-common.js

packages/web-components/examples/codesandbox/components/dotcom-shell/.babelrc, packages/web-components/examples/codesandbox/components/dotcom-shell/.gitignore, packages/web-components/examples/codesandbox/components/dotcom-shell/index.html, packages/web-components/examples/codesandbox/components/dotcom-shell/package.json, packages/web-components/examples/codesandbox/components/dotcom-shell/sandbox.config.json, packages/web-components/examples/codesandbox/components/dotcom-shell/src/index.js, packages/web-components/examples/codesandbox/components/dotcom-shell/src/index.scss, packages/web-components/examples/codesandbox/components/dotcom-shell/src/links.js, packages/web-components/examples/codesandbox/components/footer/.babelrc, packages/web-components/examples/codesandbox/components/footer/.gitignore, packages/web-components/examples/codesandbox/components/footer/index.html, packages/web-components/examples/codesandbox/components/footer/package.json, packages/web-components/examples/codesandbox/components/footer/sandbox.config.json, packages/web-components/examples/codesandbox/components/footer/src/index.js, packages/web-components/examples/codesandbox/components/masthead/index.html, packages/web-components/src/components/dotcom-shell/__stories__/README.stories.mdx, packages/web-components/src/components/dotcom-shell/__stories__/dotcom-shell.stories.ts, packages/web-components/src/components/dotcom-shell/index.ts, packages/web-components/src/components/footer/__stories__/README.stories.mdx, packages/web-components/src/components/footer/__stories__/footer.stories.ts, packages/web-components/src/components/footer/locale-button.ts, packages/web-components/src/components/masthead/__stories__/README.stories.mdx, packages/web-components/src/components/masthead/__stories__/masthead.stories.ts, packages/web-components/src/components/masthead/index.ts
One of the discoveries made is that the store has to be initialized in order for
the Masthead to render properly. Rather than adding that to the documentation
for the `quick start` version, this entry point was created so that adopters 
do not need to do this on their own. Most adopters most likely won't need to 
bootstrap the redux store manually. Documentation has been add for application 
teams that do want to do that though.
Some other things added were the `dotcom-shell` code sandbox, as that appears
to be missing. 
The `getLang` attribute was also getting hardcoded into the storybook stories. 
This adds logic to only apply if using a mock.
**New**
- `dotcom-shell` codesandbox example
- `footer` codesandbox example
- new entry points for `dotcom-shell` and …
=> fix(masthead): added entry point to self-init redux store

packages/web-components/src/components/footer/__stories__/footer.stories.ts, packages/web-components/tests/snapshots/dds-footer-composite.md
This change ensures that the default footer story uses regular size.
Lack of this change caused the default footer story use short size when going to short story and then default story.
**New**
-  Code to ensure that the default footer story uses regular size.
=> chore(devenv): fix footer size

packages/web-components/src/components/dotcom-shell/__stories__/dotcom-shell.stories.ts
This change fixes a bug where Storybook knob for footer size in dotcom shell story was not working.
**Changed**
- A fix for a bug where Storybook knob for footer size in dotcom shell story was not working.
=> chore(devenv): fix footer size in dotcom shell

packages/web-components/src/components/dotcom-shell/dotcom-shell-container.ts, packages/web-components/src/components/footer/footer-container.ts
We made a quick fix to dotcom shell (in #3595) in a way that sends redundant property (`footerLinks`) to `<dds-footer-container>`, in standalone footer story. This change fixes the problem by having `<dds-dotcom-shell-container>`'s `mapStateToProps()` rename `links` property that `<dds-footer-container>`'s `mapStateToProps()` generates.
**Changed**
- A fix to ensure redundant property is not sent to `<dds-footer-container>` in standalone footer story.
=> chore(dotcom-shell): avoid redundant prop sent for standalont footer

packages/web-components/src/components/button/__stories__/button.stories.ts, packages/web-components/src/components/card-link/__stories__/card-link.stories.ts, packages/web-components/src/components/cta/__stories__/cta.stories.ts, packages/web-components/src/components/cta/__tests__/cta-container.test.ts, packages/web-components/src/components/dotcom-shell/__stories__/dotcom-shell.stories.ts, packages/web-components/src/components/footer/__stories__/footer.stories.ts, packages/web-components/src/components/footer/__tests__/footer-composite.test.ts, packages/web-components/src/components/footer/__tests__/footer-container.test.ts, packages/web-components/src/components/lightbox-media-viewer/__stories__/lightbox-media-viewer.stories.ts, packages/web-components/src/components/lightbox-media-viewer/__tests__/lightbox-media-viewer-container.test.ts, packages/web-components/src/components/link-with-icon/__stories__/link-with-icon.stories.ts, packages/web-components/src/components/link-with-icon/__tests__/link-with-icon.test.ts, packages/web-components/src/components/locale-modal/__stories__/locale-modal.stories.ts, packages/web-components/src/components/masthead/__stories__/masthead.stories.ts, packages/web-components/src/components/modal/__stories__/modal.stories.ts, packages/web-components/src/components/modal/__tests__/modal.test.ts
The preference of knob group names in Web Components codebase seems pascal cased names rather than component tag names. Changes the stories as such.
**Changed**
- Change knob group names in Web Components codebase seems pascal cased names rather than component tag names.
=> chore(devenv): change knob group names

packages/react/src/components/Masthead/Masthead.js
Mega Menu:- Accessibility :- Close icon (issues related to hamburger menu once it is expanded) #3584
Screen reader is reading the hamburger menu as "Open menu" even when the menu has been opened and the icon has changed to the `X` icon. Should change to "Close menu" when the hamburger menu is open.
**Changed**
- toggle `aria-label` of hamburger menu when menu is opened/closed
=> fix(MegaMenu): set correct aria label to hamburger menu when open/closed

packages/react/src/components/carbon-components-react/UIShell/SideNavMenu.js, packages/react/src/components/carbon-components-react/UIShell/SideNavMenuWithBackForward.js, packages/styles/scss/components/masthead/_masthead-leftnav.scss
Refs #3512.
This change fixes an issue where the list of parent menu items is larger than its overlayed child menu items and thus the bottom portion of the parent menu items is still shown even if child menu items are on top of them.
The problem is seen, at the point of the fix, when user navigates to "Products and Solutions" - "Supply Chain" and then user scrolls up the nav.
**New**
- `bx--side-nav__menu--hasactivechildren` CSS class and its corresponding CSS rules.
- `onToggle()` prop to `<SideNavMenu>`
- `<SideNavMenuWithBackForward>` code to add/remove `bx--side-nav__menu--hasactivechildren` CSS class upon `onToggle()` in `<SideNavMenu>`
=> fix(side-nav): cope with large list of parent menu items

packages/react/src/components/carbon-components-react/UIShell/SideNavMenu.js, packages/react/src/components/carbon-components-react/UIShell/SideNavMenuWithBackForward.js
Mega Menu:- Accessibility :- Back link (issues related to hamburger menu once it is expanded) #3587
Add button `role` to the back button of the mobile menu nav.
Also check for the Enter `charCode` of `13` to make sure back button works on key press.
**Changed**
- add `role="button"` for the back button
- check for `13` when `Enter` key is pressed for back button
=> fix(MegaMenu): assign button role for the back button in mobile menu

packages/web-components/src/components/footer/footer-logo.ts, packages/web-components/tests/snapshots/dds-footer-logo.md
Web component: Footer - IBM logo link is announced as slash link on iPhone. #3609
Add aria-label to the IBM logo in the footer for iphone voiceover
**Changed**
- add aria-label to ibm logo
=> fix(Footer): add aria label to IBM logo in footer

packages/web-components/src/components/masthead/left-nav.ts
Fixes a bug where left nav cannot be opened by `<dds-masthead-menu-button>`.
There was a bug in `<dds-left-nav>` where duplicate `HostListenerMixin` is in its prototype chain (class hierarchy) chain that made `@HostListner()` decorator for `bx-header-menu-button-toggled` event (which is defined in parent class `BXSideNav`) not working.
**Changed**
- Fix for a bug where left nav cannot be opened by `<dds-masthead-menu-button>`.
=> fix(left-nav): fix left nav not being able to open

packages/react/src/__tests__/__snapshots__/storyshots.test.js.snap, packages/react/src/components/LinkWithIcon/LinkWithIcon.js, packages/react/src/components/Masthead/MastheadMegaMenu/CategoryLink.js
[MM] When I scroll down and then up a menu, clicking on a mega menu doesn't take me to the destination - Safari only #3641
When clicking on a link in the megamenu, it triggers the `onBlur` function which checks for the `event.relatedTarget`. This is coming back null on safari. Adding `tabIndex={0}` makes the element appear in the `event.relatedTarget`
https://stackoverflow.com/questions/42764494/blur-event-relatedtarget-returns-null
**Changed**
- add `tabIndex={0}` to the megamenu links
=> fix(MegaMenu): add tabindex attr for safari not detecting event

packages/styles/scss/components/masthead/_masthead.scss
[MM] IBM logo changing positions in L0 when mobile menu is opened #3657
IBM logo was shifting when opening the mobile nav.
BEFORE: 
AFTER:
**Changed**
- remove padding when in between `md` and `lg` breakpoints
- set the hamburger icon position to `relative`
=> fix(MegaMenu): prevent shift of IBM logo when opening mobile nav

packages/react/src/components/carbon-components-react/UIShell/HeaderMenu.js
[MM] Attempting to scroll through the mega menu and the home page scrolls instead #3633
Disable the body scroll when user has megamenu open on desktop
**Changed**
- when megamenu is expanded, set body overflow-y style to `hidden`
=> fix(MegaMenu): disable body scroll when megamenu is open

packages/web-components/examples/codesandbox/components/dotcom-shell/src/index.js
The codesandbox looked out of date, fixing the import reference for the `dotcom-shell-container`.
**Changed**
- codesandbox for dotcomshell
=> chore(dotcomshell): fixed import reference in codesandbox example

packages/react/src/__tests__/__snapshots__/storyshots.test.js.snap, packages/react/src/components/Card/Card.js, packages/react/src/components/Card/__stories__/Card.stories.js, packages/react/src/components/CardGroup/CardGroup.js
The #3654 introduced a new card variation using a prop. But missed passing this prop trough the `CardGroup`, which is where I need to use it for the Support page. 
**New**
- `pictogram` prop being passed to `CTA` at `CardGroup`. This prop will, eventually, reach out to the `Card` component.
=> fix(CardGroup): passing pictogram prop to card from CardGroup

packages/react/src/components/Masthead/Masthead.js, packages/react/src/components/carbon-components-react/UIShell/HeaderMenu.js, packages/styles/scss/components/masthead/_masthead-leftnav.scss, packages/styles/scss/components/masthead/_masthead.scss
Component:- Masthead/Dotcom Shell(Stage) :- Scroll is not working on mega menu #3661
When user has mobile nav open and scrolls, the body scroll was getting triggered. Disable the body scroll when mobile nav is open.
**Changed**
- add `${prefix}--body__lock-scroll` class to the `body` when mobile nav is open. 
- `${prefix}--body__lock-scroll` sets the body to `overflow: hidden`
- add `64px` to the bottom of the mobile nav so that last menu item for menus that overflow can be seen when there is a bottom nav bar from browser
=> fix(MegaMenu): disable scrolling for mobile nav

packages/react/.storybook/webpack.config.js, packages/styles/.storybook/_container.scss, packages/styles/.storybook/webpack.config.js, packages/styles/scss/themes/expressive/README.md, packages/styles/scss/themes/expressive/index.scss
Refs #3698, #3643
Currently the only way for the theme to work is to enable CSS custom
properties in Carbon.
~This is a test to enable CSS Custom properties by default in the expressive theme.~
This approach does not work, so adding documentation on how to enable by default.
**Changed**
- enable `enable-css-custom-properties` by default
=> fix(expressivetheme): enable css custom properties with the theme

packages/react/src/components/Masthead/MastheadLeftNav.js, packages/styles/scss/components/masthead/_masthead-leftnav.scss
#3663 
I've added a focus sentinel so it prevent focus going out of the left menu while expanded.
=> fix(masthead): locked focus while left menu active

packages/react/README.md, packages/styles/README.md, packages/web-components/README.md
These are updated documentation for adopters on how to use the expressive theme. Since we have discovered that CSS custom properties needs to be enabled for it to work, this documentation needed to be included.
**Changed**
- READMEs changes
=> docs(expressivetheme): updating docs for expressive theme

packages/styles/scss/components/masthead/_masthead-leftnav.scss
[MM] In the hamburger menu, I'm unable to scroll down the menu for Learn & Support - What Is #3718
Add `overflow-y: auto` for the submenu as the "What is..." menu was not scrolling
**Changed**
- specify `overflow-y: auto`
=> fix(MegaMenu): add scroll for submenu

packages/web-components/src/components/footer/footer-composite.ts, packages/web-components/src/components/footer/locale-button.ts
The footer is missing the import for the locale modal, so this includes it.
**Changed**
- Adding locale modal import to the footer.
=> fix(footer): adding locale modal import to the footer

packages/web-components/src/components/locale-modal/locale-modal.ts
`<dds-locale-modal>` renders several other components in shadow DOM, but those components were not declaraed as the dependencies. Fixed that problem.
**New**
- Add missing imports in `<dds-locale-modal>`.
=> fix(locale-modal): add missing import

packages/react/src/components/Masthead/MastheadLeftNav.js, packages/styles/scss/components/masthead/_masthead-leftnav.scss
#3663
Added a sentinel in order to keep focus on the currently selected sub menu
=> fix(Masthead): keep focus in sub menus

packages/react/src/components/Masthead/MastheadSearch.js
Spotted a misaligned proptype definition for `MastheadSearch`.
**Changed**
- MastheadSearch propTypes
=> chore(masthead): fix to nav type proptype definition

packages/react/src/components/carbon-components-react/UIShell/HeaderMenu.js
[MM] My IBM maintaining focus when switching to mega menu #3617
[HP] [MM] multiple menus open at once #3731
The `<OverflowMenu />` component that we are using for the profile menu has logic to trap the focus when user clicks outside of the component. This affects the megamenu when user opens the profile menu, then clicks on the L0 nav item. The focus is trapped in the `<OverflowMenu />` which affects the `onBlur` event triggered used when opening another L0 nav item.
This PR forces focus on the L0 nav item when it is clicked.
**BEFORE:**
**AFTER:**
**Changed**
- force focus on the `HeaderMenu` L0 item
=> fix(MegaMenu): explicity set focus to HeaderMenu L0 item when clicked

packages/react/src/components/Masthead/MastheadMegaMenu/NavigationGroup.js, packages/react/src/components/carbon-components-react/UIShell/HeaderMenu.js, packages/styles/scss/components/masthead/_masthead-megamenu.scss
[MM]: When clicking on empty space, megamenu does not close causing stacking #3758
When user clicked on the empty space within the megamenu, the focus on the L0 nav item was lost causing issues with the `onBlur()` event. Also the `onClick()` event was placed on the wrapper container of the `<HeaderMenu />` which caused the menu to open and close unnecessarily. 
The `onClick()` event has been moved to specifically  the anchor tag so that the menu does not toggle its expanded state when user clicks anywhere within the menu. Adding `tabIndex` to the `<NavigationGroup />` (which is the container component for the megamenu) so that when user clicks on it, it will be captured in `event.relatedTarget` used in the `onBlur()` method otherwise it will render null. 
**BEFORE:**
**AFTER:** …
=> fix(MegaMenu): account for focus within the megamenu component

packages/web-components/src/components/locale-modal/locale-modal.ts, packages/web-components/src/components/locale-modal/locale-search.ts
Refs #3769 
This change resets the search query in locale selector upon being navigated from region selector.
**Changed**
- A change to reset the search query in locale selector upon being navigated from region selector.
=> fix(locale-search): reset query on page navigation

.eslintignore, .eslintrc, packages/react/src/components/carbon-components-react/UIShell/HeaderMenu.js, packages/react/src/components/carbon-components-react/UIShell/SideNavIcon.js, packages/react/src/components/carbon-components-react/UIShell/SideNavMenu.js, packages/react/src/components/carbon-components-react/UIShell/SideNavMenuWithBackForward.js, packages/react/src/components/carbon-components-react/UIShell/index.js
This change makes ESLint run against old React vendor files, a.k.a. `packages/react/src/components/carbon-components-react`.
Even though they are "vendor files", we seem to manually edit those files and good to catch errors there. Relaxed some rules for those files given the "vendor files" nature.
**New**
- A series of changes to make ESLint run against old React vendor files, a.k.a. `packages/react/src/components/carbon-components-react`.
=> chore(lint): lint old React vendor files

.github/workflows/ci-check.yml, packages/react/tests/integration/ui/setup-env.js, packages/web-components/src/components/masthead/__tests__/masthead.steps.js, packages/web-components/tests/integration/build/setup-env.js
This change attempts to further stabilize UI integration test in Web Components codebase, by avoiding to let `afterEach()` to reset the page and use `beforeEach()` for that instead.
Also increases the timeout for `page.goto()`.
**Changed**
- An attempt to further stabilize UI integration test in Web Components codebase, by avoiding to let `afterEach()` to reset the page and use `beforeEach()` for that instead.
- Increases the timeout for `page.goto()`.
=> test(integration-ui): navigation in beforeEach

packages/web-components/src/components/dotcom-shell/dotcom-shell.scss, packages/web-components/src/components/dotcom-shell/dotcom-shell.ts
This change fixes a problem where the `.css.js` file, the `lit-html` template for the compiled CSS, for `<dds-dotcom-shell>` was not generated by the build process. It caused an internal error in `lit-element` in an application.
This was caused by our JS code directly importing Sass code from `@carbon/ibmdotcom-styles`, where we should have had a corresponding `.scss` file in `@carbon/ibmdotcom-web-components`.
**New**
- `dotcom-shell.scss`, so our build process can generate `.css.js` file from `@carbon/ibmdotcom-styles/scss/components/dotcom-shell/_dotcom-shell.scss`.
=> fix(dotcom-shell): fix style imports

docs/building-for-ibm-dotcom.md, docs/contributing-license.md, docs/cors-proxy.md, packages/utilities/src/utilities/settings/settings.js, packages/web-components/examples/codesandbox/components/dotcom-shell/src/index.js, packages/web-components/examples/codesandbox/components/footer/src/index.js, packages/web-components/examples/codesandbox/components/masthead/src/index.js
Refs #3754 
The documentation for how `LocaleAPI` is fetching the language has been
updated. This reflects the logic where the `digitalData` is the first
source of the language/locale, followed by the html lang attribute.
Because of this, it was necessary to explain what the `digitalData`
object is first, before pointing out the specific fields that the
service is looking for.
Additionally, we will be setting `Carbon:IBM.com Library` as the default value
for the `version` that's being set in the `digitalData` object, as we have worked with 
Analytics team and want to set a default value based on the data we're seeing
in the analytics results.
**Changed**
- Updated documentation on setting language for the page
- Updated documentation for the version setting in DDO
=> docs(lang): updated documentation for setting the page language/locale

packages/web-components/src/components/locale-modal/locale-modal-composite.ts
Refs #3833.
Adds a logic to emit a console warning when `<link rel="alternate">` for alternate language is missing, that yeilds to an empty result in `<dds-locale-search>`.
**New**
- A logic to emit a console warning when `<link rel="alternate">` for alternate language is missing.
=> chore(locale-modal): warn missing links for alternate language

packages/styles/scss/components/footer/_locale-button.scss
#3771 
Update micro footer mobile layout styles causing locale button to position out of viewport
**Removed**
- `carbon--make-col` for `sm` breakpoint
=> fix(Footer): micro footer mobile layout styles

packages/utilities/src/utilities/ipcinfoCookie/ipcinfoCookie.js
Refs #3838
There was a discrepency identified where the cookie was being set under
`www.ibm.com` domain on the IBM.com homepage, whereas v18 was setting it
under `.ibm.com` on all other pages. When returning to the homepage and
clicking the logo, this caused the server-side level redirect rule to
kick in and create a garbled homepage url and causing a 404 to occur.
**Changed**
- Set the explicit domain when setting `ipcinfo` cookie
=> fix(ipcinfo): setting domain for the ipcinfo cookie

packages/styles/scss/components/content-block-simple/_content-block-simple.scss, packages/styles/scss/internal/content-block/_content-block.scss
#3454
Fixes `LinkList` spacing when used in `aside` element of `ContentBlock`
**Changed**
- update spacing in `ContentBlock` `<aside />` for `lg` breakpoint.
=> fix(LinkList): update styles in aside element

packages/services/src/services/Translation/Translation.js, packages/services/src/services/Translation/__tests__/Translation.test.js, packages/services/src/services/Translation/__tests__/data/response.json
Refs #3851 
The original implementation of the signin url for ibm included a string
replace of `{{window.location}}`, which was not accounted for in the IBM
.com Library. This adds a transformation logic now to replace the
default value in the data (state=https%3A%2F%2Fwww.ibm.com) and replace
with `state=[the actual window.location value]` in the service before
reaching the presentation layer.
**Changed**
- transformation logic in TranslationAPI to dynamically update the login url
=> fix(translation): adding string/replace of login url state param

packages/styles/scss/components/masthead/_masthead-leftnav.scss
#3504, #3510, #3516
Update `MegaMenu` mobile styles
**Changed**
- various css fixes to `MegaMenu` mobile styles
=> fix(Megamenu): update mobile styles

packages/web-components/src/components/card/card-footer.ts
This change fixes duplicate content shown in `<dds-card-cta-footer>`, was noticed in its video mode, showing video duration as `1:001:00` where it should have been `1:00`.
The change removes `_renderContent()` from the `render()`. The super class (`<dds-link-with-icon>`)'s `_renderInner()` takes care of running `_renderContent()`.
**Changed**
- A fix for duplicate content in `<dds-card-cta-footer>`.
=> fix(card-footer): fix duplicate content

packages/react/.env.example, packages/react/src/components/Masthead/Masthead.js, packages/react/src/components/Masthead/MastheadSearch.js, packages/react/src/components/Masthead/README.stories.mdx, packages/services/.env.example, packages/services/src/services/SearchTypeahead/SearchTypeahead.js, packages/services/src/services/SearchTypeahead/__tests__/SearchTypeahead.test.js, packages/vanilla/.env.example, packages/web-components/src/globals/services-store/actions/searchAPI.ts, tasks/jest/env.js
#3766 
This adds custom typeahead API support to masthead search. Also includes updated documentation to implement `customTypeaheadApi` and custom search redirect URLs.
**New**
- masthead prop `customTypeaheadApi` for user-defined typeahead API support
- `Masthead` documentation for custom typeahead and redirect 
**Changed**
- `SEARCH_TYPEAHEAD_HOST` changed to `SEARCH_TYPEAHEAD_API`
=> feat(search): add redirect and typeahead hooks

packages/react/src/components/Masthead/MastheadSearch.js
=> fix(masthead-search): no redirect when search input empty

packages/react/src/components/Masthead/Masthead.js
#3958 
Remove breakpoint calculation for masthead L0. New implementation will be added when final designs of navigation menu overflow are complete.
**Removed**
- masthead L0 visibility logic
=> fix(masthead): remove hide L0 logic

packages/styles/scss/components/content-group-cards/_content-group-cards.scss, packages/styles/scss/components/content-group-pictograms/_content-group-pictograms.scss
This change to content group style drifts away from BEM concatenation, so the style can be reused with Web Components.
**Changed**
- A change to content group style drifts away from BEM concatenation, so the style can be reused with Web Components.
=> chore(content-group): drift away from BEM concatenation

packages/styles/scss/components/content-block-cards/_content-block-cards.scss, packages/styles/scss/components/content-block-headlines/_content-block-headlines.scss
This change to content block style drifts away from BEM concatenation, so the style can be reused with Web Components.
**Changed**
- A change to content block style drifts away from BEM concatenation, so the style can be reused with Web Components.
=> chore(content-block): drift away from BEM concatenation

packages/styles/scss/components/masthead/_masthead-l1.scss, packages/styles/scss/components/masthead/_masthead-leftnav.scss, packages/styles/scss/components/masthead/_masthead-search.scss, packages/styles/scss/components/masthead/_masthead.scss
Refs #3471.
This change to masthead style drifts away from BEM concatenation, so the style can be reused with Web Components.
**Changed**
- A change to masthead style drifts away from BEM concatenation, so the style can be reused with Web Components.
=> chore(masthead): drift away from BEM concatenation

packages/styles/scss/components/image-with-caption/image-with-caption.scss
This change to image with caption style drifts away from BEM concatenation, so the style can be reused with Web Components.
**Changed**
- A change to image with caption style drifts away from BEM concatenation, so the style can be reused with Web Components.
=> chore(image-with-caption): drift away from BEM concatenation

packages/web-components/src/components/masthead/masthead-composite.ts, packages/web-components/src/components/masthead/masthead-menu-button.ts
Refs #3940.
Changes the element order of `<dds-left-nav>` vs. the rest of the masthead so VoiceOver cursor won't immediately go out as user moves VoiceOver cursor after opening left nav.
Also, deactivates the focus sentinel of `<dds-masthead-menu-button>` given it's not needed unless left nav opens and using it while left nav is closed adds redundant tab-stop.
**Changed**
- The element order of `<dds-left-nav>`.
- A change to deactivate the focus sentinel of `<dds-masthead-menu-button>` while left nav is closed.
=> fix(left-nav): change element order

packages/react/src/components/Masthead/MastheadTopNav.js, packages/react/src/components/carbon-components-react/UIShell/HeaderMenu.js
[Masthead]: when opening L1 dropdown, body scroll is disabled #3999 
Dropdown menus on the Masthead should allow for body scrolling as opposed to the MegaMenu which disables body scroll.
This PR passes in a `disableScroll` prop to the `<HeaderMenu />` component based on whether the menu is a MegaMenu or a regular dropdown. 
**New**
- `disableScroll` prop to the `<HeaderMenu />`
**Changed**
- use `disableScroll` to determine whether to disable scrolling
=> fix(Masthead): nav dropdowns should allow body scroll

packages/react/examples/codesandbox/components/DotcomShell/package.json, packages/react/examples/codesandbox/components/Footer/package.json, packages/react/examples/codesandbox/components/Masthead/package.json
This change locks `browserlist` and `caniuse-lite` versions to work around a bug that is recently introduced in either of the packages, that broke our build integration tests.
**Changed**
- A change to kock `browserlist` and `caniuse-lite`.
=> docs(examples): lock browserlist version

packages/web-components/src/components/locale-modal/locale-modal-composite.ts, packages/web-components/src/components/locale-modal/locale-modal.ts, packages/web-components/src/components/locale-modal/locale-search.ts, packages/web-components/tests/snapshots/dds-locale-modal-composite.md
Refs #3895.
This change adds `unavailability-label-text` attribute to `<dds-locale-search>` so it can show a different text when it gets an empty search result.
Also made some changes to ensure translation text for locale modal is in use fully.
**New**
- `unavailability-label-text` attribute to `<dds-locale-search>` so it can show a different text when it gets an empty search result.
**Changed**
- Some changes to ensure translation text for locale modal is in use fully.
=> fix(locale-modal): add missing text for unvailable locale

packages/services/src/services/VideoPlayer/VideoPlayer.js
#4012 
Add closed caption button to `VideoPlayer`.
**New**
- closed captioning button to Kaltura video player
=> feat(videoplayer): add closed captions

packages/styles/package.json
It was reported that the styles package was pulling in `carbon-components-react`, which is not necessary for the styles package itself but for the storybook generation for the expressive theme. This moves this dependency to `devDependencies` instead.
**Changed**
- Moved `carbon-components-react` to `devDependencies` for the styles package
=> fix(styles): adjusting carbon-components-react to dev dependency

packages/web-components/docs/coding-conventions.md, packages/web-components/src/components/card/card-footer.ts, packages/web-components/src/components/card/card.ts, packages/web-components/src/components/footer/footer-nav-group.ts, packages/web-components/src/components/image/image.ts, packages/web-components/src/components/locale-modal/locale-modal.ts, packages/web-components/src/components/modal/modal.ts
Starts using `@internalProperty()` decorator for all components so we don't have to manually call `requestUpdate()` to re-render the view upon change in `private`/`proptected` properties.
**Changed**
- A series of changes to use `@internalProperty()` decorator for all components.
=> chore(components): use internalProperty decorator

packages/web-components/src/components/card/card.ts, packages/web-components/src/components/content-block-simple/__stories__/README.stories.mdx, packages/web-components/src/components/content-block-simple/__stories__/content-block-simple.stories.ts, packages/web-components/src/components/content-block-simple/content-block-simple.ts, packages/web-components/src/components/content-block/content-block.ts, packages/web-components/src/components/content-item/content-item.ts, packages/web-components/src/components/feature-card-block-medium/feature-card-block-medium.ts, packages/web-components/src/components/footer/footer-nav-group.ts, packages/web-components/src/components/footer/footer.ts, packages/web-components/src/components/image/image.ts, packages/web-components/src/components/lightbox-media-viewer/lightbox-image-viewer.ts, packages/web-components/src/components/lightbox-media-viewer/lightbox-video-player.ts, packages/web-components/src/components/link-list/link-list.ts, packages/web-components/src/components/link-with-icon/link-with-icon.ts, packages/web-components/src/components/locale-modal/locale-modal.ts, packages/web-components/src/components/masthead/masthead-search-composite.ts, packages/web-components/src/components/masthead/masthead.ts, packages/web-components/src/components/quote/quote.ts
Adds JSDoc comments for named slots so Web Component Analyzer can harvest them and show them in our docs.
Also fixed the missing doc for `<dds-content-block-simple>`.
**New**
- JSDoc comments for named slots in several components.
**Changed**
- A fix for missing doc for `<dds-content-block-simple>`.
=> docs(components): add JSDoc comments for named slots

packages/web-components/src/components/button-group/__stories__/README.stories.mdx, packages/web-components/src/components/card-group/__stories__/README.stories.mdx, packages/web-components/src/components/card-link/__stories__/README.stories.mdx, packages/web-components/src/components/card/__stories__/README.stories.mdx, packages/web-components/src/components/feature-card-block-large/__stories__/README.stories.mdx, packages/web-components/src/components/feature-card-block-medium/__stories__/README.stories.mdx, packages/web-components/src/components/feature-card/__stories__/README.stories.mdx, packages/web-components/src/components/link-list/__stories__/README.stories.mdx
The exmaples shown originally were a bit misleading as embedding web
component markup on HTML would not yield an SVG when imported. This
shows how to use an SVG inlined and defining its slot when using in
conjunction with the IBM.com Library web components.
**Changed**
- Multiple READMEs for Web Components
- missing import for `feature-card-block-medium`
=> docs(svg): updating documentation for web components and svg imagery

packages/react/src/components/Masthead/Masthead.js, packages/react/src/components/Masthead/MastheadProfile.js, packages/react/src/components/Masthead/README.stories.mdx, packages/react/src/components/Masthead/__stories__/Masthead.stories.js, packages/react/src/components/SimpleBenefits/README.stories.mdx, packages/react/src/internal/FeatureFlags.js
#3854 
Adds custom login URL to masthead profile menu. This is an experimental feature.
**New**
- masthead profile login url can be user defined
**Removed**
- deprecated `primaryFocus` prop
=> feat(masthead): add custom profile login url

packages/web-components/src/components/masthead/masthead-container.ts
Removes a data type from `<dds-masthead-container>`, given it's defined in another file and no longer used.
**Removed**
- A data type from `<dds-masthead-container>`.
=> chore(masthead): remove data type

docs/enable-rtl.md, packages/react/.storybook/_container.scss, packages/react/.storybook/config.js, packages/react/docs/enable-rtl.stories.mdx, packages/web-components/docs/enable-rtl.stories.mdx
We have been seeing issues appear where RTL is not configured properly. This is due to adopters not enabling `rtlcss` in their applications, which will have applications render incorrectly if only `<html dir="rtl">` is set since some of our components use `rtlcss` directives.
**New**
- Documentation on enabling RTL
- Added documentation to `React` and `Web Components` storybooks
=> docs(rtl): adding documentation on how to enable RTL

packages/styles/scss/components/masthead/_masthead-search.scss
#4140 
Fix masthead platform name to remain visible until hamburger menu appears. Note this issue can be reproduced in all browsers, not only tablet/mobile devices.
**Changed**
- update responsive css for masthead platform name
=> fix(masthead): update platform name responsive css

packages/web-components/src/components/masthead/masthead.scss
Refs #4177.
The masthead nav overflow feature made tweaks to overflow style so it can keep track of overflowed content. It works with mega menu that "floats", but Web Components masthead menu with classic menu style still relies on the overflow area being visible. Introduces Web Components-specific style to fix that.
**Changed**
- Fix to masthead style so the overflow area is visible in Web Components, as masthead nav menu relies on that style.
=> fix(masthead): fix menu

.github/CONTRIBUTING.md, README.md, docs/contributing-license.md, docs/developing.md, package.json, packages/react/CHANGELOG.md, packages/react/docs/contributing-to-react.md, packages/react/src/components/Card/README.stories.mdx, packages/react/src/components/CardGroup/README.stories.mdx, packages/react/src/components/CardLink/README.stories.mdx, packages/react/src/components/HorizontalRule/README.stories.mdx, packages/react/src/components/Image/README.stories.mdx, packages/react/src/components/PictogramItem/README.stories.mdx, packages/services/CHANGELOG.md, packages/services/src/services/Analytics/README.md, packages/vanilla/.storybook/config.js, tasks/beta-releases.js, tasks/deploy_preview_comment.js, tasks/tag-release.js
This rename is mostly documentation. However, this does fix a CI build
issue with the comment creation script where it will need to point to
the new repo name.
**Changed**
- Changed repo link to `carbon-for-ibm-dotcom`
=> chore(rename): renaming to the new repo url

.github/workflows/publish-canary.yml, .github/workflows/publish-nightly.yml
This is a new github action that will publish the latest canary release,
then will trigger a dispatch event to the NextJS test and Web
Components HTML test environments to rebuild once the new canary
artifact is available.
Also adding in a nightly publish github action so that can also be moved
out of our other CI.
**New**
- `publish-canary.yml` workflow for publishing canary release, then sending dispatch to NextJS Text and Web Components HTML Test
- `publish-nightly.yml` workflow for publishing nightl release, every evening on workdays
=> chore(githubactions): adding github action for NPM publish Canary

packages/web-components/src/components/masthead/__tests__/masthead.steps.js
Refs #4158.
This change fixes the following in the UI integration tests for `<dds-masthead-*>`:
* A wrong selector for selecting a profile menu item.
* A redundant test for `<dds-masthead-search>`.
**Changed**
- Fixes the following in the UI integration tests for `<dds-masthead-*>`:
- A wrong selector for selecting a profile menu item.
- A redundant test for `<dds-masthead-search>`.
=> test(masthead): fix UI tests

.github/ISSUE_TEMPLATE/question.md
This is the rename of the support slack channel from `#ibm-digital-design` to `#carbon-for-ibm-dotcom`.
**Changed**
- Slack channel rename
=> docs(slack): rename support slack channel to `#carbon-for-ibm-dotcom`

packages/react/src/components/LightboxMediaViewer/LightboxMediaViewer.js
This property was causing the `LightboxMediaPlayer` to trigger the video even for the component closed/collapsed. 
**Removed**
- `autoPlay` prop from `VideoPlayer` at `LightboxMediaViewer`;
=> fix(lightbox-m-viewer): removing autoplay from VideoPlayer

packages/web-components/gulp-tasks/config.js
#3258 
The motivation of this PR is that a `yarn reset` would fail if the
vendor folder for the service store doesn't exist, primarily during a
`gulp clean`. In order to allow the `gulp clean` to continue, it cannot
have an exit code 1 if the folder doesn't exist, and just continue with
the clean.
The full `yarn install`/`yarn build` works afterwards, as the link works
after that.
**Changed**
- added null check for `servicesStoreESSrcDir` in gulp `config.js`
=> chore(services-store): added null check of services-store vendor folder

packages/react/src/components/DotcomShell/__stories__/DotcomShell.stories.js, packages/react/src/components/Masthead/__stories__/Masthead.stories.js
Adds `WithL1` story to `DotcomShell` in React Storybook
**New**
- `WithL1` story to `DotcomShell`
**Changed**
- clean up knobs in `Masthead: WithL1` story
=> chore(dotcomshell): add WithL1 story

packages/services/src/services/Locale/Locale.js, packages/services/src/services/Translation/Translation.js, packages/web-components/README.md, packages/web-components/examples/codesandbox/usage/handlebars/index.hbs, packages/web-components/examples/codesandbox/usage/handlebars/package.json, packages/web-components/examples/codesandbox/usage/handlebars/sandbox.config.json, packages/web-components/examples/codesandbox/usage/handlebars/src/index.js, packages/web-components/examples/codesandbox/usage/handlebars/src/index.scss, packages/web-components/examples/codesandbox/usage/handlebars/webpack.config.js
Introduces the guide to use our Web Components library with a server-side template like Handlebars, along with a CodeSandbox example.
**New**
- The guide to use our Web Components library with a server-side template like Handlebars
- CodeSandbox example for above usage.
=> docs(template): introduce Handlebars example

packages/styles/scss/components/card/index.scss, packages/web-components/src/components/link-list/link-list.scss
Fix focus styles for web components `LinkList`
**Changed**
- `LinkList` focus styles
=> fix(linklist): fix linklist focus styles

.github/workflows/publish-nightly.yml
The github build ID was improperly set to the dist tag and not preid.
**Changed**
- `publish-nightly.yml`
=> fix(nightly): fix to preid

packages/react/src/components/LightboxMediaViewer/LightboxMediaViewer.js
For some reason, removing the `autoPlay` prop from `VideoPlayer` at the `LightboxMediaViewer` is causing:
- the video thumb to not fully occupy the available space for the video;
- the lightbox media viewer to close on video click.
=> fix(lightbox-m-viewer): adding again `autoPlay` to video

packages/react/src/components/Masthead/MastheadMegaMenu/CategoryGroup.js, packages/styles/scss/components/masthead/_masthead-megamenu.scss
fixes #4078 
What a fickle little layout problem we have here. I saw we were having trouble with this and had an idea of how to fix it. Basically, I threw in one or two wrapping divs to help protect the content, and render consistently across the board. It looks like it's working from my perspective and understanding, but let me know if I missed some consideration here.
**Changed**
- Added two new divs to help protect content and help fix
=> fix(megamenu): added protection to fix layout problem

packages/web-components/docs/enable-rtl.md, packages/web-components/docs/enable-rtl.stories.mdx, packages/web-components/examples/codesandbox/usage/rtl/index.hbs, packages/web-components/examples/codesandbox/usage/rtl/package.json, packages/web-components/examples/codesandbox/usage/rtl/sandbox.config.json, packages/web-components/examples/codesandbox/usage/rtl/src/index.js, packages/web-components/examples/codesandbox/usage/rtl/webpack.config.js, packages/web-components/src/components/masthead/masthead.scss
Refs #3772.
Introduces a CodeSandbox example that demonstrates how our adaptors can create a RTL page with `@carbon/ibmdotcom-web-components`, as well as its corresponding documentation.
Also fixes an issue that the left nav overlay is not flipped for RTL.
**New**
- RTL CodeSandbox example.
- Documentation on how to use RTL.
=> docs(example): introduce RTL example

packages/services/src/services/Locale/Locale.js, packages/services/src/services/Locale/__tests__/Locale.test.js, packages/services/src/services/Locale/__tests__/data/timestamp_response.json
#3959 
As done in [TranslationAPI](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/4240), this PR adds a new timestamp property within the response json to compare with the current time. If the timestamp is older than two hours, a new response will be fetched with a new, current timestamp.
Also implemented tests for the new methods.
**New**
- `timestamp` property added to the response json for cache busting purposes
=> feat(locale): introducing cache busting logic

packages/react/src/components/Footer/Footer.js, packages/react/src/components/Footer/LanguageSelector.js, packages/react/src/components/Footer/README.stories.mdx, packages/styles/scss/components/footer/_language-selector.scss, packages/styles/scss/components/footer/_legal-nav.scss
#4330, #4331 
This change adds Carbon's `Select` component for the footer language selector in mobile/tablet breakpoints. Desktop views will continue to use `ComboBox`.
**Changed**
- `Footer` language selector now uses Carbon's `Select` instead of `ComboBox` for mobile/tablet breakpoints
- updated various styles for new component
=> fix(language-selector): update language selector to use select

packages/web-components/src/components/button-group/button-group.scss
#4347 
In ButtonGroup, whenever the user focuses on any button (by pressing or tabbing), the focus outline extends past the button as pictured below.
Before:
After:
**New**
- added new css properties for `button-group.scss` specific to the web components version
=> fix(button-group): fixed focus outline going past the buttons on web components

packages/web-components/src/components/button-group/button-group.scss
Refs #4348.
Fixes duplicate focus outline in `<dds-button-group-item>`, that made the focus outline too thick. Also given the earlier workaround for such duplicate focus outline issue is no longer needed, removed it.
**Removed**
- The redundant focus outline on `<dds-button-group-item>`
- The earlier workaround for above issue.
=> fix(button-group): eliminate duplicate outline

packages/web-components/src/components/masthead/__stories__/README.stories.mdx
**Changes**
- Fix wrong doc for custom search box implementation, where `dds-masthead-search-input` event name instead of `input` should be used.
=> docs(masthead-search): fix wrong event name in the doc

packages/styles/scss/components/buttongroup/_buttongroup.scss
The explicit declaration of `top` and `bottom` positioning fixed the icon's alignment on iOS devices.
**Previous**
**Current**
**New**
- `bottom` and `top` set to `13px` at the button's icons.
=> style(button-group): fixing alignment for icons on iOS

docs/building-for-ibm-dotcom.md, packages/utilities/src/utilities/settings/settings.js
After renaming to `Carbon for IBM.com`, our version was renamed but
retained the `Carbon:` prefix as it was originally `Carbon:IBM.com
Library`. Now that we have Carbon in the name, it is a bit redundant to
have the prefix now.
**Changed**
- DDO version
=> chore(ddo): removing redundant carbon in version text

packages/styles/scss/components/content-item-horizontal/_content-item-horizontal.scss
#4400
heading needs additional styling for smaller breakpoints
**New**
- added display block so margin is correctly applied
=> fix(content-item-horizontal): fix heading styling

packages/react/src/components/Footer/README.stories.mdx, packages/web-components/src/components/footer/__stories__/README.stories.mdx
#4346 
Add `dds--privacy-cp` to stable selector documentation for both React and web components.
**New**
- `dds--privacy-cp` stable selector added to docs
**Changed**
- fixed typos in docs
=> fix(Footer): update readme

packages/web-components/examples/codesandbox/components/card/index.html, packages/web-components/examples/codesandbox/components/content-item-horizontal/index.html, packages/web-components/examples/codesandbox/components/feature-card-block-large/index.html, packages/web-components/src/components/card/__stories__/README.stories.mdx, packages/web-components/src/components/card/__stories__/card.stories.ts, packages/web-components/src/components/content-item-horizontal/__stories__/content-item-horizontal.stories.ts, packages/web-components/src/components/content-item-horizontal/__tests__/content-item-horizontal.test.ts, packages/web-components/src/components/feature-card-block-large/__stories__/feature-card-block-large.stories.ts, packages/web-components/src/components/feature-card-block-medium/__stories__/README.stories.mdx, packages/web-components/src/components/feature-card/__stories__/feature-card.stories.ts
Replaces `<slot>` elements used in light DOM with `<span>`, as `<slot>` is for defining a placeholder in Shadow DOM, instead of using such placeholder.
**Changed**
- Replaces `<slot>` elements used in light DOM with `<span>`.
=> chore(components): replace slot in light DOM

packages/web-components/src/components/masthead/left-nav-menu.ts, packages/web-components/src/components/masthead/masthead-composite.ts, packages/web-components/tests/snapshots/dds-masthead-composite.md
#3849 
Adds megamenu to left nav (mobile view)
**Changed**
- add nested left nav menu for megamenu links
- replace `ArrowLeft16` with `ChevronDown20` for back button
=> feat(Masthead): add mobile megamenu

tasks/get-changelog.js
This is a modification of the changelog generation script to split up
the commit changes based on changes in each package folder. This will
help with separating out the logs based on the changes that went on in
the corresponding package folders in an automated way. From what I could
tell, there is no existing open source package that can generate the
logs in the desired way.
The pinned issue has been updated using the script:
https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/3598
NOTE: one thing I did notice in one library during my research that I liked is where it was putting all of the line items with the same heading and grouping the changes into sub-bullets. Might look at that for an enhancement to the script, as well as alphabetically ordering the …
=> chore(changelog): updating changelog script to separate by folder

packages/react/src/components/Masthead/MastheadSearch.js, packages/react/src/components/Masthead/README.stories.mdx
#4398 
Adds several custom events to masthead search.
**New**
- adds `onOpenSearch`, `onSearchCloseClicked`, `onSearchButtonClicked`, `onSearchValueChanged` custom events to masthead search
- add custom event documentation
=> feat(Masthead): add search custom events

packages/web-components/src/components/link-list/link-list.scss
#3366
The horizontal rules from LinkList now overhang in order to make the links match with the text above.
**Removed**
- unnecessary left padding that made horizontal rules align with text instead of overhanging
=> fix(cta-section): aligning link list with other text elements

packages/web-components/src/components/link-list/link-list-item-card.ts, packages/web-components/src/components/link-list/link-list-item.ts
Web component: Link List - In iPhone VO there is no role for the mentioned links #4061
Change the role to link from link-list item and card for screen readers. Previously it was set to `listitem` which does not let screen reader users know that it's actually a clickable link.
**Changed**
- change `role` for `link-list-item` and `link-list-card` to `link`
=> fix(link-list): change role for link-list items to link

packages/web-components/src/components/link-list/link-list-item-card.ts, packages/web-components/src/components/link-list/link-list-item.ts
Refs #4061.
Makes `<dds-link-list-item>`'s host element's a11y role back to `<listitem>` as the host element works as `<li>` and the `<a>` is rendered into Shadow DOM.
The earlier change that made `<dds-link-list-item>`'s host element's a11y role to `link` was from a testing from ChromeVox, but some links tell that ChromeVox does support Shadow DOM. Also, in native Chrome DevTools, the a11y tree inspector correctly shows `link` role in `<a>`, and in desktop/mobile Safari VoiceOver correctly announces the `<a>`s in Shadow DOM as links.
**Changed**
- `<dds-link-list-item>`'s host element's a11y role back to `listitem`
=> fix(link-list): make item role back to listitem

packages/styles/scss/components/dotcom-shell/_dotcom-shell.scss, packages/styles/scss/components/masthead/_masthead.scss
#4334 
This addresses various `TableOfContents` CSS issues when it is contained in the `DotcomShell`.
**Changed**
- update `TOC` styles to position itself correctly when contained in the `DotcomShell`
=> fix(tableofcontents): fix top positions in dotcomshell

packages/react/src/components/Masthead/__stories__/data/MastheadLinks.js, packages/styles/scss/components/masthead/_masthead-l1.scss, packages/styles/scss/components/masthead/_masthead-search.scss, packages/styles/scss/components/masthead/_masthead.scss, packages/web-components/src/components/masthead/masthead.scss
[Masthead]: Dropdown menu items are appearing on scroll within the masthead nav bar #4504
The dropdown menu was appearing within the nav bar and user had to scroll within the nav bar to see the menu items. Setting the overflow to visible allows the dropdown to be visible outside of the nav bar
**Changed**
- removed the `hasMegapanel` field from one of the nav links in the masthead story data file so this fix is easily testable in storybook (be sure to set the `navigation knob` to `custom` in order to test)
- set `bx--header__search` and `bx--header__nav-container` div `overflow-x` to `visible` so the dropdown is visible outside of the nav bar
- set the z-index and background colors for the IBM logo, search, and profile buttons so it doesn't clash with the overflowing nav items
**Removed** …
=> fix(Masthead): regular dropdown menu visible outside of masthead nav bar

packages/web-components/src/components/logo-grid/__stories__/logo-grid.stories.ts
#4427 
The Web Components story version of `LogoGrid` was using different layout classes than the React version, making the cards appear smaller. The updated story now includes the same classes as the React version, now showing their size as intended.
**Changed**
- changed story grid layouts to match the React story version of `LogoGrid`
=> fix(logo-grid): changing story styles to adhere to react version

packages/react/src/components/LinkList/__stories__/LinkList.stories.js, packages/web-components/src/components/link-list/__stories__/link-list.stories.ts
#4058 
Update React and web components `LinkList` link text to be more descriptive.
**Changed**
- update link text in story
=> chore(LinkList): update story links

packages/react/src/components/carbon-components-react/UIShell/SideNavMenu.js
React: Masthead - On iPhone Voice over, sub menu options are not identified #4526
Change the `role` from tab to `menuitem` and also change `aria-selected` from `false` to empty string so the screenreader doesn't read "not selected" for every menu item.
**Changed**
- change role to menu item
- return empty string for `aria-selected`
=> fix(Masthead): change side nav menu item role to menuitem

packages/styles/scss/components/masthead/_masthead.scss
#4525 
add styles so menu-items that are partially hidden stay hidden when clicked
**New**
- `z-index: 0` to `li`
=> fix(masthead): menu-item styles

packages/styles/scss/components/leadspace/_leadspace.scss, packages/web-components/.storybook/config.ts, packages/web-components/src/components/leadspace/__stories__/leadspace.stories.ts, packages/web-components/src/components/leadspace/leadspace.scss, packages/web-components/src/components/leadspace/leadspace.ts, packages/web-components/tests/snapshots/dds-leadspace.md
Refs #4250.
Refs #4285.
Made the following enhancements/fixes to the gradient in `<dds-leadspace>`:
* Auto-updates the gradient color upon `--cds-ui-background` CSS custom property, by using `<svg>` instead of CSS `background-image`. Upon this change, `theme` attribute is removed from `<dds-leadspace>`.
* Workarounds Safari's issue where `trasnparent` means `rgba(0, 0, 0, 0)`.
Also changes `gradient` boolean attribute to `gradient-style-scheme`, to make sure the code is forward-compatible with additional options.
**Changed**
- Switch to `<svg>` for gradient, so that `<dds-leadspace>` auto-switches the gradient upon theme change.
- A change to workaround Safari's issue where `trasnparent` means `rgba(0, 0, 0, 0)`.
- `gradient` boolean attribute to `gradient-style-scheme`.
**Removed**
- …
=> fix(leadspace): fix gradients

packages/react/src/components/carbon-components-react/UIShell/SideNavMenu.js
React: Masthead - On iPhone Voice over, sub menu options are not identified #4526
On iphone VO, with swipe, the focus goes to the `<li>` element instead of the button where the label to be read out is. Removing the `role` attribute from the `<li>` and moving the `aria-selected` attribute to the button instead allows for the focus to be on the button on swipe.
**Changed**
- set `aria-selected` attribute to the menu item button
**Removed**
- `role` attribute from wrapper `<li>` element
=> fix(SideNavMenu): remove role from li wrapper on menu item buttons

packages/styles/scss/components/masthead/_masthead-search.scss
#4539 
Fix IPad ios13 issues with overflow menu items showing next to platform name. 
**New**
- add top: -2px to ::after platform styles
=> fix(masthead): overflow style fix

packages/styles/scss/components/footer/_language-selector.scss
React: Footer - Short language only - label is displayed in the background. #4551
Set the Language Selector label to visibility hidden
BEFORE:
AFTER:
=> fix(LanguageSelector): set language selector label visibility to hidden

packages/react/src/components/Footer/LanguageSelector.js
#4550 
Fixes an error when clearing the current language selector value
**New**
- add `placeholder` value to language selector text input
**Changed**
- check for `null` value when clearing language selector text input
=> fix(Footer): fixes language selector clear

packages/styles/scss/components/link-list/_link-list.scss
Fixes `card` styles used in `LinkList` that were affected by aspect ratio changes in https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/4542.
**incorrect aspect ratio styles being applied**
**Changed**
- aspect ratio removed from `card` styles
- remove unused css
=> fix(LinkList): fix card styles

packages/services/src/services/Translation/Translation.js
Another fix to support our translation service to run in node.js environment, by using session storage only if it's available.
**Changed**
- A change to our translation service code to use session storage only if it's available.
=> fix(translation): support for running in node.js environment

packages/web-components/README.md
There was a typo in the first line of the README, this is also a slight
adjustment to the wording.
**Changed**
- minor tweak to `README.md` in web components
=> docs(readme): fix to the web components README.md

packages/styles/scss/components/buttongroup/_buttongroup.scss
#4292 
Fixes button wrapping.
**Changed**
- add `flex-wrap` to `ButtonGroup` styles in large breakpoint
=> fix(ButtonGroup): add flex wrap to large breakpoint

packages/react/src/components/Masthead/__stories__/Masthead.stories.js
This re-introduces the `inPercy` check to check against mock data for visual snapshots that was mistakenly removed in https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/4617.
**New**
**Changed**
**Removed**
=> chore(masthead): fix percy mock data for storybook

packages/react/src/components/LocaleModal/LocaleModal.js, packages/react/src/components/LocaleModal/LocaleModalRegions.js, packages/web-components/src/components/locale-modal/locale-modal.ts, packages/web-components/tests/snapshots/dds-locale-modal.md
Fixed the bug where Storybook refreshes entire page upon clicking the `LinkWithIcon` component to go back to the Selection geographic area menu.
It was caused by using `href='#`, which made the page redirect to the `iframe` address url over Storybook's. With this change, the component will stop the `href` from activating and fall back to the original functionality.
**New**
-- added `e.preventDefault()` to the event handlers
=> fix(locale-modal): replaced href target to avoid storybook refresh

packages/styles/scss/components/card-group/_card-group.scss, packages/web-components/src/components/card-group/__stories__/card-group.stories.scss, packages/web-components/src/components/card-group/__stories__/card-group.stories.ts, packages/web-components/src/components/card-group/card-group.scss
Refs #4375.
Switches flex-box-bassed Carbon grid layout system to native CSS grid so we can apply same height to all cards upon card contents.
**Changed**
- Switches flex-box-bassed Carbon grid layout for `<dds-card-group>` to native CSS grid.
=> fix(card-group): same height by CSS grid

packages/web-components/src/components/locale-modal/locale-modal.scss, packages/web-components/src/components/locale-modal/region-item.ts, packages/web-components/tests/snapshots/dds-region-item.md
#4628 
Add missing markup structure of `region-item` that was affecting layout of region cards
**Changed**
- add missing `content` div
=> fix(LocaleModale): region card layout

packages/web-components/src/components/locale-modal/locale-search.ts, packages/web-components/tests/snapshots/dds-locale-search.md
Web component: Locale selector - list of options (locations and languages) are not identified by the screen reader. Only a "List box" is identified #4668
Remove the "listbox" role from the locale modal options as screen reader user will think it is a dropdown and try to navigate using up/down arrow keys.
**Removed**
- remove "listbox" role from locale modal language options list
=> fix(locale-modal): remove listbox role for accessibility

packages/web-components/src/components/footer/footer-composite.ts, packages/web-components/src/components/footer/locale-button.ts
#4667
Added `aria-label` to the locale button in order to provide an accessible description of its purpose in Web Components.
**New**
- added `aria-label="Select geographic area"` to `locale-button`
=> fix(footer): added label to locale button for better description

packages/web-components/src/components/footer/footer.scss
Refs #4676.
Adds a change to align the style of cookie preference link in micro footer to other legal nav items.
**Changed**
- A change to align the style of cookie preference link in micro footer to other legal nav items.
=> fix(legal-nav): align cookie preference to other nav items

packages/web-components/src/components/masthead/masthead-composite.ts, packages/web-components/src/components/masthead/top-nav.ts
Refs #4677.
**Changed**
- A change to avoid rendering L0 if L1 is there.
=> fix(masthead): avoid rendering L0 if L1 is there

packages/web-components/src/components/masthead/masthead-composite.ts, packages/web-components/src/components/masthead/top-nav.ts
Reverts carbon-design-system/carbon-for-ibm-dotcom#4679
=> chore(masthead): reverts fix on release branch, avoid rendering L0 if L1 is there

packages/react/src/components/ButtonGroup/ButtonGroup.js, packages/styles/scss/components/buttongroup/_buttongroup.scss, packages/styles/scss/components/carousel/_carousel.scss, packages/styles/scss/components/video-player/_video-player.scss, packages/web-components/src/components/button-group/button-group.ts, packages/web-components/src/components/carousel/carousel.ts, packages/web-components/src/components/masthead/megamenu-top-nav-menu.ts
Refs #4375.
Uses CSS grid for the same width effect for better performance and fix FOUC.
**New**
- A static property to `<dds-megamenu-top-nav-menu>` for its component-level CSS custom properties, to align the coding pattern to the rest of the codebase.
**Changed**
- Switches from JavaScript code to CSS grid for the same width effect.
- Renamed component-level CSS custom properties to unify their format.
**Removed**
- A prop in React `<ButtonGroup>` that enables/disables JavaScript-based same width effect.
- Some redundant CSS rules in button group.
=> chore(button-group): same width effect by CSS grid

packages/react/src/components/CardGroup/CardGroup.js, packages/styles/scss/components/card-group/_card-group.scss, packages/web-components/src/components/card-group/card-group.scss
Refs #4693.
Switches flex-box-bassed Carbon grid layout system to native CSS grid so we can apply same height to all cards upon card contents.
**Changed**
- A change to switch flex-box-bassed Carbon grid layout system to native CSS grid.
=> chore(card-group): same height by CSS in React

packages/web-components/src/components/dotcom-shell/__stories__/README.stories.mdx, packages/web-components/src/components/dotcom-shell/dotcom-shell-composite.ts, packages/web-components/src/components/footer/footer-composite.ts
Refs #4684.
**New**
- `disable-locale-button` attribute to `<dds-footer-composite>` and `<dds-dotcom-shell-composite>`.
=> feat(footer): support forcing omitting locale button

packages/web-components/src/components/footer/footer.scss
Refs #4676.
Adds a change to align the style of cookie preference link in micro footer to other legal nav items.
**Changed**
- A change to align the style of cookie preference link in micro footer to other legal nav items.
=> fix(legal-nav): align cookie preference to other nav items (#4680)

packages/web-components/src/components/cta-section/cta-section.scss
#4472
#4474
Different copy text caused uneven height between the two components. This PR uses CSS `grid` feature to make both elements be the same height without any complicated or time-consuming code.
**New**
- added `display: grid` for `cta-section-item-paragraph` to match sibling element's height
**Removed**
- unused styles for `slotted(p)` within `cta-section-item-copy`
=> fix(cta-section): same height by CSS for copy text

packages/react/src/components/CardGroup/CardGroup.js
Noticed this was pointing to `Card` when the code was using `CTA`. Figured I would update it to help out. Without it, adopters can't find the types allowed to pass in.
> Side question: Is there a reason Card is still a dependency in here, and we're not using CTA for that?
**Changed**
- Card to CTA link reference.
=> docs(cta): update documentation link to proper dependency

packages/styles/scss/themes/expressive/components/_ui-shell.scss
Visual Regression | Carbon Expressive | UI Shell Sidenav item heights are smaller #3524
Height for UI Shell sidenav changed when upgrading carbon, this pr adjusts the heights back to the expected expressive height.
=> fix(ui-shell): adjust ui shell for expressive from carbon update

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/contribution_request.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md
Refs https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/4605
This adds a new issue template for contributors wishing to contribute to `Carbon for IBM.com`, and tracking its work.
**New**
- `contribution_request.md`
**Changed**
- updated roster for other issue templates
=> chore(github-template): adding `Contribution Request` issue template

packages/web-components/src/components/leadspace/leadspace.ts, packages/web-components/tests/snapshots/dds-leadspace.md
Added `::part` pseudo-element to `leadspace`
**New**
- `::part` pseudo element in `leadspace.ts`
=> feat(leadspace): added ::part pseudo-element to component

packages/web-components/examples/codesandbox/components-react/carousel/package.json
The Carousel React Webcomponents codesandbox example failed to compile the example with 
Error: Cannot find module '@babel/core' babel-loader@8 requires Babel 7.x (the package '@babel/core'). If you'd like to use Babel 6.x ('babel-core'), you should install 'babel-loader@7'.
- Added babel core to package.json under devDependencies
=> Added babel core to devDependencies

packages/styles/scss/components/feature-card/_feature-card.scss
There are some cases where the `feature-card` image aspect ratio mixin is bugging the image height. Define an explicit `height: 100%` would solve the problem.
**Changed**
- Explicit `height: 100%` to `feature-card` image.
=> style(feature-card): fixing img aspect ratio

packages/styles/scss/components/leadspace/_leadspace.scss
After the `::part` pseudo-element introduction (#4752) to change the leadspace height according to the Partner world landing page requirements, I've missed adding an explicit `height: 100%` declaration for the wrappers below it. This is causing the leadspace to be visually broken for the `md` and `sm` breakpoints.
=> style(leadspace): added explicit height declaration for sections

packages/styles/scss/components/dotcom-shell/_dotcom-shell.scss
This `min-height: 100vh` property was causing the `/build` page to be taller than it should.
=> fix(dotcom-shell): removing min-height from dotcom-shell

packages/react/package.json, packages/styles/package.json, packages/web-components/package.json
Bumps `@carbon/ibmdotcom-styles` package to version `1.14.0`
**Changed**
- updates `@carbon/ibmdotcom-styles` dependency package to `1.14.0`
=> chore(deps): bump styles package version to 1.14.0

packages/services-store/package.json, packages/web-components/package.json, packages/web-components/src/components/carousel/carousel.ts, packages/web-components/src/components/dotcom-shell/dotcom-shell-composite.ts, packages/web-components/src/components/masthead/megamenu-top-nav-menu.ts, packages/web-components/src/components/table-of-contents/table-of-contents.ts, packages/web-components/src/components/video-player/video-player-container.ts, yarn.lock
Refs #4101.
To `3.7`, to cover Angular8 users with minimum effort in user side.
**Changed**
- Downgrades TypeScript to `3.7`.
=> chore(dependencies): downgrade TypeScript

packages/services/src/services/Locale/Locale.js, packages/services/src/services/Translation/Translation.js
Footers not displaying properly in FF incognito #4737
Firefox's private window has tracking protection enabled by default that blocks the ibm.com endpoint api calls so users don't see the footer or masthead populated when using the private window.
Solution is to swap the translation host from ibm.com to the akamai endpoint instead.
**Changed**
- set the default host for Locale and Translation api to akamai
=> fix(Footer): swap out translation host default endpoint for FF

packages/web-components/src/components/masthead/top-nav.ts
Refs #4814.
Ensures `IntersectionObserver` in `<dds-top-nav>` is re-created when the nav content is shown after it's hidden, to avoid stale DOM node references.
**Changed**
- A change to ensure `IntersectionObserver` in `<dds-top-nav>` is re-created when the nav content is shown after it's hidden.
=> fix(masthead): recreate IntersectionObserver upon showing/hiding nav

packages/web-components/src/components/leadspace/__stories__/README.stories.mdx, packages/web-components/src/components/leadspace/__stories__/leadspace.stories.ts, packages/web-components/src/components/leadspace/leadspace.ts, packages/web-components/tests/snapshots/dds-leadspace.md
Refs #4627.
Changes `<slot name="buttons">` to `<slot name="action">` to align the naming strategy to `<dds-cta-section>`.
**Changed**
- Changes `<slot name="buttons">` to `<slot name="action">`.
=> refactor(leadspace): reorganize slots

packages/web-components/src/components/content-block-segmented/content-block-segmented.ts, packages/web-components/src/components/content-block-simple/content-block-simple.ts, packages/web-components/src/components/content-group-cards/content-group-cards.ts
Fixes stale `@slot` JSDoc comments of `<dds-content-block>` descendants by re-using the JSDoc comments of `<dds-content-block>` themselves.
**Changed**
- Fixes stale `@slot` JSDoc comments of `<dds-content-block>` descendants.
=> docs(content-block): update JSDoc

packages/web-components/src/components/masthead/masthead.scss
Web component: Masthead - On hover over the menu options, background color is black #4734
Removing the dark background from `dds-top-nav-menu-item`
=> fix(masthead-top-nav-menu-item): removing the dark background

.github/workflows/deploy-canary.yml, .github/workflows/deploy-staging.yml
Change profile endpoint on Carbon Masthead for signed in state #4701
Add the PROFILE_HOST env variable for our canary and staging storybook environments
**New**
**Changed**
**Removed**
=> chore(github-workflow): update test environments with profile host env variable

packages/web-components/src/components/carousel/__stories__/carousel.stories.react.tsx, packages/web-components/src/components/carousel/__stories__/carousel.stories.ts
Refs #4918.
Removes `page-size` knob from the stories of carousel given user may get too large number there where our demo in storybook will look very weird.
**Removed**
- `page-size` knob in carousel story.
=> docs(carousel): remove page-size knob

.github/workflows/deploy-canary.yml, .github/workflows/deploy-staging.yml
Change profile endpoint on Carbon Masthead for signed in state #4701
Add the profile host env var to various testing envs
previously added the variable to only react testing envs
deploy-canary:
- react-experimental
- react-rtl
- web-components
- web-components-rtl
- web-components-experimental
- web-components-react
- services
deploy-staging:
- web-components
=> chore(github-workflow): add profile host env var to various testing envs

packages/styles/scss/components/masthead/_masthead-l1.scss
#4920 
Changes the target breakpoint in the media query to not include the breakpoint itself. This was causing the `L1` to be hidden in all conditions. See [this](https://github.com/carbon-design-system/carbon/pull/5791) PR for more details.
**Changed**
- change `L1` responsive breakpoint to `799.98px` to exclude the breakpoint target (`800px`)
=> fix(masthead): update L1 responsive breakpoint

packages/services-store/src/actions/__tests__/profileAPI.test.ts, packages/services-store/src/actions/profileAPI.ts, packages/services-store/src/reducers/__tests__/profileAPI.test.ts, packages/services-store/src/reducers/profileAPI.ts, packages/services-store/src/types/profileAPI.ts, packages/web-components/src/components/dotcom-shell/dotcom-shell-composite.ts, packages/web-components/src/components/masthead/__stories__/masthead.stories.ts, packages/web-components/src/components/masthead/masthead-composite.ts, packages/web-components/src/components/masthead/masthead-container.ts
Change profile endpoint on Carbon Masthead for signed in state #4701
Update naming and unit tests from feedback: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/4909
**Changed**
- update `getUserStatus` action to `loadUserStatus` in accordance to naming strategy
- create `Unauthenticated` const in ProfileAPI type
- use `request` instead of `status` for the `setRequestUserStatusInProgress` and `setUserStatus` actions
=> fix(profile): update profile requx actions, types, and reducers naming and unit tests

packages/web-components/IMPLEMENTATION_NOTES.md
Refs #4916.
Adds documentation about the implementation details of `@carbon/ibmdotcom-web-components` so new developers can easily jump into the codebase. More to be added as separate commits.
**Changed**
- Initial documentation about the implementation details of `@carbon/ibmdotcom-web-components`.
=> docs(web-components): implementation notes for Web Components

packages/web-components/src/components/content-block-mixed/__stories__/content-block-mixed.stories.scss, packages/web-components/src/components/content-block-mixed/__stories__/content-block-mixed.stories.ts
#4933 
For web components, the pictograms on content block mixed weren't switching to white when on g90 and g100 theme
=> fix(content-block-mixed): fixed pictogram color on g90 and g100 theme

packages/web-components/src/components/dotcom-shell/__stories__/data/content.ts, packages/web-components/src/components/masthead/__stories__/masthead.stories.scss, packages/web-components/src/components/table-of-contents/table-of-contents.scss
#4943 
Adds styles to allow `table-of-contents` to stick to the correct position in mobile when scrolling.
**New**
- update `top` position for `table-of-contents` for scrolling in mobile viewports
=> fix(TOC): update mobile sticky position when scrolling

packages/react/src/components/FadeInOut/__stories__/FadeInOut.stories.js, packages/web-components/src/components/fade-in-out/__stories__/fade-in-out.stories.ts
The fade component storybook snapshots are causing false positives in our automated visual regression tests. As this is not a necessary test for visual regression, this PR adds the flag to skip these tests in Percy.
**Changed**
- fade component percy configuration
=> chore(percy): skip percy testing of the fade component

packages/web-components/.storybook/webpack.config.js
#4976 
This changes the `web-component` webpack to use `file-loader` instead of `url-loader`. The latter base64 encodes images, which interfere with Storybook when used in knobs.
**Changed**
- Web components webpack config now uses `file-loader`
=> chore(storybook): add file-loader for static images

packages/react/src/components/Masthead/MastheadLeftNav.js, packages/react/src/components/Masthead/__stories__/data/MastheadLinks.js, packages/styles/scss/components/masthead/_masthead-leftnav.scss
menu item doesn't show active state in hamburg menu in masthead #4971
If selected menu item is a link (not a dropdown or has megamenu panel) and is the last menu item in the nav, it currently does not get the selected styles applied on the mobile nav.
Compare correctly the titleEnglish and selected prop from adopter and set classname.
**Changed**
- create a `selected` const so we don't have the same comparison statement in multiple places
- add `titleEnglish` field to last menu item in the custom nav data json file so we can test on storybook
=> fix(Masthead): make sure last selected menu item has selected styles in mobile nav

package.json
Not sure if this was a decision made awhile ago to not include, but I
think ci-checks should include full lint and stylelint so these can be
caught early on rather than later when these checks are made during
preflight.
**Changed**
- Expanded ci-check
=> chore(ci-check): extending ci-check to include lint and stylelint

.github/workflows/release-preflight.yml
The motivation of this is to add full preflight checks with every commit
to any release branch. These include additional checks in addition to
the standard ci-checks. The preflight checks have been taking much
longer on the other CI build, so this is a way to offload this to
Github Actions.
**New**
- Preflight checks in github actions
=> chore(preflight): adding preflight checks on github actions

packages/react/.storybook/_container.scss, packages/react/src/components/Card/__stories__/Card.stories.js, packages/react/src/components/CardLink/__stories__/CardLink.stories.js, packages/web-components/.storybook/container.scss, packages/web-components/src/components/card/__stories__/card.stories.ts
#4399 
Updated Card and Card Link to align left and have top padding of 1 rem, so that react and web components are aligned
**Changed**
- storybook change container styles
=> fix(card): adjust storybook to align left

packages/react/src/components/CardSectionCarousel/__stories__/CardSectionCarousel.stories.js, packages/web-components/.storybook/container.scss, packages/web-components/.storybook/react/config.tsx
#5002 
Update conditional classes for web component Storybook container.
**Changed**
- `dds-ce-demo-devenv--container` is now optional for web component stories
=> chore(storybook): fix web component Storybook container classes

packages/web-components/IMPLEMENTATION_NOTES.md
Refs #4975.
Add notes on how React integration for `@carbon/ibmdotcom-web-components` works, and how build procedure automates in this area.
**New**
- Notes on how React integration for `@carbon/ibmdotcom-web-components` works, and how build procedure automates in this area.
=> docs(web-components): implementation notes for React integration

.github/workflows/deploy-staging.yml, .github/workflows/publish-staging.yml
Currently the staging trigger is through another CI. This is moving the
triggers from staging deployments directly from Github, similar to
canary releases through Github Actions and repository dispatches.
**New**
- `publish-staging.yml`
=> chore(staging): adding triggers for staging environments through GH

packages/styles/scss/components/footer/_footer.scss, packages/web-components/src/components/footer/footer.scss
#4615
There was a small inconsistency where a top border added an extra pixel of height in the Micro Footer, which this PR removes.
**Removed**
- removed `border-top` value in `bx--legal-nav`
=> fix(footer): removed top border in micro footer

packages/web-components/src/components/link-list/link-list-item-card.ts
This is removing changes from this [PR](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/5010). 
After discussing in more detail it seems that this issue needs to be brought up with QA team wondering why it should read "region" vs "link" as the link list item is passed a `href` value
**Changed**
- `role: listitem`
=> chore(linkList): revert changes to aria roles

packages/web-components/src/components/content-section/content-section.scss
#4781 
For Card Section Carousel, on 300% zoom you need to scroll both horizontally and vertically to see the full page contents. This fix gets rid of the horizontal scroll, bringing accessibility back in check. This will also fix horizontal scroll on all other web components that use Content Section
=> fix(card-section-carousel): fixes horizontal scroll

packages/web-components/IMPLEMENTATION_NOTES.md
Refs #4989.
Adds implementation notes for vendor directory for `@carbon/ibmdotcom-services-store`, so that new developers can quickly
understand the difference from regular NPM packages.
**New**
- Implementation notes for vendor directory for `@carbon/ibmdotcom-services-store`.
=> docs(web-components): add notes on vendor directory

packages/styles/scss/themes/expressive/components/_data-table.scss
https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/5056
Fixes spacing issues introduced in latest Carbon upgrade (10.27)
**Removed**
- `padding-right` for expansion variants
=> fix(datatable): fix expansion spacing styles

packages/services/src/services/Profile/Profile.js
[Unhandled Runtime Error #32](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-nextjs-template/issues/32)
Catch the profile api call error and console log it in attempt to prevent error overlay from appearing in nextjs template dev mode.
**Changed**
- catch error and console log while returning `Unauthenticated`
=> fix(profile): catch error for profile api and console log error

packages/web-components/src/component-mixins/cta/video.ts
#4744 
Added focus on click for the card component, as Safari would faltly consider `body` as the active element when the card was clicked, this caused an accessibility bug where the focus would be trapped inside `ExpressiveModal` even after closed.
=> fix(card): added focus on click

packages/web-components/examples/codesandbox/components/content-block-media/index.html, packages/web-components/examples/codesandbox/components/content-block-media/src/index.js, packages/web-components/src/components/content-block-media/__stories__/README.stories.mdx, packages/web-components/src/components/content-block-media/__stories__/content-block-media.stories.ts, packages/web-components/src/components/content-block-media/content-block-media.scss, packages/web-components/src/components/content-block-media/content-block-media.ts, packages/web-components/src/components/content-block-segmented/__stories__/content-block-segmented.stories.ts, packages/web-components/tests/snapshots/dds-content-block-media.md
#4961 
Align to non-gutter grid line. Also updated stories to match react storybook options. 
**Changed**
- use CSS grid for layout for `<dds-content-block-media>`.
=> fix(contentBlockMedia): align to non-gutter grid

packages/styles/scss/components/masthead/_masthead-leftnav.scss
React & Web component: Mega Menu - Hamburger menu options are not left aligned and divider lines are missing. #5079
BEFORE:
AFTER:
**Changed**
- set border-bottom and height for submenus
- set text to show ellipsis when overflow in menu item links
=> fix(megamenu): fix alignment issues in mobile nav

packages/styles/scss/components/masthead/_masthead-megamenu.scss
Web component: Mega Menu MVP - accommodations for HC + AI updates - Visual QA (Firefox, Chrome) #5089
Add padding between the category description and first link.
**Changed**
- set 8px bottom padding to category copy
=> fix(megamenu): add padding between category desc and link

packages/react/src/components/DotcomShell/__stories__/data/content.js, packages/web-components/src/components/dotcom-shell/__stories__/data/content.ts, packages/web-components/src/components/table-of-contents/table-of-contents.scss, packages/web-components/src/components/table-of-contents/table-of-contents.ts, packages/web-components/tests/snapshots/dds-table-of-contents.md
#5124
When scrolling in Dotcom Shell the table of contents sticks behind the masthead. This adds a stickyOffset, so that the TOC is visible when scrolling
**New**
- added `stickyOffset` property to ToC (wc)
- add `stickyOffset=48` to Dotcom shell storybook (wc & react)
**Changed**
- stickyOffset styles to inline styles in ToC  (wc)
=> fix(ToC): add property stickyOffset and update stories

packages/react/src/components/Masthead/README.stories.mdx
An adopter spotted an issue where the React documentation is pointing to the incorrect scss import. This should fix the typo.
**Changed**
- Masthead README
=> docs(masthead): fix to masthead styles import line in documentation

packages/styles/scss/components/masthead/_masthead-megamenu.scss
React stand alone: Mega Menu MVP enhancement to accommodate HC + AI updates Visual QA #5136
Visual QA fix to reduce padding between megamenu categories and view all link to 32px
**Changed**
- set `margin-top` to `-32px`
=> fix(megamenu): reduce padding in megamenu above view all link

packages/web-components/src/components/masthead/megamenu-top-nav-menu.ts
Web component: Mega Menu - "The essentials, Hybrid Cloud" are read as menu options for screen reader users. #5081
This PR removes the `role='menu'` from the `ul` as it is unnecessary and conflicts with the elements placed in the megamenu/dropdown.
PR here from carbon-for-ibm-dotcom where we removed the menu role from our own version of the header menu
https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/4624
The dropdown menu/megamenu shouldn't have the role="menu" applied as listed here:
Example Disclosure for Navigation Menus | WAI-ARIA Authoring Practices 1.1
https://www.w3.org/TR/wai-aria-practices/examples/disclosure/disclosure-navigation.html
**Changed**
- grab the `bx--header-menu` element and remove the `role` attribute
=> fix(megamenu): remove menu role for accessibility

packages/react/src/components/Masthead/__stories__/data/MastheadLinks.js, packages/web-components/src/components/masthead/__stories__/links.ts
P&S mega menu: some capitalization fixes #5163
Capitalize the `c` in `Hybrid Cloud` for megamenu custom navigation content
**Changed**
- capitalize `c` in `hybrid cloud` for 2nd link in Hybrid Cloud highlighted category and link under the Solutions category
=> fix(megamenu): capitalize content in custom navigation

packages/react/src/components/Masthead/MastheadSearch.js, packages/react/src/components/Masthead/README.stories.mdx, packages/services/src/services/SearchTypeahead/SearchTypeahead.js, packages/services/src/services/SearchTypeahead/__tests__/SearchTypeahead.test.js, tasks/jest/env.js
Updates masthead search `customTypeAheadApi` to be fully on the application side. When using a custom API, it will no longer pass through `SearchTypeaheadAPI` at all. This allows users to pass a full API including any necessary query params that were not defined in `SearchTypeaheadAPI`. With this change the use of environment variables is no longer necessary.
**Changed**
- moves `customTypeAheadApi` out of `SearchTypeaheadAPI`
- update jest environment variables
- section titles no longer appear when there are no section items
=> fix(masthead): customtypeahead api fix

packages/web-components/src/components/masthead/masthead-composite.ts
#4800 
Tooltip for masthead logo not appearing on firefox. 
**New**
- `tabIndex="0"` to `masthead-composite` which renders `masthead-logo`
=> fix(masthead): add tabIndex

packages/styles/scss/components/footer/_language-selector.scss
#5178 
Fixes responsive styling for `Footer: micro footer with language selector`
**Changed**
- micro footer language only responsive styles
=> fix(footer): update micro language only styles

packages/web-components/src/components/masthead/masthead-composite.ts, packages/web-components/src/components/masthead/masthead-logo.ts
#4800
tab accessibility for firefox on masthead logo tooltip
**New**
- update tabIndex to 0
=> fix(masthead): update tabindex

packages/styles/scss/components/card/index.scss
#5034 
Removes underline from `Card` active state 
**Changed**
- update card styles to remove underline when active
=> fix(card): remove text decoration from active state

packages/styles/scss/components/video-player/_video-player.scss
#5127 
Updates caption spacing for video player caption
**Changed**
- video player caption top spacing reduced to `8px`
=> fix(video-player): update caption styles

packages/web-components/src/components/expressive-modal/__tests__/expressive-modal.test.ts, packages/web-components/src/components/expressive-modal/expressive-modal.ts, packages/web-components/src/components/locale-modal/locale-modal.ts
Refs #5173.
Changes the "focus on the primary focusable element" logic in `<dds-expressive-modal>` to wait for `transitionend` event. Without it, the attempt to focus fails.
Also changes `<dds-locale-modal>` to make `<dds-region-item>` as the primary focusable element.
**Changed**
- The "focus on the primary focusable element" logic in `<dds-expressive-modal>` to wait for `transitionend` event.
- `<dds-locale-modal>` to make `<dds-region-item>` as the primary focusable element.
=> fix(expressive-modal): ensure waiting for transitionend event

packages/web-components/src/components/card/card.ts, packages/web-components/tests/snapshots/dds-card-cta.md, packages/web-components/tests/snapshots/dds-card.md, packages/web-components/tests/snapshots/dds-feature-card-block-large.md, packages/web-components/tests/snapshots/dds-feature-card.md, packages/web-components/tests/snapshots/dds-feature-cta.md
#5194 
remove aria-hidden from copy. Reads copy text in carasoul
**Removed**
- `aria-hidden: true`
=> fix(card): remove aria-hidden from copy

packages/react/src/components/Masthead/MastheadSearchSuggestion.js
#4845 
This adds support for user-defined URLs when using the [`searchNoRedirect`](http://ibmdotcom-react.mybluemix.net/?path=/docs/components-masthead--default#searchnoredirect) option in the masthead search. If provided, a URL will be placed in a search element's `data-href` attribute. This is useful when a URL redirect is required, instead of using the search value as a query param.
**Note:** when using `searchNoRedirect`, all logic must be provided by the user.
**New**
- add custom URL support to search result elements
=> feat(search): allow custom url with noSearchRedirect

packages/styles/scss/components/card/index.scss, packages/web-components/src/components/card/card.scss
https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/5033
Dds-card and dds-card-link had 2 outlines showing at the same time. I removed the default outline behavior which caused the black rounded border.
**Added**
+ outline: none on /packages/styles/scss/components/card/index.scss
+ outline: none on /packages/web-components/src/components/card/card.scss
=> fix(card): focus state outline is off

packages/web-components/IMPLEMENTATION_NOTES.md
Refs #5054.
Adds implementation notes on focus wrapping for `@ibmdotcom-web-components` so that new developers can quickly
understand how it works.
**New**
- Implementation notes on focus wrapping for `@ibmdotcom-web-components`.
=> docs(web-components): implementation notes on focus wrapping

packages/styles/scss/components/card/index.scss, packages/styles/scss/components/feature-card-block-large/_feature-card-block-large.scss, packages/web-components/src/components/feature-card-block-large/__stories__/feature-card-block-large.stories.ts, packages/web-components/src/components/feature-card-block-large/feature-card-block-large.scss, packages/web-components/src/components/feature-card-block-medium/__stories__/feature-card-block-medium.stories.ts
#4925 
#4938 
#5092 
Addressing:
* `FeatureCardBlockLarge` specs mismatches where there was extra padding within the content
* `FeatureBlockCard` and `FeatureCardBlockMedium` color not changing on hover
* some Storybook-related issues where the image's dimensions clashed with the story wrapper, making `FeatureCard` looks weird
**Changed**
- `FeatureCardBlockLarge` arrow icon now moved to the left of the card
- slight Storybook layout and image changes to accommodate `FeatureCard` dimensions
** Removed **
- removed `padding` within `FeatureCardBlockLarge` contents
=> fix(feature-card): fixed multiple style mismatches from specs

packages/react/src/components/Masthead/MastheadSearch.js
#5287 
I've removed the prop that makes Autosuggest focus on the first suggested item, this prop was causing a bug where the typed content would be overwritten by the first suggested item when enter is pressed.
=> fix(masthead-search): removed focus on first item prop

packages/react/src/components/ScrollAnimations/__stories__/ScrollAnimations.stories.js
None.
The React storybook variation for the new `ScrollAnimations` component was left unchanged from its previous title of `FadeInOut`. This PR addresses this issue and changes to the correct name for its title.
**Changed**
- changed `FadeInOut` Storybook title to `ScrollAnimations`
=> fix(scroll-animations): rename storybook title

packages/web-components/src/components/footer/footer.ts, packages/web-components/tests/snapshots/dds-footer-composite.md
#4890
Even though `<dds-footer>` has a `role='footer'`, it appears it's not being detected as such. Added an `aria-label='footer'` to accommodate for this.
**New**
- added `aria-label='footer'` to `<dds-footer>`
=> fix(footer): added aria-label to describe footer

packages/web-components/src/components/content-block-headlines/content-block-headlines.scss
Web component: Content block headlines - 'Link text' links are not aligned on sections #4860
Aligning CTA at the bottom.
[web-components experimental](http://ibmdotcom-web-components-experimental.mybluemix.net/?path=/story/components-content-block-headlines--default)
This PR
=> fix(content-block-headlines): aligning CTA at the bottom

packages/react/src/components/ContentBlockHeadlines/ContentBlockHeadlines.js, packages/styles/scss/components/content-block-headlines/_content-block-headlines.scss
#4694
The Headlines Item container currently uses `display: grid`, but each of the items' CTAs weren't properly aligned to the bottom. This PR addresses that, and also fixes a wrong class name for the heading element so the correct stylings are applied.
Before:
After:
**New**
- added `display: flex` and `flex-direction: columns` to the `headlines__item` class
- set custom class name to the previously unnamed CTA div container
- set `margin-top: auto` for the `CTA` div container to ensure proper alignment
**Changed**
- fixed a mislabeled class name for HeadlineItem's `<h4>` to apply proper styles
**Removed**
- removed the dynamic setting of height for the copy elements that used the `setHeight` utility function
=> fix(content-block-headlines): same height using CSS grid

packages/react/src/components/TableOfContents/TOCMobile.js
Removes extra character in `data-autoid` attribute.
**Removed**
- extra `}` in `TOC` mobile options
=> chore(toc): fix autoid interpolation

packages/web-components/src/components/leaving-ibm/leaving-ibm.scss
https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/5058
Limited the max height of modal to screen height. Affects landscape mode for touch devices only.
=> fix(leavingIbm): max height limit to modal in landscape

packages/web-components/src/components/video-player/video-player.ts
Refs #5342.
Replaces usage of React `classnames` library with `lit-html`'s `classMap`, given the latter is the library we use for
`@carbon/ibmdotcom-web-components` and thus our user's environment of `@carbon/ibmdotcom-web-components` won't have React `classnames`.
**Changed**
- Replaces usage of React `classnames` library with `lit-html`'s `classMap`.
=> fix(video-player): remove usage of React classnames

packages/styles/scss/components/link-with-icon/_link-with-icon.scss
Removes unused style that is also causing compile errors for web components.
**Removed**
- `inverse` styling. It is not being used and the scss concatenation is not supported with `:host` pseudo-classes.
=> fix(linkwithicon): remove inverse styles

packages/react/src/components/Masthead/Masthead.js, packages/react/src/components/Masthead/MastheadL1.js, packages/react/src/components/Masthead/__stories__/Masthead.stories.js, packages/web-components/src/components/masthead/__stories__/links.ts, packages/web-components/src/components/masthead/masthead-composite.ts
Corporate Masthead - Specify what is the currently selected element in a L1 menu #5302
The selected menu item state is currently only available for the L0 menu items. This PR adds that functionality to the L1 as well. NOTE: we have user passing in one `selectedMenuItem` prop - right now, usage is menu items only appear either L0 or L1 - not both.
REACT:
WEB COMPONENTS:
**New**
- copy over selected menu item logic to the masthead L1
=> feat(masthead): specify selected menu item style for L1 menu item 

packages/web-components/src/components/carousel/__stories__/carousel.stories.ts
#5328 
Simplify `carousel` story by removing variations which are not yet needed.
**Removed**
- `Right 12` and `Center 8` stories
- `Number of cards per page` knob
=> chore(carousel): carousel variation stories

packages/react/examples/codesandbox/components/ContentBlockMedia/src/index.js, packages/react/src/components/ContentGroupSimple/__stories__/data/ContentGroupSimple.knobs.js, packages/react/src/internal/components/ContentBlock/ContentBlock.js, packages/styles/scss/components/content-block-media/index.scss
#5379 
Add missing style imports to `Content Block - Media`. Also updates the React Codesandbox example.
**New**
- stylesheet imports
**Changed**
- update React Codesandbox example
=> chore(content-block-media): add missing style imports

packages/styles/scss/components/expressive-modal/_expressive-modal.scss, packages/styles/scss/components/lightbox-media-viewer/_lightbox-media-viewer.scss, packages/web-components/src/components/expressive-modal/expressive-modal.scss
#5348 
Fixes for `expressive-modal` close button positioning and responsive styles.
**Changed**
- adjust close button position for web component
- fix modal container responsive styles
**Removed**
- duplicate styles
=> fix(expressive-modal): various style fixes

packages/styles/scss/components/callout-data/_callout-data.scss
NextJS - Services Page - Callout data, text color is same as background. #5193
style(callout-data): fixing background
**Current**
**This PR**
=> fix(callout-data): background token fix

packages/react/src/components/ButtonGroup/ButtonGroup.js, packages/react/src/components/ButtonGroup/README.stories.mdx
Add `onClick` prop definition so adopters are aware that it can be passed in and remove the requirement from the `href` and `copy` props.
=> docs(ButtonGroup): add onClick prop and remove href & copy prop requirement

packages/styles/scss/components/masthead/_masthead-megamenu.scss
#5181 
The previous token was `$body-short-01` while it should've been `$body-long-01`.
**Changed**
- changed the slotted `dds-megamenu-category-group-copy` type from `$body-short-01` to `$body-long-01`
=> fix(masthead): using correct token for essentials description text

packages/styles/scss/components/leadspace/_leadspace.scss, packages/web-components/src/components/leadspace/leadspace.scss
#5503 
Fixes heading and copy text not being visible on g90 and g100 theme
=> fix(leadspace): fixes carbon theme issue on small breakpoints

packages/react/src/components/BackToTop/README.stories.mdx
Fixes incorrect component name in README.
**Changed**
- `Carousel` changed to `Back to top`
=> chore(back-to-top): fix typo in readme

packages/tests-e2e/__tests__/callout-quote/callout-quote.e2e.js, packages/tests-e2e/__tests__/quote/quote.e2e.js, packages/tests-e2e/__tests__/table-of-contents/table-of-contents.e2e.js
This adds additional test coverage for Carbon themes for the following components:
- Callout quote
- Quote
- Table of contents
**New**
- e2e tests for various components
=> test(e2e): adding additional carbon theme test coverage for percy

packages/react/src/components/TableOfContents/__stories__/TableOfContents.stories.js, packages/tests-e2e/__tests__/callout-quote/callout-quote.e2e.js, packages/tests-e2e/__tests__/leadspace/leadspace.e2e.js, packages/tests-e2e/__tests__/locale-modal/locale-modal.e2e.js, packages/tests-e2e/__tests__/masthead/masthead.e2e.js, packages/tests-e2e/__tests__/quote/quote.e2e.js, packages/tests-e2e/__tests__/table-of-contents/table-of-contents.e2e.js, packages/tests-e2e/jest.config.js
Refs #5474 
The table of contents was not properly passing in the theme into the
component, which is causing some rendering issues.
The masthead is also noticing some flakiness in the renders regardless
of await commands for selectors. This adds in some additional time for
the overflow to render fully. In addition, the visual check between the
first and second mega menu nav items were separated out into two
separate tests as keeping them in one looked to have errors.
And fundamentally, the configuration for page load has been changed to detect for no more network traffic in order to continue. This will allow for completed rendering of network calls, etc.
**Changed**
- e2e tests for percy
=> test(e2e): fixes to table of contents and masthead e2e tests

packages/web-components/src/components/video-player/video-player.ts
Video Player Web Component not rendering video thumbnail #5615
Video player needs the image import otherwise the video image overlay does not appear.
**Changed**
- add image component import
=> fix(video-player): import image component within video-player component

packages/styles/scss/themes/expressive/components/_file-uploader.scss
https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/5614
Width and height properties were pointing at parent. Pointed to svg (doesn't have a class name).
=> fix(file-uploader): icon size fix

packages/web-components/README.md
None.
Updated `includePaths` in the Webpack example to use relative pathing in order to help adopters avoid any potential importing errors coming from `carbon-components` if they build off their webpack configuration off our example.
**Changed**
- now using relative paths in `includePaths` for the Webpack example
=> docs(README): updated webpack sass options to use relative paths

packages/web-components/src/components/card-group/__stories__/card-group.stories.ts
https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/5415
Added `inPercy` check for random title lengths.
=> fix(card-group): random title percy check

packages/web-components/src/components/masthead/__stories__/masthead.stories.ts
Percy was generating false positives with the placeholder text in
snapshots, specifically for the story with the masthead search open.
This will blank out the placeholder text in Percy only.
**Changed**
- Blank masthead search placeholder for Percy
=> chore(percy): setting blank search placeholder in percy

packages/styles/scss/components/masthead/_masthead-search.scss, packages/styles/scss/components/masthead/_masthead.scss
[Carbon v10.31.0 Upgrade | React] Masthead icons are white #5596
The Carbon upgrade added some new selectors to the `HeaderGlobalAction` component that were overriding the styles set at the `MastheadSearch` buttons. This was fixed by increasing the specificity of the previous selectors.
=> fix(masthead-search): increasing css selectors specificity

packages/react/gulp-tasks/config.js, packages/react/gulp-tasks/vendor.js, packages/react/tests/integration/bundle/bundle-size.test.js
#5600 
This is an update to the way the vendor build task is done in order to include the `@carbon/feature-flags` library that was introduced last month in Carbon.
**Changed**
- Various updates to the gulp build task
=> test(bundle): update vendor build task to include @carbon/feature-flags

.github/workflows/percy-update-base.yml
Now that the chore branch has been successfully merged down, this branch for updating the percy baseline for that particular branch is no longer needed.
**Changed**
- `percy-update-base.yml`
=> chore(percy): removing chore branch from percy update github action

packages/react/src/components/Masthead/MastheadSearch.js, packages/styles/scss/components/masthead/_masthead-search.scss
Custom Masthead searchbar tooltip text #5778
Hide the tooltip from the masthead search buttons
**Changed**
- set tooltip to `display: none`
=> fix(MastheadSearch): remove tooltip from search button

packages/styles/scss/components/masthead/_masthead-megamenu.scss
#5743 
Removes underline from **The Essentials** links on `hover`.
**New**
- `text-decoration: none` on `hover` for **The Essentials** links
=> fix(megamenu): removes text-decoration on hover

packages/web-components/src/components/content-block-simple/content-block-simple.scss
#5423 
I've added max-width to the slotted media components on `ContentBlockSimple`.
This change affects React and Web Components.
=> fix(content-block-simple): added max-width to media components

packages/styles/scss/components/masthead/_masthead-search.scss
NextJS page: Masthead Search bar - On hover search icon and close icon are hidden #5789
=> fix(masthead-search): overriding carbon core button styles

packages/web-components/src/components/masthead/masthead-logo.ts, packages/web-components/src/components/masthead/masthead-menu-button.ts, packages/web-components/src/components/masthead/masthead-search.ts
#5800
On Mobile view, the Masthead Search wasn't closing properly upon hitting the close button. This also happened when typing a space character on the search input. This ensures it closes properly, and fixes the space character bug. 
This PR also adds back "Closing search on blur" feature the Web Component Masthead used to have, and currently has in the React version, fixing another overflow issue happening.
**New**
- brought back the close on blur feature of the Masthead Search
**Changed**
- added a check to ensure the search toggle CustomEvent was defined before toggling the visibility of the Masthead Button and IBM Logo.
=> fix(masthead): ensure search closes properly & close on blur

packages/styles/scss/components/masthead/_masthead-search.scss
NextJS page: Masthead Search bar - On hover search icon and close icon are hidden #5789
Make sure that the tooltip for the search icons are not displaying on hover and click of the icons. Need to use more specific selectors for the NextJS test pages.
**Changed**
- use more specific selectors
=> fix(Masthead): use specific selectors to remove tooltip
