- .github/CONTRIBUTING.md
- README.md
Updates main README.
**New**
- update README repository description
- adds status tags to README (circleci, PR, etc)
> chore(docs): update documentation

- .circleci/config.yml
This is used only for testing releasing/publishing packages to npm.
> For CircleCI package release testing

- .circleci/config.yml
Closes #
{{short description}}
**New**
**Changed**
- {{change thing}}
**Removed**
> chore(ci): remove artifact job requirement

- .circleci/config.yml
Closes #
{{short description}}
**New**
**Changed**
- {{change thing}}
**Removed**
> chore(ci): add circleci deployment

- .circleci/config.yml
Closes #
{{short description}}
**New**
**Changed**
- {{change thing}}
**Removed**
> fix(yaml): testing syntax

- .github/stale.yml
Adds stalebot configuration. Further customization still needed (labels to ignore, etc)
**New**
- stalebot configuration [kennylam@f58de23333d54d1f9122e8f309fdc18d52957726]
> feat(stale): add stalebot config

- .github/stale.yml
Test `stalebot`:
- 1 day to stale
- 2 days to close
**Changed**
- change `stalebot` intervals for testing [kennylam@35278b6c341daf3f8ed7e87c64a5e66f61e4b543]
> Test stalebot functionality

- .github/stale.yml
Updating the stalebot configuraton to 15 days, then 3 days to close.
**Changed**
- stale.yml file updated to 15 days
> chore(stale): updated stalebot configuration to two weeks

- .circleci/config.yml
- package.json
- packages/react/.gitignore
- packages/react/manifest.yml
Update CircleCI configuration with IBM Cloud account variables
**New**
- Add `manifest` for IBM Cloud [[7352b09](https://github.com/kennylam/ibm-dotcom-library/commit/7352b092e1754ba37e2b4cd29c6a75a43b686f8b)]
- Add `.gitignore` for static Storybook files [[5f0d7f3](https://github.com/kennylam/ibm-dotcom-library/commit/5f0d7f3c94357baead05874b68bc606ec8885d51)]
**Changed**
- Update CircleCI config with updated account info and environment variables [[995f1b9](https://github.com/kennylam/ibm-dotcom-library/commit/995f1b93be9a91f9904df9078e9c7def72205065)]
> CircleCI deployment configurations

- docs/publishing.md
- lerna.json
- package.json
Closes #
https://github.ibm.com/webstandards/digital-design/issues/1301
**Changed**
- lerna config to include standard commit message
- changed base package version
> feat(publishing): adding standard commit message for lerna publishing

- packages/styles/package.json
- packages/styles/scss/components/masthead/_masthead.scss
- yarn.lock
This adds basic dotcom styling to the masthead component
**New**
- Light theme for IBM.com Library masthead
> style(masthead): add basic dotcom theme

- packages/react/src/components/index.js
https://github.com/carbon-design-system/ibm-dotcom-library/issues/88
export hr component
**New**
- export <HorizontalRule /> component
> fix(hr): export hr in components

- packages/react/src/components/carbon-components-react/UIShell/SideNavMenu.js
No related tickets
This removes the console log output from `SideNavMenu`.
**Changed**
- Removed console logs
> fix(masthead): removed console logs

- packages/eslint-config-ibmdotcom/CHANGELOG.md
- packages/eslint-config-ibmdotcom/package.json
- packages/patterns-react/CHANGELOG.md
- packages/patterns-react/package.json
- packages/react/CHANGELOG.md
- packages/react/package.json
- packages/services/CHANGELOG.md
- packages/services/package.json
- packages/stylelint-config-ibmdotcom/CHANGELOG.md
- packages/stylelint-config-ibmdotcom/package.json
- packages/styles/CHANGELOG.md
- packages/styles/package.json
- packages/utilities/CHANGELOG.md
- packages/utilities/package.json
- packages/vanilla/CHANGELOG.md
- packages/vanilla/package.json
- @carbon/eslint-config-ibmdotcom@1.1.0-rc.0
- @carbon/ibmdotcom-patterns-react@1.1.0-rc.0
- @carbon/ibmdotcom-react@1.1.0-rc.0
- @carbon/ibmdotcom-services@1.1.0-rc.0
- @carbon/stylelint-config-ibmdotcom@1.1.0-rc.0
- @carbon/ibmdotcom-styles@1.1.0-rc.0
- @carbon/ibmdotcom-utilities@1.1.0-rc.0
- @carbon/ibmdotcom-vanilla@0.1.0-rc.0
#529
> Release v1.1.0

- packages/react/src/components/Footer/FooterNav.js
Fixes #599
This pull request fixes the columns in firefox
> Note: need to test in IE edge
**Changed**
- moved container class to accordion
**Removed**
- removed container div
> fix(react): moved container class onto accordion

- packages/styles/scss/components/masthead/_masthead-search.scss
Fixes #595 
this pull request fixes the bug where the search button wasn't getting the correct focus styling
**Changed**
- Grouped close and search button's styles for focus state and active state
> Fix search button focus

- packages/patterns-react/.env.example
- packages/patterns-react/src/internal/FeatureFlags.js
- packages/react/.env.example
- packages/react/src/internal/FeatureFlags.js
#609 
This creates a single flag that will enable all feature flags.
**New**
- `DDS_FLAGS_ALL` environment flag
> feat(flags): adding DDS_FLAGS_ALL environment flag

- packages/react/src/components/index.js
It exports Layout component form react component index.js
> fix(layout): added Layout in index export

- packages/react/src/components/Masthead/MastheadSearchInput.js
#648 
This fixes an issue where CSR code is being triggered on the server side.
**Changed**
- Masthead search input SSR fix
> fix(masthead): ssr fix for missing document

- tasks/publish.sh
This adds in the necessary flag for graduating a patch release
**Changed**
- publish script
> fix(publish): fix to properly graduate a patch release

- .github/ISSUE_TEMPLATE/feature_request.md
- packages/react/src/components/Masthead/README.md
These are tweaks to the Masthead README to better clarify how to use the props.
**Changed**
- Masthead README
> docs(masthead): updated documentation for the masthead to clarify props

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
#551 
Updating fireline support members for sprint 23.
**Changed**
- Bug and Feature request assignees
> Fireline 23

- packages/patterns-react/src/patterns/PictogramArray/README.md
- packages/patterns-react/src/patterns/PictogramArray/__stories__/PictogramArray.stories.js
- packages/patterns-react/src/patterns/PictogramArray/__stories__/index.scss
Created a story level scss file to import the styles into storybook.
**New**
- Story level scss file.
> fix(pattern): created a story level scss file

- packages/patterns-react/src/patterns/LeadSpace/__stories__/LeadSpace.stories.js
No related stories
Fixed the LeadSpace feature flag in the story.
**Changed**
- LeadSpace story feature flag reference
> fix(leadspace): fixed leadspace feature flag name in the story

- packages/styles/README.md
Fixed the link to the README for expressive.
**Changed**
- README link to expressive theme
> docs(expressive): update to the README link to expressive

- .github/workflows/automerge.yml
This adds automerging of changes in the release branch
#280 
This adds a Github action that will automerge changes from `release/*` to `master`.
**New**
- Github automerge action
> feat(release): adding automerge action

- packages/patterns-react/src/patterns/CardArray/__stories__/CardArray.stories.js
- packages/patterns-react/src/patterns/PictogramArray/__stories__/PictogramArray.stories.js
Super simple pull request changing the names of card array and pictogram array within storybook.
**Changed**
-  storybook names
> chore(patterns): updated names to reflect latest

- packages/patterns-react/.storybook/_container.scss
- packages/react/.storybook/_container.scss
- packages/styles/.storybook/_container.scss
I noticed that the layout for the storybook overview page in mobile was breaking, so this fixes that issue.
**Changed**
- Storybook styles
> fix(storybook): fix to layout issues in storybook for mobile

- packages/react/src/components/LocaleModal/LocaleModalCountries.js
- packages/react/src/components/LocaleModal/LocaleModalRegions.js
#847 
Fixes an issue where filter was including countries from all regions
**Changed**
- fix filter list to only include countries of selected region
> fix(locale): fix locale filter availability text; fixes #847

- packages/styles/scss/components/footer/_footer-logo.scss
- packages/styles/scss/components/footer/_footer-nav-group.scss
- packages/styles/scss/components/footer/_footer-nav.scss
- packages/styles/scss/components/footer/_footer.scss
- packages/styles/scss/components/footer/_legal-nav.scss
- packages/styles/scss/components/footer/_locale-button.scss
- packages/styles/scss/components/footer/index.scss
#718 
This is a fix to properly set the g90 background for the footer.
**Changed**
- footer carbon theme application of g90
> fix(footer): style theme fixes for the footer

- packages/eslint-config-ibmdotcom/CHANGELOG.md
- packages/eslint-config-ibmdotcom/package.json
- packages/patterns-react/CHANGELOG.md
- packages/patterns-react/package.json
- packages/react/CHANGELOG.md
- packages/react/package.json
- packages/services/CHANGELOG.md
- packages/services/package.json
- packages/stylelint-config-ibmdotcom/CHANGELOG.md
- packages/stylelint-config-ibmdotcom/package.json
- packages/styles/CHANGELOG.md
- packages/styles/package.json
- packages/utilities/CHANGELOG.md
- packages/utilities/package.json
- packages/vanilla/CHANGELOG.md
- packages/vanilla/package.json
- @carbon/eslint-config-ibmdotcom@1.2.0
- @carbon/ibmdotcom-patterns-react@1.2.0
- @carbon/ibmdotcom-react@1.2.0
- @carbon/ibmdotcom-services@1.2.0
- @carbon/stylelint-config-ibmdotcom@1.2.0
- @carbon/ibmdotcom-styles@1.2.0
- @carbon/ibmdotcom-utilities@1.2.0
- @carbon/ibmdotcom-vanilla@0.2.0
**New**
**Changed**
**Removed**
> chore(release): publish

- packages/styles/scss/patterns/cardarray/README.md
_No tickets associated_
Just a typo fix in the Cards Array style readme
**Changed**
- Updated Cards Array scss readme
> fix(cards-array): fix typo

- packages/styles/scss/themes/expressive/components/_combo-box.scss
- packages/styles/scss/themes/expressive/index.scss
Expressive theme – Combo box #978
bump icons to 20x20
**Changed**
- increase icon svgs to 20x20
> feat(expressive): combo-box expressive theme

- packages/react/src/components/ContentGroup/ContentGroup.js
- packages/react/src/components/ContentGroup/README.md
- packages/react/src/components/ContentGroup/__stories__/ContentArrayGroup.stories.js
- packages/react/src/components/ContentGroup/__stories__/index.scss
- packages/react/src/components/ContentGroup/index.js
- packages/react/src/components/index.js
- packages/react/src/internal/FeatureFlags.js
- packages/styles/scss/components/content-group/_content-group.scss
#745 
I've updated the PictogramArray pattern in order to use the newly created ContentGroup component
**New**
- ContentGroup implemented on pattern
**Changed**
- Updated JS and SCSS coding
> fix(branch): Fixed branch update issues on previous PictogramArray PR

- packages/react/src/components/LightboxMediaViewer/LightboxMediaViewer.js
- packages/react/src/components/LightboxMediaViewer/README.md
- packages/react/src/components/LightboxMediaViewer/__stories__/LightboxMediaViewer.stories.js
- packages/styles/scss/components/lightbox-media-viewer/_lightbox-media-viewer.scss
Related to #918
used the spread operator to pass the modal props and changes image object to an array and copy text justified. Updated the README file 
**Changed**
LightboxMediaViewer - js , scss, stories.js and README.md
> fix(pattern): addresed the PR review comments

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
#1166 
Updating sprint 3 fireline support roster.
**Changed**
- Github issue templates
> chore(support): update sprint 3 fireline support

- packages/react/ssr-tests/nextjs/components/altlang.js
- packages/react/ssr-tests/nextjs/components/data/altlang.json
This adds some additional files missing for the nextjs test environment, missed these in the first round.
**Changed**
- nextjs files
> fix(ssr-test): adding missing ssr test files

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
Update issue templates support roster for sprint 4
> chore(docs): update support roster for sprint 4

- packages/react/src/components/CTA/CTA.js
- packages/react/src/components/CTA/__stories__/CTA.stories.js
- packages/react/src/components/LocaleModal/LocaleModalRegions.js
- packages/react/src/patterns/blocks/ContentBlockMedia/ContentBlockMediaGroup.js
- packages/react/src/patterns/blocks/ContentBlockMedia/__stories__/ContentBlockMedia.stories.js
- packages/react/src/patterns/blocks/ContentGroupCards/ContentGroupCards.js
- packages/react/src/patterns/blocks/ContentGroupSimple/__stories__/ContentGroupSimple.stories.js
- packages/react/src/patterns/blocks/FeaturedLink/FeaturedLink.js
- packages/react/src/patterns/blocks/FeaturedLink/__stories__/FeaturedLink.stories.js
- packages/react/src/patterns/blocks/SimpleLongForm/SimpleLongForm.js
- packages/react/src/patterns/sections/CardSection/CardSection.js
- packages/react/src/patterns/sub-patterns/Card/Card.js
- packages/react/src/patterns/sub-patterns/Card/README.md
- packages/react/src/patterns/sub-patterns/Card/__stories__/Card.stories.js
- packages/react/src/patterns/sub-patterns/Card/__stories__/index.scss
- packages/react/src/patterns/sub-patterns/ContentBlock/ContentBlock.js
- packages/react/src/patterns/sub-patterns/ContentBlock/__stories__/ContentBlock.stories.js
- packages/react/src/patterns/sub-patterns/ContentGroup/__stories__/ContentGroup.stories.js
- packages/react/src/patterns/sub-patterns/ContentItem/ContentItem.js
- packages/styles/scss/components/link-with-icon/_link-with-icon.scss
- packages/styles/scss/components/locale-modal/_locale-modal.scss
- packages/styles/scss/patterns/sub-patterns/card/README.md
- packages/styles/scss/patterns/sub-patterns/card/index.scss
Card: Text and icon should not change to blue #1093
Pattern: Card High Contrast Modifier #1070
A high contrast version (inverse) of the card that can be used with different color themes.
**New**
- add theme option to storybook so we can toggle and see how the card looks in different themes
**Changed**
- utilize different color tokens based based on the `inverse` flag
> fix(card): high contrast modifier

- packages/styles/scss/ibm-dotcom-styles.scss
Another fix for the main styles import
**Changed**
- Fix to index reference for a couple of patterns
> fix(styles): fix to style imports

- packages/react/src/internal/FeatureFlags.js
This is a cleanup PR that removes unused feature flags.
**Removed**
- Unused feature flags
> fix(featureflags): removed unused feature flags

- packages/react/src/patterns/blocks/ContentBlockMixed/__stories__/ContentBlockMixed.stories.js
- packages/styles/scss/patterns/blocks/content-group-cards/index.scss
This fixes a style build compilation issue where it is not finding the index file properly.
**Changed**
- Style import fix
> fix(styles): fix to import in style build

- packages/react/src/patterns/blocks/ContentBlockMixed/README.md
- packages/react/src/patterns/blocks/ContentBlockSegmented/README.md
- packages/react/src/patterns/blocks/ContentBlockSimple/README.md
- packages/react/src/patterns/blocks/ContentGroupCards/README.md
- packages/react/src/patterns/blocks/ContentGroupPictograms/README.md
- packages/react/src/patterns/blocks/ContentGroupSimple/README.md
Updating READMEs for the content block patterns to point to the correct scss files
**Changed**
- Pattern READMEs
> docs(contentblock): updated READMES for content block/groups

- packages/react/src/__tests__/__snapshots__/storyshots.test.js.snap
- packages/react/src/components/CTA/CTA.js
- packages/react/src/patterns/sub-patterns/LinkList/LinkList.js
- packages/react/src/patterns/sub-patterns/LinkList/README.md
- packages/react/src/patterns/sub-patterns/LinkList/__stories__/LinkList.stories.js
- packages/react/src/patterns/sub-patterns/LinkList/__stories__/index.scss
- packages/react/src/patterns/sub-patterns/LinkList/__tests__/LinkList.test.js
- packages/react/src/patterns/sub-patterns/LinkList/index.js
- packages/react/src/patterns/sub-patterns/index.js
- packages/styles/scss/ibm-dotcom-styles.scss
- packages/styles/scss/patterns/sub-patterns/card/index.scss
- packages/styles/scss/patterns/sub-patterns/link-list/README.md
- packages/styles/scss/patterns/sub-patterns/link-list/_link-list.scss
- packages/styles/scss/patterns/sub-patterns/link-list/index.scss
Related issue: #1258 
Implemented the LinkList pattern which uses the CTA and lists out a collection of links .
Changelog
**New**
- LinkList pattern and scss
> feat(pattern): created LinkList pattern

- packages/react/src/patterns/sections/CardSection/CardSection.js
- packages/react/src/patterns/sections/CardSection/README.md
- packages/react/src/patterns/sections/CardSection/__stories__/CardSection.stories.js
- packages/react/src/patterns/sections/CardSectionImages/__stories__/CardSectionImages.stories.js
- packages/react/src/patterns/sections/CardSectionSimple/CardSectionSimple.js
- packages/react/src/patterns/sections/CardSectionSimple/__stories__/CardSectionSimple.stories.js
- packages/styles/scss/patterns/sections/card-section/_card-section.scss
Related issue: #1196 
Added CTA inverse for CardSection simple.
**New**
- Added CTA Inverse card in CardSection-simple
**Changed**
- CardSection.js , its story and scss
> feat(pattern): added CTA inverse for cardSection simple

- packages/react/src/patterns/blocks/ContentBlockMedia/README.md
Update `ContentBlockMedia` README to match latest functional specs (props, layout, etc).
**Changed**
- update README
> chore(docs): update ContentBlockMedia readme

- packages/react/src/patterns/sections/CardSection/CardSection.js
Related issue: #1481 
Added the role and aria-labelledby attributes to the cards of cardSection pattern, so that the screen readers could understand.
**New**
- added role and aria-labelledby
> fix(pattern): added role and aria-labelledby in card of cardSection

- packages/react/src/patterns/sub-patterns/Layout/Layout.js
- packages/react/src/patterns/sub-patterns/Layout/README.md
#1581 
Minor tweaks to the Layout README, and some default props definitions.
**Changed**
- Layout README and default props
> docs(layout): minor tweaks to layout docs

- packages/react/src/patterns/sub-patterns/TableOfContents/TableOfContents.js
- packages/react/src/patterns/sub-patterns/TableOfContents/__stories__/data/dataContent.js
#1630 
Updated the `TableOfContents` script in order to avoid deadzones between headings
> fix(pattern): fixed left navigation not showing any selected section

- packages/react/ssr-tests/nextjs/package.json
- packages/react/ssr-tests/nextjs/pages/learn.js
- packages/react/ssr-tests/nextjs/yarn.lock
#1653 
Updated learn template with new nested layout modification, and link list pattern.
**New**
- Nested Layout
- Link List added
**Changed**
- updated to latest `rc-0`
> chore(learn): added layout and link list examples to template

- packages/react/src/patterns/sub-patterns/Layout/Layout.js
- packages/styles/scss/patterns/sub-patterns/layout/_layout.scss
#1679 
This fixes the sticky behavior for Safari browsers.
Deploy preview available: https://ibmdotcom-nextjs.s3.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/1/learn.html
**Changed**
- Style fixes for the position sticky classes in Layout
> fix(layout): fix to sticky attribute for safari browsers

- packages/react/src/patterns/sub-patterns/TableOfContents/TOCDesktop.js
#1395 
Added the focus trigger to the release branch
> fix(accessibility): focus now change to the content heading on toc

- packages/styles/scss/patterns/sub-patterns/card/index.scss
#1619 
I've added the max-width to the `Card` pattern scss, so it better fits the design specs.
**New**
- Max-width added
> fix(scss): added max-width to card content

- packages/styles/scss/components/locale-modal/_locale-modal.scss
#1408 
I've tried to change the cta color for the cards in the locale selector modal
> fix(styling): changed arrow color on locale-modal card

- packages/react/src/patterns/blocks/ContentBlockMedia/__stories__/ContentBlockMedia.stories.js
#1887 
Draft PR to show the image media prop for configuration as a knob.
**Changed**
- exposed new knob for ContentBlockMedia
> fix(contentblockmedia): exposing knob for media object

- packages/react/src/patterns/blocks/FeatureCard/FeatureCard.js
add proptype validation for onClick prop so it can pass linting
**Changed**
- add Proptype validation for `onClick` to featureCard
> chore(proptype): add prop validation for feature card

- packages/react/src/components/LocaleModal/LocaleModal.js
- packages/react/src/components/LocaleModal/LocaleModalRegions.js
#1777 
Added label for the back button on the `locale selector` so it helps the screen reader
> fix(accessibility): added aria-label to back button

- packages/react/src/patterns/sub-patterns/ContentBlock/ContentBlock.js
- packages/react/src/patterns/sub-patterns/ContentBlock/__stories__/ContentBlock.stories.js
- packages/styles/scss/patterns/sub-patterns/content-block/_content-block.scss
Reverts carbon-design-system/ibm-dotcom-library#2023
> Revert "fix(content-block): render optional linklist in layout"

- packages/react/src/components/VideoPlayer/VideoPlayer.js
#1774 
I added the `aria-label` attribute with the video title on the `VideoPlayer` wrapping div.
> fix(accessibility): added video description as aria-label

- packages/react/src/__tests__/__snapshots__/storyshots.test.js.snap
- packages/react/src/components/Image/Image.js
- packages/react/src/components/Image/README.md
- packages/react/src/components/ImageWithCaption/README.md
This is a minor cleanup of the docs for `Image`.
**Changed**
- docs for `Image`
> docs(image): minor cleanup of image docs

- packages/react/src/__tests__/__snapshots__/storyshots.test.js.snap
- packages/react/src/components/CTA/README.md
- packages/react/src/patterns/sub-patterns/LinkList/README.md
- packages/react/src/patterns/sub-patterns/LinkList/__stories__/LinkList.stories.js
This updates the CTA and LinkList documentation to include the video types
**Changed**
- `CTA` and `LinkList` READMEs
- Added video to `LinkList` story
> docs(cta): updated cta/linklist docs

- packages/react/src/components/LocaleModal/LocaleModalCountries.js
- packages/react/src/patterns/blocks/ContentGroupCards/ContentGroupCards.js
- packages/react/src/patterns/sections/CardSection/CardSection.js
- packages/react/src/patterns/sections/SimpleBenefits/SimpleBenefits.js
- packages/react/src/patterns/sub-patterns/TableOfContents/TableOfContents.js
#1685
The listener cleanup was added for most of our `React` patterns.
> fix(pattern): added listener cleanup for several patterns

- packages/styles/scss/components/masthead/_masthead.scss
#2204 
Fixes hover and active background colors for various Masthead buttons.
**Changed**
- profile and hamburger button background colors updated for active/hover
> fix(css): fix masthead button hover/active colors

- tasks/tag-release.sh
#2435 
Minor fix to the diff threshold when creating the changelogs.
**Changed**
- tag/release script change
> fix(release): fixed diff history threshold for change log generation

- tasks/check-license.js
This change fixes an issue in license checker code where files are being clobbered when one file is found as missing license header (completely) while another file is updating license year.
**Changed**
- A fix for an issue in license checker code where files are being clobbered when one file is found as missing license header (completely) while another file is updating license year.
> chore(lint): fix an error in check-license.js

- packages/react/src/__tests__/__snapshots__/storyshots.test.js.snap
- packages/react/src/components/CTA/CardCTA.js
- packages/react/src/components/CTA/FeatureCTA.js
- packages/react/src/components/CardLink/CardLink.js
- packages/react/src/components/CardLink/README.stories.mdx
- packages/react/src/components/CardLink/__stories__/CardLink.stories.js
- packages/react/src/components/CardLink/index.js
- packages/react/src/components/LinkList/__stories__/LinkList.stories.js
- packages/react/src/components/LocaleModal/LocaleModalRegions.js
- packages/react/src/components/index.js
- packages/react/src/patterns/sections/CTASection/__stories__/CTASection.stories.js
- packages/styles/scss/components/expressive-modal/_expressive-modal.scss
- packages/styles/scss/components/locale-modal/_locale-modal.scss
- packages/utilities/src/utilities/smoothScroll/smoothScroll.js
Fixes #2235
This adds opinionated `CardLink` component.
**New**
- `CardLink`
**Changed**
- `LocaleModal` and `CTA` now use `CardLink` instead of `Card`
**Removed**
- `CTASection` story CSS
> feat(cardlink): adds cardlink

- packages/styles/scss/components/feature-card/_feature-card.scss
https://github.com/carbon-design-system/ibm-dotcom-library/issues/2547
**Changed**
- feature card heading type
> fix(featurecard): fixed feature card style type

- packages/react/src/components/Quote/Quote.js
Moved execution of `decodeString` to inside `useEffect`. So it only runs after mounting.
> fix(quote): decode-string util called on effect

- packages/react/src/components/LinkWithIcon/README.stories.mdx
#1913 
Added CodeSandbox example implementation link to `README`.
> chore(link-with-icon): added codesandbox example to readme

- packages/react/src/__tests__/__snapshots__/storyshots.test.js.snap
- packages/react/src/patterns/blocks/FeatureCardBlockLarge/__stories__/FeatureCardBlockLarge.stories.js
- packages/styles/scss/patterns/blocks/feature-card-block-large/_feature-card-block-large.scss
https://app.zenhub.com/workspaces/ibmcom-library-5d449f3642eb1962336cbe52/issues/carbon-design-system/ibm-dotcom-library/2407
corrected featcardblocklarge alignment via design QA feedback
**Changed**
- featcardblocklarge css and story updated
> fix(FeatCardBlockLarge): corrected grid alignment

- packages/react/examples/codesandbox/components/Layout/index.html
- packages/react/examples/codesandbox/components/Layout/package.json
- packages/react/examples/codesandbox/components/Layout/src/index.js
- packages/react/examples/codesandbox/components/Layout/src/styles.scss
- packages/react/examples/codesandbox/components/LinkWithIcon/index.html
- packages/react/examples/codesandbox/components/LinkWithIcon/package.json
- packages/react/examples/codesandbox/components/LinkWithIcon/src/index.js
- packages/react/examples/codesandbox/components/LinkWithIcon/src/styles.scss
- packages/react/examples/codesandbox/components/TableOfContents/index.html
- packages/react/examples/codesandbox/components/TableOfContents/package.json
- packages/react/examples/codesandbox/components/TableOfContents/src/index.js
- packages/react/examples/codesandbox/components/TableOfContents/src/styles.scss
- packages/react/src/components/Layout/README.stories.mdx
- packages/react/src/components/LinkWithIcon/README.stories.mdx
- packages/react/src/components/TableOfContents/README.stories.mdx
Our codesandbox examples were moved to our examples folder, so it's part of our repository
> feat(examples): codesandbox examples added to layout, table-of-contents and link-with-icon

- packages/services/src/services/Locale/Locale.js
- packages/services/src/services/Translation/Translation.js
Refs #2761.
This change supports `REACT_APP_TRANSLATION_HOST` environment variable in addition to `TRANSLATION_HOST`.
**New**
- Code to support `REACT_APP_TRANSLATION_HOST`.
> feat(services): support REACT_APP_TRANSLATION_HOST

- packages/styles/scss/components/locale-modal/_locale-modal.scss
(Please use the gear icon - Hide whitespace changes for reviewing)
Refs #2793.
This change forces local modal to come with white theme (only) for now. In future we may consider rendering locale modal outside footer (e.g. with React portal) so the zoned theme of footer won't be applied to locale modal.
**New**
- Zoned theme (white) applied to locale modal.
> fix(LocaleModal): force white theme

- packages/react/examples/codesandbox/patterns/sections/CardSectionImages/index.html
- packages/react/examples/codesandbox/patterns/sections/CardSectionImages/package.json
- packages/react/examples/codesandbox/patterns/sections/CardSectionImages/src/index.js
- packages/react/examples/codesandbox/patterns/sections/CardSectionImages/src/styles.scss
- packages/react/src/patterns/sections/CardSectionImages/README.stories.mdx
#1893 
I've added an example  codesandbox implementation on `README`
> feat(CardSectionImages): added codesandbox implementation

- packages/react/examples/codesandbox/patterns/blocks/ContentBlockSimple/index.html
- packages/react/examples/codesandbox/patterns/blocks/ContentBlockSimple/package.json
- packages/react/examples/codesandbox/patterns/blocks/ContentBlockSimple/src/index.js
- packages/react/examples/codesandbox/patterns/blocks/ContentBlockSimple/src/styles.scss
- packages/react/src/patterns/blocks/ContentBlockSimple/README.stories.mdx
#1899 
I've added a codesandbox example implementation on `README`.
> feat(ContentBlockSimple): added codesandbox example implementation

- packages/react/examples/codesandbox/patterns/blocks/ContentBlockSegmented/index.html
- packages/react/examples/codesandbox/patterns/blocks/ContentBlockSegmented/package.json
- packages/react/examples/codesandbox/patterns/blocks/ContentBlockSegmented/src/index.js
- packages/react/examples/codesandbox/patterns/blocks/ContentBlockSegmented/src/styles.scss
- packages/react/src/patterns/blocks/ContentBlockSegmented/README.stories.mdx
#1898 
Added a codesandbox example implementation to the `README`.
> feat(ContentBlockSegmented): added codesandbox example implementation

- packages/react/examples/codesandbox/patterns/blocks/ContentBlockMixed/index.html
- packages/react/examples/codesandbox/patterns/blocks/ContentBlockMixed/package.json
- packages/react/examples/codesandbox/patterns/blocks/ContentBlockMixed/src/index.js
- packages/react/examples/codesandbox/patterns/blocks/ContentBlockMixed/src/styles.scss
- packages/react/src/patterns/blocks/ContentBlockMixed/README.stories.mdx
#1897 
Added example codesandbox implementation  to  `README`.
> feat(ContentBlockMixed): added codesandbox example implementation

- .github/workflows/automerge-pr.yml
Refs https://github.com/carbon-design-system/ibm-dotcom-library/issues/3018
This adds a new github action that will automerge approved PRs. Adding the label `automerge` will activate this action.
**New**
- automerge github action
> chore(automerge): adding automerge GH action

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
assign akira and lara as assignees for incoming bug tickets
**New**
**Changed**
**Removed**
> chore(support): updating fireline support team for sprint 14

- .github/workflows/ci-check.yml
Fix variable name for node version in Github workflow.
**Changed**
- fix `matrix.node` variable name
> chore(ci-check): fix variable name

- packages/web-components/src/components/button/__stories__/README.stories.mdx
- packages/web-components/src/components/cta/__stories__/README.stories.mdx
- packages/web-components/src/components/lightbox-media-viewer/__stories__/README.stories.mdx
- packages/web-components/src/components/link-with-icon/__stories__/README.stories.mdx
- packages/web-components/src/components/masthead/__stories__/README.stories.mdx
- packages/web-components/src/components/modal/__stories__/README.stories.mdx
This change fixes wrong paths to CONTRIBUTING `.md` files in stories.
**Changed**
- Fix for wrong paths to CONTRIBUTING `.md` files in stories.
> chore(devenv): fix CONTRIBUTING path

- .github/actions/set-dotenv/action.yml
- .github/actions/set-dotenv/index.js
- .github/workflows/deploy-canary.yml
- .github/workflows/deploy-staging.yml
An attempt to fix video player in Canary site.
**Changed**
- Usage of `.env` file to make Kaltura keys in effect in our Canary site.
> chore(build): fix video player in canary site

- .github/PULL_REQUEST_TEMPLATE.md
React and Web Component deploy previews are now enabled
by default. This is updating the instructions in the
pull request template.
**Changed**
- updated `PULL_REQUEST_TEMPLATE.md`
> chore(pr): updating pr template instructions

- packages/web-components/docs/coding-conventions.md
This change adds a developer documentation for better encapsulation in Web Components codebase.
**New**
- A developer documentation for better encapsulation in Web Components codebase.
> docs(dev): add doc for WC encapsulation

- packages/react/src/components/CardSectionSimple/README.stories.mdx
- packages/react/src/components/LogoGrid/README.stories.mdx
#3332 #3333 
Fixed wrong scss path import on docs.
> fix(docs): wrong scss import path in docs

- .github/workflows/percy-update-base.yml
#3422 
This is a Github Action that will update the base snapshots
for React, Web Components, and Carbon Expressive. This will
trigger on both master and release branches.
**New**
- Github actions `percy-update-base.yml`
> chore(percy): creating github actions for percy

- .github/workflows/percy-update-base.yml
#3422 
The indentation was off in the yml file for this, this is a fix.
**Changed**
- percy-update-base.yml
> chore(percy): fix yml formatting

- packages/react/src/__tests__/__snapshots__/storyshots.test.js.snap
- packages/react/src/components/CTASection/__tests__/CTASection.test.js
- packages/react/src/components/ContentItemHorizontal/__tests__/ContentItemHorizontal.test.js
- packages/react/src/components/TableOfContents/TOCMobile.js
- packages/react/src/components/carbon-components-react/UIShell/SideNavMenuWithBackForward.js
Fix the console errors coming from React package #2693
Fixing console errors displayed when running `yarn test:unit`
PS: This PR fixes only some of the errors. More fixes need to be done.
**Changed**
- Minimum changes and fixes con components and test files in order to fix console error issues
> fix(jest): remove console errors

- packages/react/src/components/Masthead/MastheadMegaMenu/MegaMenu.js
- packages/react/src/components/Masthead/MastheadTopNav.js
Fix the console errors coming from React package #2693
Removing console errors when running `yarn test:unit` - Masthead related
**New**
- Added `keys` to `MegaMenu` menuItems
> test(Masthead): fixing console errors

- packages/react/src/__tests__/__snapshots__/storyshots.test.js.snap
- packages/react/src/components/Masthead/Masthead.js
- packages/react/src/components/Masthead/MastheadSearchSuggestion.js
#3588 
Focus now goes directly to the side menu once it's opened.
> fix(masthead): left menu focus

- packages/web-components/package.json
add update snapshot npm script to web-components package
**Changed**
- add update snapshot npm script to web-components package
> feat(package.json): add update snapshot npm script to web-components package.json

- packages/react/src/components/Masthead/__tests__/Masthead.steps.js
This change updates the UI integration test case of `<Masthead>` to catch up the change in #3618.
**Changed**
- A change to the UI integration test case of `<Masthead>` to catch up the change in #3618.
> test(Masthead): update UI integration test case

- packages/react/src/__tests__/__snapshots__/storyshots.test.js.snap
- packages/react/src/components/DotcomShell/__stories__/DotcomShell.stories.js
- packages/react/src/components/Footer/Footer.js
- packages/react/src/components/Footer/LegalNav.js
- packages/react/src/components/Footer/__stories__/Footer.stories.js
- packages/react/src/components/Masthead/Masthead.js
- packages/styles/scss/components/footer/_footer.scss
- packages/styles/scss/components/footer/_legal-nav.scss
- packages/web-components/src/components/masthead/left-nav.ts
#3431 
Adds `micro` variation to Footer component
**New**
- `micro` version added to Footer component
> feat(Footer): add micro variation

- packages/web-components/docs/coding-conventions.md
Updates the coding convention in our Web Components codebase, to reflect newer APIs introduced in upstream `carbon-web-components`, etc.
**Changed**
- The coding convention in our Web Components codebase, to reflect newer APIs introduced in upstream `carbon-web-components`, etc.
> docs(coding-convention): updates

- packages/styles/scss/components/footer/_footer-logo.scss
- packages/styles/scss/components/footer/_footer.scss
#3642 
Fix `Footer` theme styles and syntax errors
**Changed**
- update `g90` theme support in `Footer` styles
> fix(Footer): fixes footer theme styles

- packages/react/src/internal/FeatureFlags.js
Chore to remove unused feature flags in React.
**Removed**
- Removed unused feature flags
> chore(featureflags): removing unused feature flags

- packages/react/src/components/Masthead/Masthead.js
- packages/react/src/components/carbon-components-react/UIShell/HeaderMenu.js
#3661 
An SSR bug was picked up after a fix for #3661, this is adding a check.
**Changed**
- Adding check for `document.body`
> fix(masthead): ssr fix for scroll check

- .github/workflows/deploy-canary.yml
- .github/workflows/deploy-staging.yml
#3767 
Fix in the latest cf action will address the IBM cloud build issues.
**Changed**
- Changed to v1.2.0 of cloud deploy action
> chore(cfaction): updating version of cf action

- packages/react/src/__tests__/__snapshots__/storyshots.test.js.snap
- packages/react/src/components/Card/Card.js
- packages/react/src/components/FeatureCard/FeatureCard.js
Refs #3756.
Adds `onClick` prop support to `<Card>`.
**New**
- `onClick` prop support to `<Card>`.
> feat(Card): supports onClick

- packages/services/src/services/Locale/Locale.js
Refs #3824
Originally, the language/locale was fetched by waiting for the full DDO object to be loaded in by `ibm-common.js` before continuing. This change instead will fetch whatever is manually set by the adopter instead, and if it is not loaded, then will continue on from the `<html lang>` instead.
This also keeps the `LocaleAPI.getLang` method as a promise, even though it should resolve immediately.
**Changed**
- get language from DDO is now immediate in `LocaleAPI`
> fix(lang): get immediate lang value rather than waiting for DDO

- packages/web-components/src/components/lightbox-media-viewer/__tests__/lightbox-media-viewer.steps.js
Fixes UI integration test for `<dds-lightbox-media-viewer>` catching up with its latest change.
**Changed**
- A fix for the UI integration test for `<dds-lightbox-media-viewer>` catching up with its latest change.
> test(lightbox-media-viewer): fix for UI integration test

- packages/styles/scss/components/tableofcontents/_tableofcontents.scss
This change to tableofcontents style drifts away from BEM concatenation, so the style can be reused with Web Components.
**Changed**
- A change to tableofcontents style drifts away from BEM concatenation, so the style can be reused with Web Components.
> chore(tableofcontents): drift away from BEM concatenation

- packages/styles/scss/components/ctasection/_ctasection.scss
This change to ctasection style drifts away from BEM concatenation, so the style can be reused with Web Components.
**Changed**
- A change to ctasection style drifts away from BEM concatenation, so the style can be reused with Web Components
> chore(ctasection): drift away from BEM concatenation

- packages/styles/scss/components/callout-data/_callout-data.scss
- packages/styles/scss/components/callout-with-media/_callout-with-media.scss
This change to callout style drifts away from BEM concatenation, so the style can be reused with Web Components.
**Changed**
- A change to callout style drifts away from BEM concatenation, so the style can be reused with Web Components.
> chore(callout): drift away from BEM concatenation

- packages/styles/scss/components/logo-grid/_logo-grid.scss
This change to logo grid style drifts away from BEM concatenation, so the style can be reused with Web Components.
**Changed**
- A change to logo grid style drifts away from BEM concatenation, so the style can be reused with Web Components.
> chore(logo-grid): drift away from BEM concatenation

- packages/styles/scss/components/quote/_quote.scss
This change to quote style drifts away from BEM concatenation, so the style can be reused with Web Components.
**Changed**
- A change to quote style drifts away from BEM concatenation, so the style can be reused with Web Components.
> chore(quote): drift away from BEM concatenation

- packages/web-components/src/components/masthead/masthead-composite.ts
- packages/web-components/src/components/masthead/masthead-search-composite.ts
- packages/web-components/src/components/masthead/masthead-search.ts
Refs #3884.
**New**
- Default placeholder in `<dds-masthead-search>`.
> fix(masthead-search): define placeholder

- packages/styles/scss/components/locale-modal/_locale-modal.scss
#4063 
Adds css specificity to avoid overrides
**Changed**
- add specificity to hidden locale items for filtering
> fix(css): update hidden styles for locale countries

- packages/styles/scss/components/buttongroup/_buttongroup.scss
Attempt of fixing the icon styling on button group.
> fix(button-group): fixed icon padding

- packages/web-components/.storybook/addons.js
- packages/web-components/.storybook/config.ts
- packages/web-components/.storybook/container.scss
This change adds theme chooser Storybook add-on to Web Components storybook.
**New**
- Theme chooser in Web Components storybook env.
> chore(devenv): introduce theme chooser

- packages/web-components/src/components/locale-modal/locale-modal-composite.scss
- packages/web-components/src/components/locale-modal/locale-modal.ts
- packages/web-components/src/components/locale-modal/locale-search.ts
**Changed**
- Makes the `:host` selector more specific.
- Re-oreder the methods to align to other classes.
> chore(locale-modal): misc changes

- docs/developing.md
Adds a dev guide that explains what to do with task errors after a new package is added to the monorepo.
**New**
- A dev guide that explains what to do with task errors after a new package is added to the monorepo.
> docs(developers): instruction on symlinks

- packages/web-components/src/components/link-list/__stories__/link-list.stories.ts
- packages/web-components/tests/snapshots/dds-leadspace.md
#4029 
Add missing URLs to web component `LinkList` stories.
**New**
- web component Storybook `LinkList` URLs
> chore(linklist): update web component story links

- packages/web-components/src/components/card/__stories__/card.stories.ts
Refs #4044.
**Changed**
- Add more grid classes to card story to align with React one.
> chore(devenv): add more grid classes to card story

- packages/react/src/components/Masthead/HeaderNavContainer.js
#4403 
remove console errors from overflow navigation work
**New**
- checks if components exist before calling function
> fix(masthead): remove console errors

- .github/workflows/ci-check.yml
- .github/workflows/e2e-test.yml
- .github/workflows/percy-update-base.yml
Fixes an issue where wrong node.js version is used in CI.
**Changed**
- Fixes an issue where wrong node.js version is used in CI.
> chore(build): update node version

- packages/styles/scss/components/footer/_legal-nav.scss
Currently there is no color theme being used in the `micro` footer variation. This adds the correct theme which fixes background and hover colors.
**Changed**
- add `g90` theme support for micro footer
> fix(Footer): fix micro footer button css

- packages/web-components/README.md
**Changed**
- Fixes broken link in Web Components README.
> docs: fix broken link in Web Components README

- packages/web-components/src/components/card-group/__stories__/README.stories.mdx
Adding stable-selectors table
**New**
- Stable selectors table;
> docs(card-group): adding stable-selectors table

- packages/web-components/docs/contributing-to-web-components.md
Our Web Components library depends on several other packages that needs to be built before running the Storybook. Updates the contribution doc to reflect that.
**Changed**
- Updates the contribution doc to reflects that other packages has to be built before running the Storybook.
> docs(contributing): update Web Components contribution docs

- packages/web-components/src/components/button-group/__stories__/README.stories.mdx
**New**
- Stable selectors table;
- Props table.
> docs(button-group): added stable-selectors and props tables

- packages/web-components/src/components/footer/footer.scss
This reverts commit 678b8e70abe7e5feacc7604d18102645751cbe98.
> Revert "fix(legal-nav): align cookie preference to other nav items (#4680)

- packages/web-components/src/components/card/__stories__/card.stories.ts
Added grid column sizes to `Card` story.
> fix(card): added grid to story

- packages/web-components/src/components/card-section-carousel/__stories__/card-section-carousel.stories.react.tsx
- packages/web-components/src/components/pictogram-item/__stories__/README.stories.mdx
Refs #4326.
**Changed**
- Updates docs wrt remaining `slot="heading"` references in docs (except one for `<dds-link-list>`).
> docs(components): some more updates

- packages/web-components/package.json
Updates `version` field of Web Components' `package.json` to `1.x` as we release Web Components package as GA as of `v1.15.0`.
**Changed**
- The `version` field of `packages/web-components/package.json`.
> chore(package): update Web Components version to 1.x

- packages/styles/scss/components/masthead/_masthead-l1.scss
Document CSS fix applied to [#4941](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/4941).
**New**
- add style comments documenting breakpoint fix
> chore(masthead): update style docs

- packages/web-components/IMPLEMENTATION_NOTES.md
Refs #4980.
Adds notes on how container/composite components in `@carbon/ibmdotcom-web-components` works.
**New**
- Notes on how container/composite components in `@carbon/ibmdotcom-web-components` works.
> docs(web-components): implementation notes on container components

- packages/web-components/IMPLEMENTATION_NOTES.md
Refs #4991.
**Changed**
- Updates to complete the implementation notes for video player support.
> docs(web-components): complete implementation notes for video player

- packages/react/src/components/CTASection/__stories__/CTASection.stories.js
- packages/react/src/components/CalloutData/CalloutData.js
- packages/react/src/components/CardSectionCarousel/__stories__/CardSectionCarousel.stories.js
- packages/react/src/components/CardSectionSimple/__stories__/CardSectionSimple.stories.js
- packages/react/src/components/Carousel/__stories__/Carousel.stories.js
- packages/react/src/components/DotcomShell/DotcomShell.js
- packages/react/src/components/Footer/LanguageSelector.js
- packages/react/src/components/Footer/LegalNav.js
- packages/react/src/components/LeadSpace/LeadSpace.js
- packages/react/src/components/LeadspaceWithSearch/LeadspaceWithSearch.js
- packages/react/src/components/LeadspaceWithSearch/__stories__/LeadspaceWithSearch.stories.js
- packages/react/src/components/LinkList/LinkList.js
- packages/react/src/components/Masthead/MastheadMegaMenu/MegaMenu.js
- packages/react/src/components/carbon-components-react/UIShell/HeaderMenu.js
- packages/react/src/internal/components/Callout/Callout.js
- packages/react/src/internal/components/ConditionalWrapper/ConditionalWrapper.js
Fixes various props/attribute validation errors
**Changed**
- various prop type and attribute naming errors
> chore(props): fix props and attribute errors

- packages/web-components/IMPLEMENTATION_NOTES.md
Refs #4982.
Adds implementation notes on our Rollup bundle so that new developers can quickly understand how it works.
**New**
- Implementation notes on our Rollup bundle.
> docs(web-components): implementation notes on the Rollup bundle

- packages/web-components/src/components/carousel/__stories__/carousel.stories.ts
#5211
Added Cards with Images variant for Carousel stories
> feat(carousel): added story for cards with images

- packages/react/src/components/CTASection/CTASection.js
#4696 
I've removed the usage of `SetSameHeight` utility. `Grid` layout scss was already applied to `dds-button-group`.
> fix(cta-section): removed set same height usage

- packages/styles/scss/components/card/index.scss
#5034 
Removes text decoration on hover
**Changed**
- update hover styles for card component
> fix(card): remove decoration on hover

- packages/react/src/components/FeatureCardBlockMedium/README.stories.mdx
Remove the array brackets from the `card` object example in docs as it should be an object not an array
**New**
**Changed**
**Removed**
> docs(FeatureCardBlockMedium): remove array brackets from card object in docs

- docs/building-for-ibm-dotcom.md
This is an update based on the documentation provided by the analytics
team.
https://w3.ibm.com/w3publisher/digital-behavior-data-management/gdpr/cookie-consent-adoption
**Changed**
- docs for `Building for IBM.com`
> docs(building): updating docs for ibm-common script tag

- packages/web-components/src/components/link-list/__stories__/link-list.stories.ts
- packages/web-components/src/components/link-list/__tests__/link-list.test.ts
https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/5403
> fix(link-list): various bug fixes

- packages/styles/scss/components/video-player/_video-player.scss
#5660 
I've updated the focus state for the video player so it matches the designs specs.
New: 
Before:
> fix(video-player): fixed focus state

- packages/styles/scss/components/content-block-simple/_content-block-simple.scss
#5423
Added max-width to video in react version
> fix(content-block-simple): added max-width to video component on react

- README.md
Web components are no longer "coming soon"!
**Changed**
- `README.md`
> docs(readme): web components

- .github/workflows/deploy-canary.yml
- .github/workflows/deploy-staging.yml
- .github/workflows/percy-update-base.yml
https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/5691
This is an attempt to reduce the build times around various jobs in
Github Actions, particularly reducing scope of the `yarn build` and
identifying specific packages that do not need to be built, rather than
building the entire project.
**Changed**
- github actions updates
> chore(github-actions): adjusting scope of yarn builds

- packages/web-components/examples/codesandbox/usage/dotcom-shell-cdn-with-handlebars/package.json
- packages/web-components/examples/codesandbox/usage/dotcom-shell-cdn-with-rtl/package.json
- packages/web-components/examples/codesandbox/usage/markdown-handlebars/package.json
- packages/web-components/examples/codesandbox/usage/webpack-handlebars/package.json
- packages/web-components/examples/codesandbox/usage/webpack-rtl/package.json
This fixes one of the security issues brought up by dependabot. Will open up a separate issue to address the other raised security issue.
**Changed**
- Updated `handlebars` in codesandbox examples
> chore(security): fix security issues with older version of handlebars

- .github/workflows/automerge-feat.yml
Refs #6121 
This will automate the merging of any changes on `master` branch to the
long-live feature branch for the expressive sunset development work.
This will be decommissioned once the expressive feature branch is merged
down to the master branch.
**New**
- `automerge-feat` github action 
**Changed**
- Name of `automerge` to better align with the other workflow names
> chore(github-actions): adding auto merge to expressive feature branch

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/contribution_request.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
This updates the support roster to sprint 11 fireline team.
**Changed**
> chore(support): updating support roster for sprint 11

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/contribution_request.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
This updates the fireline support roster for sprint 12.
**Changed**
> chore(support): updating support roster for sprint 12

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/contribution_request.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
This updates the support roster for sprint 13.
**Changed**
> chore(support): updating support roster for sprint 13

- packages/react/src/components/LeadSpace/LeadSpace.js
This cleans up the `Leadspace` component in React which has compile errors and console warnings.
**Changed**
- change `class` to `className`
**Removed**
- `image` argument from section class name
> chore(leadspace): clean up args and attr

- packages/web-components/package.json
This adds the `visual-snapshot` script to the web components package.
> chore(percy): add visual snapshots script

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/contribution_request.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
Updating fireline support roster for sprint 14.
**Changed**
> chore(support): updating support roster for sprint 14

- .github/workflows/deploy-staging.yml
- packages/react/manifest-rtl-staging.yml
- packages/web-components/manifest-rtl-staging.yml
This adds RTL staging environments for react and web components storybooks.
**New**
- React RTL Staging manifest and deploy script
- Web Components RTL Staging manifest and deploy script
> feat(env): adding rtl staging environments

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/contribution_request.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
Updating fireline support roster for sprint 17.
**Changed**
- Issue template assignees
> chore(support): updating support roster for sprint 17

- packages/react/src/components/TabsExtendedMedia/README.stories.mdx
- packages/react/src/components/TabsExtendedMedia/__stories__/TabsExtendedMedia.stories.js
- packages/web-components/examples/codesandbox/components-react/tabs-extended-media/.gitignore
- packages/web-components/examples/codesandbox/components-react/tabs-extended-media/index.html
- packages/web-components/examples/codesandbox/components-react/tabs-extended-media/package.json
- packages/web-components/examples/codesandbox/components-react/tabs-extended-media/sandbox.config.json
- packages/web-components/examples/codesandbox/components-react/tabs-extended-media/src/index.css
- packages/web-components/examples/codesandbox/components-react/tabs-extended-media/src/index.js
- packages/web-components/examples/codesandbox/components-react/tabs-extended-media/webpack.config.js
- packages/web-components/examples/codesandbox/components/tabs-extended-media/.babelrc
- packages/web-components/examples/codesandbox/components/tabs-extended-media/.gitignore
- packages/web-components/examples/codesandbox/components/tabs-extended-media/.sassrc
- packages/web-components/examples/codesandbox/components/tabs-extended-media/cdn.html
- packages/web-components/examples/codesandbox/components/tabs-extended-media/index.html
- packages/web-components/examples/codesandbox/components/tabs-extended-media/package.json
- packages/web-components/examples/codesandbox/components/tabs-extended-media/sandbox.config.json
- packages/web-components/examples/codesandbox/components/tabs-extended-media/src/index.js
- packages/web-components/examples/codesandbox/components/tabs-extended-media/src/index.scss
- packages/web-components/src/components/masthead/masthead-global-bar.ts
- packages/web-components/src/components/tabs-extended-media/__stories__/README.stories.react.mdx
- packages/web-components/src/components/tabs-extended-media/__stories__/tabs-extended-media.stories.react.tsx
- packages/web-components/src/components/tabs-extended-media/tabs-extended-media.ts
- packages/web-components/tests/e2e/__tests__/tabs-extended-media/tabs-extended-media.cdn.e2e.js
- packages/web-components/tests/e2e/__tests__/tabs-extended-media/tabs-extended-media.e2e.js
#5395
Create Tabs Extended Media react wrapper. 
**New**
- create react wrapper story, readme, and codesandbox
- regular web component codesandbox
- e2e tests
- 
**Removed**
- left over console.log in masthead search
> fix(tabs-extended-media): add react wrapper

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/contribution_request.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
This updates the fireline support roster for sprint 18.
**Changed**
> chore(support): updating support roster for sprint 18

- .github/workflows/codeql-analysis.yml
This sets up a code scan workflow in our repo.
**New**
- `codeql-analysis.yml`
> chore(code-scan): introduce codeQL scan workflow

- packages/react/src/components/LightboxMediaViewer/LightboxMediaViewer.js
- packages/react/src/components/LightboxMediaViewer/README.stories.mdx
**New**
**Changed**
**Removed**
> docs(LightboxMediaViewer): typo and syntax fixes and prop descriptions update

- packages/styles/scss/components/feature-card/_feature-card.scss
- packages/web-components/src/components/feature-card/feature-card.scss
[feature card] theming is off #6350
**New**
**Changed**
**Removed**
> fix(feature-card): updating color tokens

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/contribution_request.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
This updates the support roster for sprint 19.
**Changed**
> chore(support): updating support roster for sprint 19

- .github/ISSUE_TEMPLATE/test_scenario_creation.yaml
This adds a test scenario issue form for Praveen to input issues for the engineering team.
**New**
- `test_scenario_creation.yaml`
> chore(issue-template): introduce test scenario creation form

- packages/web-components/src/globals/mixins/stable-selector.ts
- packages/web-components/tests/snapshots/dds-content-block-card-static.md
#6813
After talking to adopter, this PR is  also adding an extra functionality in which the transposition works to reflect target changes even after initialization (i.e. if you update in dev tools it also changes in shadow dom).
**New**
- transposition function can also now update after initialization
> feat(data-transpose): changes in light reflect to shadow dom

- .github/ISSUE_TEMPLATE/bug_report.yaml
- .github/ISSUE_TEMPLATE/contribution_request.yaml
- .github/ISSUE_TEMPLATE/feature_request.yaml
- .github/ISSUE_TEMPLATE/question.yaml
This updates the fireline roster for sprint 23.
**Changed**
- issue template assignees
> chore(support): update fireline roster for sprint 23

- packages/react/package.json
- packages/services-store/package.json
- packages/services/package.json
- packages/web-components/package.json
Update `utilities` package version to non-canary
> chore(utilities): update package version

- .github/ISSUE_TEMPLATE/bug_report.yaml
- .github/ISSUE_TEMPLATE/contribution_request.yaml
- .github/ISSUE_TEMPLATE/feature_request.yaml
- .github/ISSUE_TEMPLATE/question.yaml
This PR updates the fireline roster on the issue templates for this sprint
> chore(support): update fireline roster for sprint 4

- packages/web-components/src/components/background-media/background-media.scss
Fixes #8995 
Updates the focus styles on the play/pause button for the background-media button
**Changed**
- Stylefix for accessible focus states
> fix(background-media): fix low-contrast focus state

- packages/styles/scss/components/link-list/_link-list.scss
Fixes invalid slotted styles that can cause build issues.
**Changed**
- changes `slotted` styles to not use invalid child selectors
> fix(link-list): fix invalid slotted styles

- packages/web-components/src/components/expressive-modal/__stories__/expressive-modal.stories.react.tsx
none
This PR updates the expressive modal React wrapper story so that the modal footer button content renders correctly
discovered while investigating #9124
> fix(expressive-modal): render footer button content correctly

- packages/react/src/components/ContentGroup/ContentGroup.js
- packages/react/src/components/ContentGroup/__stories__/ContentGroup.stories.js
- packages/react/src/components/ContentSection/__stories__/ContentSection.stories.js
- packages/react/src/components/FeatureCard/__stories__/FeatureCard.stories.js
#9119
#9117
#9116
Fixing some of the React Stories:
- Feature Card
- Content group
- Content Section
**Changed**
- changing the way parameters are being passed to the stories
> fix(storybook): various react story fixes

- packages/react/examples/codesandbox/components/NoticeChoice/package.json
none
add missing build script the e2e-integration test is looking for
**New**
**Changed**
**Removed**
> fix(notice-choice): missing build cmd

- .github/workflows/ci-check.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/e2e-integration.yml
- .github/workflows/e2e-tests.yml
- .github/workflows/percy-update-base.yml
- packages/services-store/src/actions/__tests__/translateAPI.test.ts
- packages/services-store/src/reducers/__tests__/translateAPI.test.ts
- packages/web-components/src/components/masthead/__stories__/links.ts
- packages/web-components/tests/snapshots/dds-content-block-card-static.md
- packages/web-components/tests/snapshots/dds-masthead-composite.md
Includes the `feat/masthead-v2` branch in relevant Github actions workflows.
**New**
- adds `feat/masthead-v2` to relevant workflows
> fix(gh-actions): update workflows to include `feat/masthead-v2`

- .github/workflows/publish-alpha.yml
- .github/workflows/publish-canary.yml
- .github/workflows/publish-nightly.yml
Adds flag to NPM publish script to bypass 2FA.
**New**
- add `no-verify` flag to bypass NPM 2FA
> fix(actions): fixes gh publish actions with `no-verify` for 2fa

- packages/web-components/examples/codesandbox/components-react/dotcom-shell/.gitignore
- packages/web-components/examples/codesandbox/components-react/dotcom-shell/index.html
- packages/web-components/examples/codesandbox/components-react/dotcom-shell/package.json
- packages/web-components/examples/codesandbox/components-react/dotcom-shell/sandbox.config.json
- packages/web-components/examples/codesandbox/components-react/dotcom-shell/src/index.css
- packages/web-components/examples/codesandbox/components-react/dotcom-shell/src/index.js
- packages/web-components/examples/codesandbox/components-react/dotcom-shell/webpack.config.js
- packages/web-components/src/components/dotcom-shell/__stories__/README.stories.mdx
- packages/web-components/src/components/dotcom-shell/__stories__/README.stories.react.mdx
- packages/web-components/src/components/dotcom-shell/__stories__/data/content.react.tsx
- packages/web-components/src/components/dotcom-shell/__stories__/data/content.ts
- packages/web-components/src/components/dotcom-shell/__stories__/dotcom-shell.stories.react.tsx
#8635 
Create dotcomshell react wrapper
**New**
- storybook, readme, codesandbox
**Changed**
- updated wc storybook to have correct docs
- updated wc storybook content to not use deprecated components
**Removed**
> feat(dotcom-shell): create react wrapper

- packages/web-components/src/components/tabs-extended-media/__stories__/tabs-extended-media.stories.ts
Fixes #9553
Fixes a logic problem in the storybook story resulting in casting a boolean to a string instead of rendering nothing.
**Changed**
- Fix to storybook story
> fix(tabs-extended-media): fix improper logic in story

- packages/web-components/.storybook/react/main.js
- packages/web-components/src/components/button-group/__stories__/README.stories.react.mdx
- packages/web-components/src/components/dotcom-shell/__stories__/README.stories.react.mdx
- packages/web-components/tools/babel-plugin-create-react-custom-element-type.js
causing react wrapper deploy previews to fail
> Revert "fix(storybook-react-wrapper): props not appearing"

- .github/workflows/ci-check.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/e2e-integration.yml
- .github/workflows/e2e-tests.yml
Add `feat/masthead-v2-dev` branch to necessary workflows
**Changed**
- Add `feat/masthead-v2-dev` branch to necessary workflows
> chore(git-actions): update workflow to include `feat/masthead-v2-dev`

- .github/workflows/automerge-content-updates.yml
- .github/workflows/ci-check.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/e2e-tests.yml
- .github/workflows/percy-update-base.yml
N/A
setup automerge for new branch making content block/group updates
> feat(content-updates): setup automerge branch

- README.md
opening new PR for "docs(README): add storybook links #9409"
**New**
**Changed**
**Removed**
> chore(readme): update with storybook demo links

- packages/styles/scss/components/masthead/_masthead-leftnav.scss
- packages/styles/scss/components/masthead/_masthead-megamenu.scss
- packages/web-components/src/components/masthead/defs.ts
- packages/web-components/src/components/masthead/masthead-composite.ts
- packages/web-components/src/components/masthead/masthead.scss
- packages/web-components/src/components/masthead/megamenu-heading.ts
- packages/web-components/src/components/masthead/megamenu-right-navigation.ts
- packages/web-components/src/components/masthead/top-nav.ts
Some code changes were made in response to design QA feedback while merging all the v2.1 work into the `feat/masthead-v2` branch. We need to get these commits back into the dev branch.
**Changed**
- Integrates design bug fixes into masthead v2 dev branch.
> chore(masthead-v2): integrate design QA changes back into dev branch

- packages/carbon-web-components/docs/welcome-story.mdx
Update welcome-story.mdx with `@carbon/web-components`
> Update welcome-story.mdx with `@carbon/web-components`

- packages/carbon-web-components/.storybook/_container.scss
Update Storybook style imports. Fixes various global style issues such as font and css resets.
**New**
**Changed**
**Removed**
> chore(sb): update storybook style imports

- .github/workflows/add-to-project.yml
**New**
**Changed**
- add indentation to `add-to-project` workflow file
**Removed**
> chore(gh): fix syntax typo in workflow file

- .github/workflows/deploy-cwc-v2-beta.yml
- packages/carbon-web-components/package.json
**New**
**Changed**
**Removed**
> chore(npm): update version to beta

- .github/ISSUE_TEMPLATE/bug_report.yaml
- .github/ISSUE_TEMPLATE/contribution_request.yaml
- .github/ISSUE_TEMPLATE/feature_request.yaml
- .github/ISSUE_TEMPLATE/question.yaml
- .github/workflows/ci-check.yml
Removes auto-assigness from various issue templates.
**New**
**Changed**
**Removed**
- assignees from issue templates
> chore(gh): remove auto assignee from issue templates

- packages/carbon-web-components/docs/styling-story.mdx
- packages/carbon-web-components/docs/styling.md
- packages/carbon-web-components/examples/codesandbox/data-table/package.json
- packages/carbon-web-components/examples/codesandbox/data-table/src/demo-data-table.js
- packages/carbon-web-components/examples/codesandbox/styling/custom-style/src/index.js
- packages/carbon-web-components/src/components/button/button-story.ts
- packages/carbon-web-components/src/components/file-uploader/demo-file-uploader.ts
- packages/carbon-web-components/src/components/layer/layer-story.ts
- packages/carbon-web-components/src/components/list/ordered-list-story.ts
- packages/carbon-web-components/src/components/list/unordered-list-story.ts
- packages/carbon-web-components/src/components/multi-select/multi-select-item.ts
- packages/carbon-web-components/src/components/tile/expandable-tile.ts
- packages/carbon-web-components/src/components/tile/radio-tile.ts
- packages/carbon-web-components/src/components/toggle-tip/toggletip-story.ts
- packages/carbon-web-components/src/components/toggle-tip/toggletip.ts
Add missed import extensions.
**Changed**
- Add missed import extensions
> fix: add missed import extensions

- packages/carbon-web-components/.storybook/manager-head.html
- packages/carbon-web-components/.storybook/preview-head.html
- packages/carbon-web-components/.storybook/theme.ts
This adds Plex via CDN, which seems to resolve certain font issues. Also added `fontBase` and `fontCode` to the theme config, which doesn't seem to do anything. Going to leave it for now because it could be something in our config that we need to fix before they are applied.
**New**
**Changed**
**Removed**
> chore(storybook): add plex cdn stylesheet

- packages/web-components/src/components/masthead/megamenu-top-nav-menu.ts
Hotfix to repair broken L0 behaviors found on ibm.com/products/* pages.
**Changed**
- removes problematic workaround for chat-module integration
> fix(masthead): remove cm-app init as minimize workaround

- packages/web-components/src/components/masthead/megamenu-top-nav-menu.ts
N/A
Merges L0 navigation + contact/chat module hotfix from dev into release branch.
> feat(masthead-v2): merge hotfix from dev

- packages/web-components/src/components/notice-choice/notice-choice.ts
Temporarily remove `notice-choice` React wrapper added in #10421 as it is throwing errors and affecting the CI workflow.
**New**
**Changed**
**Removed**
- `notice-choice` React wrapper
**New**
**Changed**
**Removed**
> chore(notice-choice): remove react wrapper causing build errors (#10442)

- packages/carbon-web-components/package.json
Bump `@carbon/web-components` to `beta.4`.
**New**
**Changed**
- bumps `@carbon/web-components` to `beta.4`
**Removed**
> chore(package): bump cwc package version

- packages/carbon-web-components/package.json
Bump package version to `beta 5`.
**New**
**Changed**
**Removed**
> chore(deps): bump package version beta 5

- packages/carbon-web-components/src/components/breadcrumb/breadcrumb.scss
Fix #10621 
Remove the unexpected breadcrumb margin.
**Changed**
- fix(breadcrumb): remove the unexpected margin
> fix(breadcrumb): remove the unexpected margin

- docs/dotcom-v2-migration.md
Add migration template for v2 so we can fill out as we make changes to the components.
**New**
- migration doc
> docs(migration): add migration v2 template

- package.json
- packages/carbon-web-components/src/globals/directives/spread.ts
- packages/carbon-web-components/src/typings/vendor.d.ts
Enable ESLint in .ts files.
**New**
- fix: enable ESLint in .ts files
> fix: enable ESLint in .ts files

- packages/carbon-web-components/src/components/ui-shell/header.scss
https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10695
Fix the expanded panel styles.
**New**
- fix(ui-shell): fix the expanded panel styles
> fix(ui-shell): fix the expanded panel styles

- packages/web-components/README.md
- packages/web-components/src/globals/mixins/stable-selector.ts
#10607 
add documentation about FOUC so adopters know to include it within their applications
**New**
- documentation
**Removed**
- FOUC script that did not work
> fix(fouc): add to documentation

- packages/carbon-web-components/src/components/data-table/stories/data-table-toolbar-story.ts
- packages/carbon-web-components/src/components/data-table/table-toolbar.ts
- packages/carbon-web-components/src/components/modal/modal-story.ts
- packages/carbon-web-components/src/components/modal/modal.scss
- packages/carbon-web-components/src/components/overflow-menu/overflow-menu.scss
- packages/carbon-web-components/src/components/overflow-menu/overflow-menu.ts
- packages/carbon-web-components/src/components/radio-button/radio-button.scss
- packages/carbon-web-components/src/components/search/search.scss
- packages/carbon-web-components/src/components/slider/slider-input.ts
- packages/carbon-web-components/src/components/slider/slider-story.ts
- packages/carbon-web-components/src/components/slider/slider.ts
#10735
Correct missing styles
**New**
**Changed**
**Removed**
> fix(styles): fix various component styles

- .github/PULL_REQUEST_TEMPLATE.md
**New**
**Changed**
**Removed**
> fix(pr-template): include keyword Closes

- packages/carbon-web-components/src/components/button/button.scss
- packages/carbon-web-components/src/components/data-table/_table-action.scss
- packages/carbon-web-components/src/components/search/search.scss
none 
missing tokens for button skeleton, search, search in toolbar
**New**
**Changed**
**Removed**
> fix(styling): missing tokens

- packages/eslint-config-ibmdotcom/package.json
- yarn.lock
Update `eslint-plugin-lit` to latest
**Changed**
- chore: update eslint-plugin-lit
> chore: update eslint-plugin-lit

- packages/web-components/src/components/notice-choice/__stories__/notice-choice.stories.ts
- packages/web-components/src/components/notice-choice/country-settings.ts
- packages/web-components/src/components/notice-choice/notice-choice.ts
- packages/web-components/src/components/notice-choice/services.ts
This section shows the specific product's legal links, terms, and conditions. Along with it, it collects users' consent regarding communication preferences.
**New**
-  A new web component to create notice & choice user interface.
**Changed**
-  Notice and Choice content loaded by languages.
**Removed**
- Postal option removed from new notice and choice version
> Notice and Choice v23 new version

- docs/cwc-v2-migration.md
#10733
add component migration docs
> fix(docs): update migration

- packages/web-components/src/components/notice-choice/__stories__/notice-choice.stories.ts
Closes #10858 
Move the component in storybook under "IBM Components" folder to better organize components
**New**
- "IBM Components" folder in storybook
> feat(notice-choice): move component in storybook to specific folder

- packages/web-components/src/components/notice-choice/notice-choice.ts
This section shows the specific product's legal links, terms, and conditions. Along with this, it collects users' consent regarding communication preferences.
**New**
-  A new web component to create notice & choice user interface.
**Changed**
-  Fixed call-back function preventFormSubmission
**Removed**
- Postal option removed from new notice and choice version
> Fix callback issue preventFormSubmission

- packages/styles/scss/components/expressive-modal/_expressive-modal.scss
Update component style to use `math.div` to suppress warnings.
**New**
**Changed**
- update `expressive-modal` styles to use `math.div`
**Removed**
> chore(sass): update style to use math.div

- docs/dotcom-v2-migration.md
- packages/styles/scss/components/carousel/_carousel.scss
- packages/styles/scss/components/image/_image.scss
- packages/web-components/examples/codesandbox/components-react/carousel/src/index.js
- packages/web-components/examples/codesandbox/components/carousel/cdn.html
- packages/web-components/examples/codesandbox/components/carousel/index.html
- packages/web-components/src/components/card/__stories__/card.stories.ts
- packages/web-components/src/components/card/card.ts
- packages/web-components/src/components/carousel/__stories__/README.stories.mdx
- packages/web-components/src/components/carousel/__stories__/README.stories.react.mdx
- packages/web-components/src/components/carousel/__stories__/carousel.stories.react.tsx
- packages/web-components/src/components/carousel/__stories__/carousel.stories.ts
- packages/web-components/src/components/carousel/carousel.ts
- packages/web-components/src/components/cta/card-cta.ts
Closes #10726
This PR updates the carousel page size to include the proper number of cards at all breakpoints, and resolves a render issue with video cards that was breaking two component stories
**Changed**
- xlg carousel page size
- video card cta thumbnail render logic
> fix(carousel): update v2 styles and fix broken video cards

- .github/workflows/automerge-cwc-releases.yml
- .github/workflows/deploy-cwc-next.yml
none
create automerge job for when pushing to `release-cwc/*`
**New**
**Changed**
**Removed**
> chore(cwc): add automerge and next storybook

- .github/workflows/automerge-cwc-releases.yml
- .github/workflows/deploy-cwc-next.yml
- packages/carbon-web-components/package.json
Merges changes from `release-cwc/*` branch to `main`
**New**
**Changed**
**Removed**
> chore(merge): merge changes from cwc release to main

- packages/carbon-web-components/src/components/checkbox/checkbox-story.ts
Remove unused var
**Removed**
- unused var
> chore(lint): remove unused var

- packages/carbon-web-components/src/components/slider/slider.scss
Closes #11272 
**New**
**Changed**
**Removed**
> fix(slider): sizing issues

- packages/carbon-web-components/README.md
- packages/carbon-web-components/examples/codesandbox/basic/components/skeleton-icon/.babelrc
- packages/carbon-web-components/examples/codesandbox/basic/components/skeleton-icon/.gitignore
- packages/carbon-web-components/examples/codesandbox/basic/components/skeleton-icon/.sassrc
- packages/carbon-web-components/examples/codesandbox/basic/components/skeleton-icon/cdn.html
- packages/carbon-web-components/examples/codesandbox/basic/components/skeleton-icon/index.html
- packages/carbon-web-components/examples/codesandbox/basic/components/skeleton-icon/package.json
- packages/carbon-web-components/examples/codesandbox/basic/components/skeleton-icon/sandbox.config.json
- packages/carbon-web-components/examples/codesandbox/basic/components/skeleton-icon/src/index.js
- packages/carbon-web-components/examples/codesandbox/basic/components/skeleton-icon/src/styles.scss
- packages/carbon-web-components/src/components/skeleton-icon/docs/overview.mdx
- packages/carbon-web-components/src/components/skeleton-icon/index.ts
- packages/carbon-web-components/src/components/skeleton-icon/skeleton-icon-story.mdx
- packages/carbon-web-components/src/components/skeleton-icon/skeleton-icon-story.ts
- packages/carbon-web-components/src/components/skeleton-icon/skeleton-icon.scss
- packages/carbon-web-components/src/components/skeleton-icon/skeleton-icon.ts
- packages/carbon-web-components/src/index.ts
Closes #11380 
Adds new skeleton icon component
**New**
- skeleton icon readme, story, codesandbox examples
> feat(skeleton-icon): new cwc component

- .github/workflows/e2e-tests-parallel.yml
- packages/services-store/src/types/translateAPI.ts
- packages/styles/scss/components/masthead/_masthead-l1.scss
- packages/utilities/src/utilities/StickyHeader/StickyHeader.js
- packages/web-components/src/components/masthead/__stories__/masthead.stories.ts
- packages/web-components/src/components/masthead/masthead-composite.ts
- packages/web-components/src/components/masthead/masthead-l1.ts
- packages/web-components/src/components/masthead/top-nav.ts
Merges latest code from `feat/masthead-v2-dev` into `feat/masthead-v2`. The only code change present is from https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/11478.
> chore(masthead-v2): merge latest alpha dev into alpha release

- packages/carbon-web-components/docs/carbon-cdn-style-helpers.md
This updates the CDN docs to include the CSS Grid CDN artifact, and differentiating from the flex grid styles.
**Changed**
- CDN docs
> chore(cdn): add CSS grid CDN urls

- packages/carbon-web-components/CHANGELOG.md
- packages/carbon-web-components/package.json
- packages/services/CHANGELOG.md
- packages/services/package.json
- packages/styles/CHANGELOG.md
- packages/styles/package.json
- packages/utilities/CHANGELOG.md
- packages/utilities/package.json
- packages/web-components/CHANGELOG.md
- packages/web-components/package.json
- yarn.lock
**New**
**Changed**
**Removed**
> chore(release): resolve merge conflict

- packages/styles/scss/components/masthead/_masthead-l1.scss
- packages/utilities/src/utilities/StickyHeader/StickyHeader.js
- packages/web-components/src/components/dotcom-shell/__stories__/data/content.ts
- packages/web-components/src/components/dotcom-shell/__stories__/dotcom-shell.stories.ts
- packages/web-components/src/components/leadspace-with-search/leadspace-with-search.ts
- packages/web-components/src/components/masthead/masthead-l1.ts
Gets latest changes cherry-picked into feat/masthead-v2-dev into feat/masthead-v2 so that we can cut a release.
> chore(masthead-v2): get latest from alpha dev into alpha release

- packages/web-components/src/components/content-group-cards/content-group-cards.ts
- packages/web-components/tests/snapshots/c4d-callout-with-media.md
- packages/web-components/tests/snapshots/c4d-content-block-cards.md
- packages/web-components/tests/snapshots/c4d-content-block-headlines.md
- packages/web-components/tests/snapshots/c4d-content-block-horizontal.md
- packages/web-components/tests/snapshots/c4d-content-block-media.md
- packages/web-components/tests/snapshots/c4d-content-block-segmented.md
- packages/web-components/tests/snapshots/c4d-content-block-simple.md
- packages/web-components/tests/snapshots/c4d-content-group-cards.md
- packages/web-components/tests/snapshots/c4d-content-group-simple.md
- packages/web-components/tests/snapshots/c4d-cta-block.md
- packages/web-components/tests/snapshots/c4d-in-page-banner.md
- packages/web-components/tests/snapshots/c4d-search-with-typeahead.md
https://jsw.ibm.com/browse/ADCMS-5059
#11673
> feat(content-group-cards): add shadowparts

- packages/carbon-web-components/src/components/ui-shell/side-nav.ts
- packages/web-components/src/components/masthead/left-nav-menu-item.ts
- packages/web-components/src/components/masthead/left-nav-menu-section.ts
- packages/web-components/src/components/masthead/left-nav-menu.ts
- packages/web-components/src/components/masthead/left-nav.ts
- packages/web-components/tests/snapshots/dds-left-nav-menu.md
https://jsw.ibm.com/browse/ADCMS-5191
TBD
**New**
**Changed**
**Removed**
> fix(left-nav): focus trapping

- packages/web-components/src/components/link-list-section/link-list-section.ts
- packages/web-components/tests/snapshots/c4d-link-list-section.md
https://jsw.ibm.com/browse/ADCMS-5164
**Changed**
- Adds CSS shadow parts to link-list-section component
> feat(link-list-section): add CSS shadow parts

- packages/web-components/src/components/link-list/link-list.ts
- packages/web-components/tests/snapshots/c4d-link-list.md
https://jsw.ibm.com/browse/ADCMS-5165
updates components in the link-list dir
**Changed**
- adds `part` attributes to the link-list components
> feat(link-list): add CSS shadowparts

- packages/web-components/src/components/leadspace-block/leadspace-block-content.ts
- packages/web-components/src/components/leadspace-block/leadspace-block.ts
- packages/web-components/tests/snapshots/c4d-leadspace-block.md
Adds shadowparts to leadspace-block elements
**Changed**
- Added shadow parts
> feat(leadspace-block): add shadow parts

- packages/web-components/src/components/leadspace-with-search/leadspace-with-search.ts
- packages/web-components/src/components/search-with-typeahead/search-with-typeahead.ts
- packages/web-components/tests/snapshots/c4d-search-with-typeahead.md
[ADCMS-5160](https://jsw.ibm.com/browse/ADCMS-5160)
Adding shadow parts to the Leadspace With Search component so it can be styled outside of the shadow tree
> feat(leadspace-with-search): add shadow parts

- packages/web-components/src/components/tabs-extended/tabs-extended.ts
none
The current implementation sets focus to a tab any time it is set as "active". This works great for the intended use case, but the problem is that the first tab is made active when the component mounts. This is not so great on page load, forcing focus to the tab and scrolling the page down to it.
The fix is to only set focus on a user interaction.
**Changed**
- Prevents DDSTabsExtended elements from stealing focus on component mount.
1. Visit the Tabs Extended deploy preview and "open the canvas in a new tab" (https://ibmdotcom-webcomponents.s3.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/11882/iframe.html?args=&id=components-tabs-extended--default&viewMode=story)
2. Using your browser console, check which element has focus on load – `document.activeElement`
- …
> fix(tabs-extended): prevent stealing focus on page load

- packages/carbon-web-components/src/components/ui-shell/header-menu-button.ts
- packages/carbon-web-components/src/components/ui-shell/header-menu.ts
- packages/carbon-web-components/src/components/ui-shell/header-name.ts
- packages/carbon-web-components/src/components/ui-shell/header-nav-item.ts
- packages/carbon-web-components/src/components/ui-shell/header-nav.ts
- packages/carbon-web-components/src/components/ui-shell/side-nav-menu-item.ts
- packages/carbon-web-components/src/components/ui-shell/side-nav-menu.ts
- packages/carbon-web-components/src/components/ui-shell/side-nav.ts
[Jira](https://jsw.ibm.com/browse/ADCMS-5361)
PR to bring the @csspart notations to the pattern set on C4IBM.COM
**Changed**
The @csspart annotations in the `ui-shell` components.
> chore(ui-shell): update shadow parts documentation

- packages/web-components/.storybook/manager-head.html
- packages/web-components/.storybook/react/manager-head.html
Adding mandatory intrumentation tags for Carbon for IBM.com web components storybook
**Changed**
- Added `ibm-common.js` and IBM footer to storybooks
> chore(ibm-common): add mandatory IBM instrumentation tags (v1)

- packages/carbon-web-components/src/components/pagination/pagination.ts
- packages/carbon-web-components/tests/snapshots/cds-copy-button.md
[ADCMS-5336](https://jsw.ibm.com/browse/ADCMS-5336)
Adding shadow parts to the pagination component, so that it can be styled outside of the shadow tree.
Snapshots updated.
> feat(pagination): adding shadow parts

- packages/carbon-web-components/src/components/structured-list/structured-list-header-cell-skeleton.ts
- packages/carbon-web-components/src/components/structured-list/structured-list-header-row.ts
- packages/carbon-web-components/src/components/structured-list/structured-list-row.ts
- packages/carbon-web-components/src/components/structured-list/structured-list.ts
- packages/carbon-web-components/tests/snapshots/cds-copy-button.md
[ADCMS-5351](https://jsw.ibm.com/browse/ADCMS-5351)
Adding shadow parts to the Structured List component so that it can be styled outside of the shadow tree.
Snapshots updated
> feat(structured-list): adding shadow parts

- packages/carbon-web-components/src/components/text-input/text-input-skeleton.ts
- packages/carbon-web-components/src/components/text-input/text-input.ts
[ADCMS-5355](https://jsw.ibm.com/browse/ADCMS-5355)
Adding shadow parts to the text-input component.
> feat(text-input): adding shadow parts

- packages/styles/scss/components/image/_image.scss
Closes # https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/11960
[JIRA](https://jsw.ibm.com/browse/ADCMS-5976)
PR to fix issue where the image component aspect ratio was not changing
**Removed**
Styles causing the issue
> fix(image): fix aspect ratio not changing

- packages/styles/scss/components/notice-choice/_notice-choice.scss
This section shows the specific product's legal links, terms, and conditions. Along with this, it collects users' consent regarding communication preferences.
**New**
**Changed**
- The problem with the Arabic checkbox displaying the tick mark in CSS has been resolved.
**Removed**
> Fixed Arabic Right Direction Issue

- packages/services/README.md
- packages/services/telemetry.yml
- packages/styles/README.md
- packages/styles/telemetry.yml
- packages/utilities/README.md
- packages/utilities/telemetry.yml
- packages/web-components/README.md
- packages/web-components/telemetry.yml
This PR updates the endpoint within each package's `telemetry.yml` file with the new stable endpoint for the collector. Also, this updates the wording used in the telemetry notice under each README.
**Changed**
- `telemetry.yml` endpoint to new stable endpoint
- updated wording under telemetry notice in each README
> chore(telemetry): updated telemetry.yml endpoint

- packages/carbon-web-components/README.md
- packages/carbon-web-components/telemetry.yml
- packages/react/README.md
- packages/react/telemetry.yml
- packages/services/README.md
- packages/services/telemetry.yml
- packages/styles/README.md
- packages/styles/telemetry.yml
- packages/utilities/README.md
- packages/utilities/telemetry.yml
- packages/web-components/README.md
- packages/web-components/telemetry.yml
This PR updates the endpoint within each package's `telemetry.yml` file with the new stable endpoint for the collector. Also, this updates the wording used in the telemetry notice under each README.
**Changed**
- `telemetry.yml` endpoint to new stable endpoint
- updated wording under telemetry notice in each README
> chore(telemetry): update telemetry.yml endpoint in v1 branch

- packages/styles/scss/components/card/_card.scss
https://jsw.ibm.com/browse/ADCMS-7078
Removes problematic styles from v2 merge
**Changed**
- minor style fix
> fix(card): remove bad styles

- packages/web-components/src/components/feature-section/__stories__/feature-section.stories.ts
- packages/web-components/src/components/feature-section/defs.ts
- packages/web-components/src/components/feature-section/feature-section.ts
Closes #[ADCMS-7463](https://jsw.ibm.com/browse/ADCMS-7463)
On CIBM v1, the Feature Card Section component allowed the author to switch the positioning of the media between the right and left sides on the component. This capability was removed in v2 and the UX team is recommending to bring this capability back.
**New**
Media alignment has been added back to the `feature-section` component.
> feat(feature-section): adding media alignment

- packages/styles/scss/components/card/_card.scss
- packages/web-components/src/components/card/card.ts
[JIRA](https://jsw.ibm.com/browse/ADCMS-7539)
PR to replicate the the v1 hover interaction on cards with pictogram.
**Changed**
- V1 hover interaction for cards with pictogram is now preesent on viwewports larger than breakpoint md and with fine pointer
> feat(card): replicate v1 hover behavior

- packages/web-components/src/components/masthead/masthead-composite.ts
- packages/web-components/src/components/masthead/masthead.scss
None - this is a work requested for the L0 work by Nishant and Neha
New globe icon added in the social bar. Between the contact and the profile icon
> fix(masthead): adding language selector at L0

- packages/styles/scss/globals/_scroll-snap.scss
- packages/web-components/src/components/content-item/content-item.ts
- packages/web-components/src/components/cta-block/cta-block-item-row.ts
- packages/web-components/src/components/cta-block/cta-block-item.ts
- packages/web-components/src/components/cta-block/cta-block.scss
- packages/web-components/src/components/masthead/masthead-l1.scss
Jira: https://jsw.ibm.com/browse/ADCMS-7820
Pr to add a scrolll-snap container to the cta-section component 
cta-section mobile brakpoints  With image/media style
Items are horizontally scrollable (swipe left/right)
> feat(cta-section): optimize for mobile

- packages/styles/scss/components/link-list/_link-list.scss
[JIRA](https://jsw.ibm.com/browse/ADCMS-7513)
PR to adjust the padding on the link-list-item-cta component
**Changed**
Reduced the padding of the component form `spacing-04` to `spacing-03`
> fix(link-list): asjust spacing

- packages/web-components/src/components/content-block-simple/content-block-simple.scss
[Jira](https://jsw.ibm.com/browse/ADCMS-7531)
PR to adjust the card spacing on the simple narrative
> fix(content-block-simple): adjust card alignment

- packages/web-components/src/components/content-block-simple/content-block-simple.scss
[ADCMS-7507](https://jsw.ibm.com/browse/ADCMS-7507)
adjusting the value to a percentage
> fix(card): fix simple narrative size

- packages/styles/scss/components/callout-quote/_callout-quote.scss
- packages/web-components/src/components/callout-quote/__stories__/callout-quote.stories.ts
- packages/web-components/src/components/quote/quote.ts
https://jsw.ibm.com/browse/ADCMS-9014
Card appearance for the callout-quote in mobile was not correct with Figma specs. Source and Footer should be inside of the cards
> fix(callout-quote): card appearance not correct in mobile
