packages/react/src/components/Masthead/MastheadSearch.js

#5819 
Fixes an issue in the `default` React masthead where clicking the search icon while the search component is open with no search value would close the entire component. The expected behavior is for the search component to remain open and do nothing.
**Changed**
- search visibility behavior in `MastheadSearch`

fix(masthead): search icon does nothing when input empty

---

packages/web-components/src/components/locale-modal/locale-search.ts

#5817 
Fixes incorrect prefix variable being used to target `locale-modal` search input filter in the web components version. This was causing the input to not receive initial focus.
**Changed**
- `${prefix}` to `${ddsPrefix}` for locale search's `selectorTabable`

fix(locale-modal): prefix selector for input focus

---

packages/services/src/services/VideoPlayer/VideoPlayer.js

I've added a quick fix to our video player service so videos work properly on Tabs extended with media.

fix(tabs-extended-with-media): videos are now working

---

packages/react/config/jest/__mocks__/ProfileAPI.js
packages/react/config/jest/setup.js
packages/react/jest.config.js

The ci-checks were failing in React, which seems to be related to the Jest snapshot tests. This PR rebuilds the snapshot file to see if this fixes the issue.
**Changed**
- React jest snapshot file

fix(ci-check): rebuilding snapshot file

---

packages/styles/scss/components/masthead/_masthead-search.scss

Masthead with Platform - Divider activates hover state on platform #5484
Space between the platform name and divider is clickable - removing the anchor link pseudo element resolves this.
BEFORE:
AFTER:
**Removed**
- remove anchor link `after` pseudo element

fix(Masthead): remove pseudo element from platform name

---

packages/tests-e2e/__tests__/locale-modal/locale-modal.e2e.js

none
Locale Modal e2e tests failing after update to react Card
**Changed**
- selector to reach the correct property

fix(localeModal): e2e tests

---

packages/styles/scss/components/content-group-cards/_content-group-cards.scss

#5732
Removed additional outline that was present when focusing on the `ContentGroupCardItem`
**Changed**
- `outline: none` when focused on `<dds-content-group-card-item>`

fix(content-group-cards): fixed bold outline

---

packages/web-components/src/components/masthead/masthead-search.ts

#5850
This PR ensures that clicking on any of the search suggestion items doesn't close the search bar and goes directly to the search results page as intended.
**Changed**
- quick check to ensure the blur event doesn't occur if clicking a masthead search result

fix(masthead-search): ensure clicking on suggestion works

---

packages/styles/scss/components/content-block-segmented/_content-block-segmented.scss
packages/web-components/src/components/content-block-segmented/content-block-segmented.scss

#5619 
#5622
Fixed the spacing in Content Block Segmented found within the Dotcom Shell and Back to Top. 
**New**
- removed `margin-bottom` for the last `content-block-segmented-item`
**Removed**
- wrong margin styles for each `content-block-segmented-item`

fix(content-block-segmented): fixed spacing issues

---

packages/web-components/src/components/masthead/masthead-composite.ts
packages/web-components/src/components/masthead/masthead-logo.ts
packages/web-components/src/components/masthead/masthead-menu-button.ts

Mentioned in the QA meeting this morning, couldn't find an open issue for this
The Masthead Menu button and IBM logo still showed up on load on the Masthead - Search Open by Default story. The previous fix which ensures toggling the search bar still works only, though only after closing it once.This fix ensures these two components hide upon load. 
**New**
- hide booleans for `<masthead-logo>` and `<masthead-menu-button>` to ensure they are hidden upon load the same way `<masthead-top-nav>` does it

fix(masthead): ensure only search bar displays on load upon search open

---

packages/react/src/components/CTA/README.stories.mdx

None.
Previous CTA README contained an outdated component, this PR adds the proper styles for CTA to work.
**Changed**
- added proper imports to the README

chore(cta): fixed style imports in README

---

packages/react/src/components/Masthead/MastheadTopNav.js
packages/styles/scss/components/masthead/_masthead-search.scss
packages/web-components/src/components/masthead/masthead.scss

Masthead with Platform - Divider activates hover state on platform #5484
There was work (PR: fix(Masthead): remove pseudo element from platform name #5835) to address the ticket by removing the pseudo element from the platform name, but in web components that led to the overflow menu options to show behind the platform name.
This PR addresses the overflow menu items by setting the `z-index` and `background` of the platform name.
BEFORE:
AFTER:
**Changed**
- set the `z-index` and `background` of `top-nav-name` component

fix(masthead): set platform name z-index and background color

---

packages/services/src/services/Locale/Locale.js
packages/services/src/services/Locale/__tests__/Locale.test.js

Masthead and Footer components not supporting locales like en-cn or en-gb #5890
For pages with DDO set to a locale that we do not support (ie. cn-en), the masthead and footer is returning blank.
When fetching the locale from the DDO to use in the translation service, we make a call to fetch the countrylist with the retrieved locale. If the countrylist call fails, we make another call with our default locale. However this change to the default locale is not communicated to the translation service and so the translation call is made with the non-existent locale.
Solution is to set the locale in the data returned from the successful countrylist call and use that locale.
**Changed**
- set locale in the returned countrylist data in `fetchList()`
- use the locale from the returned data

fix(locale): return locale with the fetch list call

---

.github/workflows/deploy-staging.yml
tasks/get-changelog.js

This was missed in order to set up the baseline snapshots for the React
e2e tests on staging.
**Changed**
- `deploy-staging.yml`

test(e2e): adding percy base update for e2e tests on staging

---

packages/react/src/components/CardGroup/CardGroup.js
packages/react/src/components/DotcomShell/__stories__/DotcomShell.stories.js
packages/react/src/components/Masthead/Masthead.js
packages/react/src/components/Masthead/MastheadL1.js
packages/react/src/components/Masthead/README.stories.mdx
packages/react/src/components/Masthead/__stories__/Masthead.stories.js
packages/react/src/components/Masthead/__stories__/data/Masthead.stories.knobs.js
packages/styles/scss/components/masthead/_masthead-leftnav.scss
packages/web-components/src/components/dotcom-shell/__stories__/dotcom-shell.stories.ts
packages/web-components/src/components/masthead/__stories__/README.stories.mdx
packages/web-components/src/components/masthead/__stories__/masthead.stories.ts
packages/web-components/src/components/masthead/masthead-composite.ts
packages/web-components/src/components/masthead/masthead.scss

#5896 
Current `L1` platform implementations in React and web components are inconsistent, and in React simply do not work. This makes both implementations consistent in their naming and data structures. Also fixes some styling inconsistencies in the web components version.
**Changed**
- `title` for L1 is now `platform` (same as `L0`)
- update Storybook stories for React and web components
- update web components masthead styles
**Removed**
- `title` and `titleUrl` from web components `L1`

fix(masthead): L1 platform not showing in hamburger menu

---

packages/react/src/components/Masthead/MastheadSearch.js

#5942 
Fixes an issue where search result section title would not show unless more than one item is in the section. The title should show when there is one or more items in the section.
**Changed**
- updated section title to show when one or more results are present

fix(masthead): multi-section search headline

---

packages/web-components/IMPLEMENTATION_NOTES.md

Updates web components [implementation notes](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/packages/web-components/IMPLEMENTATION_NOTES.md) with various typo fixes, shortening links, etc.
**Changed**
- typos
- shorten link text
- various grammatical fixes

chore(docs): update wc implementation docs

---

packages/web-components/src/components/expressive-modal/expressive-modal.ts
packages/web-components/tests/snapshots/dds-expressive-modal.md
packages/web-components/tests/snapshots/dds-locale-modal.md

#5669 
removed unnessary dialog role. The dialog role is already being set in carbon-web-components modal
**Removed**
- dialog role from expressive modal

fix(expressive-modal): remove dialog role

---

packages/web-components/src/components/locale-modal/locale-modal.ts

#5847
This fixes a bug where the current `locale-modal` does not re-focus on the first `region-item` button when a user navigates back to the first pane from the country filter.
https://user-images.githubusercontent.com/909118/117159277-23a66200-ad8e-11eb-82e5-acb18af403d5.mp4
**New**
- add focus state to first geographic `region-item` when navigating back to the first modal pane from search pane

fix(locale-modal): re-focus on region item when navigating within modal

---

packages/web-components/src/components/cta/__stories__/cta.stories.ts

#6010 
Update CTA-Card story to reflect icon changes when changing storybook cta-type knob
**New**
- added conditions so each type's icon is updated appropriately and card-footer copy still gets rendered.

fix(cta-card): cta-type updating icon in storybook knob

---

packages/web-components/src/components/masthead/left-nav.ts

Web component: Dotcom Shell - Hamburger menu open, while user scrolls menu options, close icon not seen for the user. #6026
Add the `${prefix}--body__lock-scroll` class to the `body` when the `left-nav` is expanded to prevent scrolling on mobile.
**New**
- add body scroll lock logic when the `left-nav` is expanded

fix(left-nav): add body scroll lock logic to left nav

---

packages/web-components/src/components/footer/footer-composite.ts

chore(footer): remove console log

---

packages/react/src/components/Masthead/Masthead.js
packages/web-components/README.md
packages/web-components/docs/enable-rtl.md
packages/web-components/examples/codesandbox/usage/dotcom-shell-cdn-with-handlebars/index.hbs
packages/web-components/examples/codesandbox/usage/dotcom-shell-cdn-with-rtl/index.hbs
packages/web-components/examples/codesandbox/usage/dotcom-shell-cdn/index.html

For the CDN artifacts, we should be pointing to the Akamai domain and not ibm.com.
**Changed**
- Various documentation

docs(akamai): switching url for artifacts to akamai domain

---

packages/web-components/src/components/footer/combo-box.ts

#6104 
Removes an unneeded `scss` import which is breaking builds when using `footer` or `dotcom-shell` components.
**Removed**
- extra `combo-box.scss` import

fix(footer): remove combo-box.scss import

---

packages/react/src/components/Footer/LegalNav.js
packages/web-components/src/components/footer/footer-composite.ts
packages/web-components/src/components/footer/legal-nav-item.ts

[Beacon for IBM.com] Create audits for the bucket "Legal" in Beacon #5939
Incorporate the legal link's name into the `data-autoid` so beacon can differentiate between the links and check if they are on the page.
**New**
- add the legal link's name to `data-autoid` based from the `titleEnglish` field in the footer data

feat(Footer): add specific link title to legal link data-autoids

---

packages/web-components/src/components/carousel/__stories__/README.stories.react.mdx

The carousel react-wrapper documentation includes unnecessary imports that aren't used in the example JS portion and is missing the card footer important needed.
**Removed**
- unnecessary imports and added card-footer import to documentation

docs(carousel): fix carousel imports in React-wrapper README instance

---

packages/web-components/src/typings/resources.d.ts

Related Ticket(s)
#5852
Description
I've added a type definition for loadend on the global ElementEventMap, so we fix the error that was blocking Angular 10 development.

fix(custom-events): onloadend type defined

---

packages/web-components/src/components/masthead/masthead.scss

#5949 
when masthead menu items open they cover the logo and other masthead iteams outside of the 
**New**
- z-index: 0

fix(masthead): menu options blocking items when active

---

packages/styles/scss/themes/expressive/components/_code-snippet.scss

[Carbon expressive] Code snippet single line off #5611
Adjustment to left padding and hover state
**Carbon reference** 
**Carbon reference**
**Changed**
- adjust `padding-left` of single code snippet
- adjust overflow-right-indicator positioning

fix(code-snippet): expressive code snippet carbon 10.31.0 update adjustments

---

packages/services-store/package.json
packages/web-components/README.md
packages/web-components/package.json
packages/web-components/src/components/table-of-contents/table-of-contents.ts
yarn.lock

TypeScript 3.8 breaking change #5852
Upgrade the typescript versions in both our `web-components` and `services-store` packages.
Fix type error in table of contents
Add documentation to address `process undefined` errors we've been seeing a lot of adopters run into.
**New**
- typescript 3.9 version bump

fix(typescript): upgrade typescript to 3.9 in web-components and services-store packages

---

packages/web-components/src/components/feature-card-block-large/feature-card-block-large.ts
packages/web-components/src/components/feature-card-block-medium/feature-card-block-medium.ts

Refs https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/6236
use the utilities package instead of relative path
**New**
**Changed**
**Removed**

fix(utilities): use util package for deprecate instead of relative path

---

packages/react/manifest-canary.yml
packages/react/manifest-experimental.yml
packages/react/manifest-expressive.yml
packages/react/manifest-rtl.yml
packages/react/manifest-staging.yml
packages/react/manifest.yml
packages/services/manifest.yml
packages/styles/manifest.yml
packages/utilities/manifest.yml
packages/web-components/manifest-canary.yml
packages/web-components/manifest-experimental.yml
packages/web-components/manifest-react.yml
packages/web-components/manifest-rtl.yml
packages/web-components/manifest-staging.yml
packages/web-components/manifest.yml

This will force https for all of our cloud foundry apps for `Carbon for IBM.com`.
**Changed**
- various manifest files for cloud foundry

chore(cloud-foundry): updating manifest configs to force https

---

packages/styles/scss/components/leadspace/_leadspace.scss
packages/web-components/src/components/leadspace/leadspace.scss

#6237
moved carbon's breadcrumb web component import to web component styles. breaking nextjs template
**Changed**
- moved breadcrumb import

fix(leadspace): breadcrumb style import

---

packages/web-components/src/components/dotcom-shell/dotcom-shell-composite.ts

#6220 
Console errors appearing in dotcomshell if user does not include the ToC component. 
**New**
- added checks in `_handleResize` and `_handleIntersect` to see if ToC is included

fix(dotcom-shell): add checks if ToC exist

---

packages/web-components/src/components/masthead/cloud/cloud-masthead.scss

Removes shorthand flex value causing build warnings.
**Changed**
- `start` to `flex-start`

chore(cloud-masthead): update styles flex value

---

packages/web-components/examples/codesandbox/components/content-block-card-static/.sassrc
packages/web-components/examples/codesandbox/components/content-block-card-static/package.json

The content-block-card-static example was using the older format for the examples code, this fixes it so that the e2e build can run properly.
**Changed**
- content-block-card-static example application setup

fix(e2e): fixing content-block-card-static e2e build test

---

packages/web-components/src/components/dotcom-shell/__stories__/data/content.ts

None created yet.
Updated Feature Card structure to use the size attribute instead of the deprecated feature card block large compoment.
**Changed**
- FeatureCard in DotcomShell Horizontal ToC story

fix(dotcom-shell): horizontal toc feature card fix

---

packages/web-components/src/components/card-group/card-group.ts
packages/web-components/src/components/cta-block/cta-block-item-row.ts

None.
Changed `sameHeight` import to use default import in Card Group and CTA Block Item Row for Web Components.
**Changed**
-  changed sameHeight imports in `DDSCardGroup` and `DDSCTABlockItemRow`

fix(card-group): use default import for sameHeight utility function

---

packages/styles/scss/components/back-to-top/_back-to-top.scss

#6303
Fixes incorrect spacing in `back-to-top` button.
**New**
- adds 16px to `padding-right`

fix(back-to-top): fix button right padding

---

packages/styles/scss/components/card-in-card/_card-in-card.scss

#6326 
The card's original `z-index` value of 5 made it go on top of AEM's masthead, this change ensures it stays in the same layer as the rest of the component.
**New**
**Changed**
- lowered `.bx--card__wrapper` in Card in Card `z-index` to `1`

fix(card-in-card): lowered z-index value

---

packages/services-store/src/types/translateAPI.ts
packages/web-components/src/components/masthead/__stories__/links.ts
packages/web-components/src/components/masthead/cloud/cloud-masthead-composite.ts
packages/web-components/src/components/masthead/masthead-composite.ts
packages/web-components/src/components/masthead/masthead.scss

Web Component: Change Mega Menu to include animation (back button & forward motion) #4831
React version data structure for L1 menu items is the same as L0 menu items from translation API. This should match expected structure of L1 in web-components.
Use the same structure and remove the L1 specific left nav item function, instead use the same function used to render the L0 top nav and left nav items.
Use same custom data as React storybook example
**Changed**
- use custom data from React example.
- edit `MastheadL1` type in the services-store translateAPI to use `MastheadLink[]` as the data structure shouldn't differ
**Removed**
- `renderL1Items()` and ulitize `renderNavItems()` instead as the structure of the L1 data and L0 data is the same

fix(masthead-l1): match data structure to react and reuse general `renderNavItems` function

---

packages/react/src/components/LeadSpace/LeadSpace.js
packages/styles/scss/components/leadspace/_leadspace.scss
packages/web-components/src/components/leadspace/defs.ts
packages/web-components/src/components/leadspace/leadspace.scss
packages/web-components/src/components/leadspace/leadspace.ts

React & Web component Service Page: Table of contents and Leadspace are overlapping #6323
fix styles and classes
**New**
- add tall def to leadspace
**Changed**
- update react heights

fix(leadspace): overlapping bug

---

docs/building-for-ibm-dotcom.md

This updates the headings in `Building for IBM.com` to follow style conventions.
**Changed**
- `building-for-ibm-dotcom.md`

docs(building-for-ibm): updated headings to follow style convention

---

packages/web-components/.storybook/config.ts
packages/web-components/README.md
packages/web-components/docs/carbon-cdn-style-helpers.md
packages/web-components/docs/carbon-cdn-style-helpers.stories.mdx
packages/web-components/docs/coding-conventions.md
packages/web-components/docs/contributing-to-web-components.md
packages/web-components/docs/enable-rtl.md
packages/web-components/docs/feature-flags.md
packages/web-components/docs/markdown-contents.md
packages/web-components/docs/stable-selectors.md
packages/web-components/gulp-tasks/build/sass-cdn.js
packages/web-components/package.json
packages/web-components/src/globals/internal/storybook-cdn.ts
packages/web-components/src/globals/scss/themes.scss
packages/web-components/tools/rollup-plugin-lit-scss.js

A bug that came up is that the CDN artifacts did not have Carbon's CSS custom properties flag enabled. This PR enables so that CSS custom properties can be taken advantage of. In addition, there are new theme classes being introduced
as a CDN style helper. This enables the ability of creating theming zones using the theme classes. Documentation has also been added for this.
**New**
- `themes.css` CDN artifact with theme zone classes
- Documentation on `Carbon CDN style helpers`
**Changed**
- Updated rollup config to include css custom properties flag

fix(cdn): enable CSS custom properties in CDN artifacts

---

packages/react/src/components/LeadSpace/LeadSpace.js
packages/styles/scss/components/leadspace/_leadspace.scss

- Added 100% width to `<picture>` for larger screens
- Moved the gradient stop color rule to `themed-items` mixin (how did this ever work before?)
- Added `g10` and `g90` to theme prop types to avoid console log error

fix(leadspace): width and theme fix

---

packages/web-components/src/globals/internal/storybook-cdn.ts

Missed the documentation on the rtl versions of CDN artifacts. This should add in all of the storybook docs.
**Changed**
- Added RTL documentation for Web Components CDN

docs(rtl): adding rtl versions of components in storybook documentation

---

packages/web-components/src/components/masthead/cloud/cloud-masthead-composite.ts

[Cloud Megamenu]: Non-alphabetical titles being selected in the cloud megamenu when using special character languages #6340
Regex was removing characters from non latin languages (ie. chinese) which caused issues with the tab component of the cloud megamenu (not knowing which tab was selected, setting all special character items as "selected" state, etc). Solution is to only remove punctuation characters.
BEFORE:
AFTER:
**Changed**
- edit regex to only target punctuation characters

fix(cloud-megamenu): modify regex to only remove punctuation special characters

---

packages/styles/scss/components/feature-section/_feature-section.scss

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/6470
- This PR adds missing 16px spacer under eyebrow that was missed during the design QA review of this PR (https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/6344).
**Testing Instructions**
- Visit the `Feature section` - `/?path=/story/components-feature-section--default`
- Ensure that there a `16px` or `$carbon--spacing-05` spacing between the eyebrow and heading.

fix(feature-section): add missing 16px spacing under eyebrow

---

packages/utilities/src/utilities/stripHTML/__tests__/index.test.js
packages/utilities/src/utilities/stripHTML/stripHTML.js

The stripHTML utility always assumes that there is a wrapping tag. However, in the cases when only a string is passed, it should just pass through without doing anything, rather than throwing an error.
**Changed**
- Add additional string check in `stripHTML`

fix(stripHTML): add check if there are no surrounding elements

---

packages/utilities/src/utilities/markdownToHtml/__tests__/markdownToHtml.test.js
packages/utilities/src/utilities/markdownToHtml/markdownToHtml.js
packages/web-components/src/components/markdown/markdown.ts

#6185 
Update markdown to use large or expressive variations for links and unordered/ordered lists

fix(markdown): use large link and expressive lists

---

packages/web-components/src/components/card/card.scss

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/6490
CTA link is now operable on mobile and desktop safari browsers.

fix(card-static): cta link not working in safari

---

packages/styles/scss/components/content-group-horizontal/_content-group-horizontal.scss

The scss file for `content-group-horizontal` still will need to exist for applications that have not yet moved to `content-block-horizontal`. This adds in the file so that applications won't break when building.
**New**
- Deprecated `_content-group-horizontal.scss` file

fix(content-group-horizontal): adding back deprecated scss file

---

packages/react/src/components/Card/Card.js

#6513 
Adds conditional rendering of `CardLink` footer based on `disabled` state.
**Changed**
- conditionally render footer based on `disabled`

fix(CardLink): fix disabled behavior

---

packages/react/src/components/Masthead/MastheadSearch.js

[Masthead] React component: Autosuggest in the searchbox causes runtime error #6505
sets the `focusInputOnSuggestionClick` prop for the `Autosuggest` component to false so error doesn't appear when user clicks on search suggestion.
**Changed**
- set `focusInputOnSuggestionClick={false}` for `Autosuggest` component

fix(MastheadSearch): set focus on search suggestion to false

---

packages/styles/scss/components/footer/_footer-nav.scss
packages/styles/scss/components/masthead/_masthead-leftnav.scss

#6554 
Temporarily use numerical breakpoint values for the `carbon--breakpoint-between` mixin. Currently there is an error in this mixin that prevents the usage of breakpoint keywords, i.e. `md`, `lg`, etc.
A [PR](https://github.com/carbon-design-system/carbon/pull/9102) for this fix is currently open. Once merged these changes can be reverted to use keywords.
Revert these changes when the changes are available in the next `carbon-components` release. [#6558]
**Changed**
- use numerical values instead of keywords for `carbon--breakpoint-between` mixin

fix(styles): temporarily hard-code breakpoint values

---

packages/web-components/tests/e2e/__tests__/video-player/video-player.cdn.e2e.js
packages/web-components/tests/e2e/__tests__/video-player/video-player.e2e.js
packages/web-components/tests/e2e/cypress.json

#6251 
These are some tweaks to the build so that it runs correctly in the CI. It needed more time to complete rendering.
Also, turning off percy snapshots for video player, as it was causing false positives.
**Changed**
- `cypress.json` config tweaks
- suppress `percySnapshot` for `video-player`

fix(e2e): added timeout for render time on CI

---

packages/web-components/tests/e2e/build/build-examples.js

This adds a dynamically created index file for the deploy preview of the web components codesandbox build, so that reviewers can view the built files. Currently there isn't an index file, so it would be tough for a review to navigate the deploy preview instance. It's no frills, but the output looks like this:
**Changed**
- Adding new method to auto-create the index file based on the examples folders

test(e2e): creating dynamically generated index file

---

.github/workflows/percy-update-base-wc-e2e-codesandbox.yml

This is making the adjustment to have the e2e code sandbox tests happen on `master` instead of the moving baseline test branch.
**Changed**
- Github workflow file

fix(e2e): change baseline target to master branch

---

.github/workflows/automerge-feat.yml
.github/workflows/automerge.yml
.github/workflows/ci-check.yml
.github/workflows/dependabot-yarn-mirror.yml
.github/workflows/deploy-canary.yml
.github/workflows/deploy-staging.yml
.github/workflows/percy-update-base-wc-e2e-codesandbox.yml
.github/workflows/percy-update-base.yml
.github/workflows/publish-canary.yml
.github/workflows/publish-nightly.yml
.github/workflows/publish-staging.yml
.github/workflows/release-preflight.yml

Per documentation from Github, Ubuntu 16.04 is deprecated. This is upgrading our workflows to 20.04.
https://github.blog/changelog/2021-04-29-github-actions-ubuntu-16-04-lts-virtual-environment-will-be-removed-on-september-20-2021/
**Changed**
- Github actions workflow files

chore(github-actions): upgrading ubuntu to 20.04

---

packages/web-components/src/components/content-block-mixed/__stories__/README.stories.mdx

Update import paths in README.
**Changed**
- update import paths to use `es` modules

chore(content-block-mixed): update import paths in docs

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/contribution_request.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question.md

This updates the fireline support roster for sprint 15.
**Changed**
- Github issue templates

chore(support): updating support roster for sprint 15

---

packages/web-components/src/components/cta/video-cta-composite.ts

Web component: Card group - Video links are broken and do not open on lightbox media view. #6674
**New**
**Changed**
**Removed**

fix(cta-card): updating `video-cta-composite` to match new API

---

packages/react/examples/codesandbox/components/FeatureCard/src/styles.scss
packages/react/src/components/FeatureCard/README.stories.mdx

None
Codebox Example wasn't styling properly due to not having the CSS custom properties flag set, this PR ensures its on.
**New**
- added CSS Custom property flag within FeatureCard Sandbox Example

chore(feature-card): update sandbox to include css custom props flag

---

packages/web-components/tests/e2e/build/build-examples.js

The codesandbox tests were missing the aspect of testing against locally
built CDN packages.
**Changed**
- e2e test build now points CDN pages to a locally built CDN folder

test(cdn): adjust e2e test to source cdn locally

---

packages/styles/scss/components/masthead/_masthead-megamenu.scss
packages/styles/scss/components/masthead/_masthead.scss

GH Issue: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/6704
JIRA ticket: https://jsw.ibm.com/browse/HC-2087
- While testing the new `<dds-cloud-masthead-container>` Web Components in Drupal, I noticed that the megamenu height is inheriting `min-height: 20rem;` instead of the height shown within the Storybook preview.
- Also, this PR addresses the `dds-megamenu-overlay` height issue where the overlay is not taking up `100%` of the viewport height.
1. Visit this Drupal preview page (VPN requires) - https://wc-masthead-jfbm8ry4yxvz0jplleccg7urlffpem5u.w3-origin-007522.intranet.ibm.com/cloud/watson-assistant
2. Click on the "Products" mega menu item
3. The height is not the same as what is being shown here - (see - …

fix(cloud-masthead): Megamenu height is not displaying correctly within the Drupal integration

---

packages/web-components/examples/codesandbox/components/cloud-masthead/.babelrc
packages/web-components/examples/codesandbox/components/cloud-masthead/.env.local
packages/web-components/examples/codesandbox/components/cloud-masthead/.gitignore
packages/web-components/examples/codesandbox/components/cloud-masthead/.sassrc
packages/web-components/examples/codesandbox/components/cloud-masthead/cdn-rtl.html
packages/web-components/examples/codesandbox/components/cloud-masthead/cdn.html
packages/web-components/examples/codesandbox/components/cloud-masthead/index.html
packages/web-components/examples/codesandbox/components/cloud-masthead/package.json
packages/web-components/examples/codesandbox/components/cloud-masthead/sandbox.config.json
packages/web-components/examples/codesandbox/components/cloud-masthead/src/index-cdn.js
packages/web-components/examples/codesandbox/components/cloud-masthead/src/index.js
packages/web-components/examples/codesandbox/components/cloud-masthead/src/index.scss
packages/web-components/tests/e2e/build/build-examples.js

This adds a codesandbox example for Cloud Masthead. In addition, this cherrypicks the local CDN testing for codesandbox deploy preview from the `master` branch.
**New**
- Cloud Masthead codesandbox example
**Changed**
- Cherry-pick test:e2e:build script changes for CDN testing

fix(rtl): add codesandbox example for cloud masthead

---

packages/services/src/services/CloudAccountAuth/CloudAccountAuth.js
packages/services/src/services/CloudAccountAuth/__tests__/CloudAccountAuth.test.js
packages/web-components/src/components/masthead/cloud/cloud-masthead-composite.ts

[HC-2086](https://jsw.ibm.com/browse/HC-2086)
Resolves #6703 
We weren't seeing the user's auth status reflected based on the cookie we're checking as expected. The issues were:
1. the cloud masthead was using the unauthenticated status const defined in the profile API, which uses a different string
2. the cloud account login API was returning a bare string, but the cloud masthead expects an object with a property called user
**New**
- n/a
**Changed**
- `packages/services/src/services/CloudAccountAuth/CloudAccountAuth.js` - add a definition for user status in cloud masthead composite which points to the correct unauthenticated status string defined in the cloud account login API
- `packages/web-components/src/components/masthead/cloud/cloud-masthead-composite.ts` -  update the API to …

fix(cloud-masthead): hc-2086 properly form request return object

---

packages/react/examples/codesandbox/components/MastheadL1/package.json
packages/react/examples/codesandbox/components/MastheadL1/snowpack.config.json
packages/react/examples/codesandbox/components/MastheadL1/src/App.js
packages/react/examples/codesandbox/components/MastheadL1/src/links.js

Fixes `Masthead - L1` Codesandbox example and update data structure to reflect latest changes.
**Changed**
- update `package.json`
- update `L1` links
**Removed**
- `snowpack`

chore(masthead): udpate L1 codesandbox example

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/contribution_request.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question.md

Week 2 of sprint 15 is swapping Ignacio with Kenny.
**Changed**
- Issue templates

chore(support): updating support roster for sprint 15 (week 2)

---

packages/styles/scss/components/masthead/_masthead-search.scss
packages/web-components/examples/codesandbox/components/masthead/cdn-rtl.html
packages/web-components/src/components/masthead/masthead.scss

Refs #6697 
This adds some updates to change the declaration for rtl in scss files so they don't get parsed out.
**Changed**
- Various RTL style declaration changes

fix(rtl): fix to not have rtlcss styles get parsed out

---

packages/web-components/examples/codesandbox/components/card-section-offset/cdn.html
packages/web-components/examples/codesandbox/components/card-section-offset/index.html
packages/web-components/src/components/back-to-top/__stories__/data/content.ts
packages/web-components/src/components/card-section-images/__tests__/card-section-images.test.ts
packages/web-components/src/components/card-section-images/index.ts
packages/web-components/src/components/card-section-offset/__stories__/README.stories.mdx
packages/web-components/src/components/card-section-offset/__stories__/card-section-offset.stories.ts
packages/web-components/src/components/card-section-offset/__tests__/card-section-offset.test.ts
packages/web-components/src/components/card-section-simple/__tests__/card-section-simple.test.ts
packages/web-components/src/components/card-section-simple/index.ts
packages/web-components/src/components/content-block-card-static/__tests__/content-block-card-static.test.ts
packages/web-components/src/components/content-block-cards/__tests__/content-block-cards.test.ts
packages/web-components/src/components/content-block-simple/__stories__/README.stories.mdx
packages/web-components/src/components/content-block-simple/__stories__/content-block-simple.stories.ts
packages/web-components/tests/snapshots/dds-content-block-card-static.md

#6733 
update components to use `card-cta-footer` instead of just `card-footer` when applicable.

fix(card-section-offset): update to use card-cta-footer

---

packages/web-components/src/components/locale-modal/locale-modal.ts

Web component: Dotcom shell - Locale modal- when we activate "Select geographic area" link, the First modal is not displayed #6077
When using voiceover on iphone, the user isn't taken back to the first modal with all the geographic regions (Americas, Asia Pacific, etc) after selecting the "Select geographic area" link to go back. The "Americas" region card is briefly focused before voiceover announces the `select` component. 
Solution is the set the `tabIndex` of the first `<dds-region-item>` component in the first modal. This way voiceover recognizes the component as tabbable and will then focus properly on it.
**Changed**
- set `tabIndex` of the first region item to 0 to ensure voiceover focuses on it

fix(locale-modal): set region item to be tabbable for voiceover

---

packages/styles/scss/components/tabs-extended/_tabs-extended.scss
packages/web-components/src/components/tabs-extended/tabs-extended.ts

#6233
This PR updates the extended tabs so that tooltips for truncated tab labels appear on tab focus in addition to hover (existing behavior from #6155)
on focus:
on hover:
**Changed**
- move tooltip mixins from tab label text to tab label anchor

fix(tabs-extended): display tooltip on truncated tab focus

---

packages/react/src/components/Footer/README.stories.mdx

Add documentation for cookie preferences, telling adopters to set the ibm-commons analytics script and link to the cookie consent adopter instructions.

docs(cookie-preferences): add documentation to set cookie preferences

---

packages/react/src/components/Footer/LanguageSelector.js

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/6022
Added missing `aria-label` to `select` in React.

fix(language-selector): added missing label to select

---

packages/styles/scss/components/leadspace/_leadspace.scss

CDN Web Component Leadspace with error #6807
The leadspace-image was not fitting the entire width of the component. Setting the `display: block` in the large breakpoint fixes this issue.
**BEFORE:**
AFTER:
**Changed**
- set `display` to `block` on large breakpoint for leadspace-image

fix(leadspace): ensure leadspace image takes up entire width in lg bp

---

packages/react/src/components/VideoPlayer/VideoImageOverlay.js
packages/react/src/components/VideoPlayer/VideoPlayer.js
packages/react/src/components/VideoPlayer/__stories__/VideoPlayer.stories.js

React: [Video Player] Include onClick enhancement to open in lightbox media viewer #5266
**New**
**Changed**
**Removed**

feat(videoPlayer): introducing `playingMode` feature (pairing with wc version)

---

packages/web-components/src/components/masthead/megamenu-top-nav-menu.ts

[Cloud Masthead] Slight page shift when the Mega Menu is opened on machines where scrollbar is set to visible + Adjust minor icon RTL issue #6831
Cloud masthead shifts when megamenu is expanded. This is due to the combination of styles implemented from the cloud side to set the masthead `position: static` to accommodate the L1 and the `margin-right` added when the scrollbar is locked on megamenu expand. This PR sets the masthead - scoped to cloud - to `position: fixed` when megamenu is expanded. 
**Changed**
- set `position:fixed` to the cloud-mastead on megamenu expand

fix(cloud-masthead): set position of masthead to fixed when expanded

---

packages/styles/scss/components/masthead/_masthead-megamenu.scss
packages/web-components/src/components/masthead/cloud/cloud-masthead.scss
packages/web-components/src/components/masthead/masthead.scss

[Cloud Masthead] Slight page shift when the Mega Menu is opened on machines where scrollbar is set to visible + Adjust minor icon RTL issue#6831
In RTL, the arrow icons in the megamenu are not flipping. This PR adds `rtlcss` styles to flip the megamenu arrow icons.
**BEFORE:**
**AFTER:**
**New**
- add `rtlcss` styles to `:host(#{$dds-prefix}-megamenu-link-with-icon)` and `:host(#{$dds-prefix}-cloud-megamenu-category-heading)`
- also set the `right` styling for `.#{$prefix}--header__nav-caret-left-container` in rtl to position caret correctly for overflow in masthead-l1

fix(masthead): flip megamenu link arrow icons in rtl

---

packages/web-components/src/components/masthead/megamenu-top-nav-menu.ts

Reverting changes made in: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/6836
Setting the position to fix solves part of the issue, but when there is a banner above the masthead, the masthead is hidden underneath the banner. Reverting the changes for no until there is a more solid fix.
**Removed**
- cloud-masthead position fixing code

fix(masthead): remove cloud masthead position fixing code

---

packages/react/src/components/CTA/ButtonCTA.js

[CTASection]: passing Onclick to the cta does not work #6844
The `button.onClick` was being overwritten, so adopters trying to pass in an onClick function were not able to. Solution is to check if an `onClick` function was passed in before setting it.
**Changed**
- check if `onClick` function has been passed before setting the jump function

fix(CTA): allow onClick for buttonCTA to be passed

---

packages/react/src/components/LightboxMediaViewer/LightboxMediaViewer.js

#6884 
Fixes an issue when Kaltura callback is called every time `onClose`, even when video isn't being used.
**Changed**
- send Kaltura notifications only when widget is detected

fix(lightbox-media): check for kaltura onClose

---

packages/web-components/src/components/masthead/cloud/cloud-masthead-composite.ts

- https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/6916
- This PR changes the value within the Cloud contact CTA attribute `data-ibm-contact` from `chat-link` to `contact-link`.
- During the latest testing of the new Cloud Masthead, we noticed that the CTA button is not visible despite having `has-contact` sets to true. We realized that v18 stylesheet and JS script are automatically hiding this button and altering the text copy on certain pages.
Screenshot of the issue seen on different adopters.
**New**
- Change CTA attribute `data-ibm-contact` from `chat-link` to `contact-link`.
- Adds `<span>` tag to prevent the copy changing.

fix(cloud-masthead-contact-btn): change data-ibm-contact to contact-link

---

packages/react/.storybook/theme.js
packages/web-components/.storybook/react/theme.js
packages/web-components/.storybook/theme.js

#6914
This PR adds package version info to our Storybook titles
web components
react
web components w/ react

docs(storybook): add package version to storybook titles

---

packages/web-components/src/components/masthead/masthead-global-bar.ts

This PR removes an unneeded console statement which was emitting a warning when running `yarn lint` and in vscode
```
/carbon-for-ibm-dotcom/packages/web-components/src/components/masthead/masthead-global-bar.ts
43:5  warning  Unexpected console statement  no-console
✖ 1 problem (0 errors, 1 warning)
```
**Removed**
- `console.log` statement in `masthead-global-bar.ts`

chore(masthead): remove lint warning

---

packages/web-components/package.json
yarn.lock

Refs #6792 
This PR is upgrading `web-components` to `v4.3.5`. 
~~This is currently in draft for now so that testing can be done on this branch.~~
All automated testing seemed to clear!
**Changed**
- Upgrade `typescript` to `v4.3.5`

feat(typescript): upgrade to typescript v4.3.5

---

packages/react/examples/codesandbox/components/VideoPlayer/src/index.js
packages/react/examples/codesandbox/components/VideoPlayer/src/styles.scss
packages/react/src/components/VideoPlayer/VideoImageOverlay.js
packages/react/src/components/VideoPlayer/VideoPlayer.js
packages/react/src/components/VideoPlayer/__stories__/VideoPlayer.stories.js

#6953
This PR resolves an issue with the video player with lightbox media viewer, where the video would autoplay on page render (ignoring the open/closed state of the lightbox media viewer modal). The video should now only autoplay after the lightbox modal is launched
**Changed**
- add click handler to `<LightboxMediaViewer>` to autoplay videos only when the lightbox is launched
- fix missing styles in code sandbox example
- update storybook video IDs so that video examples play properly

fix(VideoPlayer): restrict lightbox variant autoplay to modal open state

---

packages/web-components/src/components/footer/legal-nav.ts
packages/web-components/tests/snapshots/dds-footer-composite.md

Fixes #6784 
This PR removes the role attribute from the `dds-legal-nav` element found within the `dds-footer`
**Changed**
- `dds-legal-nav` no longer has a role.

fix(footer): Remove role=complimentary from footer legal-nav

---

packages/web-components/src/components/footer/footer.ts
packages/web-components/tests/snapshots/dds-footer-composite.md

Fixes #6890 
This PR sets the `dds-footer` element's role to `contentinfo` overriding any pre-existing roles that may have been set on the element.
**Changed**
- `dds-footer` has `contentinfo` landmark role

fix(footer): Set dds-footer role to contentinfo

---

packages/web-components/src/components/masthead/cloud/cloud-masthead-composite.ts
packages/web-components/src/components/masthead/cloud/cloud-masthead.scss

- https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/6956
- This PR fixes one of the issues mentioned within this issue - https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/6956
**Changed**
- make sure the menu items do not appear behind the Cloud platform name

fix(cloud-masthead-6956): Safari text showing issue on cloud-top-nav-name

---

.github/workflows/snapshot-update.yml

The react snapshot update workflow failed because it didn't have the right permissions to push. This should hopefully fix it, as well as updating the existing snapshots so that it clears.
**Changed**
- Updated snapshot-update.yml
- Updated react snapshot file

chore(snapshot): update snapshot and workflow token

---

packages/react/src/components/LightboxMediaViewer/LightboxMediaViewer.js

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/6953
related PR https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/6958
This PR updates the `autoPlay` prop on lightbox media viewers with embedded video players so that it is dependent on whether or not the lightbox modal is open. The original issue stemmed from how the video player with lightbox media viewer recursively creates `VideoPlayer` components
Reviewers should confirm that the fix from #6958 is preserved and that switching between `VideoPlayer` stories does not trigger autoplay in the background
**Changed**
- `autoPlay` logic in `LightboxMediaViewer`

fix(LightboxMediaPlayer): set `autoPlay` based on modal open state

---

packages/styles/scss/components/tabs-extended/_tabs-extended.scss

#7011 
On Tabs Extended this PR allows for word breaks on long words. Example:
Before:
After:
**New**
- add word break to the buttons in Tabs extended

fix(tabs-extended): add word break

---

.github/workflows/snapshot-update.yml

The Github Action to update the react snapshot is still failing due to permissions issues. This is another attempt to remedy the permissions issue so that the github actions bot can successfully update the snapshot files.
**Changed**
- `snapshot-update.yml`
- Updated react snapshot files

fix(github-action): fix to the github action to have push access

---

packages/web-components/src/components/masthead/cloud/cloud-masthead-composite.ts
packages/web-components/src/components/masthead/masthead-composite.ts

[Cloud-masthead]: Adjust tabs to not use title as the identifier for related tab content, use unique ID instead #6975
Ran into an issue with the cloud megamenu tabs when the same tab title is used in two different megamenus. This causes an issue because the current logic uses the title as the identifier of the tabs. Solution is to use a unique id for the tabs instead so no issues occur if the same title is used in multiple megamenus.
**BEFORE:**
**AFTER:**
**Changed**
- set a unique id using the parent menu item key + the tab key

fix(cloud-masthead): set unique id for megamenu tabs instead of using title

---

.github/ISSUE_TEMPLATE/bug_report.md

#6695
Updated the bug issue template to ensure new issues can be more specific from the get go. Implemented from @JBrandwine's updates.
**Changed**
- updated bug report template

chore(bug-report): updated template

---

packages/services/src/services/CloudAccountAuth/CloudAccountAuth.js
packages/services/src/services/CloudAccountAuth/__tests__/CloudAccountAuth.test.js
packages/web-components/src/components/masthead/cloud/cloud-masthead-composite.ts
packages/web-components/src/components/masthead/cloud/cloud-masthead.scss

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/7032
- This PR addresses the two bugs that we've discovered after the launch of the new Cloud Masthead on the Drupal PROD environment (see - https://www.ibm.com/cloud?bust=foo).
- See this issue for more detail - https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/7032
**New**
**Changed**
**Removed**

fix(cloud-masthead): adjust the cookie to PROD ID & overlapping issue on v18 L1 Nav

---

packages/web-components/src/components/video-player/__stories__/video-player.stories.ts
packages/web-components/src/components/video-player/video-player-composite.ts

#6195
This PR adds support for custom thumbnails and video captions in the `<video-player-container>/<video-player-composite>` web component. If no custom overrides are provided the values will be taken from the Kaltura API
**New**
- `thumbnail` and `caption` properties on `<video-player-container>`/`<video-player-composite>`

feat(video-player-composite): support image and caption overrides

---

packages/services/src/services/CloudAccountAuth/CloudAccountAuth.js
packages/services/src/services/CloudAccountAuth/__tests__/CloudAccountAuth.test.js
packages/web-components/src/components/masthead/cloud/cloud-masthead-composite.ts
packages/web-components/src/components/masthead/cloud/cloud-masthead.scss

cherry pick #7037 for `v1.24.0` release
> ### Related Ticket(s)
> 
> https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/7032
> 
> ### Description
> 
> - This PR addresses the two bugs that we've discovered after the launch of the new Cloud Masthead on the Drupal PROD environment (see - https://www.ibm.com/cloud?bust=foo).
> - See this issue for more detail - https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/7032
> 
> ### Changelog
> 
> **New**
> 
> - {{new thing}}
> 
> **Changed**
> 
> - {{changed thing}}
> 
> **Removed**
> 
> - {{removed thing}}
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> ### Related Ticket(s)
> 
> {{Provide url(s) to the related ticket(s) that this pull request addresses}}
> 
> ### Description
> 
> {{Add a human-readable description / detail …

fix(cloud-masthead): adjust the cookie to PROD ID & overlapping issue on v18 L1 Nav (#7037)

---

packages/styles/scss/components/image/_image.scss
packages/web-components/src/components/image/__stories__/image.stories.ts
packages/web-components/src/components/image/image.ts

Resolves #6528
This PR adds the ability to toggle an optional border around `<dds-image>` elements. Adopters can enable the border by adding the `border` attribute to the element:
```
<dds-image border>
```
**New**
- Adds support for a `border` attribute on the `<dds-image>` element that, when present, applies a border around the image.

feat(image): support optional image borders

---

packages/react/src/components/Masthead/MastheadTopNav.js

#6764 
React masthead L0 parent menu now shows selected state when the current page is a child item. Example can be seen [here](https://codesandbox.io/s/github/kennylam/masthead-submenu-csb) (must open into external window).
**New**
- L0 parent menu shows selected state when current page is a child item

feat(masthead): masthead L0 selected when child item is current page

---

packages/styles/scss/components/feature-card/_feature-card.scss

#6689
In mobile breakpoint, the arrow did not move to the bottom. This PR ensures that it does.
**Removed**
- removed unnecessary `height: auto` from a feature-card class

fix(feature-card): ensure arrow stays at the bottom

---

packages/services/package.json
packages/utilities/package.json

Refs https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/6203
This fixes an import issue for `services` and `utilities` if they are used in Node 14.
**Changed**
- Updated `exports` configuration for `services` and `utilities`

fix(node): adding default package exports for services/utilities

---

packages/web-components/src/components/button/button.ts
packages/web-components/tests/snapshots/dds-button-group.md

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/6141
CTA text already using lg size, updated Button to use expressive

fix(cta): updated button to use expressive

---

packages/web-components/src/components/dotcom-shell/dotcom-shell-composite.ts

#7050
This bug occurs when scrollbars are always active. Make sure to activate this setting on MacOS for testing purposes.
Opening the modal causes the scrollbar to disappear and resize the page, which called the scroll handler, closing the modal immediately as its considered an "out of modal" action/click event. In other words, the modal closed immediately as it opened. 
This PR ensures that this resize change only affects the code when it's actually scrolling.
**Changed**
- moved a variable update to within the conditional that uses its value

fix(dotcom-shell): ensure locale modal opens with scrollbars on

---

packages/web-components/src/components/card-section-simple/__stories__/card-section-simple.stories.ts

#5857
In the current Storybook example in Card Section Simple, it still has the old demo classes. This PR ensures that it only uses the `bx--grid` classes only so it aligns to the grid properly.
**Changed**
- Card Section Simple story now uses `bx--grid` classes
**Removed**
- removed demo classes from the Card Section Simple story in Web Components

fix(card-section-simple): aligning component in storybook

---

packages/web-components/src/components/image-with-caption/image-with-caption.ts

#7073 
Image with caption modal not displaying properly in large breakpoints
**Changed**
- updated prop from `size` to `expressive-size`

fix(image-with-caption): update expressive modal prop to expressive-size

---

packages/react/src/components/LocaleModal/__stories__/LocaleModal.stories.js
packages/styles/scss/components/locale-modal/_locale-modal.scss

#6265
This PR updates the locale modal styles to match the updated expressive theme spec 
Confirm that the React and web component locale modals match the expressive component spec
**Changed**
- locale modal styles
- story formatting

fix(locale-modal): update expressive theme styles

---

packages/styles/scss/components/locale-modal/_locale-modal.scss

#7079
This PR updates the locale modal styles so that the React version of the component follows the [component spec](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-website/wiki/Locale-modal). The styles should be directly inherited from the composed modal in `carbon-web-components`
Confirm that the React locale modal close button renders in the correct position and there are no regressions with the web component version
**Changed**
- locale modal close button positioning

fix(locale-modal): correct modal close button positioning

---

packages/styles/scss/themes/expressive/index.scss

Remove scss warning for expressive theme deprecation from global imports. The deprecation notice can now be seen in the `Styles` section of the [release notes](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/releases/tag/v1.24.0).
**Removed**
- expressive theme deprecation notice

chore(styles): remove global deprecation notice

---

packages/react/src/components/carbon-components-react/UIShell/SideNavMenuSection.js

Type error was occurring when user hovered over the mobile nav items in smaller breakpoints. This was happening because there is a `transitionend` listener needed to provide focus for tabbing through the menu. Add a check for the `focusElement` to prevent error.
**Changed**
- add check for `focusElement` before setting focus

fix(masthead): add check for focus elem in Masthead SideNavMenuSection to prevent type error

---

packages/react/src/components/Footer/LanguageSelector.js
packages/styles/scss/components/footer/_language-selector.scss
packages/web-components/src/components/footer/footer.scss

#7094
This PR updates the footer and language selector to retain expressive theme styles
Web components language selector icon sizes should be 16px
React language selector height should be 48px
React language selector container should no longer have extra side padding which indented the input field

fix(footer): expressive sunset cleanup

---

packages/web-components/src/components/content-block-simple/__stories__/README.stories.react.mdx
packages/web-components/src/components/content-block-simple/__stories__/content-block-simple.stories.react.tsx
packages/web-components/src/components/content-block-simple/__stories__/content-block-simple.stories.scss
packages/web-components/src/components/content-block-simple/content-block-simple.ts

This adds the `content-block-simple` React wrapper.
Note: the `card` style CTA layout is slightly off (missing top margin) because the `CTA` component React wrapper has not been created yet. Will create a separate issue to track that work.
**New**
- `content-block-simple` React wrapper

feat(content-block-simple): add react wrapper

---

packages/web-components/src/components/masthead/cloud/cloud-masthead-composite.ts

GH Issue: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/7061
HC JIRA Ticket: https://jsw.ibm.com/browse/HC-2179
- This PR adds the `reflect: true` to the property parameter object so that value is passed correctly to the `has-contact` attribute.
- Pull down the changes of this PR in a test preview and sets the following markup with the `has-contact` attribute sets to `false` or remove from the markup.
- Ensure that the "Contact us" button is removed when the attribute is set to `false` or not defined within the markup.
```
<dds-cloud-masthead-container
platform="Cloud"
auth-method="API"
has-contact=false
data-endpoint="/common/carbon-for-ibm-dotcom/translations/cloud-masthead"
></dds-cloud-masthead-container>
```

fix(cloud-masthead): ensure that true is passed to the has-contact attribute

---

packages/web-components/src/components/video-player/video-player.ts

GH Issue: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/6944
HC JIRA Ticket: https://jsw.ibm.com/browse/HC-2168
- This PR adds a `tabindex` of `0` to `dds-video-player` component so that it receives the focus with Firefox.
- Visit the `Video Player` component in Firefox - `/iframe.html?id=components-video-player--default`
- Ensure that the blue focus outline is visible.

fix(video-player): set tabindex of 0 to dds-video-player

---

packages/react/src/components/Masthead/MastheadLeftNav.js
packages/react/src/components/Masthead/MastheadMegaMenu/RightNavigation.js
packages/styles/scss/components/masthead/_masthead-l1.scss
packages/styles/scss/components/masthead/_masthead-leftnav.scss
packages/web-components/src/components/masthead/masthead.scss

#7087
This PR includes several fixes to the `web-components` and `react` masthead component
* "View all products" button should be center aligned in the React version:
* L1 menu headers should be vertically centered in the React version:
Mobile view
* Back button should be properly positioned in the web components version
* "The essentials" should be 32px tall + 1px for the bottom border in the mobile WC and React versions
* "View all products" should appear correct in the React version
**Changed**
- explicitly set `iconInline` in right nav link with icon
- remove React specific padding rule in L1 masthead
- **manually override `body-long-01` styles in masthead leftnav (appears to be due to base font size differences)**
- fix back button positioning
- add `role="menuitem"` to React …

fix(masthead): expressive sunset cleanup

---

packages/react/examples/codesandbox/components/DotcomShell/package.json

The React codesandbox build was failing as it was not finding a dependency in the DotcomShell codesandbox example. This should fix the issue.
**Changed**
- React codesandbox for DotcomShell adding `carbon-components-react` dependency

fix(dotcom-shell): adding missing dependency for codesandbox example

---

.github/workflows/deploy-canary.yml
.github/workflows/percy-update-base.yml

Refs #6139
I missed removing this workflow in Github Actions, removed and added the new one to `percy-update-base.yml`.
**Changed**
- Added react e2e percy update
- Removed `test-e2e` workflow in deploy-canary

fix(e2e): removed `test-e2e` percy base update and added to react e2e

---

packages/styles/scss/components/content-block-media/_content-block-media.scss
packages/styles/scss/components/content-block-media/index.scss
packages/styles/scss/components/feature-card/_feature-card.scss

Fixes various style issues for `content-block-media`.
**New**
- add `feature-card.scss`
**Changed**
- update max width styles for `feature-card` CTA

fix(content-block-media): add missing style import

---

packages/web-components/src/components/link-list-section/link-list-section.ts

Needed for #6732
Just adding the annotation to generate the Linklist React wrapper.
**New**
- created `<dds-link-list-section>` react wrapper

feat(link-list-section): create react wrapper

---

packages/web-components/src/components/masthead/left-nav-overlay.ts
packages/web-components/src/components/masthead/left-nav.ts

To unblock users on the cloud pages with locale banners, set the position of the masthead to `fixed` when menu is opened.
Previous attempts to set offset of the menu haven't been successful, so this will be a temporary workaround
**Changed**
- query for the `cloud-masthead-container` masthead and set position to `fixed` on `expanded`
**Removed**
- remove top offset calculation logic for the `left-nav-overlay`

fix(cloud-masthead): set masthead position to fixed on menu open

---

.github/ISSUE_TEMPLATE/bug_report.yaml
.github/ISSUE_TEMPLATE/contribution_request.yaml
.github/ISSUE_TEMPLATE/feature_request.yaml
.github/ISSUE_TEMPLATE/question.yaml

This updates the fireline support roster for sprint 20.
**Changed**
- Github issue forms

chore(support): update support roster for sprint 20

---

.github/ISSUE_TEMPLATE/feature_request.yaml

This adds additional fields to the feature request form for better capturing information from adopters. Example up on my fork:
https://github.com/jeffchew/carbon-for-ibm-dotcom/issues/new?assignees=jeffchew%2Cljcarot%2Cshixiedesign%2CRobertaJHahn%2Cskuruvil%2Cannawen1%2CBrunnoM7&labels=Feature+request&template=feature_request.yaml&title=%5BYOUR+TITLE%5D%3A+Brief+description
**Changed**
- Feature request issue form

chore(issue-form): adding fields to feature request form

---

packages/react/src/components/BackToTop/README.stories.mdx
packages/react/src/components/BackToTop/__stories__/BackToTop.stories.js
packages/react/src/components/CardInCard/README.stories.mdx
packages/react/src/components/CardInCard/__stories__/CardInCard.stories.js
packages/react/src/components/CardSectionCarousel/README.stories.mdx
packages/react/src/components/CardSectionCarousel/__stories__/CardSectionCarousel.stories.js
packages/react/src/components/Carousel/README.stories.mdx
packages/react/src/components/Carousel/__stories__/Carousel.stories.js
packages/react/src/components/ContentGroupBanner/README.stories.mdx
packages/react/src/components/ContentGroupBanner/__stories__/ContentGroupBanner.stories.js
packages/react/src/components/ContentItemHorizontal/__stories__/ContentItemHorizontal.stories.js
packages/react/src/components/LeavingIBM/README.stories.mdx
packages/react/src/components/LeavingIBM/__stories__/LeavingIBM.stories.js
packages/react/src/components/TabsExtended/README.stories.mdx
packages/react/src/components/TabsExtended/__stories__/TabsExtended.stories.js
packages/react/src/components/TabsExtendedMedia/README.stories.mdx
packages/react/src/components/TabsExtendedMedia/__stories__/TabsExtendedMedia.stories.js
packages/react/src/components/TagGroup/README.stories.mdx
packages/react/src/components/TagGroup/__stories__/TagGroup.stories.js
packages/react/src/components/TagLink/README.stories.mdx
packages/react/src/components/TagLink/__stories__/TagLink.stories.js

Updating React Wrapper production url to point to `https://www.ibm.com/standards/carbon/web-components/react`.
**Changed**
- Storybook documentation

chore(react-wrapper): updating production url for react wrapper

---

packages/web-components/docs/carbon-cdn-style-helpers.md

This reformats the list of available Plex CDN font files into a table format, which also includes the actual font family name in the table.
**Changed**
- CDN helper documentation

docs(plex): reformatting plex cdn to table format

---

packages/styles/README.md
packages/styles/scss/themes/expressive/README.md

This updates additional documentation on the sunset of the expressive theme.
**Changed**
- Styles package README documentation

docs(expressive): missed documentation on expressive deprecation

---

packages/web-components/src/components/masthead/__stories__/README.stories.mdx

This adds the codesandbox link for Masthead L1 to the README.
**Changed**
- Masthead README (web components)

docs(masthead): add codesandbox link for L1 to documentation

---

packages/web-components/tests/e2e-storybook/cypress.json

When enabling web components e2e tests, the CI seems to need additional time to run some tests, so this will bump up the timeout to accommodate.
**Changed**
- `cypress.json` config for web components

test(cypress): bumping timeout configuration for web components e2e

---

packages/web-components/.storybook/preview-head.html
packages/web-components/src/components/locale-modal/locale-modal-composite.ts

#6761
This PR marks region items as invalid in the locale modal if a locale is not configured in the given region
~~The storybook preview locales have been reviewed for testing but will be restored prior to merging~~
EU locales have been commented out for future testing

fix(locale-modal-composite): set region item as invalid if locale not configured

---

packages/web-components/.storybook/preview-head.html

#6761
2 EU locales weren't removed in the latest commit pushed up to #7302 so this PR removes them
**Removed**
- final 2 EU locales to disable region selector in locale modal

docs(storybook): remove EU locales

---

packages/react/tests/e2e-storybook/cypress/integration/Footer/Footer.e2e.js
packages/web-components/tests/e2e-storybook/cypress/integration/footer/footer.e2e.js

#7427
This PR adds e2e tests on the micro language only footer variant for the following scenarios:
a. Check language selector (dropdown) is available and clickable
b. Click on language selector, drop down opens and user must be able to select language/geoFooter

test(footer): add e2e tests for footer - micro language only

---

packages/react/tests/e2e-storybook/cypress/integration/CalloutQuote/CalloutQuote.e2e.js
packages/react/tests/e2e-storybook/cypress/integration/Footer/Footer.e2e.js
packages/react/tests/e2e-storybook/cypress/integration/Masthead/Masthead.e2e.js
packages/react/tests/e2e-storybook/cypress/integration/Quote/Quote.e2e.js
packages/web-components/tests/e2e-storybook/cypress/integration/masthead/masthead.e2e.js

We were noticing some false positives in the percy snapshots, which is probably due to elements not properly loading before the snapshots are being taken. For the tests in `Masthead`,  `CalloutQuote`, and `Quote`, additional selector gets were added in order to ensure that the proper elements are in place before taking a snapshot.
**Changed**
- e2e tests for `Masthead`, `CalloutQuote`, and `Quote`

test(e2e): various false positive fixes for Masthead and Quote

---

packages/react/tests/e2e-storybook/browserstack.json
packages/web-components/tests/e2e-storybook/browserstack.json

Forgot to add `cypress-wail-until` to the `browserstack.json` config file to load that dependency for the automate runs. This should fix the issues there.
**Changed**
- `browserstack.json` added `cypress-wait-until` as npm dependency

fix(browserstack): add `cypress-wait-until` for browserstack automate

---

packages/web-components/src/components/search-with-typeahead/search-with-typeahead.ts

#7587
Ensured that, in mobile, clicking on the close search button the component renders properly, as well as making sure to retain the fixes for #6321.
**Changed**
- added some additional checks for handling focus out in search with typeahead

fix(search-with-typeahead): fixed mobile focus bug

---

packages/web-components/src/components/masthead/masthead-global-bar.ts
packages/web-components/src/components/search-with-typeahead/search-with-typeahead.ts

#7587 
Removes the `handleFocusOut` code that used to be in the `dds-masthead-search` component since it causes a cypress test to fail, as well as any search toggle related issue.
**Removed**
- removes `handleFocusOut` code from `dds-search-with-typeahead` so its reverted to how it was since #7200

fix(search-with-typeahead): remove focusout code

---

.github/workflows/automerge.yml
.github/workflows/ci-check.yml
.github/workflows/codeql-analysis.yml
.github/workflows/dco.yml
.github/workflows/dependabot-yarn-mirror.yml
.github/workflows/deploy-canary.yml
.github/workflows/deploy-staging.yml
.github/workflows/e2e-tests.yml
.github/workflows/percy-update-base-wc-e2e-codesandbox.yml
.github/workflows/percy-update-base.yml
.github/workflows/publish-canary.yml
.github/workflows/publish-nightly.yml
.github/workflows/publish-staging.yml
.github/workflows/release-preflight.yml
.github/workflows/snapshot-update.yml

Adding a new `concurrency` configuration may assist with removing redundant workflows in the queue. 
**Changed**
- Add `concurrency` setting for all workflows (except DCO)

chore(github-actions): introduce concurrency limit to workflows

---

.github/workflows/automerge.yml
.github/workflows/dco.yml
.github/workflows/dependabot-yarn-mirror.yml
.github/workflows/deploy-canary.yml
.github/workflows/deploy-staging.yml
.github/workflows/percy-update-base.yml
.github/workflows/publish-canary.yml
.github/workflows/publish-nightly.yml
.github/workflows/publish-staging.yml
.github/workflows/release-preflight.yml
.github/workflows/snapshot-update.yml

This minor update will prevent unnecessary github actions to run on forks if actions are enabled.
Another minor thing is renaming some of the jobs to more proper names.
**Changed**
- Added restriction for most github workflows to only run on `carbon-design-system/carbon-for-ibm-dotcom`
- Renamed `release-preflight / react` to `release-preflight / preflight`
- Renamed `DCO Assistant / CLAAssistant` to `DCO Assistant / DCOAssistant`

chore(github-actions): prevent actions from running on forks

---

.github/workflows/dco.yml

The name for the `dependabot` name needed the appended `[bot]` in order to be added properly to the `allowlist` for the `DCO Assistant` workflow.
**Changed**
- Updated name for `dependabot` in `dco` workflow

fix(github-actions): update dependabot name for dco allowlist

---

.github/workflows/dco.yml

I misspelled `DCOAssistant` in a previous PR (https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/7618)
**Changed**
- `dco.yml`

fix(github-actions): fix to dco workflow name

---

packages/react/src/components/Masthead/MastheadL1.js
packages/react/src/components/Masthead/MastheadLeftNav.js
packages/react/src/components/Masthead/MastheadTopNav.js
packages/web-components/src/components/masthead/masthead-composite.ts

DotcomShell component L1 not working #7678
When setting up DotcomShell with L1 in NextJS template, adopter is running into an error specifically with ` const currentUrlPath = root.location.href;`. Seems like NextJS is trying to load it server-side and throws an error that `root.location` is undefined. Adding optional chaining resolves this issue.
**Changed**
- add optional chaining to `currentUrlPath`

fix(Masthead): add optional chaining to root.location to remove error in NextJS when rendering server-side

---

packages/react/src/components/Masthead/Masthead.js

#7707
#6391
This PR updates a `window` object reference to `root` to avoid NPE issues when server side rendering the React Masthead
**Changed**
- React Masthead `window` object reference to `root`

fix(Masthead): use `window` or `global` object

---

.github/ISSUE_TEMPLATE/bug_report.yaml
.github/ISSUE_TEMPLATE/contribution_request.yaml
.github/ISSUE_TEMPLATE/feature_request.yaml
.github/ISSUE_TEMPLATE/question.yaml

This will update the fireline support roster for sprint 24.
**Changed**
- Updated issue templates

chore(support): update fireline roster for sprint 24

---

packages/react/src/components/PictogramItem/PictogramItem.js
packages/react/src/components/PictogramItem/__stories__/PictogramItem.stories.js
packages/react/tests/e2e-storybook/cypress/integration/PictogramItem/PictogramItem.e2e.js
packages/web-components/tests/e2e-storybook/cypress/integration/pictogram-item/pictogram-item.e2e.js

#7433
This PR adds Pictogram Item e2e tests for the following scenarios
a. Check pictogram item and content is loaded 
b. Check the Link with icon is loaded and clickable
c. Verify Pictogram item can be customized (desktop, touch, pattern) [depends on #7661]
d. Customize theme from Carbon theme and verify gray 10, gray 90 and gray 100 theme.

test(pictogram-item): add e2e tests

---

packages/react/tests/e2e-storybook/cypress/integration/LogoGrid/LogoGrid.e2e.js
packages/web-components/tests/e2e-storybook/cypress/integration/logo-grid/logo-grid.e2e.js

#7475
Created the e2e tests for the LogoGrid component
**New**
- created e2e tests for LogoGrid component for both React and Web Components

test(logo-grid): add e2e tests

---

packages/web-components/src/components/leaving-ibm/__stories__/README.stories.mdx
packages/web-components/src/components/leaving-ibm/__stories__/README.stories.react.mdx

#7738 
This updates `leaving-ibm` documentation to instruct users on what is required to trigger the modal.
**New**
- short instructions pointing out the need to manually set the modal state, as well as links to the modal's custom events

chore(leaving-ibm): update `leaving-ibm` docs

---

packages/react/tests/e2e-storybook/cypress-canary.json
packages/react/tests/e2e-storybook/cypress-local.json
packages/react/tests/e2e-storybook/cypress.json
packages/react/tests/e2e-storybook/cypress/integration/CalloutQuote/CalloutQuote.e2e.js
packages/react/tests/e2e-storybook/cypress/integration/Card/Card-Static.e2e.js
packages/react/tests/e2e-storybook/cypress/integration/FeatureCard/FeatureCard.e2e.js
packages/react/tests/e2e-storybook/cypress/integration/Footer/Footer.e2e.js
packages/react/tests/e2e-storybook/cypress/integration/LeadSpace/LeadSpace.e2e.js
packages/react/tests/e2e-storybook/cypress/integration/LocaleModal/LocaleModal.e2e.js
packages/react/tests/e2e-storybook/cypress/integration/LogoGrid/LogoGrid.e2e.js
packages/react/tests/e2e-storybook/cypress/integration/Masthead/Masthead.e2e.js
packages/react/tests/e2e-storybook/cypress/integration/PictogramItem/PictogramItem.e2e.js
packages/react/tests/e2e-storybook/cypress/integration/Quote/Quote.e2e.js
packages/react/tests/e2e-storybook/cypress/integration/TableOfContents/TableOfContents.e2e.js
packages/react/tests/e2e-storybook/cypress/support/commands.js
packages/web-components/tests/e2e-storybook/cypress-local.json
packages/web-components/tests/e2e-storybook/cypress.json
packages/web-components/tests/e2e-storybook/cypress/integration/card/card-static.e2e.js
packages/web-components/tests/e2e-storybook/cypress/integration/feature-card/feature-card.e2e.js
packages/web-components/tests/e2e-storybook/cypress/integration/footer/footer.e2e.js
packages/web-components/tests/e2e-storybook/cypress/integration/leadspace/leadspace.e2e.js
packages/web-components/tests/e2e-storybook/cypress/integration/link-list/link-list.e2e.js
packages/web-components/tests/e2e-storybook/cypress/integration/locale-modal/locale-modal.e2e.js
packages/web-components/tests/e2e-storybook/cypress/integration/logo-grid/logo-grid.e2e.js
packages/web-components/tests/e2e-storybook/cypress/integration/masthead/masthead.e2e.js
packages/web-components/tests/e2e-storybook/cypress/integration/pictogram-item/pictogram-item.e2e.js
packages/web-components/tests/e2e-storybook/cypress/integration/table-of-contents/table-of-contents.e2e.js
packages/web-components/tests/e2e-storybook/cypress/support/commands.js

Noticed in percy snapshots in our e2e tests that there were duplicate names being set for the snapshots:
~~This PR should fix the existing duplicate names, though we should perhaps by practice change all tests to use the variable `titlePath` values so that we won't run into this in the future.~~
I ended up creating a new global method called `cy.takeSnapshots`, and then applied it across all tests. Hopefully this will help to normalize how we do screenshot/snapshot testing going forward.
**Changed**
- Added `cy.takeSnapshots` method, can switch between `desktop` and `mobile` snapshots, and pass additional options
- Replaced all instances of `cy.screenshot()` and `cy.percySnapshot` with `cy.takeSnapshots`
- Replaced all theme tests with `cy.carbonThemesScreenshot()`
- …

test(e2e): overhaul of snapshot testing for web components and react

---

packages/web-components/src/components/dotcom-shell/__stories__/data/content.ts

#7766 
Update `card-group` example with latest markup.
**Changed**
- change `dds-card-footer` to `dds-card-cta-footer`

chore(dotcomshell): update `card-group` component example

---

packages/web-components/src/components/carousel/__stories__/carousel.stories.ts

This will skip the `Carousel | Cards with Video` story in Percy diff checking, as the async data is causing false positives in reports.
**Changed**
- Add `percy: skip` to the `Carousel | Cards with Video` story

chore(percy): skip cards with video in percy diffs

---

packages/web-components/src/components/card-group/card-group.ts
packages/web-components/src/components/carousel/carousel.ts

We were occasionally getting exception errors on a NextJS page that loaded in the carousel, which seems to be stemming from the internal `_setSameHeight` method:
Adding a null check in this method will hopefully fix the issues here.
**Changed**
- Added optional chaining in `_setSameHeight` method in `carousel.ts`

fix(carousel): add null check for carousel same height method

---

packages/react/tests/e2e-storybook/cypress/integration/Card/Card.e2e.js
packages/react/tests/e2e-storybook/cypress/integration/CardSectionSimple/CardSectionSimple.e2e.js
packages/web-components/tests/e2e-storybook/cypress/integration/card-section-images/card-section-images.e2e.js
packages/web-components/tests/e2e-storybook/cypress/integration/card-section-simple/card-section-simple.e2e.js
packages/web-components/tests/e2e-storybook/cypress/integration/card/card.e2e.js
packages/web-components/tests/e2e-storybook/cypress/integration/footer/footer.e2e.js
packages/web-components/tests/e2e-storybook/cypress/integration/link-list/link-list.e2e.js

This fixes a number of issues with browserstack and how it handles tests. React seems fine, still sorting through web components but can probably do a followup PR to do additional fixes if needed.
**Changed**
- Multiple fixes across e2e tests

test(e2e): multiple fixes for browserstack automate

---

packages/react/src/components/LinkList/__stories__/LinkList.stories.js
packages/react/src/components/TableOfContents/__stories__/TableOfContents.stories.js
packages/react/src/components/TableOfContents/__stories__/data/DataContent.js
packages/react/tests/e2e-storybook/cypress/integration/TableOfContents/TableOfContents.e2e.js
packages/styles/scss/components/tableofcontents/_tableofcontents.scss
packages/web-components/src/components/table-of-contents/__stories__/content.ts
packages/web-components/src/components/table-of-contents/__stories__/table-of-contents.stories.react.tsx
packages/web-components/src/components/table-of-contents/__stories__/table-of-contents.stories.ts
packages/web-components/src/components/table-of-contents/__stories__/wrapper-content.tsx
packages/web-components/tests/e2e-storybook/cypress/integration/table-of-contents/table-of-contents.e2e.js

#5644
This PR updates the web components, React wrapper, and React storybook Table of Contents stories according to match the expected content described in #5644:
* only "Default" (vertical) and "Horizontal" stories remain
* "With heading content" knob in default story toggles a link list header instead of an image
* the number of items is limited from 4-8 and the copy can be customized. This does not work properly in the web components storybook UI so you will need to view the story in a separate tab. This will work in the React storybook after #7687 is merged
**New**
- dynamic content knobs (the table of contents component does not update when its child elements change though, need to view story in new tab for updates)
- "Horizontal" story in React
- "Default" story in React
**Changed** …

docs(table-of-contents): add dynamic copy knobs

---

packages/react/src/components/ImageWithCaption/ImageWithCaption.js
packages/web-components/src/components/image-with-caption/image-with-caption.ts
packages/web-components/tests/snapshots/dds-image-with-caption.md

This reverts commit 335a02bd06652e7acadd6a6ff6579a05b210a4a3.
#6871
#7257
related Slack thread https://cognitive-app.slack.com/archives/C2PLX8GQ6/p1638980498318300
This PR removes the default value and reverts the required caption in the image with caption component
**New**
**Changed**
- `heading` requirement in ImageWithCaption
**Removed**
- default image-with-caption `heading` value

fix(image-with-caption): revert caption requirement

---

packages/web-components/examples/codesandbox/components/masthead/package.json
packages/web-components/examples/codesandbox/components/masthead/src/index.js

#7847
This PR adds a missing dependency to the masthead sandbox example so that it displays without any build errors
The working sandbox should be viewable at https://codesandbox.io/s/github/emyarod/carbon-for-ibm-dotcom/tree/7847-docs/masthead-sandbox-example/packages/web-components/examples/codesandbox/components/masthead

docs(masthead): add missing sandbox dependency

---

packages/web-components/tests/e2e-storybook/cypress/integration/card-section-images/card-section-images.e2e.js

#7880
This PR wraps the card group item images in Cypress to ensure that they are visible before testing

test(card-section-images): yield images in card group items

---

packages/react/src/components/CardSectionOffset/README.stories.mdx
packages/react/src/components/CardSectionOffset/__stories__/CardSectionOffset.stories.js
packages/react/src/components/FeatureSection/README.stories.mdx
packages/react/src/components/FeatureSection/__stories__/FeatureSection.stories.js
packages/react/src/components/FilterPanel/README.stories.mdx
packages/react/src/components/FilterPanel/__stories__/FilterPanel.stories.js

Noticed that the lower environment was being used for the React wrapper links. This updates to use the prod url instead.
**Changed**
- Multiple files updated to point to `www.ibm.com/standards/carbon/web-components/react` for react wrapper links

chore(react-wrapper): update to use prod url

---

packages/web-components/tests/e2e-storybook/cypress/integration/card-section-images/card-section-images.e2e.js

#7880 
This fixes the desktop e2e test for `dds-card-section-images` to wrap the image before testing.
**Changed**
- `card-section-images.e2e.js`

fix(card-section-image): fix to image check in e2e tests

---

packages/react/tests/e2e-storybook/cypress/integration/LinkWithIcon/Default.e2e.js
packages/web-components/tests/e2e-storybook/cypress/integration/link-with-icon/default.e2e.js

Resolves #7841
Adds e2e test coverage for the `Link with Icon` component in both the `react` and `web-components` packages.
**New**
- Adds e2e-storybook tests for `dds-link-with-icon` web component
- Adds e2e-storybook tests for `LinkWithIcon` React component

test(link-with-icon): add e2e tests

---

packages/styles/scss/components/masthead/_masthead-leftnav.scss
packages/web-components/src/components/masthead/left-nav-menu-section.ts
packages/web-components/src/components/masthead/masthead-composite.ts
packages/web-components/src/components/masthead/masthead.scss

[Masthead] Web component and React version discrepancies #7116
There's some difference between the react and web-components mobile masthead versions:
- the category heading arrow doesn't appear in the web components masthead
- the category heading in react is using different color tokens
- the horizontal rule under the category headings have different lengths
This PR fixes both web-components and react styles to align.
**REACT BEFORE:**
**REACT AFTER:**
**WEB COMPONENTS BEFORE:**
**WEB COMPONENTS AFTER:**
**New**
- check if section title has associated link, if so render with arrow icon
**Changed**
- adjust styles for the section title and back button

fix(masthead): align react and wc mobile menu styles

---

.github/workflows/deploy-canary.yml
.github/workflows/deploy-next.yml

The slack webhook as a global environment variable was getting burned into the React artifacts when building to Github Pages. This exposes the secret which isn't desired.
This PR moves the environment variable specifically under the Slack action in the workflow to avoid this.
**Changed**
- `deploy-canary.yml`
- `deploy-next.yml`

fix(github-actions): move slack webhook url to under slack action

---

packages/styles/scss/components/leadspace/_leadspace.scss

#8034
The Leadspace currently has a bug where, if the image is big enough, it can be scrolled within its own component. This means that if a user tries to scroll a bug when the cursor is on the leadspace, the leadspace will out of view. See the issue for a video with the bug.
You can see this in any Leadspace story containing an image (e.g. Leadspace Super with Image), though in the deploy previews here it will be fixed and unscrollable.
**Changed**
- `overflow-x` to `overflow` to account for the `y` overflow

fix(leadspace): fix scrollable component

---

packages/web-components/examples/codesandbox/components/cta-button/.babelrc
packages/web-components/examples/codesandbox/components/cta-button/.gitignore
packages/web-components/examples/codesandbox/components/cta-button/cdn.html
packages/web-components/examples/codesandbox/components/cta-button/index.html
packages/web-components/examples/codesandbox/components/cta-button/package.json
packages/web-components/examples/codesandbox/components/cta-button/sandbox.config.json
packages/web-components/examples/codesandbox/components/cta-button/src/index.js
packages/web-components/src/components/cta/__stories__/README.stories.mdx
packages/web-components/src/components/masthead/__stories__/README.stories.mdx
packages/web-components/tests/e2e/cypress/integration/cta-button/cta-button.cdn.e2e.js
packages/web-components/tests/e2e/cypress/integration/cta-button/cta-button.e2e.js

[Masthead]: Update platform url documentation #8002
Add documentation for button-cta:
- add `button-cta` codesandbox
- add code snippet for adopter to get started in cta readme
Updated masthead's documentation on how to set up `platformUrl`. Current example shows how it works within `lit-html` template which most adopters are not using. Change documentation to show how to set up with javascript instead.
**New**
- created codesandbox example for `button-cta`
**Changed**
- fix codesandbox example links for cta components in cta readme

docs(storybook): add button-cta documentation in CTA readme and update masthead's platform url documentation

---

packages/web-components/src/components/masthead/cloud/cloud-masthead-composite.ts
packages/web-components/src/components/masthead/masthead-composite.ts
packages/web-components/tests/snapshots/dds-masthead-composite.md

[Cloud Masthead]: Mobile menu items are not rendering #8082
Pass in object literal as argument for function rendering left nav menu items. By doing this and setting a default value, it's easier to keep track of these parameter between `masthead-composite` and `cloud-masthead-composite`
**Changed**
- pass object literal as arg to `_renderLeftNavMenuSections()`

fix(masthead): ensure sectionUrl is passed in and has default value

---

packages/web-components/src/components/card/__stories__/card.stories.react.tsx

#8105 
update storybook variable for static card. so static card renders properly

fix(static-card): react wrapper story not showing

---

packages/web-components/src/components/feature-section/feature-section.scss

#8103 
Update mobile styles when feature section `media-alignment=left`
**Changed**
- add responsive styles for `sm`/`md` breakpoints

fix(feature-section): responsive card styles

---

packages/web-components/src/components/masthead/__stories__/cloud-masthead.stories.ts
packages/web-components/src/components/masthead/__stories__/masthead.stories.ts
packages/web-components/src/components/masthead/masthead-composite.ts

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/8017
- This PR addresses the issue for adopters using the `has-profile="false"` to optionally hide the "Profile" button.
**Changed**
- This PR sets the `has-profile` prop to accept a string instead of a boolean.
- Spin up a sandbox example of the Masthead component - https://codesandbox.io/s/github/preoung/carbon-for-ibm-dotcom/tree/fix/masthead-8017/packages/web-components/examples/codesandbox/components/masthead
- Set `has-profile` attribute sets to `false`.
- Ensure that the "Profile" button is removed when the attribute is set to `false`. If the `has-profile` is not defined or set to `true`, the "Contact us" button should be set visible.
```
<dds-masthead-container
has-contact="false"
></dds-masthead-container>
```

fix(masthead): change hasProfile to accept a string instead of boolean

---

packages/react/tests/e2e-storybook/cypress/fixtures/translation.json
packages/react/tests/e2e-storybook/cypress/integration/Footer/Footer-micro.e2e.js
packages/react/tests/e2e-storybook/cypress/integration/Footer/Footer-short.e2e.js
packages/react/tests/e2e-storybook/cypress/integration/Footer/Footer.e2e.js
packages/react/tests/e2e-storybook/cypress/support/index.js
packages/web-components/tests/e2e-storybook/cypress/fixtures/translation.json
packages/web-components/tests/e2e-storybook/cypress/integration/footer/footer-micro.e2e.js
packages/web-components/tests/e2e-storybook/cypress/integration/footer/footer-short.e2e.js
packages/web-components/tests/e2e-storybook/cypress/integration/footer/footer.e2e.js
packages/web-components/tests/e2e-storybook/cypress/support/index.js

The footer e2e tests were for some reason switching between 38 and 41 nav links in some of the tests. This seems to be coming from the fact that the `Follow IBM` links are getting duplicated.
This PR has some stabilization fixes, so will see if this addresses it.
**Changed**
- Separated out footer e2e tests into variant files
- Updated translation mock fixture data
- Inject mock translation and countrylist data into sessionStorage to ensure mocking
- Switch test to check for 38 links instead of 41
- Add `cy.waitUntil` for all footer e2e tests

fix(footer): stabilization of e2e tests

---

packages/web-components/src/components/table-of-contents/__stories__/README.stories.mdx
packages/web-components/src/components/table-of-contents/table-of-contents.ts

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/8216
- This PR exposes an event that triggers the harvesting of anchor tags within the Table of Contents component.
- This feature allows AEM CMS Content Authors to see their inline text changes reflected in the anchor tags area of the Table of Contents.
**New**
- `dds-table-of-contents-reharvest` custom event.
https://user-images.githubusercontent.com/1815714/154524031-c537f882-ff0b-46ec-a971-a99c0c463039.mov

feat(toc): add an event to trigger harvesting of anchor tags

---

packages/styles/scss/components/card-in-card/_card-in-card.scss
packages/styles/scss/components/image/_image.scss

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/7667
- This PR implements the new design treatment for the `Card-in-Card` component within the medium breakpoints.
- See epic for more detail related to the design specs - https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/7355
**Final design for `md` breakpoints:**
**Changed**
- Mostly styling changes within the `_card-in-card.scss` partial

fix(card-in-card): implement md breakpoints redesign enhancement

---

.github/workflows/e2e-tests.yml

This adds a timeout to the `e2e-tests` GitHub jobs for both React and web components. These jobs can hang for hours and clog the pipeline. At a quick glance, these jobs can finish as quickly as 14 minutes to as long as 35 minutes (or longer, depending on the amount of jobs in the queue). Initial timeout value is set to 60, which can be adjusted as needed.
**New**
- add `timeout-minutes` to end-to-end Github jobs

chore(gh-actions): add timeout to e2e tests

---

.github/workflows/e2e-tests.yml
packages/web-components/tools/get-rollup-config.js

Refs https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/8383
The namedExport declaration specific to `marked` needed to be very specific in order for the commonjs plugin in rollup to register the import correctly. This will hopefully be the fix.
**Changed**
- Updated `namedExports` declaration in rollup config for web components

fix(rollup): fix to named exports declaration for marked dependency

---

packages/utilities/src/utilities/settings/settings.js
packages/web-components/src/components/masthead/cloud/cloud-masthead-composite.ts

#8450 
Removes extra top spacing from `cloud-masthead`
**Removed**
- extra spacing from `cloud-masthead`

fix(cloud-masthead): remove extra spacing from masthead

---

packages/web-components/src/components/masthead/masthead-composite.ts

#8450 
This removes extra spacing above the web components `masthead` component.
**Removed**
- extra spacing above `masthead`

fix(masthead): remove extra spacing above masthead

---

packages/web-components/package.json
yarn.lock

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/8233/
https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/8147/
This PR downgrades Cypress in the `web-components` package back to v8.1.0 due to out of memory issues present in v8.2+
Firefox is also added to the browsers matrix again for end to end tests

chore: downgrade cypress

---

packages/react/.storybook/manager-head.html
packages/web-components/.storybook/manager-head.html
packages/web-components/.storybook/react/manager-head.html
packages/web-components/examples/codesandbox/components-react/card-group/src/index.css
packages/web-components/examples/codesandbox/components-react/card-in-card/src/index.css
packages/web-components/examples/codesandbox/components-react/card-link/src/index.css
packages/web-components/examples/codesandbox/components-react/card-section-offset/src/index.css
packages/web-components/examples/codesandbox/components-react/card/src/index.css
packages/web-components/examples/codesandbox/components-react/carousel/src/index.css
packages/web-components/examples/codesandbox/components-react/content-group-banner/src/index.css
packages/web-components/examples/codesandbox/components-react/content-item-horizontal/src/index.css
packages/web-components/examples/codesandbox/components-react/cta-section/src/index.css
packages/web-components/examples/codesandbox/components-react/feature-section/src/index.css
packages/web-components/examples/codesandbox/components-react/filter-panel/src/index.css
packages/web-components/examples/codesandbox/components-react/leadspace-with-search/src/index.css
packages/web-components/examples/codesandbox/components-react/leadspace/src/index.css
packages/web-components/examples/codesandbox/components-react/leaving-ibm/src/index.css
packages/web-components/examples/codesandbox/components-react/search-with-typeahead/src/index.css
packages/web-components/examples/codesandbox/components-react/table-of-contents/src/index.css
packages/web-components/examples/codesandbox/components-react/tabs-extended-media/src/index.css
packages/web-components/examples/codesandbox/components-react/tabs-extended/src/index.css
packages/web-components/examples/codesandbox/components-react/tag-group/src/index.css
packages/web-components/examples/codesandbox/components-react/tag-link/src/index.css
packages/web-components/examples/codesandbox/components-react/universal-banner/src/index.css
packages/web-components/examples/codesandbox/usage/dotcom-shell-cdn-with-handlebars/index.hbs
packages/web-components/examples/codesandbox/usage/dotcom-shell-cdn-with-rtl/index.hbs
packages/web-components/examples/codesandbox/usage/dotcom-shell-cdn/index.html
packages/web-components/examples/codesandbox/usage/react-ssr/src/index.css
packages/web-components/examples/codesandbox/usage/webpack-basic/index.html
packages/web-components/examples/codesandbox/usage/webpack-rtl/index.hbs

#8501 
This replaces all font references in the library to use the IBM Akamai CDN rather than Google Fonts server (`gstatic`). This is necessary in order to GDPR compliance issues with fonts hosted on Google Fonts.
**Changed**
- update all instances of `gstatic` external font references to IBM Akamai.

fix(plex): replace `gstatic` font references with akamai

---

packages/web-components/tests/e2e-storybook/browserstack.json

The Browserstack Automate testing for WC is hanging on FF Windows. Removing for now.
**Removed**
- FF on windows configuration from browserstack.json

chore(browserstack): remove FF on Windows testing for browserstack automate

---

packages/styles/scss/components/pictogram-item/_pictogram-item.scss
packages/web-components/src/components/pictogram-item/__stories__/pictogram-item.stories.ts
packages/web-components/src/components/pictogram-item/defs.ts
packages/web-components/src/components/pictogram-item/pictogram-item.ts

#8603: [Pictogram Item]: Allow for changing of Pictogram color
Expose a pictogram-color color prop/attribute that allows Content Editors to pick and choose from the following options.
- Black (Default)
- Blue 50
1. Open the component at `/?path=/story/components-pictogram-item--default`
2. In the "Knobs" tab, the last knob should be "Pictogram color"
3. Select "Blue 50" and check that the pictogram SVG changes to blue

feat(pictogram-item): Allow for changing of Pictogram color

---

packages/react/src/components/Masthead/Masthead.js

None.
This PR ensures that the Masthead only checks for the horizontal ToC if the `getRootNode` exists. In other words, it ensures no errors happen when checking for it as can be seen happening in the NextJS page.
**Changed**
- added optional chaining for the React wrapper ToC

fix(masthead): add optional chaining

---

packages/react/tests/e2e-storybook/cypress/integration/CardSectionImages/CardSectionImages.e2e.js
packages/react/tests/e2e-storybook/cypress/integration/CardSectionSimple/CardSectionSimple.e2e.js
packages/react/tests/e2e-storybook/cypress/integration/TableOfContents/TableOfContents.e2e.js

Noticing consistent false positives happening around snapshots in Percy that involve motion/height calculation. This adds some wait time to see if this helps at all.
**Changed**
- Added `cy.wait()` to various React e2e tests

fix(e2e): adding wait times for React storybook e2e percy snapshots

---

packages/web-components/src/components/table-of-contents/__stories__/content.ts
packages/web-components/src/components/table-of-contents/table-of-contents.ts
packages/web-components/src/components/tabs-extended/__stories__/tabs-extended.stories.react.tsx
packages/web-components/src/components/tabs-extended/__stories__/tabs-extended.stories.ts
packages/web-components/src/components/tabs-extended/tab.ts
packages/web-components/src/components/tabs-extended/tabs-extended.ts

Resolves  #8751
There were cases where certain boolean attributes were being parsed as strings (e.g. `"false"`). Since non-empty strings are truthy, the value `"false"` was treated as `true`, and this caused any new tabs injected into the DOM to be  disabled.
This has been fixed by declaring to Lit Element that these attributes should be reflected as booleans. This tells Lit Element to convert the strings `"true"` and `"false"` to the booleans `true` and `false`, respectively.
The `slotchange` event that we typically use to catch updates to slotted DOM nodes has a limitation. From [the MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/HTMLSlotElement/slotchange_event):
> Note: the slotchange event doesn't fire if the children of a slotted node change — only if you change (e.g. …

fix(tabs-extended & table-of-contents): ensure DOM updates are handled

---

packages/web-components/src/components/masthead/__tests__/masthead.steps.js

Update snapshot URLs to remove regex values, which were causing [CodeQL alerts](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/security/code-scanning/14).
**Changed**
- remove unneeded regex values for test URLs

chore(jest): update snapshot urls

---

packages/web-components/docs/carbon-cdn-style-helpers.md

This PR adds missing documentation for Plex Serif.
**Changed**
- add serif font list to CDN helpers documentation

docs(plex): add missing documentation for serif fonts

---

packages/web-components/src/components/back-to-top/back-to-top.ts

#8230
This PR resets the tab order after the back to top component is clicked. The first focusable element in the document should be focused after clicking the back to top component and the pressing <kbd>Tab</kbd>
https://user-images.githubusercontent.com/8265238/170094268-db4f27f6-a572-4df1-b530-3627121bc40b.mov

fix(back-to-top): reset tab order on click

---

packages/react/src/components/CalloutQuote/__stories__/CalloutQuote.stories.js
packages/styles/scss/components/quote/_quote.scss

#8690 
This PR updates the Quote and Callout Quote corner bracket placement at the `max` breakpoint in both the `web-components` and `react` packages. The other quote variants should be unchanged at all breakpoints

fix(quote): update max breakpoint corner bracket position

---

packages/web-components/src/components/video-player/video-player-container.ts

None.
The TextCTA component test was failing due to the href being updated erroneously, this should fix it.
**Changed**
- added a `video-id` attribute check for videos before transposing the href

fix(cta): ensure href works again

---

packages/styles/scss/components/structured-list/_structured-list.scss

Fixes #9022
Moves style layout rules from targeting `:host(dds-*-cell)` to `:host(dds-*-row) ::slotted(*:nth-child(n))`
This helps AEM devs creating the authoring experience by enabling the tabular layout to remain in place with extra wrapping divs.
**Changed**
- Updated styles for smoother AEM adoption

fix(structured-list): refactor table column layout styles

---

.github/workflows/dco.yml

This updates the `renovate` bot username in the DCO Assistant `allowlist`. The incorrect name is preventing the GitHub action from passing.
**Changed**
- change `renovate-bot` to `renovate[bot]`

chore(deps): update allowlist for DCO assistant

---

packages/styles/scss/components/content-item-horizontal/_content-item-horizontal.scss

Removes an unused and invalid selector that can cause build issues in bundlers.
**Removed**
- unused styles for `p` selector

fix(content-item-horizontal): remove invalid selector

---

packages/styles/scss/components/masthead/_masthead-megamenu.scss

#9065 
Cherry-pick of the megamenu item styles fix into patch release branch:
Megamenu child items are being displayed in one, long, single column. This fixes that.
**Removed**
- `.bx--masthead__megamenu__category-group-shield` as child to `::slotted` selector
**New**
**Changed**
**Removed**

fix(masthead): fixes megamenu item styles (#9066)

---

packages/react/src/components/ExpressiveModal/__stories__/ExpressiveModal.stories.js

#9124
This PR updates the ExpressiveModal story props so that the components render properly again

fix(ExpressiveModal): render react story correctly

---

packages/web-components/src/globals/internal/storybook-cdn.ts

[Documentation]: Update storybook and website documentation about using tagged versions of Carbon for IBM.com #9138
Add more specific information about CDN tagged versions in Storybook Docs tab for all web components.
**Changed**
- edit language in the `storybook-cdn` file that renders in all component storybook docs

chore(docs): adding to CDN artifact documentation in storybook docs

---

packages/react/src/components/ContentBlockSegmented/__stories__/ContentBlockSegmented.stories.js
packages/web-components/tests/e2e-storybook/cypress/integration/storybook-docs/storybook-components.e2e.js

#9151 
Update snapshots for unit tests, so ci-checks pass for react.
**Changed**
- update snapshots and fix formating

fix(snapshots): react storybook6

---

.github/workflows/publish-alpha.yml

Adds GitHub workflow to publish `alpha` tag for NPM package from the `feat/masthead-v2` branch. This workflow can be modified to target the `c4dotcom-v2` feature branch when it is created.
**New**
- GH workflow `publish-alpha`

chore(github): add `publish-alpha` workflow

---

packages/web-components/src/components/tabs-extended/tabs-extended.ts

[Tab Extended]: QA: Screen reader does not identify the currently selected tab #9230
Screen reader was not picking up the `aria-selected` attribute on the tab buttons. According to https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-selected#description, the `aria-selected` attribute should be applied to elements with the `role="tab"` attribute, which in this case is the `li` element wrapping the `button`. 
Moving the `aria-selected` attribute to the `li` should hopefully work to have the screen reader pick it up.
**Changed**
- move `aria-selected` to `li` element wrapping tabs-extended button

fix(tabs-extended): move aria-selected to li elem with tab role

---

packages/styles/carbon.yml

Related: https://github.com/carbon-design-system/carbon-platform/issues/967
The IBM.com Web Components and IBM.com React libraries have a design kits page, to view a subset of indexed design kits that are compatible with those libraries:
https://next.carbondesignsystem.com/libraries/ibmdotcom-web-components/latest/design-kits
https://next.carbondesignsystem.com/libraries/ibmdotcom-react/latest/design-kits
Because both of those libraries inherit IBM.com Styles, and `designKits` array in the schema is inheritable, this PR adds compatible design kits to the styles library.
**New**
- `designKits` in IBM.com Styles library index
**Changed**
- N/A
**Removed**
- N/A

docs: index compatible design kits

---

packages/services-store/src/actions/__tests__/profileAPI.test.ts
packages/services-store/src/actions/profileAPI.ts
packages/services-store/src/types/profileAPI.ts
packages/services/src/services/Profile/Profile.js
packages/web-components/src/components/masthead/__stories__/README.stories.mdx
packages/web-components/src/components/masthead/__stories__/masthead.stories.ts
packages/web-components/src/components/masthead/cloud/cloud-masthead-composite.ts
packages/web-components/src/components/masthead/masthead-composite.ts

https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/9291
- This PR consolidates the Cloud authentication methods and ensures that we deliver the right utility menu items based on the value defined in the auth-method prop/attribute.
- Add different storybook previews per masthead endpoint (eg, `with V2 Data`, `with Cloud Data`), since the endpoint knob does not update the source string of the endpoint consistently.
**Changed**
- Move Cloud auth methods/functions into the Profile services within the `@carbon/ibmdotcom-services` package and adjust `@carbon/ibmdotcom-services-store`
- Add `has-contact` knob to show adopters that they can optionally add/remove `contact` CTA/button.
**To do**

feat(masthead-v2): consolidate Cloud auth methods with profileAPI & update docs

---

packages/web-components/src/components/masthead/masthead.ts

[DCMS-6277](https://jsw.ibm.com/browse/DCMS-6277)
This PR helps fix an otherwise undocumented issue where adding/removing an L1 menu after the masthead's `firstUpdated` callback prevents the global `StickyHeader` utility class from having knowledge of L1 menus.
This was discovered during Drupal ingestion of the v2 Mastheadwork, since they're pulling L1 data in separately from the masthead component.
**Changed**
- Updated logic to fortify the masthead/StickyHeader combination

fix(StickyHeader): fix masthead-l1 logic for Masthead v2

---

packages/styles/scss/components/link-list/_link-list.scss

#8977
There was a small leftover where the Link list icon doesn't stay at the top when there is more than two lines. 
**Changed**
- removed `padding-top` of `card-cta-footer` when slotted within `list-list-item-card-cta` at `md` or less breakpoint

fix(link-list): ensure icon stays on top

---

packages/web-components/src/components/leadspace-with-search/__stories__/leadspace-with-search.stories.ts

#8793
The current Storybook lacked a knob to modify the subheading in Leadspace with search, this ensures the knob works. 
**New**
- new subheading knob and logic to ensure it works

chore(leadspace-search): add subheading knob

---

packages/web-components/src/components/dotcom-shell/__stories__/data/content.ts
packages/web-components/src/components/lightbox-media-viewer/__stories__/lightbox-media-viewer.stories.ts

#9420 
Storybook bug where stories are missing all of the component imports and displaying wrong. This updates dotcomshell stories to include a table-of-contents import and lightbox-media-viewer to include importing the carousel
**New**
- add missing component import to stories

fix(storybook): dotcomshell/lightbox missing imports

---

packages/web-components/src/components/filter-panel/filter-panel-input-select.ts

#9391 
Removes `aria-expanded` attribute for the options within the filter panel that do not "expand/collapse". aria-expanded attribute should be present only for the elements that behave like expand/collapse e.g. Artificial intelligence, etc.
**Changed**
- checks which filter panel input has items and adds `aria-expanded` to only the ones with items

fix(filter-panel-input-select): aria expanded

---

packages/styles/scss/internal/content-block/_content-block.scss

#8331 
Content block CTA should align to the left of the viewport in mobile only when `cta-type=card`.
before:
after:
**Changed**
- update `content-block` CTA alignment for mobile viewport

fix(content-block): fix cta alignment for mobile viewport

---

packages/react/package.json

N/A
update build scripts. The gh-pages are showing feature flag components with[ blank pages](https://carbon-design-system.github.io/carbon-for-ibm-dotcom/canary/react-experimental/?path=/story/components-audio-player--default) even though the `DDS_FLAGS_ALL=true`

fix(react): storybook experimental/rtl gh-pages

---

.github/workflows/automerge-mastheadv2.yml

Related to #9459 
To avoid volatility in masthead v2 now that it's on prod environments, we'd like to move active development to the `feat/masthead-v2-dev` branch. This includes the automerge workflow that keeps the masthead v2 work up to date with `main`.
**Changed**
- update automerge workflow name & target

chore(masthead-v2): update automerge target

---

packages/web-components/src/components/masthead/top-nav.ts

[Masthead]: Screen reader announces the landmark label as "Nav LTR" which is not meaningful #8853
the `top-nav` aria-label is unnecessary and should be removed to not confused the user.
**Removed**
- `aria-label` from `top-nav`

fix(masthead): remove unnecessary aria-label

---

packages/web-components/src/components/feature-section/__stories__/feature-section.stories.react.tsx

[Feature section]: VO does not read out image #8131
`alt` prop wasn't being passed in for `feature-section` React wrapper. React wrapper story should now read the image alt text in VO
https://user-images.githubusercontent.com/54281166/194951646-dedc2c33-9911-445e-9bdd-4f7a54c5a23a.mov
**Changed**
- pass in `alt` to image in `feature-section` React wrapper story

fix(feature-section): react wrapper img alt not being used in story

---

packages/web-components/.storybook/react/main.js
packages/web-components/src/components/button-group/__stories__/README.stories.react.mdx
packages/web-components/src/components/dotcom-shell/__stories__/README.stories.react.mdx
packages/web-components/tools/babel-plugin-create-react-custom-element-type.js

N/A
Components that extend other components were not showing props in the storybook `docs` tab. 
Note: the first time the react wrapper deploy preview ran it failed, but the second time it passed. not sure if it will be finnicky when running on github pages
**New**
- Added to `babel-create-react-custom-element-type` to check if parentProps exist and if they do copies and pastes props into current component `es` files

fix(storybook-react-wrapper): props not appearing

---

packages/web-components/.storybook/react/main.js
packages/web-components/src/components/button-group/__stories__/README.stories.react.mdx
packages/web-components/src/components/dotcom-shell/__stories__/README.stories.react.mdx
packages/web-components/tools/babel-plugin-create-react-custom-element-type.js

Reverts carbon-design-system/carbon-for-ibm-dotcom#9597
Github actions for deploying react-wrapper continues to fail because of some inconsistency. Will try to look more closely and restore.

Revert "fix(storybook): react wrapper props not rendering"

---

packages/carbon-web-components/src/components/content-switcher/content-switcher-item.ts
packages/carbon-web-components/src/components/tabs/defs.ts
packages/carbon-web-components/src/components/tabs/tab.ts
packages/carbon-web-components/src/components/tabs/tabs.scss
packages/carbon-web-components/src/components/tabs/tabs.ts
packages/carbon-web-components/tests/spec/tabs_spec.ts

https://github.com/carbon-design-system/carbon-web-components/issues/970
https://github.com/carbon-design-system/carbon-web-components/issues/707
This PR ensures that the Tabs and Content Switcher components are able to be work with tab navigation.
**New**
- added tab-index in the tab shadow dom
- added home/end key functionality
**Changed**
- triggering the content switching upon pressing the enter key
**Removed**
- remove unneeded inFocus property in the tab item component

fix(tabs): basic keyboard navigation

---

packages/web-components/src/components/content-block-mixed/__stories__/content-block-mixed.stories.react.tsx
packages/web-components/src/components/content-block-mixed/__stories__/content-block-mixed.stories.ts
packages/web-components/src/components/video-player/__stories__/video-player.stories.react.tsx
packages/web-components/src/components/video-player/__stories__/video-player.stories.ts

[video-player]: use controls #9552
[Content-block-mixed]: use controls #9503
Switch to storybook controls for `video-player` and `content-block-mixed` and its React Wrappers
**Changed**
- change video-player storybook to use controls
- change content-block-mixed storybook to use controls

feat(storybook): switch to storybook controls for video-player and content-block-mixed

---

packages/carbon-web-components/src/components/progress-indicator/index.ts

[BX Progress Indicator Skeleton]: Vue: Unknown custom element: <bx-progress-indicator-skeleton> #9825
For adopter using `import "@carbon/web-components/es/components/progress-indicator/index.js"` and `bx-progress-indicator-skeleton` there is an error. Seems adding the missing import to the `index.js` file should resolve the issue.
**New**
- add import for `progress-indicator-skeleton` in the index.js file

fix(progress-indicator): add missing import for progress indicator skeleton

---

packages/styles/scss/components/card/index.scss

#9815
Removes hover styles from `disabled` card links.
**New**
- add disabled hover styles to card links

fix(styles): update disabled card hover styles

---

packages/carbon-web-components/src/components/dropdown/dropdown.ts
packages/carbon-web-components/src/components/tile/selectable-tile.ts
packages/carbon-web-components/src/components/tooltip/tooltip.ts
packages/react/src/components/ButtonGroup/ButtonGroup.js
packages/react/src/components/Icon/IbmLogo.js
packages/web-components/src/components/button-group/button-group.ts

#9567 
This updates the React masthead logo URL to use `https`.
**Changed**
- React masthead logo URL changed to use `https`

fix(masthead): update logo url protocol

---

packages/carbon-web-components/src/components/breadcrumb/breadcrumb.scss
packages/carbon-web-components/src/components/modal/modal.scss

[breadcrumb]: / separator not showing on v1.27.0 #9936
Modal not displaying with @carbon/web-components 1.23.0 #9923
Some styles have not been extending from `carbon-components` for `bx-modal` and `bx-breadcrumb` components. Will need to dig further to see why they aren't showing, but in the mean time we can add those styles to ours.
**Changed**
- added styles from `carbon-components` that are not showing for `bx-modal` and `bx-breadcrumb`

fix(styles): add missing styles for breadcrumb and modal

---

packages/styles/scss/components/masthead/_masthead.scss
packages/web-components/src/components/masthead/__stories__/masthead.stories.ts
packages/web-components/src/components/masthead/__tests__/masthead-composite.test.ts
packages/web-components/src/components/masthead/masthead-composite.ts
packages/web-components/src/components/masthead/masthead.scss
packages/web-components/tests/e2e-storybook/cypress/integration/masthead/masthead-custom-search.e2e.js
packages/web-components/tests/e2e-storybook/cypress/integration/masthead/masthead-l1.e2e.js
packages/web-components/tests/snapshots/dds-masthead-composite.md

Resolves #9821 
The masthead was breaking to the mobile version too early, below 960px. The design team informed us it should break below 800px instead.
**Changed**
- Updates DDSMasthead to break to mobile version below 800px instead of 960px.
Visit the "Masthead / With V2 Data" Story ([direct link](https://ibmdotcom-webcomponents.s3.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/9939/iframe.html?args=&knob-platform%20name%20(platform)=&knob-show%20the%20profile%20functionality%20(has-profile)=true&knob-show%20the%20search%20functionality%20(has-search)=true&knob-search%20placeholder%20(searchPlaceholder)=Search%20all%20of%20IBM&knob-selected%20menu%20item%20(selected-menu-item)=Consulting%20&%20Services=&knob-The%20user%20authenticated%20status%20(user-status)=Unauthenticate …

fix(masthead-v2): switch to mobile nav at smaller breakpoint

---

packages/web-components/tests/e2e-storybook/cypress/integration/masthead/masthead-authenticated.e2e.js
packages/web-components/tests/e2e-storybook/cypress/integration/masthead/masthead-v2.e2e.js

Resolves #9607 
This adds e2e Cypress tests for the [DOM pruning](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/9595) and [lazy loading](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/9602) [performance optimizations](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/9582) that were previously made.
Together with #10053, this resolves #9607.
**New**
- Tests for the masthead around DOM pruning and lazy loading performance optimizations
- Bonus new tests for authenticated state
- Bonus new test for mobile menu level 3 navigation

Additional Masthead tests including coverage for DOM pruning and lazy loading

---

packages/web-components/tests/e2e-storybook/cypress/integration/masthead/masthead-v2.e2e.js

none
There's some duplicated steps in one of the new tests we merged in this morning. I don't know why it passed earlier, but now it's causing timeouts (see https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/10066).
**Removed**
- Removes duplicate test steps to fix test runs.

fix(masthead-v2): remove breaking redundancy in masthead mobile test

---

packages/web-components/src/components/masthead/left-nav-menu-section.ts
packages/web-components/src/components/masthead/left-nav.ts

#10026 
Similar to the updates made here: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/10019
because of the updates to v11 we have to target the event.target differently to get the appropriate value
**Changed**
- updated the else if statement to make sure the right values are getting passed

fix(masthead): left nav focuswrap

---

.github/workflows/e2e-integration.yml
.github/workflows/percy-update-base.yml
packages/react/tests/e2e/build/build-examples.js
packages/web-components/tests/e2e/build/build-examples.js
packages/web-components/tests/e2e/cypress/integration/dotcom-shell/dotcom-shell.cdn.e2e.js
packages/web-components/tests/e2e/cypress/integration/dotcom-shell/dotcom-shell.e2e.js
packages/web-components/tests/e2e/cypress/integration/masthead/masthead.cdn.e2e.js
packages/web-components/tests/e2e/cypress/integration/masthead/masthead.e2e.js

This fixes the `e2e-integration` GH actions that are failing for `react` and `web-components`. With the upgrade to Yarn v3, building the Codesandbox examples needed for e2e tests becomes problematic as they have not been upgraded. The simplest solution is to switch back to an older version of Yarn for the test builds only.
**New**
- Use `execa` for `web-components` build process. Now that `vendor/@carbon/web-components` are bundled with `ibmdotcom-web-components`, the packed file is huge. This exceeds the `maxBuffer` limit in `execSync`, while `execa` has no such issue.
**Changed**
- update `dotcom-shell` and `masthead` e2e tests
**Removed**

chore(e2e): fixes `e2e-integration` tests

---

packages/carbon-web-components/.storybook/theme.ts

N/A
Clicking on the storybook title for cwc was linking us back to the old repo
**Changed**
-updated link to the current repo

fix(cwc): storybook link

---

packages/carbon-web-components/src/components/tile/tile.scss

#10202 
Fixes styles for `tile - expanded` content to be visible when tile is expanded.
**New**
**Changed**
- make expanded content `visible`
**Removed**

fix(tile): fix expanable content visibility

---

packages/carbon-web-components/.storybook/_container.scss
packages/carbon-web-components/src/components/accordion/accordion-item.ts
packages/carbon-web-components/src/components/accordion/accordion.scss

N/A
added missing animation styles on open and close
added back the styles in storybook... otherwise they overwrite all slotted `p` styles, but wasn't exactly sure what was broken before? 
- what this pr shows
- how it shows with previous container styles
**New**
**Changed**
**Removed**

fix(accordion): misisng animation styles

---

packages/carbon-web-components/src/components/icon/icon-story.ts
packages/carbon-web-components/tests/snapshots/cds-btn.md
packages/carbon-web-components/tests/snapshots/cds-link.md
packages/carbon-web-components/tests/snapshots/cds-tile.md
packages/carbon-web-components/tests/snapshots/cds-toggle.md
packages/carbon-web-components/tests/spec/accordion_spec.ts
packages/carbon-web-components/tests/spec/link_spec.ts
packages/carbon-web-components/tests/spec/loading_spec.ts
packages/carbon-web-components/tests/spec/radio-button_spec.ts
packages/carbon-web-components/tests/spec/tag_spec.ts
packages/carbon-web-components/tests/spec/tile_spec.ts
packages/carbon-web-components/tests/spec/tooltip_spec.ts

This fixes various unit tests in `@carbon/web-components` which were breaking and preventing CI checks from running to completion. This does not imply that all tests are passing - they are not. The failing tests can be updated as their corresponding components are synced with their React counterparts. This fix simply allows the checks to finish.
**New**
**Changed**
- update various unit tests
- update snapshots
**Removed**

chore(ci): fixes cwc-v2 failing unit test specs

---

.github/workflows/add-to-project.yml
yarn.lock

This adds a new GitHub workflow to automatically add new issues and pull requests to the Carbon for IBM.com project. Currently it will add anything newly created labeled. This workflow is just a starting point. In the future, new workflow filters can be created to add to other GitHub projects.
See https://github.com/actions/add-to-project for more use cases.
**New**
- workflow to automatically add new issues to default project
**Changed**
**Removed**

chore(gh): adds workflow to auto add issues/PRs to project

---

packages/react/package.json

react storybook build cmd failing in the [deploy canary git action workflows](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/actions/workflows/deploy-canary.yml). This PR adds the needed open ssl flag
**New**
**Changed**
**Removed**

chore(actions): add open ssl flag to react storybook build cmds

---

packages/carbon-web-components/src/components/skeleton-text/defs.ts
packages/carbon-web-components/src/components/skeleton-text/skeleton-text-story.ts
packages/carbon-web-components/src/components/skeleton-text/skeleton-text.scss
packages/carbon-web-components/src/components/skeleton-text/skeleton-text.ts

#10090
This PR updates the skeleton text export name and story to match the core v11 component

chore(skeleton-text): sync with v11

---

.github/workflows/ci-check.yml

A current [bug](https://github.com/nodejs/node/issues/47563) in the latest version of Node is causing CI checks to fail. The bug has been fixed but not yet back-ported, so in the meantime will test pinning the version to `18.15`.
**New**
**Changed**
- pin `ci-check` workflow Node version to `18.15`
**Removed**

chore(checks): pin node version to 18.15

---

packages/carbon-web-components/package.json
packages/carbon-web-components/src/components/date-picker/fix-events-plugin.ts
packages/carbon-web-components/src/components/date-picker/focus-plugin.ts
packages/carbon-web-components/src/components/date-picker/shadow-dom-events-plugin.ts
packages/carbon-web-components/src/components/ui-shell/side-nav.ts
packages/carbon-web-components/src/globals/mixins/form.ts
packages/carbon-web-components/src/globals/mixins/host-listener.ts
packages/carbon-web-components/src/globals/mixins/on.ts
packages/carbon-web-components/src/globals/wrappers/createReactCustomElementType.ts
packages/carbon-web-components/tests/utils/event-manager.ts

This imports the `on` helper function from `carbon-components` into the package, as `carbon-components` is no longer a dependency.
**New**
- `on` mixin added
**Changed**
- change `on` references from `carbon-components` to local
**Removed**

chore(mixin): import `carbon-components` mixin

---

packages/web-components/src/components/notice-choice/notice-choice.ts

Temporarily remove `notice-choice` React wrapper added in #10421 as it is throwing errors and affecting the CI workflow.
@sanjitbauli Since there is still a current React version this doesn't need to be any sort of blocker. Once it is fixed we can re-enable it.
**New**
**Changed**
**Removed**
- `notice-choice` React wrapper

chore(notice-choice): remove react wrapper causing build errors

---

packages/web-components/src/components/masthead/masthead-l1.ts

Closes #10521
Previous logic used only `Node.compareDocumentPosition()` and closed if the `currentTarget` did not contain `relatedTarget`. This forgot to account for `currentTarget === relatedTarget`.
**Changed**
- fixed focusout handler bug in masthead L1

fix(masthead-l1): fix focusout logic

---

packages/styles/scss/components/masthead/_masthead-l1.scss
packages/web-components/src/components/masthead/masthead-l1.ts

The `:has` pseudo-class is not supported across all browsers yet (lookin' at you Firefox). This PR removes the usage of `:has` inside the masthead L1 styles, without changing the look on the front end. 
**Changed**
- Added a `classMap` to the L1 dropdown links element to dynamically add a class if the dropdown contains a wide column. 
- Added a similar functionality to the pre-existing headingClasses `classMap` to account for when headings inside dropdowns are not links. 
- Updated the corresponding styles to use the new classes instead of `:has`.

feat(masthead-l1): Removing the has pseudo-class

---

packages/carbon-web-components/src/components/progress-indicator/progress-indicator-skeleton.ts
packages/carbon-web-components/src/components/progress-indicator/progress-indicator-story.ts
packages/carbon-web-components/src/components/progress-indicator/progress-indicator.scss
packages/carbon-web-components/src/components/progress-indicator/progress-indicator.ts
packages/carbon-web-components/src/components/progress-indicator/progress-step-skeleton.ts
packages/carbon-web-components/src/components/progress-indicator/progress-step.ts
packages/carbon-web-components/tests/spec/progress-indicator_spec.ts

#10092
This PR updates the progress switcher to match the v11 React component
**New**
- `space-equally` property for nonvertical progress indicator
**Changed**
- update and fix skeleton state
- sync attributes to match React props
**Removed**
- extraneous styles

feat(progress-indicator): sync with v11

---

packages/carbon-web-components/package.json

Fixes #10564 
This updates the NPM export fields for the `@carbon/web-components` package.
**New**
**Changed**
- update NPM export path for `@carbon/web-components`
**Removed**

chore(node): update component exports

---

packages/carbon-web-components/src/components/ui-shell/header-menu.ts
packages/web-components/src/components/masthead/megamenu-top-nav-menu.ts
packages/web-components/src/components/masthead/top-nav-menu.ts

Cherry pick changes from https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/10555
The Cloud masthead (and other mastheads) simple menus were not closing upon hitting Esc if focus was inside the submenu. This PR fixes that. 
**Changed**
- Adds ability to close Cloud Masthead non-megamenu (and all non-megamenus) with Esc key, just as megamenus already do.
**New**
**Changed**
**Removed**

fix(masthead): Esc to close Cloud Masthead (#10555)

---

packages/web-components/src/components/leaving-ibm/leaving-ibm.scss

Fixes #7416 
Update body content padding in `leaving-ibm` component.
**New**
**Changed**
- update body content padding
**Removed**

fix(leaving-ibm): update body content padding

---

packages/styles/scss/components/pricing-table/_pricing-table.scss
packages/styles/scss/components/structured-list/_structured-list.scss
packages/web-components/src/components/pricing-table/__stories__/pricing-table.stories.ts
packages/web-components/src/components/structured-list/__stories__/structured-list.stories.ts
packages/web-components/src/components/structured-list/structured-list-cell.ts

https://jsw.ibm.com/browse/ADCMS-3264
https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10499
Related pull request: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/10550
This is a patch PR against the release branch. We've discussed that we will get this feature into the upcoming release. See Slack: https://ibm-marketing-comms.slack.com/archives/G01LKRP5RB6/p1687529564522979
Allows a user of the pricing table to opt in to their slotted text to be shown alongsizde an icon within a pricing table cell.
**New**
- `dds-pricing-table-cell` now supports an `icon-text` attribute that when set will signal slotted text nodes to display next to the selected icon. If the icon attribute is not set, no change.

feat(pricing-table): support combined checkmark with copy (#10550)

---

packages/carbon-web-components/src/components/tabs/defs.ts
packages/carbon-web-components/src/components/tabs/tab-skeleton.ts
packages/carbon-web-components/src/components/tabs/tab.ts
packages/carbon-web-components/src/components/tabs/tabs-skeleton.ts
packages/carbon-web-components/src/components/tabs/tabs-story.scss
packages/carbon-web-components/src/components/tabs/tabs-story.ts
packages/carbon-web-components/src/components/tabs/tabs.scss
packages/carbon-web-components/src/components/tabs/tabs.ts
packages/carbon-web-components/tests/spec/content-switcher_spec.ts
packages/carbon-web-components/tests/spec/tabs_spec.ts

#10086
This PR updates the tabs to match the upstream React version
Note: still missing icon-only variants
**New**
- implement overflow tabs
**Changed**
- update stories
**Removed**
- remove unused styles and breakpoints
- remove dropdown mobile tabs logic

feat(tabs): implement overflow tabs and sync with v11

---

packages/carbon-web-components/src/components/multi-select/multi-select.scss

[Filterable doesn't work in multi-select#9729](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/9729)
The filterable option for `multi-select` doesn't appear to work because the styles to hide the options are not coming through when pulling in the package externally outside of storybook.
You can see it currently doesn't appear to filter in this codesandbox: https://codesandbox.io/p/sandbox/dazzling-burnell-4my6t8
Moving the selector out of the scope should fix this. 
**Changed**
- use separate selector rule when referencing the filterable attribute

fix(multi-select): move filterable attribute out of scope for styles

---

packages/carbon-web-components/src/components/button/button.ts
packages/carbon-web-components/src/components/code-snippet/code-snippet.ts
packages/carbon-web-components/src/components/copy-button/copy-button.ts
packages/carbon-web-components/src/components/pagination/pagination.ts
packages/carbon-web-components/src/components/tile/tile-group.ts

Proposal to fix #10602
Replace `className` property to avoid override native property:
https://developer.mozilla.org/en-US/docs/Web/API/Element/className
**Changed**
- fix: replace `className` property to avoid override native property

fix: replace `className` property to avoid override native property

---

packages/styles/scss/components/masthead/_masthead-l1.scss
packages/web-components/src/components/masthead/masthead-l1.ts
packages/web-components/tests/e2e-storybook/cypress/integration/masthead/masthead-default.e2e.js
packages/web-components/tests/e2e-storybook/cypress/integration/masthead/masthead-l1.e2e.js

**1. Fixes text overflows in dropdowns:**
Before:
After:
**2. Masks the menu item track, which uses absolute positioning to make it scrollable, when it overflows the menu container.**
Before: 
After:
**Changed**
- Updates Masthead L1 styles to prevent text overflow in dropdowns.
- Updates Masthead L1 styles to prevent menu items from overflowing menu bar on the horizontal axis.

fix(masthead-v2): prevent text overflow in L1 dropdown items

---

packages/carbon-web-components/src/components/button/button.scss

Fix #10428
Match the `part="button"` size with the host.
**Changed**
- fix(button): match the `part="button"` size with the host

fix(button): match the `part="button"` size with the host

---

packages/carbon-web-components/src/components/button/button.scss

Fix #10600
Add the missed `slot="icon"` styles
**Changed**
- fix(button): add the missed `slot="icon"` styles

fix(button): add the missed `slot="icon"` styles

---

packages/carbon-web-components/src/components/button/button.ts
packages/carbon-web-components/src/components/code-snippet/code-snippet-story.ts
packages/carbon-web-components/src/components/code-snippet/code-snippet.ts
packages/carbon-web-components/src/components/copy-button/copy-button.ts
packages/carbon-web-components/src/components/copy/copy.ts
packages/carbon-web-components/src/components/icon-button/icon-button.ts
packages/carbon-web-components/src/components/overflow-menu/overflow-menu.ts
packages/carbon-web-components/src/components/tooltip/tooltip-story.mdx
packages/carbon-web-components/src/components/tooltip/tooltip-story.ts
packages/carbon-web-components/src/components/tooltip/tooltip.ts

#10599 
The overflow-menu wasn't passing the accessibility checker because of a missing label. Digging deeper most buttons with tooltips were not passing the accessibility checker for the same reason
Updated the following components:
- overflow-menu
- button (icon variation)
- icon-button
- code-snippet
- copy
- copy-button
- tooltip
**New**
- added an aria-label where needed to support the accessibility checker

fix(buttons): added missing aria-labels for tooltip-buttons

---

packages/carbon-web-components/src/components/ui-shell/side-nav.ts

[[cwc-v2]: The cds-side-nav-menu collapses when click outside#10612](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10612)
Issue: 
- open side-nav-menu
- click outside of the side-nav
- see that the side-nav-menu closes
https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/1007051/f096c227-0f15-417a-8c3f-745cd4e7781c
**Changed**
- only toggle the `expanded` for certain collapse modes so that the menu still collapses in mobile view when user focuses out
- remove the `updatedSideNavMenuForceCollapsedState()` from firing whenever the expand toggles - not necessary to fire then

fix(ui-shell): keep side-nav-menu open when on focusout

---

packages/styles/gulp/tasks/watch.js

Fixes `gulp watch` task. `yarn gulp watch` works now.
**New**
**Changed**
- fix `gulp watch` task for `@carbon/ibmdotcom-styles` package
**Removed**

chore(gulp): fix gulp watch

---

packages/carbon-web-components/src/components/ui-shell/header-nav-item.ts
packages/carbon-web-components/src/components/ui-shell/side-nav-link.ts

None
Add `target` and `rel` properties to ui-shell links.
**New**
- feat(ui-shell): add `target` and `rel` properties to links

feat(ui-shell): add `target` and `rel` properties to links

---

packages/carbon-web-components/src/components/button/button.scss

#10691 
ghost button with icon wasn't aligning correctly 
Showing fixed button with hover state in 2xl size
**New**
**Changed**
- added styles to temporarly resolve this, but eventually should be able to remove once we can upgrade `@carbon/styles`
**Removed**

fix(ghost-button): icon alignment for larger sizes

---

.github/workflows/deploy-cwc-v2-rc.yml

Change `@carbon/web-components` staging deploy from `beta` to `rc` for gh-pages.
**New**
**Changed**
**Removed**

chore(gh): deploy `rc` to gh-pages

---

packages/carbon-web-components/src/components/ui-shell/header.scss
packages/carbon-web-components/src/components/ui-shell/ui-shell-story.ts

#10711
updates so the popover for the header-global-action buttons are visible when right panel is visible 
**Changed**
- added z-index increase

fix(ui-shell): global action button popover visibility

---

docs/cwc-v2-migration.md

[[docs]: update @carbon/web-components documentation for v2#10676](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10676)
Adding migration doc for Carbon Web Components v2. We can fill in as we go through all the components we sync-ed
**New**
- migration doc for cwc v2

docs(migration): add migration doc for cwc v2

---

packages/web-components/tests/e2e-storybook/cypress/integration/cta-block/cta-block.e2e.js

E2E test for `cta-block` randomly fails, disabling for now.
**New**
**Changed**
**Removed**

chore(e2e): disable cta-block e2e

---

packages/carbon-web-components/package.json
packages/carbon-web-components/tools/fix-carbon-sass-imports.js

#10705 
This PR adds a Node.js script that updates Carbon Sass module import paths based on paths manually specified in a Map. The script currently updates imports for Carbon colors and feature flag modules and runs automatically on after `install` and before `build` scripts. After running the script, the `build` script should no longer emit any errors and build artifacts should reappear in `dist` which will also resolve issues with missing CDN resources
**New**
- Carbon Sass import fixer
- `postinstall` npm script
- `prebuild` npm script

fix: add carbon sass import updater

---

packages/carbon-web-components/package.json

The imports script was causing errors when the package is pull into an external app - remove the script from `postinstall`
**New**
**Changed**
**Removed**

fix(script): remove postinstall script and add import script to package.json files

---

packages/carbon-web-components/src/components/tag/tag.scss

Fix the red tag styles.
From:
To:
**Changed**
- fix(tag): fix the red tag styles

fix(tag): fix the red tag styles

---

packages/carbon-web-components/src/components/data-table/table-row.ts
packages/carbon-web-components/src/components/progress-indicator/progress-step-skeleton.ts

Update import paths for Carbon icons
**New**
**Changed**
- Carbon icon paths updated for `progress-step-skeleton` and `table-row`
**Removed**

chore(icons): update icon imports

---

packages/carbon-web-components/src/components/ui-shell/side-nav.ts

#10709
Close side-nav when click on the overlay.
**New**
- feat(ui-shell): close side-nav when click on the overlay

feat(ui-shell): close side-nav when click on the overlay

---

packages/carbon-web-components/src/globals/decorators/carbon-element.ts

With the current decorator, the components can't be imported into the server because of the `window.` reference.
There was also a lot of code that wasn't being used.
Original Lit decorator:
https://github.com/lit/lit/blob/main/packages/reactive-element/src/decorators/custom-element.ts
**Changed**
- fix: update the carbon-element decorator

fix: update the carbon-element decorator

---

packages/web-components/.storybook/preview.ts

none
fixes skip to content in storybook uses `cds` prefix
**Changed**
- bx to cds

fix(skip-to-content): v2 storybook

---

packages/carbon-web-components/tools/fix-carbon-sass-imports.js

The build for CWC now complains about the `@carbon/motion` package path, adding the package to the script so it can pull from the root

chore(tools): add motion package to import sass script

---

packages/styles/scss/components/content-item-horizontal-media/_content-item-horizontal-media.scss

Closes #10841
The Content Item horizontal component with featured media displayed an overflow of its media on mobile (really any breakpoint below large). This was due to the media being set to span 12 cols on larger screens, when the grid is actually 12 cols wide, but then on smaller screens the grid is 4 cols. The media was updated to span 4 cols to match its grid on screens smaller than "lg".
**Changed**
- updates the styles package for Content Item Horizontal Featured Media to set media's column span to match its grid.

fix(content-item-horizontal): fix media overflow on mobile

---

docs/cwc-v2-migration.md
packages/carbon-web-components/src/components/code-snippet/code-snippet-story.ts
packages/carbon-web-components/src/components/code-snippet/code-snippet.ts

Closes #10839 
Closes #10733
fix tooltip-content for inline codesnippet, so adopters can just use the property 
Also updated migration docs

fix(code-snippet): tooltip-content prop and migration docs

---

packages/carbon-web-components/.storybook/manager.js
packages/carbon-web-components/.storybook/preview.js
packages/carbon-web-components/.storybook/theme.js

none
updates cwc storybook v2 so it shows the correct version at the top header
**New**
**Changed**
**Removed**

fix(storybook): header theme

---

packages/web-components/docs/coding-conventions.md

Closes #10278 
This PR updates documentation to include information on the `@carbonElement` decorator and its usage. This will help ensure contributors use the decorator correctly and understand its purpose. 
**New**
- Added a 'Custom Elements' heading to documentation; added information about `@carbonElement` decorator in a subheading to that.

fix(docs): add documentation regarding the carbonElement decorator

---

packages/web-components/src/components/card-group/__stories__/card-group.stories.react.tsx
packages/web-components/src/components/card-group/__stories__/card-group.stories.ts
packages/web-components/src/components/lightbox-media-viewer/lightbox-video-player-composite.ts

none
`<dds-video-cta-container>` can handle multiple Kaltura video embed requests within the same modal/lightbox by slotting a `<div>` per video into the same `<dds-lightbox-video-player>`. When the modal is activated by user interaction, the current video ID is sent along, and the `<dds-lightbox-video-player-composite>` sets `hidden` on the `<div>`s that don't have a matching ID. This works great when there is only one `<dds-video-cta-container>`.
The problems start when multiple video containers are used throughout the document. Each creates some number modal render root elements depending on the structure of the content, and the lightbox composite uses `document.querySelector('dds-lightbox-video-player')` to find the video player when trying to hide embedded Kaltura videos that are not …

fix(lightbox-video-player): use more reliable reference to video player

---

packages/carbon-web-components/src/components/pagination/page-sizes-select.ts
packages/carbon-web-components/src/components/pagination/pagination-story.ts

Closes https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10553
https://jsw.ibm.com/browse/ADCMS-3821
Fixes a bug where the initial value of the `page-size` attribute on the `<bx-pagination>` component previously did not set the correct `<option>` element within the `<bx-page-sizes-select>` component.
**Changed**
- Updated the `slotchange` handler for the `<bx-page-sizes-select>` component to set the `selected` attribute when applicable.
* Navigate to Pagination > Default story
* Enter a different value for "Number of rows per page (page-size)", using one of the other values in the dropdown, eg. 20 or 30
* Click the "Open canvas in new tab" button, this will initiate the story with the set value for `page-size` to test the bug
* Should see the value you set for the items …

fix(pagination): mark selected option in page-sizes-select component

---

packages/carbon-web-components/src/components/combo-box/combo-box-story.ts
packages/carbon-web-components/src/components/combo-box/combo-box.scss

Closes #10901 
combox fix outline and hover on items
**Changed**
- storybook update to use width: 300px
- update padding for outline
- add hover fix

fix(combo-box): outline/hover issues

---

packages/web-components/src/components/notice-choice/__stories__/notice-choice.stories.ts
packages/web-components/src/components/notice-choice/notice-choice.ts

Cherry pick of https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/10917 for patch release.
**New**
-  A new web component to create a notice & choice user interface.
**Changed**
-  Notice and Choice content loaded by languages.
-   Set the default language to English.
-  Gain access to the hidden email and phone fields. 
**Removed**
- Postal option removed from new notice and choice version 
**New**
**Changed**
- {{changed …

fix(notice-choice): fixed onclick hidden values (#10917)

---

.github/workflows/ci-check.yml
packages/web-components/package.json

This updates deprecated folder mappings in `@carbon/ibmdotcom-web-components` which was causing applications using Node 18+ to fail builds.
**New**
**Changed**
- update folder mapping exports in `package.json`
**Removed**

fix(package): update web components component exports

---

docs/dotcom-v2-migration.md
packages/styles/scss/components/back-to-top/_back-to-top.scss

Closes #10721 
This PR fixes the border width for the back to top component
**Changed**
- remove unneeded `border-color` rule

fix(back-to-top): remove border-color rule

---

.github/workflows/add-to-project.yml
.github/workflows/ci-check.yml
.github/workflows/codeql-analysis.yml
.github/workflows/dco.yml
.github/workflows/e2e-tests-parallel.yml
.github/workflows/e2e-tests.yml

Downgrades the GH action Ubuntu version to `20.04` from `latest`. In the latest version `chrome-headless` binary fails, causing tests to exit prematurely.
**New**
**Changed**
- downgrade `ubuntu-latest` to `ubuntu-20.04` in all GH actions
**Removed**

chore(gh): downgrade ubuntu to version 20.04

---

packages/carbon-web-components/package.json

N/A
Working on Carbon for AI, I'm trying to pull in CWC v2 styles and extend them but running into issues accessing them (ie. `@use "@carbon/web-components/scss/components/button/button";`). This PR adds the `scss` files to the `exports` field so they can be pulled in.
**New**
- add `scss` files under exports in package.json

feat(package.json): add entry point for cwc scss files

---

packages/web-components/src/components/video-player/video-player.ts

[ADCMS-4128](https://jsw.ibm.com/browse/ADCMS-4128)
As discovered in ADCMS-4128, the video-player component does not always update to the correct kaltura thumbnails. This was found on https://www.ibm.com/think/videos, but replication and diagnosis of the issue has been difficult.
The blurry thumbnails were added in #7914 and are a function of the default thumbnail width [being set to 3px](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/packages/web-components/src/components/video-player/video-player-composite.ts#L230-L234). This allows for a softer, more deliberate blurring effect. These thumbnails are intended to be replaced by thumbnails that are the perfect size to help optimize memory/network requests.
Unfortunately, as we see on the Think Videos page, this …

fix(video-player): move updateThumbnailUrl callback after updateComplete

---

packages/carbon-web-components/src/components/input/input.ts
packages/web-components/src/components/footer/combo-box.ts
packages/web-components/src/components/footer/language-selector-desktop.ts
packages/web-components/src/components/footer/language-selector-mobile.ts

Closes #10885 
Removes the `@internal` decorator from `language-selector` which was preventing output to the `.d.ts`. Also removes unneeded code from `bx-input`.
**New**
**Changed**
**Removed**
- `@internal` decorator
- unused getter/setter from `bx-input`

fix(language-selector): remove internal decorator

---

packages/web-components/src/components/masthead/masthead-l1.ts

The previous implementation of L1 submenu toggling relied on the toggle button's `nextElementSibling` returning specifically the `div` that contains the menu items. However, some teams are loading analytics and/or testing scripts that modify the markup that is delivered by the component, causing a different element to be returned instead, and thusly preventing the L1 menu items from opening.
Visit the deploy preview's Masthead with L1 story and verify the dropdown menus still open and close as expected.
**Changed**
- L1 submenu toggle buttons use a more explicit selector to target the DOM elements necessary for opening and closing their respective submenus.

fix(masthead-v2): use more explicit selector in dropdown toggle action

---

packages/styles/scss/components/masthead/_masthead.scss
packages/web-components/src/components/masthead/masthead-composite.ts

The visible parts of the masthead are `position: fixed;`, which prevents them from being in the document flow. This forces adopters to manually add spacing to their page content so the masthead doesn't overlap. We provide the `--dds-sticky-header-height` variable via the StickyHeader utility as a value to use, but this changes as the user scrolls, creating a potentially unwanted parallax effect.
To overcome this, we force the masthead's container into the document flow by giving it a height equal to its visible parts' height. This avoids the parallax effect, and adopters should only need to add the spacing they want between their content and the masthead, rather than solving for the masthead's height in some way.
Visit deploy preview Stories for the masthead with and without the L1. In …

feat(masthead-v2): add masthead to document flow

---

packages/carbon-web-components/src/components/tabs/tabs.ts

#10952
This PR updates `tabs` to remove a conditional check for overflow button rendering. These changes should allow for megamenu tabs to continue functioning as expected in #10952 while resolving a regression in Carbon Web Components tabs which was affecting Dotcom v2 work.
**Removed**
- remove render check in overflow button render methods

fix(tabs): remove overflow button conditional rendering check

---

packages/styles/scss/components/video-player/_video-player.scss

none
looks like some v2 changes accidentally effected the video-player alignment. This should bring it back centered
before: 
after:
**Changed**
- set padding to 0

fix(video-player): v2 alignment

---

.github/workflows/publish-v2alpha-cdn.yml

This is a workflow for publishing a v2 alpha CDN of Carbon for IBM.com web components. This is a manually triggered workflow. 
This was created as we were seeing memory issues running on Jenkins.
**New**
- `publish-v2alpha-cdn.yml`

feat(github-actions): add workflow for publishing masthead v2 alpha

---

packages/web-components/gulp-tasks/build/modules/icons.js

Fix `spread.js` import path
**New**
**Changed**
**Removed**

chore(gulp): fix spread import path

---

packages/carbon-web-components/package.json
yarn.lock

feat(cwc): bump package to 2.0.2-rc.1

---

packages/web-components/src/components/masthead/masthead-container.ts

Closes https://github.ibm.com/webstandards/ibm-dotcom-translations/issues/973
We weren't conditionally accessing all the data that is sourced from the translations CDN endpoint before mapping it to props. In cases where data is not where expected, it throws an undefined error and prevents the whole L0 from appearing. 
**Changed**
- Prevents L0 from failing to appear if certain nav data is not present where expected.
See the L0 doesn't show up in the latest alpha version's Storybook example: https://carbon-design-system.github.io/carbon-for-ibm-dotcom/masthead-v2/web-components/iframe.html?args=&id=components-masthead--with-l-1&viewMode=story&cc=ie&lc=en. You'll see an error in the console, too: `Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'signedin')`. …

fix(masthead-v2): do not fail if object data does not exist

---

packages/web-components/src/components/card/card.scss
packages/web-components/src/components/cta/card-cta.ts
packages/web-components/src/components/feature-section/__stories__/feature-section.stories.ts

Closes #11159
[Jira ticket](https://jsw.ibm.com/browse/ADCMS-4274)
Expand options in the Feature section story to include all supported CTA types. Fix a bug when using the video CTA type, where a double header would appear.
**Changed**
- Expand options in the Feature section story to include all supported CTA types.
- Fix a bug when using the video CTA type, where a double header would appear.

[Feature Section]: Expand the availability of CTA types in feature card sections

---

packages/carbon-web-components/src/components/radio-button/radio-button-group.ts
packages/carbon-web-components/src/components/radio-button/radio-button.scss
packages/carbon-web-components/src/components/radio-button/radio-button.ts
packages/carbon-web-components/src/components/slug/slug-example-story.ts
packages/carbon-web-components/src/components/slug/slug-story.scss
packages/carbon-web-components/src/components/tile/tile.scss

Closes #11141 
Adds slug slot to radio-button and radio-button-group
**New**
- slug option to radio-button and radio-button-group
- radio-button slug changes size depending on slug kind
**Changed**
- changing the `id` and `query` logic allowed the modal to appear from the slug
- fix error in radio-button invalid where the `checked` radio-button border wasn't turning red
- cleaned up slug-story.scss to use tokens
**Testing**
Experimental -> Slug -> Examples -> Radio Button

feat(radio-button): slug

---

packages/web-components/src/components/masthead/masthead-container.ts
packages/web-components/src/components/notice-choice/notice-choice.ts

Merges bug fix from masthead v2 alpha's dev branch into its release branch.

chore(masthead-v2): merge latest from alpha dev into alpha main

---

packages/carbon-web-components/src/components/checkbox/checkbox-story.ts
packages/carbon-web-components/src/components/slug/slug-example-story.ts
packages/carbon-web-components/src/components/slug/slug-story.scss
packages/carbon-web-components/src/components/slug/slug.scss
packages/carbon-web-components/src/components/tag/tag-story.ts
packages/carbon-web-components/src/components/tag/tag.scss
packages/carbon-web-components/src/components/tag/tag.ts

Closes #11143 
Adds slug to `cds-tag` component
**New**
- add new slot for icon
- new story for tag with slug
**Changed**
- set default in storybook for `tag` size to be medium
- add styles specific to slug within tag to the slug stylesheet
**Removed**
- `hasCustomIcon` property not needed - looking at Carbon React, the close icon doesn't get replaced
**Testing**
Experimental -> Slug -> Examples -> Tag

feat(tag): slug

---

.github/workflows/ci-check.yml
packages/carbon-web-components/src/components/checkbox/checkbox-story.ts
packages/carbon-web-components/src/components/data-table/_table-core.scss
packages/carbon-web-components/src/components/data-table/_table-selection.scss
packages/carbon-web-components/src/components/data-table/_table-sizes.scss
packages/carbon-web-components/src/components/data-table/_table-sort.scss
packages/carbon-web-components/src/components/data-table/data-table.scss
packages/carbon-web-components/src/components/data-table/table-header-cell.ts
packages/carbon-web-components/src/components/data-table/table-row.ts
packages/carbon-web-components/src/components/data-table/table.ts
packages/carbon-web-components/src/components/slug/slug-data-table-story.ts
packages/carbon-web-components/src/components/slug/slug-example-story.ts
packages/carbon-web-components/src/components/slug/slug-story.scss
packages/carbon-web-components/src/components/slug/slug.scss
packages/carbon-web-components/src/components/tag/tag-story.ts
packages/carbon-web-components/src/components/tag/tag.scss
packages/carbon-web-components/src/components/tag/tag.ts
packages/web-components/package.json
yarn.lock

**New**
**Changed**
**Removed**

chore(merge): conflict from cwc-2.1.0

---

.github/workflows/publish-v2alpha-cdn.yml

Re-adds workflow that allows Innovation Team to build masthead v2 alpha CDN bundles. Workflow originally authored by @jeffchew in https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/11153.
**New**
- Restores masthead v2 alpha CDN bundle publishing workflow.

feat(github-actions): restore workflow for publish masthead v2 alpha

---

packages/web-components/src/components/masthead/masthead-l1.ts

Fixes L1 mobile dropdowns.
**Changed**
- Ensures L1 dropdowns, including submenus, work on mobile.

fix(masthead-v2): ensure L1 dropdown targets exist

---

packages/web-components/src/components/masthead/masthead-l1.ts
packages/web-components/src/components/notice-choice/notice-choice.ts

Merges bug fix from masthead v2 alpha's dev branch into its release branch.

chore(masthead-v2-alpha): merge alpha dev changes into alpha main

---

packages/carbon-web-components/package.json

Closes #11274 
Remove the `node` exports field that was pointing to the `lib` folder containing only the source map files.
**Removed**
- `node` exports field

fix(package.json): remove node exports field

---

packages/web-components/src/components/masthead/top-nav.ts

Resolves https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/11267
Provides an overridable `aria-label` for the top nav.
Visit the [deploy preview masthead story](https://ibmdotcom-webcomponents.s3.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/11269/index.html?path=/story/components-masthead--default) and verify the `<nav>` element within the `<dds-top-nav>` component has an `aria-label`.
**New**
- Adds a `navLabel` property to `DDSTopNav` that sets an `aria-label` on the `<nav>` element in the shadow root.

fix(masthead-v2): provide accessible nav label

---

packages/utilities/src/utilities/StickyHeader/StickyHeader.js

Safari treats the bounce back from an "overscrolled" position as a scroll event. This can cause elements to be scrolled out of view when a user, for example, rapidly swipes to scroll to the top of the document.
https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/12532727/097c055e-d039-4a9b-b23d-b8e5a2100da4
This PR fixes this interaction by limiting how far up the scroll is considered to be. This effectively ignores overscroll.
https://github.com/carbon-design-system/carbon-for-ibm-dotcom/assets/12532727/344ffe1b-1354-4c3d-b485-e83039eb782c
Visit the Web Components deploy preview's [Dotcom Shell With L1 story](https://ibmdotcom-webcomponents.s3.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/11266/index.html?path=/story/components-dotcom-shell--with-l-1) in …

fix(sticky-header): prevent negative overscroll from hiding stuck elements

---

packages/utilities/src/utilities/StickyHeader/StickyHeader.js

Cherry picks 51015ed into `v1`.

chore(sticky-header): cherry pick "prevent negative overscroll" into v1

---

packages/carbon-web-components/src/components/date-picker/range-plugin.ts

Closes #none
fixes old `on` import and changes it local import

fix(date-picker): range plugin on import

---

packages/carbon-web-components/src/components/input/input.ts
packages/carbon-web-components/src/components/number-input/number-input.ts

Closes #11391
Ensures `bx-input` value property works as intended
**Changed**
- now uses `this.value` instead of `this._value` as the latter isn't used anywhere
**Removed**
- `_value` internal property

fix(input): display default value properly

---

.github/workflows/percy-update-base.yml
packages/carbon-web-components/package.json
packages/web-components/package.json

The `build-storybook` is running twice since it is included in the `visual-snapshot` command. This removes the extra build command.
**New**
**Changed**
**Removed**
- remove `build-storybook` from `visual-snapshot`

chore(deps): remove duplicate build storybook from percy command

---

packages/carbon-web-components/src/components/checkbox/checkbox.ts

Closes #11345
Accessibility issue on checkbox:
The ARIA attributes `aria-checked` are not valid for the element <input> with implicit ARIA role "checkbox"
**Removed**
- Removed `aria-checked` attribute from the input field.

Fix(checkbox): a11y issue v1

---

packages/web-components/src/components/masthead/masthead-composite.ts

Closes
[JIRA](https://jsw.ibm.com/browse/ADCMS-4398)
Adding `position: relative` style to the masthead container so it stacks properly.

fix(masthead): change container position to relative

---

packages/web-components/src/components/background-media/__stories__/background-media.stories.ts
packages/web-components/src/components/leadspace/__stories__/leadspace.stories.ts

When capturing visual snapshots, Percy can (will) be inconsistent if the component contains auto-playing videos. This is because it is impossible for Percy to take the snapshot at the exact same frame every time, resulting in frequent visual diffs. This PR skips components with auto-playing videos.
**New**
**Changed**
- skip components with auto-play videos
**Removed**

chore(percy): skip components with autoplay video

---

packages/services-store/src/types/translateAPI.ts
packages/styles/scss/components/masthead/_masthead-l1.scss
packages/web-components/src/components/masthead/__stories__/masthead.stories.ts
packages/web-components/src/components/masthead/masthead-l1.ts

Backports https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/11403 into alpha branch.
The AEM team asked for this feature, and they are still using the alpha masthead. This PR backports the feature so we can cut an alpha release for them to use while they prepare to upgrade to the full v2 release.

feat(masthead-v2-alpha): backport L1 CTA Contact Module integration

---

packages/carbon-web-components/src/components/data-table/table.ts

Closes #11483
Search is not working as expected with uppercase characters in query string.
**Changed**
- Updated the search logic to convert the query string as well as the main string to lowercase and then compare.

fix(datatable): search not working with uppercase characters in query

---

packages/carbon-web-components/src/components/data-table/table-header-cell.ts
packages/carbon-web-components/src/components/data-table/table.ts

Closes https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/11474
Passing `is-sortable` to `<cds-table-header-cell>` makes the column unsortable.
Column being unsortble is already fixed with [PR](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/11468)
But clicking on the sort icon makes all the columns sortable, this is fixed.
**Changed**
- `expandable` and `is-selectable` attributes mapped to proper variables. This was affecting the sorting action on individual columns.
- Updated the sort action to check if only specific columns are made sortable with `is-sortable` attribute and if so prevent other columns from showing sort icon.

fix(datatable): is-sortable not working with table column cell

---

packages/web-components/src/components/background-media/__stories__/background-media.stories.ts
packages/web-components/src/components/background-media/background-media.ts

none
We already had functionality built-in to the Background Media component that can optionally hide the gradient effect that overlays the media. This PR exposes that option to end users and documents the feature in Storybook.
**Changed**
- Exposes `DDSBackgroundMedia`'s `gradient-hidden` option that, when true, disables the gradient overlay.
Visit the Background Media stories in the deploy preview and verify the "hide gradient" checkbox functions as expected.

feat(background-media): expose gradient-hidden option

---

packages/web-components/src/components/footer/footer-composite.ts

Closes #11494
The locale modal button used to be working right until the v2 merge -- seems like Lit v2 decided to change the way it binds `this` to `@click` events, it now has to be explicit. So no matter how many times you were pressing the button to change the `openLocaleModal` boolean to true, it never changed the actual Footer's prop, it changed the **Button's** (nonexistent) prop instead 🤦 , so the modal rendering functions never ran.
**Changed**
- the locale modal button in the footer now binds `this` to its `@click` function to trigger the modal render functions properly

fix(footer): locale modal button now working

---

packages/carbon-web-components/.storybook/manager-head.html
packages/styles/scss/components/footer/_footer-logo.scss
packages/web-components/.storybook/manager-head.html
packages/web-components/src/components/footer/footer-composite.ts

Closes #11465 
**New**
- add `footer` to Storybook environments

chore(storybook): add dotcom footer

---

packages/carbon-web-components/src/components/tabs/tabs.scss
packages/styles/scss/components/tabs-extended-media/_tabs-extended-media.scss

Closes #11540 
The tab size had the incorrect height
**Changed**
- styles to use $spacing-08 instead of 09

fix(tabs): container size wrong

---

packages/carbon-web-components/src/components/tag/tag.scss

Closes [#10874](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10874)
filter tag `open` styles aren't coming through
**Changed**
- seperate the styles out

fix(filter-tag): v1 open not showing

---

packages/carbon-web-components/src/components/data-table/table.ts

Fix for an issue reported in the support channel
Using `is-sortable` attribute in Data table was causing console error in firefox browser.
**Changed**
- Updated the initial value of variable `columnIndex` which was causing the error.

fix(datatable): is sortable console error

---

packages/carbon-web-components/examples/codesandbox/autoalign/cdn.html
packages/carbon-web-components/examples/codesandbox/autoalign/index.html
packages/carbon-web-components/examples/codesandbox/autoalign/package.json

Closes # N/A
Codesandbox example was displaying errors - this PR adds the `.sassrc` file necessary for the styles to be imported correctly and adjustments to the click function for the popover as optional chaining isn't supported in the codesandbox example
**New**
**Changed**
**Removed**

fix(autoalign): fix autoalign CSB example

---

packages/web-components/docs/enable-rtl.md
packages/web-components/examples/codesandbox/usage/webpack-rtl/package.json

None.
This fixes the webpack-rtl example for v1, which is currently broken on account of `main` branch and `latest` and `canary` tags all pointing to v2.
**Changed**
- Update webpack-rtl example links and dependencies to v1

fix(webpack-rtl): pin dependencies to v1 for webpack-rtl example

---

packages/utilities/src/utilities/StickyHeader/StickyHeader.js

Closes #11588
[Jira ticket](https://jsw.ibm.com/browse/ADCMS-4307)
Fixes sticky behavior issue with TOC horizontal plus Dotcom shell at less than lg breakpoint.
1. Open the Dotcom shell > Default
2. Scroll the page
3. The Masthead should be sticky until it reaches the TOC, then the masthead should scroll away, while the TOC becomes sticky to the top.
4. Repeat at both `lg` and less than `lg` breakpoints
5. Repeat 1-4 with the Dotcom shell > With ToC horizontal  story
**Changed**
- TOC dotcom shell sticky behavior fixed at less than lg breakpoint.

fix(toc): adjust mobile selector to condition on layout

---

packages/carbon-web-components/src/components/side-panel/side-panel.ts

With reduce motion enabled the side panel was left in a state where it was waiting for a transition to end before completing the close. There is not transition with reduced motion, and as a result a transparent pane was left over the rest of the page.
This PR corrects that to ensure the side panel is correctly closed when reduced motion is enabled.
**Changed**
- packages/carbon-web-components/src/components/side-panel/side-panel.ts

fix: a11y - ensure side panel closes properly with reduced motion

---

packages/web-components/src/components/card-group/card-group.ts

Closes https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/11605
JIRA  [ADCMS-4691](https://jsw.ibm.com/browse/ADCMS-4691) 
Fix for the  big extra unexpected space on cards between heading and paragraph.
**Changed**
Changing the card group script so it adds `tagGroupHeight`  as margin-botton to paragraphs instead of  headings

fix(card-group):change tagGroupHeight target Element

---

packages/web-components/docs/carbon-cdn-style-helpers.md

I noticed that there is an identical doc for Carbon for IBM.com in regards to the CSS grid links, so this adds this here.
**Changed**
- CSS Grid docs (CDN links)

chore(cdn): add CSS grid CDN urls (carbon for ibm.com)

---

packages/web-components/tests/e2e-storybook/cypress/integration/masthead/masthead-authenticated.e2e.js
packages/web-components/tests/e2e-storybook/cypress/integration/masthead/masthead-custom-search.e2e.js
packages/web-components/tests/e2e-storybook/cypress/integration/masthead/masthead-default.e2e.js
packages/web-components/tests/e2e-storybook/cypress/integration/masthead/masthead-l1.e2e.js
packages/web-components/tests/e2e-storybook/cypress/integration/masthead/masthead-platform.e2e.js
packages/web-components/tests/e2e-storybook/cypress/integration/masthead/masthead-scoped-search.e2e.js
packages/web-components/tests/e2e-storybook/cypress/integration/masthead/masthead-search-onload.e2e.js
packages/web-components/tests/e2e-storybook/cypress/integration/masthead/masthead.e2e.js

Closes # 
ADCMS-4576 | https://jsw.ibm.com/browse/ADCMS-4576
There were some gaps in our tests for the masthead and they're now fixed:
- tests were using the wrong prefix, trying to access elements that had their semantics changed
- all prefixes are now grouped in an object for better maintenance
- fixed lots of tests that were not working
- added mobile test cases for the L1

chore(masthead-tests): updating/fixing masthead cypress tests

---

packages/web-components/.storybook/main.js
packages/web-components/src/components/leadspace/leadspace.ts

Closes #11690 
https://jsw.ibm.com/browse/ADCMS-4848
Updates leadspace background gradient stops to use explicit closing tabs. Previously gradient stops were authored as self-closing tabs which seem to render as nested stops
Replace the tagged releases in [this codepen](https://codepen.io/andy-blum/pen/oNOEgxN/c58d6ab48ee80510e0c8124a535e7e5e) with the preview CDN URLs
**Changed**
- Fixes a bug where leadspace gradients don't render correctly

fix(leadspace): be explicit about svg closing tags

---

packages/carbon-web-components/package.json
packages/services/package.json
packages/services/telemetry.yml
packages/styles/package.json
packages/utilities/package.json
packages/utilities/telemetry.yml
packages/web-components/package.json
packages/web-components/telemetry.yml
yarn.lock

N/A
Updates `@ibm/telemetry-js` dependency to latest version in all instrumented packages and adds [JS Scope](https://github.com/ibm-telemetry/telemetry-config-schema?tab=readme-ov-file#js-scope) config to applicable packages.
**Changed**
***@carbon/web-components***
- Update `@ibm/telemetry-js` version to 1.5.0
***@carbon/ibmdotcom-services***
- Update `@ibm/telemetry-js` version to 1.5.0
- Add [JS Scope](https://github.com/ibm-telemetry/telemetry-config-schema?tab=readme-ov-file#js-scope) - functions only - config to `telemetry.yml`
***@carbon/ibmdotcom-styles***
- Update `@ibm/telemetry-js` version to 1.5.0
***@carbon/ibmdotcom-utilities***
- Update `@ibm/telemetry-js` version to 1.5.0
- Add [JS Scope](https://github.com/ibm-telemetry/telemetry-config-schema?tab=readme-ov-file#js-scope) …

feat: instrument with telemetry JS scope

---

packages/styles/scss/components/card-group/_card-group.scss
packages/web-components/src/components/card-group/card-group.scss
packages/web-components/src/components/card-group/card-group.ts

Closes #11755
We programmatically set borders & padding for cards within `<dds-card-group>` elements, and we've only been accounting for LTR writing directions. This PR uses logical properties so these borders and paddings look correct in RTL documents.
While working on this I noticed an issue where certain tracked elements could be undefined, causing an error that halts execution. Ultimately this resulted in the "empty" elements we generate for certain card groups to fail to be created, and the dark gray background appearing when it shouldn't. I fixed this with simple optional accessors.
Verify the borders and gaps between Cards appear correctly in [the Card Group story in the RTL deploy preview](https://ibmdotcom-web-components-rtl.s3.us-east.cloud-object-storage.appdomain.cloud/deploy-p …

fix(card-group): support RTL borders & padding

---

packages/styles/scss/components/masthead/_masthead-l1.scss
packages/utilities/src/utilities/StickyHeader/StickyHeader.js
packages/web-components/src/components/dotcom-shell/__stories__/data/content.ts
packages/web-components/src/components/dotcom-shell/__stories__/dotcom-shell.stories.ts
packages/web-components/src/components/leadspace-with-search/leadspace-with-search.ts
packages/web-components/src/components/masthead/masthead-l1.ts

none
Given the page uses both an L1 menu and a table of contents (ToC),
and the page is displaying at a mobile breakpoint,
and the ToC menu is the sticky element (i.e. stuck to the top of the viewport),
and the user scrolls up slightly to reveal the L1 dropdown,
and the user open the L1's dropdown menu,
then the dropdown menu gets hidden above the viewport, forcing the user to scroll up more to access it.
Instead, the top of L1 dropdown menu should be visible when opened.
This problem is occurring because the dropdown exists in the document flow, and the StickyHeader utility doesn't reset stuck elements' positions when the menu is opened. 
The easiest solution I found was to position the dropdown menu absolutely like most other dropdown menus you might encounter. This bypasses the tricky …

fix(masthead): ensure opened L1 mobile dropdown is visible while there is also a ToC

---

packages/web-components/src/components/content-block/content-block.ts
packages/web-components/tests/snapshots/dds-callout-with-media.md
packages/web-components/tests/snapshots/dds-content-block-cards.md
packages/web-components/tests/snapshots/dds-content-block-headlines.md
packages/web-components/tests/snapshots/dds-content-block-horizontal.md
packages/web-components/tests/snapshots/dds-content-block-media.md
packages/web-components/tests/snapshots/dds-content-block-segmented.md
packages/web-components/tests/snapshots/dds-content-block-simple.md
packages/web-components/tests/snapshots/dds-content-group-banner.md
packages/web-components/tests/snapshots/dds-content-group-cards.md
packages/web-components/tests/snapshots/dds-content-group-simple.md
packages/web-components/tests/snapshots/dds-cta-block.md

Replaces #11774 
[ADCMS-4976](https://jsw.ibm.com/browse/ADCMS-4976)
As per https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/11750
Adding a `part` attribute to the shadowroot's `.bx--content-layout` element so that it can be styled outside the shadow tree and have its padding manipulated if needed.

feat(cta-block): add CSS shadowpart

---

packages/services/package.json
yarn.lock

For some reason, lerna hasn't been bumping up the `@carbon/ibmdotcom-utilities` package within `services` package automatically. Bumping it manually for now to remove a security risk dependency.
**Changed**
- bump up `@carbon/ibmdotcom-utilities` package within `services`

chore(dependency): bump up utilities version in services package

---

packages/carbon-web-components/examples/codesandbox/basic/components/tearsheet/.babelrc
packages/carbon-web-components/examples/codesandbox/basic/components/tearsheet/.gitignore
packages/carbon-web-components/examples/codesandbox/basic/components/tearsheet/.sassrc
packages/carbon-web-components/examples/codesandbox/basic/components/tearsheet/cdn.html
packages/carbon-web-components/examples/codesandbox/basic/components/tearsheet/index.html
packages/carbon-web-components/examples/codesandbox/basic/components/tearsheet/package.json
packages/carbon-web-components/examples/codesandbox/basic/components/tearsheet/sandbox.config.json
packages/carbon-web-components/examples/codesandbox/basic/components/tearsheet/src/index.js
packages/carbon-web-components/examples/codesandbox/basic/components/tearsheet/src/styles.scss
packages/carbon-web-components/src/components/tearsheet/tearsheet-story.ts
packages/carbon-web-components/src/components/tearsheet/tearsheet.scss
packages/carbon-web-components/src/components/tearsheet/tearsheet.ts

Closes #11790
Adopter was running into an issue with the tearsheet not rendering when imported via npm in her application. This PR breaks out the nested styles which were not getting picked up. Also adds missing `modal` import in tearsheet
Also adds codesandbox example.
**New**
- codesandbox example for tearsheet
**Changed**
- break out tearsheet styles where attribute selectors were nested

fix(tearsheet): tearsheet styles and codesandbox example

---

packages/styles/scss/components/masthead/_masthead-l1.scss

Addresses internal ticket [ADCMS-5023](https://jsw.ibm.com/browse/ADCMS-5023)
Recent changes to the mobile L1 dropdown necessitated this visual change.
**Changed**
- Applies darker shadow under mobile L1 dropdown when open.
1. Visit the Dotcom Shell > With L1 story and reduce the viewport to a mobile size
2. Open the L1 dropdown and verify the shadow at the bottom is a dark, natural-looking shadow.

feat(masthead): use more visible box shadow

---

.github/workflows/percy-update-base.yml
packages/web-components/src/components/back-to-top/__stories__/back-to-top.stories.ts
packages/web-components/src/components/background-media/__stories__/background-media.stories.ts
packages/web-components/src/components/button/__stories__/button.stories.ts
packages/web-components/src/components/callout-with-media/__stories__/callout-with-media.stories.ts
packages/web-components/src/components/card-group/__stories__/card-group.stories.ts
packages/web-components/src/components/card-in-card/__stories__/card-in-card.stories.ts
packages/web-components/src/components/card-section-offset/__stories__/card-section-offset.stories.ts
packages/web-components/src/components/card/__stories__/card.stories.ts
packages/web-components/src/components/carousel/__stories__/carousel.stories.ts
packages/web-components/src/components/content-block-cards/__stories__/content-block-cards.stories.ts
packages/web-components/src/components/content-block-horizontal/__stories__/content-block-horizontal.stories.react.tsx
packages/web-components/src/components/content-block-media/__stories__/content-block-media.stories.ts
packages/web-components/src/components/content-block-mixed/__stories__/content-block-mixed.stories.ts
packages/web-components/src/components/content-block-segmented/__stories__/content-block-segmented.stories.ts
packages/web-components/src/components/content-block-simple/__stories__/content-block-simple.stories.ts
packages/web-components/src/components/content-block/__stories__/content-block.stories.ts
packages/web-components/src/components/content-group-simple/__stories__/content-group-simple.stories.ts
packages/web-components/src/components/content-item-row/__stories__/content-item-row.stories.ts
packages/web-components/src/components/dotcom-shell/__stories__/dotcom-shell.stories.ts
packages/web-components/src/components/feature-card/__stories__/feature-card.stories.ts
packages/web-components/src/components/feature-section/__stories__/feature-section.stories.ts
packages/web-components/src/components/global-banner/__stories__/global-banner.stories.ts
packages/web-components/src/components/image/__stories__/image.stories.ts
packages/web-components/src/components/leadspace-block/__stories__/leadspace-block.stories.ts
packages/web-components/src/components/leadspace/__stories__/leadspace.stories.ts
packages/web-components/src/components/logo-grid/__stories__/logo-grid.stories.ts

This temporarily disables several story snapshots that are timing out in Percy. Once the cause of this is determined they can be re-enabled.
**Changed**
- temporarily `disable` Percy snapshots for stories that are timing out in Percy
- temporarily remove `visual-snapshots` entirely from `@carbon/web-components` package
- update GH workflow snapshot command for `@carbon/ibmdotcom-web-components`
**Removed**

chore(percy): update config and story snapshots

---

packages/web-components/src/components/background-media/background-media.ts
packages/web-components/tests/snapshots/c4d-background-media.md
packages/web-components/tests/snapshots/c4d-callout-with-media.md
packages/web-components/tests/snapshots/c4d-content-block-cards.md
packages/web-components/tests/snapshots/c4d-content-block-headlines.md
packages/web-components/tests/snapshots/c4d-content-block-horizontal.md
packages/web-components/tests/snapshots/c4d-content-block-media.md
packages/web-components/tests/snapshots/c4d-content-block-segmented.md
packages/web-components/tests/snapshots/c4d-content-block-simple.md
packages/web-components/tests/snapshots/c4d-content-group-cards.md
packages/web-components/tests/snapshots/c4d-content-group-simple.md
packages/web-components/tests/snapshots/c4d-cta-block.md
packages/web-components/tests/snapshots/c4d-in-page-banner.md
packages/web-components/tests/snapshots/c4d-search-with-typeahead.md

[ADCMS-5036](https://jsw.ibm.com/browse/ADCMS-5036)
Adding shadow parts to Background Media component so that it can be styled outside the shadow tree.
Shadow parts added to Background Media. 
Snapshots updated

feat(background-media): add shadow parts to bg-media

---

packages/web-components/src/components/callout-quote/callout-quote.ts
packages/web-components/tests/snapshots/c4d-callout-quote.md
packages/web-components/tests/snapshots/c4d-callout-with-media.md
packages/web-components/tests/snapshots/c4d-content-block-cards.md
packages/web-components/tests/snapshots/c4d-content-block-headlines.md
packages/web-components/tests/snapshots/c4d-content-block-horizontal.md
packages/web-components/tests/snapshots/c4d-content-block-media.md
packages/web-components/tests/snapshots/c4d-content-block-segmented.md
packages/web-components/tests/snapshots/c4d-content-block-simple.md
packages/web-components/tests/snapshots/c4d-content-group-cards.md
packages/web-components/tests/snapshots/c4d-content-group-simple.md
packages/web-components/tests/snapshots/c4d-cta-block.md
packages/web-components/tests/snapshots/c4d-in-page-banner.md
packages/web-components/tests/snapshots/c4d-search-with-typeahead.md

[JIRA](https://jsw.ibm.com/browse/ADCMS-5039)
All non-slot elements in the shadow DOM should be given a unique "part" name allowing CSS to target and override component default styles. 
This PR is for the callout-quote component.
**New**
adding the part attribute to html elements inside the render methotd

feat(callout-quote): add shadow parts

---

packages/web-components/src/components/carousel/carousel.ts
packages/web-components/tests/snapshots/c4d-carousel.md

[ADCMS-5048](https://jsw.ibm.com/browse/ADCMS-5048)
#11673
Add shadow parts to the elements of carousel.
**New**
- Added shadow parts to the carousel component.

feat(carousel): add shadowparts

---

packages/web-components/src/components/content-block/content-block.ts
packages/web-components/tests/snapshots/c4d-callout-with-media.md
packages/web-components/tests/snapshots/c4d-content-block-cards.md
packages/web-components/tests/snapshots/c4d-content-block-headlines.md
packages/web-components/tests/snapshots/c4d-content-block-horizontal.md
packages/web-components/tests/snapshots/c4d-content-block-media.md
packages/web-components/tests/snapshots/c4d-content-block-segmented.md
packages/web-components/tests/snapshots/c4d-content-block-simple.md
packages/web-components/tests/snapshots/c4d-content-group-cards.md
packages/web-components/tests/snapshots/c4d-content-group-simple.md
packages/web-components/tests/snapshots/c4d-cta-block.md
packages/web-components/tests/snapshots/c4d-in-page-banner.md
packages/web-components/tests/snapshots/c4d-logo-grid.md

[ADCMS-5049](https://jsw.ibm.com/browse/ADCMS-5049)
#11673
Add shadow parts to the elements of content-block.
**New**
- Added shadow parts to the content-block component.

feat(content-block): add shadowparts

---

packages/web-components/src/components/content-item/content-item.ts

[ADCMS-5062](https://jsw.ibm.com/browse/ADCMS-5062)
Description
All non-slot elements in the shadow DOM should be given a unique "part" name allowing CSS to target and override component default styles. This is for the "content-item" component.
Changelog
New
Adding the shadow parts for the "content-item" component

feat(content-item): add shadow parts

---

packages/web-components/src/components/content-section/content-section.ts

[ADCMS-5064](https://jsw.ibm.com/browse/ADCMS-5064)
Description
All non-slot elements in the shadow DOM should be given a unique "part" name allowing CSS to target and override component default styles. This is for the "content-secion" component.
Changelog
New
Adding the shadow parts for the "content-section" component

feat(content-section): add shadow parts

---

packages/web-components/src/components/dotcom-shell/dotcom-shell.ts

[ADCMS-5142](https://jsw.ibm.com/browse/ADCMS-5142)
Description
All non-slot elements in the shadow DOM should be given a unique "part" name allowing CSS to target and override component default styles. This is for the "dotcom-shell" component.
Changelog
New
Adding the shadow parts for the "dotcom-shell" component

feat(dotcom-shell): add shadow parts

---

packages/web-components/src/components/cta/card-cta-footer.ts
packages/web-components/src/components/cta/card-cta.ts
packages/web-components/src/components/cta/cta.ts
packages/web-components/src/components/cta/feature-cta.ts

[ADCMS-5065](https://jsw.ibm.com/browse/ADCMS-5065)
Description
All non-slot elements in the shadow DOM should be given a unique "part" name allowing CSS to target and override component default styles. This is for the "cta" component.
Changelog
New
Adding the shadow parts for the "cta" component

feat(cta): add shadow parts

---

packages/web-components/src/components/card-section-offset/card-section-offset.ts
packages/web-components/tests/snapshots/c4d-card-section-offset.md
packages/web-components/tests/snapshots/c4d-card-section-simple.md
packages/web-components/tests/snapshots/c4d-content-group-simple.md
packages/web-components/tests/snapshots/c4d-content-item-row.md
packages/web-components/tests/snapshots/c4d-content-item.md
packages/web-components/tests/snapshots/c4d-content-section.md

[Internal](https://jsw.ibm.com/browse/ADCMS-5046)
Allows adopters to style elements in `<c4d-card-section-offset>`s' shadow roots via `part` attributes, which are selectable across shadow root boundaries.
**New**
- Adds `part` attributes to `<c4d-card-section-offset>`s' shadow root elements.

feat(card-section-offset): add shadow parts

---

packages/web-components/src/components/filter-panel/filter-panel-composite.ts
packages/web-components/src/components/filter-panel/filter-panel-input-select-item.ts
packages/web-components/src/components/filter-panel/filter-panel-input-select.ts
packages/web-components/src/components/filter-panel/filter-panel-modal.ts
packages/web-components/src/components/filter-panel/filter-panel.ts
packages/web-components/tests/snapshots/c4d-filter-panel-composite.md

[ADCMS-5146](https://jsw.ibm.com/browse/ADCMS-5146)
Description
All non-slot elements in the shadow DOM should be given a unique "part" name allowing CSS to target and override component default styles. This is for the "filter-panel" component.
Changelog
New
Adding the shadow parts for the "filter-panel" component

feat(filter-panel): add shadow parts

---

packages/web-components/src/components/expressive-modal/expressive-modal.ts
packages/web-components/tests/snapshots/c4d-expressive-modal.md
packages/web-components/tests/snapshots/c4d-locale-modal.md

[ADCMS-5143](https://jsw.ibm.com/browse/ADCMS-5143)
Description
All non-slot elements in the shadow DOM should be given a unique "part" name allowing CSS to target and override component default styles. This is for the "expressive-modal" component.
Changelog
New
Adding the shadow parts for the "expressive-modal" component

feat(expressive-modal): add shadow parts

---

packages/web-components/src/components/global-banner/global-banner.ts

[ADCMS-5148](https://jsw.ibm.com/browse/ADCMS-5148)
Description
All non-slot elements in the shadow DOM should be given a unique "part" name allowing CSS to target and override component default styles. This is for the "global-banner" component.
Changelog
New
Adding the shadow parts for the "global-banner" component

feat(global-banner): add shadow parts

---

packages/web-components/src/components/notice-choice/__stories__/notice-choice.stories.ts

Remove `notice-choice` from Percy snapshots.
**Changed**
- skip `notice-choice` in Percy snapshot tests

chore(percy): skip notice-choice component

---

packages/web-components/src/components/notice-choice/__stories__/README.stories.mdx
packages/web-components/src/components/notice-choice/notice-choice.ts

[ADCMS-5171](https://jsw.ibm.com/browse/ADCMS-5171)
Description
All non-slot elements in the shadow DOM should be given a unique "part" name allowing CSS to target and override component default styles. This is for the "notice-choice" component.
Changelog
New
Adding the shadow parts for the "notice-choice" component and documentation

feat(notice-choice): add shadow parts

---

packages/web-components/src/components/logo-grid/logo-grid-item.ts
packages/web-components/src/components/logo-grid/logo-grid.ts
packages/web-components/tests/snapshots/c4d-logo-grid.md

[JIRA](https://jsw.ibm.com/browse/ADCMS-5168)
**New**
Adding Shadow parts to the logo-grid component

feat(logo-grid):  add shadow parts

---

packages/web-components/src/components/image/image.ts
packages/web-components/tests/snapshots/c4d-image.md

[ADCMS-5150](https://jsw.ibm.com/browse/ADCMS-5150)
#11673
Add shadow parts to image component.
**New**
- Added shadow parts to the image component.

feat(image): add shadow parts

---

packages/web-components/src/components/lightbox-media-viewer/__stories__/README.stories.mdx
packages/web-components/src/components/lightbox-media-viewer/lightbox-image-viewer.ts
packages/web-components/src/components/lightbox-media-viewer/lightbox-media-viewer-body.ts
packages/web-components/src/components/lightbox-media-viewer/lightbox-media-viewer.ts
packages/web-components/src/components/lightbox-media-viewer/lightbox-video-player-composite.ts
packages/web-components/src/components/lightbox-media-viewer/lightbox-video-player.ts
packages/web-components/tests/snapshots/c4d-lightbox-image-viewer.md
packages/web-components/tests/snapshots/c4d-lightbox-video-player-composite.md
packages/web-components/tests/snapshots/c4d-lightbox-video-player.md

[ADCMS-5163](https://jsw.ibm.com/browse/ADCMS-5163)
#11673
Add shadow parts to the elements of lightbox-media-viewer and friends.
**New**
- Added shadow parts to the lightbox-media-viewer component and related components.

feat(lightbox-media-viewer): add shadow parts

---

packages/web-components/src/components/leadspace/leadspace.ts
packages/web-components/tests/snapshots/c4d-leadspace.md

[ADCMS-5161](https://jsw.ibm.com/browse/ADCMS-5161)
Description
All non-slot elements in the shadow DOM should be given a unique "part" name allowing CSS to target and override component default styles. This is for the "leadspace" component.
Changelog
New
Adding the shadow parts for the "leadspace" component and documentation

feat(leadspace): add shadow parts

---

packages/web-components/src/components/quote/quote.ts
packages/web-components/tests/snapshots/c4d-callout-quote.md
packages/web-components/tests/snapshots/c4d-quote.md

[ADCMS-5174](https://jsw.ibm.com/browse/ADCMS-5174)
Description
All non-slot elements in the shadow DOM should be given a unique "part" name allowing CSS to target and override component default styles. This is for the "quote" component.
Changelog
New
Adding the shadow parts for the "quote" component and documentation

feat(quote): add shadow parts

---

packages/web-components/src/components/search-with-typeahead/scoped-search-dropdown-mobile.ts
packages/web-components/src/components/search-with-typeahead/search-with-typeahead-item.ts
packages/web-components/src/components/search-with-typeahead/search-with-typeahead.ts

[ADCMS-5176](https://jsw.ibm.com/browse/ADCMS-5176)
Description
All non-slot elements in the shadow DOM should be given a unique "part" name allowing CSS to target and override component default styles. This is for the "search-with-typeahead" component.
Changelog
New
Adding the shadow parts for the "search-with-typeahead" component and documentation

feat(search-with-typeahead): add shadow parts

---

packages/web-components/src/components/structured-list/structured-list-cell.ts
packages/web-components/src/components/structured-list/structured-list-group.ts
packages/web-components/src/components/structured-list/structured-list.ts

[ADCMS-5178](https://jsw.ibm.com/browse/ADCMS-5178)
Description
All non-slot elements in the shadow DOM should be given a unique "part" name allowing CSS to target and override component default styles. This is for the "structured-list" component.
Changelog
New
Adding the shadow parts for the "structured-list" component and documentation

feat(structured-list): add shadow parts

---

packages/utilities/src/utilities/StickyHeader/StickyHeader.js

[ADCMS-5224](https://jsw.ibm.com/browse/ADCMS-5224)
The StickyHeader utility validates all components it tracks, prior to this PR is expects the provided element's `tagName` to match `${ddsPrefix}-component-name`. This works when all components are using the same prefix, but as we work on upgrading from v1 to v2 we'll need to mix-and-match prefixes. This PR will allow the StickyHeader to continue working despite the prefix differences
**Changed**
- allows StickyHeader to validate (with a warning) components that have unexpected prefixes.

feat(sticky-header): allow mixed prefixes with warning

---

packages/web-components/src/components/pricing-table/pricing-table-annotation-toggle.ts
packages/web-components/src/components/pricing-table/pricing-table-cell.ts
packages/web-components/src/components/pricing-table/pricing-table-header-cell.ts
packages/web-components/src/components/pricing-table/pricing-table.ts

[ADCMS-5173](https://jsw.ibm.com/browse/ADCMS-5173)
Description
All non-slot elements in the shadow DOM should be given a unique "part" name allowing CSS to target and override component default styles. This is for the "pricing-table" component.
Changelog
New
Adding the shadow parts for the "pricing-table" component and documentation

feat(pricing-table): add shadow parts

---

packages/carbon-web-components/src/components/code-snippet/code-snippet.scss
packages/carbon-web-components/src/components/code-snippet/code-snippet.ts

Closes #11872
The `<bx-code-snippet>` copy button is positioned absolutely, creating scenarios where it can overlay text in the component body. Giving it a greater `z-index` value allows it to sit atop the text rather than gets mashed into the text.
**Changed**
- Prevents `<bx-code-snippet>` copy button from obscuring component text and becoming difficult to identify in certain scenarios.

fix(code-snippet): improve copy button overlay presentation

---

packages/carbon-web-components/src/components/accordion/accordion-item-skeleton.ts
packages/carbon-web-components/src/components/accordion/accordion-item.ts
packages/carbon-web-components/src/components/accordion/accordion-skeleton.ts
packages/carbon-web-components/tests/snapshots/cds-combo-box.md
packages/carbon-web-components/tests/snapshots/cds-dropdown.md
packages/carbon-web-components/tests/snapshots/cds-multi-select.md
packages/carbon-web-components/tests/snapshots/cds-number-input.md
packages/carbon-web-components/tests/snapshots/data-table.md

Related to https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/11673
Makes `<cds-accordion>` family of components' shadow tree elements style-able.
**New**
- Adds `part` attributes to `<cds-accordion>` components' shadow root markup.

feat(accordion): add shadow parts

---

packages/carbon-web-components/src/components/breadcrumb/breadcrumb-link.ts
packages/carbon-web-components/src/components/breadcrumb/breadcrumb-overflow-menu.ts
packages/carbon-web-components/src/components/breadcrumb/breadcrumb-skeleton.ts
packages/carbon-web-components/src/components/breadcrumb/breadcrumb.ts

[Jira](https://jsw.ibm.com/browse/ADCMS-5309)
we should add CSS Shadow Parts to v2 components to allow light customizations to component internals.
This PR targets the breadcrumbs component
**New**
Adding shadow parts to the breadcrumbs component

feat(breadcrumb): add shadow parts

---

packages/carbon-web-components/src/components/ai-skeleton/ai-skeleton-icon.ts
packages/carbon-web-components/src/components/ai-skeleton/ai-skeleton-placeholder.ts
packages/carbon-web-components/src/components/ai-skeleton/ai-skeleton-text.ts

[ADCMS-5308](https://jsw.ibm.com/browse/ADCMS-5308)
Description
All non-slot elements in the shadow DOM should be given a unique "part" name allowing CSS to target and override component default styles. This is for the "ai-skeleton" component.
Changelog
New
Adding the shadow parts for the "ai-skeleton" component and documentation.

feat(ai-skeleton): add shadow parts

---

packages/carbon-web-components/src/components/code-snippet/code-snippet-skeleton.ts
packages/carbon-web-components/src/components/code-snippet/code-snippet.ts

[Jira](https://jsw.ibm.com/browse/ADCMS-5313)
We should add CSS Shadow Parts to v2 components to allow light customizations to component internals.
**New**
Adding shadow parts to the code snippet component.

feat(code-snippet): add shadow parts

---

packages/carbon-web-components/src/components/chat-button/chat-button-skeleton.ts
packages/carbon-web-components/src/components/chat-button/chat-button.ts

[ADCMS-5311](https://jsw.ibm.com/browse/ADCMS-5311)
Description
All non-slot elements in the shadow DOM should be given a unique "part" name allowing CSS to target and override component default styles. This is for the "chat-button" component.
Changelog
New
Adding the shadow parts for the "chat-button" component and documentation.

feat(chat-button): add shadow parts

---

packages/carbon-web-components/src/components/checkbox/checkbox-group.ts
packages/carbon-web-components/src/components/checkbox/checkbox-skeleton.ts
packages/carbon-web-components/src/components/checkbox/checkbox.ts

[Jira](https://jsw.ibm.com/browse/ADCMS-5312)
adding shadow parts to the checkbox component

feat(checkbox): add shadow parts

---

packages/carbon-web-components/src/components/content-switcher/content-switcher-item.ts

[ADCMS-5315](https://jsw.ibm.com/browse/ADCMS-5315)
Description
All non-slot elements in the shadow DOM should be given a unique "part" name allowing CSS to target and override component default styles. This is for the "content-switcher" component.
Changelog
New
Adding the shadow parts for the "content-switcher" component and documentation.

feat(content-switcher): add shadow parts

---

packages/carbon-web-components/src/components/combo-box/combo-box.ts
packages/carbon-web-components/tests/snapshots/cds-checkbox.md
packages/carbon-web-components/tests/snapshots/cds-code-snippet.md
packages/carbon-web-components/tests/snapshots/cds-combo-box.md

[ADCMS-5314](https://jsw.ibm.com/browse/ADCMS-5314)
Adding CSS Shadow Parts to v2 components to allow light customizations to component internals.

feat(combobox): adding shadow parts

---

packages/web-components/src/component-mixins/cta/video.ts

[Jira](https://jsw.ibm.com/browse/ADCMS-5207)
An issue where the CTA on cards with videos is not being populated on some pages is being caused  by an order of operation issue where the element is making calls tho an event listener that is not yet defined. 
This PR is to ensure the correct order of execution  
**Changed**
Added `customElements.whenDefined()` to the video mixin  to make sure the event only triggers after all componets needed are loaded.

fix(text-cta): prevent order of operations issues

---

packages/carbon-web-components/.storybook/preview-head.html
packages/web-components/.storybook/preview-head.html
packages/web-components/.storybook/react/preview-head.html

Add `ibm-common` tag to all Storybook environments.
**New**
- `ibm-common` analytics added to Storybook environments

chore(storybook): add ibm-commons analytics tag

---

packages/web-components/src/globals/scss/plex.scss

the plex font paths are defaulting to `~ibm/plex` which ends up 404ing when we use the font CDNs. This PR sets `use-akamai-cdn` flag to true in the carbon font configs.
**New**
- set `use-akamai-cd` flag for plex fonts

fix(fonts): set font path for plex fonts cdn

---

packages/web-components/package.json
packages/web-components/src/components/carousel/carousel.ts
yarn.lock

Closes #11907
The `wicg-inert` package poses a security vulnerability. As the `inert` attribute seems to be [supported by all browsers](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inert#browser_compatibility), this polyfill package is no longer needed.
**Removed**
- remove `wicg-inert` package

fix(package): remove unneeded wicg-inert package - v1

---

packages/carbon-web-components/src/components/copy/copy.ts

[ADCMS-5316](https://jsw.ibm.com/browse/ADCMS-5316)
Description
All non-slot elements in the shadow DOM should be given a unique "part" name allowing CSS to target and override component default styles. This is for the "copy" component.
Changelog
New
Adding the shadow parts for the "copy" component and documentation.

feat(copy): add shadow parts

---

packages/carbon-web-components/src/components/tag/tag.ts

[ADCMS-5353](https://jsw.ibm.com/browse/ADCMS-5353)
Description
All non-slot elements in the shadow DOM should be given a unique "part" name allowing CSS to target and override component default styles. This is for the "tag" component.
Changelog
New
Adding the shadow parts for the "tag" component and documentation.

feat(tag): add shadow parts

---

packages/carbon-web-components/src/components/tabs/tab-skeleton.ts
packages/carbon-web-components/src/components/tabs/tab.ts
packages/carbon-web-components/src/components/tabs/tabs-skeleton.ts
packages/carbon-web-components/src/components/tabs/tabs.ts

[ADCMS-5352](https://jsw.ibm.com/browse/ADCMS-5352)
Description
All non-slot elements in the shadow DOM should be given a unique "part" name allowing CSS to target and override component default styles. This is for the "tabs" component.
Changelog
New
Adding the shadow parts for the "tabs" component and documentation.

feat(tabs): add shadow parts

---

packages/web-components/.storybook/manager-head.html
packages/web-components/.storybook/preview-head.html
packages/web-components/.storybook/react/manager-head.html
packages/web-components/.storybook/react/preview-head.html

Adding mandatory intrumentation tags for Carbon for IBM.com web components storybook
**Changed**
- Added `ibm-common.js` and IBM footer to storybooks

chore(ibm-common): add mandatory IBM instrumentation tags (v2)

---

packages/carbon-web-components/src/components/textarea/textarea-skeleton.ts
packages/carbon-web-components/src/components/textarea/textarea.ts

[ADCMS-5356](https://jsw.ibm.com/browse/ADCMS-5356)
Description
All non-slot elements in the shadow DOM should be given a unique "part" name allowing CSS to target and override component default styles. This is for the "textarea" component.
Changelog
New
Adding the shadow parts for the "textarea" component and documentation.

feat(textarea): add shadow parts

---

packages/carbon-web-components/src/components/chat-button/chat-button.ts
packages/carbon-web-components/src/components/copy-button/copy-button.ts
packages/carbon-web-components/src/components/copy/copy.ts
packages/carbon-web-components/src/components/data-table/table-skeleton.ts
packages/carbon-web-components/src/components/file-uploader/demo-file-uploader.ts
packages/carbon-web-components/src/components/file-uploader/file-uploader-button.ts
packages/carbon-web-components/src/components/form-group/form-group.ts
packages/carbon-web-components/src/components/icon-button/icon-button.ts
packages/carbon-web-components/src/components/layer/layer.ts
packages/carbon-web-components/src/components/notification/actionable-notification.ts
packages/carbon-web-components/src/components/popover/popover-content.ts
packages/carbon-web-components/src/components/popover/popover.ts
packages/carbon-web-components/src/components/progress-bar/progress-bar.ts
packages/carbon-web-components/src/components/select/select-skeleton.ts
packages/carbon-web-components/src/components/stack/stack.ts
packages/carbon-web-components/src/components/text-input/text-input-skeleton.ts
packages/carbon-web-components/src/components/text-input/text-input.ts
packages/carbon-web-components/src/components/toggle-tip/toggletip.ts
packages/carbon-web-components/src/components/ui-shell/header-global-action.ts
packages/carbon-web-components/src/components/ui-shell/header-panel.ts
packages/carbon-web-components/src/components/ui-shell/header-side-nav-items.ts
packages/carbon-web-components/src/components/ui-shell/switcher-item.ts
packages/carbon-web-components/src/components/ui-shell/switcher.ts

Ensure all CWC are using the `carbonElement` decorator to prevent clashing when user is trying to import the same component from different locations
**Changed**
- ensure all CWC are importing and using the `carbonElement` decorator

fix(custom-element): ensure all cwc components use carbonElement

---

packages/react/package.json

Set React package to `private` to prevent further publishing to NPM.
**Changed**
- `@carbon/ibmdotcom-react` set to private

chore(deps): set react package to private

---

packages/carbon-web-components/src/components/toggle/toggle.ts

[ADCMS-5358](https://jsw.ibm.com/browse/ADCMS-5358)
Description
All non-slot elements in the shadow DOM should be given a unique "part" name allowing CSS to target and override component default styles. This is for the "toggle" component.
Changelog
New
Adding the shadow parts for the "toggle" component and documentation.

feat(toggle): add shadow parts

---

packages/carbon-web-components/src/components/toggle-tip/toggletip.ts

[Jira](https://jsw.ibm.com/browse/ADCMS-5359)
**New**
- Added shadow - parts to the toggle-tip CWC component

feat(toggle-tip): add shadow parts

---

packages/web-components/package.json

Closes #11933 
Fixes issues with the export sub-paths in @carbon/ibmdotcom-web-components
**Changed**
- Fixes export sub-paths.

fix(build): fix exports subpaths

---

packages/styles/scss/components/card-group/_card-group.scss
packages/styles/scss/components/card-in-card/_card-in-card.scss
packages/styles/scss/components/card/_card.scss
packages/styles/scss/components/content-block-mixed/_content-block-mixed.scss
packages/styles/scss/components/cta-block/_cta-block.scss
packages/styles/scss/components/cta-section/_cta-section.scss
packages/styles/scss/components/feature-card/_feature-card.scss
packages/styles/scss/components/footer/_language-selector.scss
packages/styles/scss/components/image/_image.scss
packages/styles/scss/components/leadspace-block/_leadspace-block.scss
packages/styles/scss/components/search-with-typeahead/_search-with-typeahead.scss
packages/styles/scss/globals/utils/_content-width.scss
packages/styles/scss/patterns/blocks/callout-data/_callout-data.scss
packages/styles/scss/patterns/blocks/leadspace-block/_leadspace-block.scss
packages/styles/scss/patterns/sections/cta-section/_cta-section.scss
packages/styles/scss/patterns/sections/leadspace/_leadspace.scss

Closes #11958
Replaces `carbon--mini-units`, which is no longer part of Carbon v11, with the equivalent `$spacing-*` token, or `to-rem` call for the intended pixel size.
**Changed**
- Replaces all `carbon--mini-units` calls with v11 equivalent.

fix(styles): remove all use of carbon--mini-units

---

packages/styles/scss/components/tabs-extended/_tabs-extended.scss
packages/web-components/src/components/tabs-extended/__stories__/tabs-extended.stories.ts
packages/web-components/tests/snapshots/dds-table-of-contents.md

Closes #11965
With certain content in tab names, Safari does not soft hyphenate how we would want it to, leading to text overflowing the container. This adds a width the the wrapping <div> of the <p> where the tab title sits.This will cause Safari to soft hyphenate better, and avoid overflowing the container.
**Changed**
- Fix text overflow issue in the tab title on Safari

fix(tabs-extended): adjustments to force Safari to soft hyphenate better for tab names

---

packages/web-components/src/components/tabs-extended/tabs-extended.ts

Closes #11975 
https://jsw.ibm.com/browse/ADCMS-5840
tabs-extended's _handleTabListKeyDown method sets `targetTab` to a default value of -1 and then modifies that value for arrow keys and home/end.
Prior to this PR, the component sets the active item and focus to targetTab, even if it's still -1. This PR changes that to only set active/focus if the value has been modified away from -1
**Changed**
- fixes a bug in which tab panels could disappear on keypress

fix(tabs): avoid setting focus/active to -1

---

packages/web-components/src/components/content-group/__stories__/content-group.stories.ts
packages/web-components/src/components/content-group/content-group-heading.ts
packages/web-components/src/components/content-group/content-group.scss

[Jira ticket](https://jsw.ibm.com/browse/ADCMS-5810)
Adjusts the `<dds-content-group-heading>` component to render its heading to the light DOM, and then reflect it back via default slot. This allows arbitrary HTML to be slotted, as we had before, but to also enforce an `<h3>` to the light DOM to fix the SEO issues.
**Changed**
- content-group-heading component will now wrap the slotted markup in and `<h3>` and write the result to the light DOM for SEO purposes
* Visit the Content Group stories. Pay particular attention to the `<dds-content-group-heading>` component.
* Check against the current v1 Storybook
* There should be no visual regressions
* Inspect the source of the `<dds-content-group-heading>` component. 
* An `<h3>` tag should be present in the light DOM, wrapping any markup …

fix(content-group-heading): render h3 tag to light DOM

---

packages/styles/scss/components/image/_image.scss
packages/web-components/src/components/card/card-footer.ts
packages/web-components/src/components/card/card.ts
packages/web-components/tests/snapshots/c4d-card-footer.md
packages/web-components/tests/snapshots/c4d-card-in-card.md
packages/web-components/tests/snapshots/c4d-card.md
packages/web-components/tests/snapshots/c4d-feature-card.md
packages/web-components/tests/snapshots/c4d-filter-panel-composite.md
packages/web-components/tests/snapshots/c4d-masthead-profile.md

[JIRA](https://jsw.ibm.com/browse/ADCMS-6137)
Adding shadow parts to the sub components of `card`
**New**
- `part` attribute to HTML tags under the `card` component

feat(card): add subcomponents shadow parts

---

packages/styles/scss/components/callout-quote/index.scss
packages/styles/scss/components/quote/_quote.scss
packages/web-components/src/components/callout-quote/__stories__/callout-quote.stories.ts
packages/web-components/src/components/carousel/__tests__/carousel.test.ts
packages/web-components/src/components/quote/quote.ts
packages/web-components/tests/karma.conf.js
packages/web-components/tests/snapshots/dds-filter-panel-composite.md
packages/web-components/tests/snapshots/dds-table-of-contents.md
packages/web-components/tests/snapshots/dds-tabs-extended-media.md
packages/web-components/tests/snapshots/dds-tabs-extended.md

[ADCMS-6085](https://jsw.ibm.com/browse/ADCMS-6085)
When using the callout-quote component, the shadowroot styles render the blockquote element in a serif font. (e.g. [mainframe application modernization](https://www.ibm.com/mainframe-application-modernization))
In non-latin fonts, however, there isn't a serif version of those typefaces, leading to the components rendering non-plex characters. (e.g. [MAM in Japanese](https://www.ibm.com/jp-ja/mainframe-application-modernization))
With this fixed applied:

fix(callout-quote): forcing sans-serif font in non latin fonts

---

packages/web-components/src/components/masthead/left-nav-menu-category-heading.ts
packages/web-components/src/components/masthead/left-nav-menu-item.ts
packages/web-components/src/components/masthead/masthead-composite.ts
packages/web-components/src/components/masthead/masthead-l1-cta.ts
packages/web-components/src/components/masthead/masthead-l1.ts
packages/web-components/src/components/masthead/megamenu-category-heading.ts
packages/web-components/src/components/masthead/megamenu-heading.ts

https://jsw.ibm.com/browse/ADCMS-6275
As part of AEM's effort to launch the Arabic geo, we need to add the ability to flip the arrow icons to point in the `inline-end` direction.
This PR updates masthead component files using `ArrowRight` icons to conditionally display `ArrowLeft` icons when `document.dir.toLowerCase === 'rtl'`
**Changed**
- Allow masthead/leftnav components to flip arrow directions for RTL support

fix(masthead): support proper icon direction in RTL languages

---

packages/web-components/src/components/content-item-horizontal/content-item-horizontal-media-featured.ts
packages/web-components/src/components/content-item-horizontal/content-item-horizontal-media.ts
packages/web-components/src/components/content-item-horizontal/content-item-horizontal.ts
packages/web-components/src/components/content-item/content-item.ts
packages/web-components/tests/snapshots/dds-content-item-horizontal.md
packages/web-components/tests/snapshots/dds-content-item.md
packages/web-components/tests/snapshots/dds-pictogram-item.md

[Jira ticket](https://jsw.ibm.com/browse/ADCMS-6329)
Adds shadow parts to the `<dds-content-item-horizontal>` family of components in order to allow for slight design adjustments in AEM.
**New**
- Added shadow parts for `<dds-content-item-horizontal>` family of components.

[v1] feat(content-item-horizontal): add shadow parts

---

packages/web-components/src/components/card/card.ts
packages/web-components/src/components/cta/video-cta-composite.ts
packages/web-components/src/components/video-player/__stories__/video-player.stories.ts

https://jsw.ibm.com/browse/ADCMS-6425
Fixes a bug in which cards with `cta-type="video"` all update with each others video data, causing the wrong video durations listed for all but one of the cards
[Demo](https://card-group-video--carbon-demos.netlify.app/)
**Changed**
- Limits card responses to `c4d-cta-request-additional-video-data` events that are related to their own videos

feat(card): fix video cta data

---

packages/web-components/src/components/card/card.ts

Closes # [ADCMS-6396](https://jsw.ibm.com/browse/ADCMS-6396)
Link icons are directing to right instead of left for card-group-pictogram in RTL pages as well as story book of v2
**Changed**
- Use the correct arrow icon for pictogram card in RTL

fix(card): arrow direction on RTL

---

packages/web-components/src/components/video-player/__stories__/video-player.stories.ts
packages/web-components/src/components/video-player/video-player-composite.ts
packages/web-components/src/components/video-player/video-player-container.ts
packages/web-components/src/components/video-player/video-player.ts

https://jsw.ibm.com/browse/ADCMS-6363
Fixes the `auto-play` attribute to play video on load and adds a `muted` attribute to load the video with sound fully muted.
**New**
- Adds `muted` attribute to `video-player-container`
- Adds storybook examples for `auto-play` and `muted` video player usage
**Changed**
- Fixes `auto-play` attribute on `video-player-container`

feat(video-player): enable autoplay & load as muted

---

packages/styles/scss/components/video-player/_video-player.scss
packages/web-components/src/components/background-media/__stories__/README.stories.mdx
packages/web-components/src/components/background-media/__stories__/background-media.stories.ts
packages/web-components/src/components/leadspace/__stories__/README.stories.mdx
packages/web-components/src/components/leadspace/__stories__/leadspace.stories.ts
packages/web-components/src/components/video-player/video-player-composite.ts
packages/web-components/src/components/video-player/video-player-container.ts

Recent changes caused visual regressions due to styles that relied on `[background-video="true"]`. These updates make `background-video` a pure boolean attribute and simplify the style selectors accordingly.
**Changed**
- Make `background-video` a reflected boolean attribute all the time.
- Fix a regression with auto-play video.

fix(video-player): correct a visual regression with background video in some contexts

---

packages/web-components/src/components/content-block-simple/content-block-simple.scss

https://jsw.ibm.com/browse/ADCMS-6496
Adds `margin-block-start` to the footer wrapper in the content-block-simple element.
**Changed**
- fix content-block-simple spacing

fix(content-block-simple): update footer spacing

---

packages/styles/scss/components/card/_card.scss
packages/styles/scss/components/feature-card/_feature-card.scss
packages/web-components/src/components/card/card.ts
packages/web-components/src/components/cta/feature-cta.ts

[ADCMS-6497](https://jsw.ibm.com/browse/ADCMS-6497)
The `<c4d-feature-card>` has been broken for some time. This PR is a refactor of the styles to align with the [v2 Figma specs](https://www.figma.com/design/DmgpvpEV6m4eJNMgKOLPmy/Feature-card-v2?node-id=407-13733&node-type=frame&t=JIxBJ4kEUMJMj1lD-0).
This ended up being close to a ground-up rewrite of the styles for `<c4d-feature-card>`. The Storybook should be compared with the Figma specs for all spacing, type, colors, interaction states, inverse states, Carbon themes, etc.
Some things to note:
* We're testing two stories: Feature card > Medium and Feature card > Large. There are slight differences between them. There is a set of specs for each [in Figma](https://www.figma.com/design/DmgpvpEV6m4eJNMgKOLPmy/Feature-card-v2?node-id=827-3 …

fix(feature-card): fix feature card broken styles and refactor

---

packages/services/src/services/SAPCommerce/SAPCommerce.js
packages/services/src/services/SAPCommerce/index.js
packages/services/src/services/index.js
packages/web-components/src/components/masthead/__stories__/masthead.stories.ts
packages/web-components/src/components/masthead/masthead-cart.ts
packages/web-components/src/components/masthead/masthead-composite.ts
packages/web-components/src/components/masthead/masthead.scss

[ADCMS-6463](https://jsw.ibm.com/browse/ADCMS-6463)
Adds a new `<c4d-masthead-cart>` component to the Masthead. Needs to be opted in using `has-cart` attribute on the `<c4d-masthead-container>` component. When opted in, there is internal logic to read a cookie that will determine if the cart should be shown.
The cart icon functionality is controlled by two new knobs on the Masthead > Default story. The "show the cart functionality (has-cart)" checkbox toggles whether or not the cart renders at all. The "mock active cart id" will affect the cookie that the cart is looking for to show / hide. Anytime you change the "mock active cart id", you need to toggle the "show the cart functionality (has-cart)" so that the `<c4d-masthead-card>` component will re-render and check the cookie value. The …

[feature] Add cart icon to Masthead for SAP Commerce integration

---

packages/styles/scss/components/card/_card.scss
packages/web-components/src/components/card/card.ts

[JIRA](https://jsw.ibm.com/browse/ADCMS-6596)
PR to solve 
> _Card's shadowroot element matching .cds--card__footer has a pseudo-element that blocks click access to the slotted link._
Removed class name from footer wrapper on the `card` component

(card): Remove class form footer to make component clickable

---

.github/workflows/dco.yml
packages/web-components/src/components/tile/__stories__/README--tile-group.stories.mdx
packages/web-components/src/components/tile/__stories__/README--tile.stories.mdx
packages/web-components/src/components/tile/__stories__/tile-group.stories.ts
packages/web-components/src/components/tile/__stories__/tile.stories.ts
packages/web-components/src/components/tile/index.ts
packages/web-components/src/components/tile/tile-group.ts
packages/web-components/src/components/tile/tile.scss
packages/web-components/src/components/tile/tile.ts
packages/web-components/tests/snapshots/c4d-card-in-card.md
packages/web-components/tests/snapshots/c4d-card.md
packages/web-components/tests/snapshots/c4d-content-block-card-static.md
packages/web-components/tests/snapshots/c4d-feature-card.md
packages/web-components/tests/snapshots/c4d-masthead-profile.md

https://jsw.ibm.com/browse/ADCMS-6691
Migrates the `tile` and `tile-group` components from `carbon-for-aem` into `carbon-for-ibmdotcom`
**New**
- adds `c4d-tile`
- adds `c4d-tile-group`

feat(tile, tile-group): add components

---

packages/styles/scss/components/pricing-table/_pricing-table.scss
packages/styles/scss/components/structured-list/_structured-list.scss
packages/web-components/src/components/structured-list/structured-list-cell.ts

Corrects v1->v2 regressions in the structured-list and pricing-table components with cells containging icons.
Current:
Expected:
**Changed**
- Fixed spacing and alignment bugs
- Slight reworking of the `part` attributes

fix(structured-list, pricing-table): correct coloration, spacing & alignment

---

packages/web-components/src/components/tile/__stories__/tile-group.stories.ts
packages/web-components/src/components/tile/__stories__/tile.stories.ts

[ADCMS-6691](https://jsw.ibm.com/browse/ADCMS-6691)
Follow up to https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/12091
Quick followup to https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/12091. Updates imports for the same package to be relative paths. Can avoid weird local development / bundling bugs and maintains consistency with the rest of the codebase.
**Changed**
- Adjusts `import '@carbon/ibmdotcom-web-components/es*';` imports to relative path imports.

refactor(tile): use relative paths for imports in the same pkg

---

packages/web-components/src/components/promo-banner/__stories__/README.stories.mdx
packages/web-components/src/components/promo-banner/__stories__/promo-banner.stories.ts
packages/web-components/src/components/promo-banner/index.ts
packages/web-components/src/components/promo-banner/promo-banner.scss
packages/web-components/src/components/promo-banner/promo-banner.ts

[ADCMS-6656](https://jsw.ibm.com/browse/ADCMS-6656)
Migrates the `promo-banner` component from carbon-for-aem into carbon-for-ibmdotcom
**New**
- Added the `c4d-promo-banner` component.

feat(promo-banner): add components

---

packages/web-components/examples/stackblitz/components/dotcom-shell/src/index.scss
packages/web-components/examples/stackblitz/components/masthead-l1/src/index.scss
packages/web-components/examples/stackblitz/components/masthead/src/index.scss
packages/web-components/examples/stackblitz/components/table-of-contents/src/index.scss
packages/web-components/examples/stackblitz/components/tabs-extended/src/styles.scss
packages/web-components/examples/stackblitz/usage/webpack-handlebars/src/index.scss
packages/web-components/examples/stackblitz/usage/webpack-sass/src/index.scss
packages/web-components/src/components/star-rating/__stories__/README.stories.mdx
packages/web-components/src/components/star-rating/__stories__/star-rating.stories.ts
packages/web-components/src/components/star-rating/index.ts
packages/web-components/src/components/star-rating/star-rating.scss
packages/web-components/src/components/star-rating/star-rating.ts
packages/web-components/src/globals/internal/storybook-decorators.ts

[JIRA](https://jsw.ibm.com/browse/ADCMS-6667)
Migrates the`star-rating` component from `carbon-for-aem` into `carbon-for-ibmdotcom`.
**New**
- adds new `c4d-star-rating` component

feat(star-rating): new component

---

packages/web-components/src/components/tile/__stories__/tile-group.stories.ts
packages/web-components/src/components/tile/__stories__/tile.stories.ts

Follow up to https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/12091
Since merging https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/12091, we've been getting Percy complaining about differences in the tile stories. The reason is that those stories have a random selection of labels and headlines each time you visit the story anew.
This PR introduces a pre-generated sequence of index numbers for the list of labels and headlines, which you can "pre-seed" by chosing a starting sequence number. This ensures that given any stating sequence number the chosen labels and headlines will be the same always. That should allow us to run Percy consistently wthout having to approve changes on every commit.
Note: Percy will report the same annoying differences in the …

fix(tile): add a knob to have deterministic random in label and headline

---

package.json
packages/styles/scss/components/tableofcontents/_table-of-contents.scss

https://jsw.ibm.com/browse/ADCMS-6886
Fixes alignment changes between v1 & v2 as exhibited [here](https://toc-comparison--carbon-demos.netlify.app/)
**Changed**
- add `stylelint --fix` to `yarn format` command
- fixes alignment changes in table of contents

fix(toc): alignment issues

---

packages/styles/scss/components/leadspace/_leadspace.scss

[ADCMS-6827](https://jsw.ibm.com/browse/ADCMS-6827)
Adding **long** text to the leadspace copy knob leads to clipping the text & CTAs.
Issue:
Fixed:
There's an apparent bug in all heading/title knobs in all components, when you try to modify it, we get the below error.
I've been trying to debug this error, but with @m4olivei 's help, we found out it's an issue that's been sitting there for a while now, so It would just be very time consuming for the tiny fix that was the original scope of this ticket

fix(leadspace): in storybook adding long copy to copy knob led to button being clipped away

---

packages/web-components/src/components/card/card.ts

[ADCMS-6850](https://jsw.ibm.com/browse/ADCMS-6850)
Removes an `onclick` handler on cards which is redundant and hinders customization by adopters. The `onlick` handler here is already covered by the `<a>` that has an `::after` pseudo element covering the card and capturing the click event for sighted and non-sighted users.
The `onclick` handler was added back in https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/6642.
**Changed**
- Removed `onclick` handler from pictogram cards

fix(card): remove onclick handler for pictogram

---

packages/styles/scss/components/feature-card/_feature-card.scss
packages/styles/scss/components/feature-section/_feature-section.scss

https://jsw.ibm.com/browse/ADCMS-6914
Stretches images in feature-card and feature-section if content causes component to grow vertically.
**Changed**
- updates feature-card & feature-section styles to stretch image to fill if needed

fix(feature-section): stretch image if needed

---

packages/styles/scss/components/callout-with-media/_callout-with-media.scss

[ADCMS-6942](https://jsw.ibm.com/browse/ADCMS-6942)
Adjust spacing on the `<c4d-callout-with-media>` component per the [Figma specs](https://www.figma.com/design/ADYTE8HS12nn63RJLZOk87/Layout-component--callout-with-media--visual-specs--2.1?node-id=0-1&node-type=canvas&t=QNmoJfFTr6bA75Ak-0). Note that there are no v2 specs for this component.
**Changed**
- Adjust spacing for slotted elements to the `<c4d-callout-with-media>` component.

fix(callout-with-media): spacing adjustments

---

packages/web-components/src/components/table-of-contents/table-of-contents.ts

[ADCMS-6990](https://jsw.ibm.com/browse/ADCMS-6990)
Adjusts the media query logic in the TOC component to line up with the Sass for the same. This fixes an issue where before, right on the lg breakpoint, the TOC was broken and stuck showing mostly mobile styles instead of desktop ones.
**Changed**
- TOC wlll now maintain the desktop layout for the lg breakpoint and above.

fix(toc): tweak media query for sidebar at lg

---

packages/web-components/src/components/footer/footer-composite.ts

[ADCMS-7082](https://jsw.ibm.com/browse/ADCMS-7082)
Fixes an issue where the `placeholder` text in the `<input>` within the `<c4d-language-selector-desktop>` component was not being correctly passed along from the `<c4d-footer-container>` attributes.
* Go to the Footer > Default language only story. We're focused here on the `<c4d-language-selector-desktop>` component:
* Click the "x" to clear the language selection
**Expected result**
You should see the placeholder text "Choose a language"
**Changed**
- `<c4d-language-selector-desktop>` component will show placeholder text for empty value

fix(footer): pass along the placeholder text to combo-box

---

packages/styles/scss/components/footer/_footer.scss
packages/styles/scss/components/footer/_legal-nav.scss

[ADCMS-7082](https://jsw.ibm.com/browse/ADCMS-7082)
Fixes the color and padding of the "Cookie Preferences" component in the footer links. Note that the Cookie Preferences link is added by an external vendor script (https://tags.tiqcdn.com/utag/ibm/web/prod/utag.js). To test it in Storybook, see below testing instructions.
* Open the Footer > Default story
* Open dev tools and look for the `<c4d-legal-nav-cookie-preferences-placeholder>` component.
* Edit as HTML and add the following markup as a child element:
```
<a role="link" id="icon-id007001372122542948" tabindex="0" lang="en" aria-haspopup="dialog" aria-label="Cookie Preferences, opens a dedicated popup modal window" class="truste_cursor_pointer cds--link cds--footer__link">Cookie Preferences</a>
```
**Expected results**
* The link …

fix(footer): adjustments to style for color and positioning

---

packages/styles/scss/components/footer/_footer.scss
packages/web-components/src/components/footer/legal-nav.ts

[ADCMS-7082](https://jsw.ibm.com/browse/ADCMS-7082)
Make some adjustments to the logic inside the legal-nav component for adjunct-links visibility. Before the fix here, the `@slotchange` event was not firing as expected when there were no adjunct links to hide them. Further, once the `hidden` class got correctly set on the `adjunct-links` wrapper, needed to fix some Sass to actually hide it.
**Changed**
- Hide adjunct-links container when there are no adjunct links.

fix(footer): adjustments to adjunct links visibility

---

packages/styles/scss/components/callout-with-media/_callout-with-media.scss
packages/styles/scss/components/feature-card/_feature-card.scss
packages/styles/scss/components/feature-section/_feature-section.scss
packages/styles/scss/components/footer/_footer.scss
packages/styles/scss/components/footer/_legal-nav.scss
packages/web-components/src/components/card/card.ts
packages/web-components/src/components/content-block-segmented/content-block-segmented.scss
packages/web-components/src/components/footer/footer-composite.ts
packages/web-components/src/components/footer/legal-nav.ts
packages/web-components/src/components/table-of-contents/table-of-contents.ts

#12123
#12126
#12124
#12129
#12133
#12134 
#12135 
#12136 
Adding the latest changes from `main` (via cherry-pick) to the v2.16.0 release branch to push out a new RC.
Note that while here, I also needed to make a couple of adjustments:
* [Branch protection rules for `release/v2*`](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/settings/branch_protection_rules/21656860) to not depend on the Jenkins jobs anymore (they no longer run)
* Needed to tell Netlify to build deploy previews for this specific branch. That happens in the Netlify dashboard under [Build & deploy settings > Branches and deploy contexts](https://app.netlify.com/sites/ibm-dotcom-web-components/configuration/deploys#branches-and-deploy-contexts).
* At first I just branched off the release branch, then merged …

Add latest fixes from main to the v2.16.0 release

---

packages/styles/scss/internal/content-block/_content-block.scss

[ADCMS-7025](https://jsw.ibm.com/browse/ADCMS-7025)
Adjustment to inline-margin-start for `<c4d-cta-block-item-row>`
**Changed**
- Adjusted inline-margin-start for `<c4d-cta-block-item-row>` when slotted into content block

fix(cta-block): adjust cta-block-item-row inline margin

---

packages/web-components/src/components/button/button.ts
packages/web-components/tests/e2e-storybook/cypress/integration/button-group/button-group.e2e.js

[ADCMS-7088](https://jsw.ibm.com/browse/ADCMS-7088)
As it was, button elements that had no label would adopt any video name fetched by the `<c4d-video-cta-container>` component, which may have been triggered by a completely unrelated CTA. This change now guards against that by ignoring events when the button is not a `cta-type="video"` or does not have the same video id as the fetched video.
**Changed**
- Fixes an issue with buttons not using a label placed on a page with other unrelated video CTAs

fix(button): avoid taking any video name bubbled on the page

---

packages/web-components/.storybook/container.scss

No ticket. Just quick clean up that I couldn't unsee.
The use of the `theme.theme` mixin from the `@carbon/styles` package (which is forwarded from `@carbon/themes`) was incorrect. The [second argument is meant to be a map of component tokens](https://github.com/carbon-design-system/carbon/blob/main/packages/themes/scss/_theme.scss#L28). We [already add the set of component tokens we want as includes](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/packages/web-components/.storybook/container.scss#L20-L22), and therefore don't need the second argument at all. As it was it produced a `--cds-true:;` CSS variable that was useless in the compiled CSS:
**Changed**
- Fixed incorrect use of `theme.theme` mixin from `@carbon/styles` package

fix(storybook): incorrect use of theme mixin

---

packages/styles/scss/components/tableofcontents/_table-of-contents.scss
packages/web-components/src/components/table-of-contents/__stories__/table-of-contents.stories.scss

[ADCMS-7171](https://jsw.ibm.com/browse/ADCMS-7171)
Removes the top and bottom implicit padding on the TOC contents in the shadow root.
**Changed**
- Removes the internal top and bottom padding from TOC contents to leave to adopter as in v1

fix(toc): remove implicit top and bottom padding for TOC

---

packages/styles/scss/components/feature-card/_feature-card.scss
packages/web-components/src/components/card/card.ts
packages/web-components/src/components/feature-card/__stories__/feature-card.stories.ts

[ADCMS-7128](https://jsw.ibm.com/browse/ADCMS-7128)
Fixes some inverse styles for Feature card component. Also adds cta type knobs to the Storybook story and fixes support in `<c4d-feature-card>` component for `cta-type="video"`.
**New**
- Support for `cta-type="video"` in Feature card
**Changed**
- Fixed inverse styles for Feature card component

fix(feature-card): inverse styles and cta-type="video"

---

packages/web-components/src/components/notice-choice/notice-choice.ts

Follow up to https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/12127
Following convention, switch `current-language` attribute to snake case.
**Changed**
- Changed `currentLanguage` attribute in `<c4d-notice-choice>` component to snake case

fix(notice-choice): switch attribute to snake case

---

packages/web-components/src/components/button/button.ts

[ADCMS-6961](https://jsw.ibm.com/browse/ADCMS-6961)
Fixes some odd icon logic left in the button component. The fix allows us to consistently re-render the correct CTA type icon whenever a change in the parent component may mean a different `<slot name="icon">` element is rendered. This allows for consistency across disable/active states.
* Toggling disable knob and/or changing the `href` should maintain the expected icon and reflect the relevant state.
* Change CTA type knob state to make sure it reflects the right value
**Changed**
- Fixed icon issues in the button component for disable state

fix(button): fix disable state of the button

---

packages/styles/scss/components/card/_card.scss

[ADCMS-7121](https://jsw.ibm.com/browse/ADCMS-7121)
[ADCMS-7158](https://jsw.ibm.com/browse/ADCMS-7158)
Under certain conditions, the footer of a card, especially within a group, might not stick to the end of the card as intended. This fixes it so that the card footer is always at the end of the card.
**Changed**
- Force the footer of cards to be at the end, corrects an issue with Content Group Cards

fix(card): push the footer to the bottom of the card consistently

---

packages/styles/scss/components/card-group/_card-group.scss
packages/styles/scss/components/card/_card.scss
packages/web-components/src/components/card-group/__stories__/card-group.stories.ts

[ADCMS-6840](https://jsw.ibm.com/browse/ADCMS-6840)
[ADCMS-7238](https://jsw.ibm.com/browse/ADCMS-7238)
Fixes some pictogram related card styling issues.
* Review and pay particular attention to Card and Card Group stories, looking for regressions
* Use the Card Group story, with a "Card type" of "Card - pictogram". Then check the "Hide description" checkbox and ensure that the cards are [matching spec](https://www.figma.com/design/oip4K9G1z0v7tLNBbDZzdr/Card-specs-v2?node-id=19-3434&node-type=canvas&t=lwI58ey8t4c8MTqo-0).
**Changed**
- Visual fixes for pictogram cards when there is no card description.

fix(card): pictogram related style adjustments

---

packages/styles/scss/components/content-group-cards/_content-group-cards.scss
packages/styles/scss/internal/content-block/_content-block.scss

Closes # 
https://jsw.ibm.com/browse/ADCMS-7030
In medium resolution, the cards are having an undesired horizontal overflow that was causing a scroll bar to appear.
I made a fix that will make them span full width, that's the behavior we have in the [v2 builds I found](https://ibmdotcom-webcomponents.s3.us-east.cloud-object-storage.appdomain.cloud/deploy-previews/11248/index.html?path=/story/overview-getting-started--page) for example, that came [from this issue](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/11248)
Fixed as per this PR:
**New**
setting `margin-inline-start` to be 0 in resolutions lower than LG.

fix(content-group-cards): fix alignment

---

packages/web-components/src/components/background-media/background-media.ts
packages/web-components/src/components/video-player/video-player-composite.ts

https://jsw.ibm.com/browse/ADCMS-7249
Modifies component logic to avoid a possible race condition. Previously we assumed the background media component was setting up after the video player container had created its video player child.
**Changed**
- avoid possible race condition in with background videos

fix(background-media): avoid potential VPC setup race

---

packages/styles/scss/components/callout-quote/_callout-quote.scss
packages/styles/scss/components/callout-with-media/_callout-with-media.scss

[ADCMS-7277](https://jsw.ibm.com/browse/ADCMS-7277)
Fixes horizontal scroll on the callout quote component at the mobile breakpoint. While here, also make slight adjustments to inline margin for the nested `<c4d-hr>` component within the callout quote component, [per the spec](https://www.figma.com/design/KQdUduecrBf4DCjRZnsl25/Layout-component--callout-quote--visual-specs--2.1.0?node-id=0-106&node-type=frame&t=y1vGtscmEVeFVKKv-0).
**Changed**
- Fixes horizontal scroll on the callout quote component at the mobile breakpoint.

fix(callout-quote): fix horizontal scroll for callout quote

---

packages/styles/scss/components/card-group/_card-group.scss
packages/web-components/src/components/cta-block/cta-block.scss

https://jsw.ibm.com/browse/ADCMS-7128
Explicitly forces card-group-item internals to use `grid-template-column: subgrid` to ensure a 1-column width throughout
**Changed**
- card-group-item internals rely on card-group grid-column

fix(card-group): subgrid fixes

---

packages/web-components/src/components/card/__stories__/card.stories.ts
packages/web-components/src/components/card/card.ts

[ADCMS-7019](https://jsw.ibm.com/browse/ADCMS-7019)
Fixes an issue where if you attempt to slot content other than a `<p>` tag into the default slot of a card, that copy remains hidden. This will allow any text node and/or element (anything not a comment) to be shown in the default slot for the card.
**Changed**
- Fixes an issue with the default slot hiding non-paragraph contents
- Added "Body copy markup" as a boolean knob to the card story. This will render a list of items in the card copy default slot.

fix(card): allow copy other than <p> tags

---

packages/web-components/src/components/cta/video-cta-composite.ts

[ADCMS-6749](https://jsw.ibm.com/browse/ADCMS-6749)
Tangentially related to [ADCMS-6749](https://jsw.ibm.com/browse/ADCMS-6749). This fix addresses the following error when bundling the video-cta-container component in some environments:
```
Uncaught (in promise) Error: The following properties on element c4d-video-cta-container will not trigger updates as expected because they are set using class fields: _embedMedia. Native class fields and some compiled output will overwrite accessors used for detecting changes. See https://lit.dev/msg/class-field-shadowing for more information.
at C4DVideoCTAContainer2.performUpdate (chunk-4KQNGL43.js?v=fb1a7d37:1973:17)
at C4DVideoCTAContainer2.scheduleUpdate (chunk-4KQNGL43.js?v=fb1a7d37:1938:17)
at C4DVideoCTAContainer2.__enqueueUpdate …
```

fix(video): remove @state declaration for function _embedMedia

---

packages/styles/scss/components/card-in-card/_card-in-card.scss

Closes # [ADCMS-6606](https://jsw.ibm.com/browse/ADCMS-6606)
It's difficult to see that cards are clickable rather than just having differently colored background when they display full-width in the TOC layout. Add proper "gutter" space on the left and right sides of cards to suggest that they are clickable cards.
**New**
Added left and right space using padding around the `card-in-card` component using the $spacing-05 token for mobile screen.

feat(card-in-card): add gutter space on mobile

---

.github/workflows/add-to-project.yml
.github/workflows/automerge.yml
.github/workflows/check-cdn.yml
.github/workflows/ci-check.yml
.github/workflows/codeql-analysis.yml
.github/workflows/dco.yml
.github/workflows/dependabot-yarn-mirror.yml
.github/workflows/deploy-canary.yml
.github/workflows/deploy-masthead-v2.yml
.github/workflows/deploy-next.yml
.github/workflows/e2e-tests-parallel.yml
.github/workflows/percy-update-base.yml
.github/workflows/publish-alpha.yml
.github/workflows/publish-canary.yml
.github/workflows/publish-nightly.yml
.github/workflows/publish-staging.yml
.github/workflows/publish-v2alpha-cdn.yml
.github/workflows/release-preflight.yml

The ubuntu image version in github actions is being deprecated. 
This PR updates it so it uses the latest tag. 
**Changed**
- The ubuntu image version in github actions to `latest`

chore: update github actions ubuntu version to latest

---

packages/web-components/src/components/table-of-contents/table-of-contents.ts

Closes [#6635](https://jsw.ibm.com/browse/ADCMS-6635)
The table of contents changes its navigation to a horizontal scrollable tabs section in mobile. When clicking through the tabs, there are tabs that can partially exist off the visible area. When they're clicked, the page scrolls to the desired content but the tab will remain there it is, sometimes being partially off the screen.
I added a `scrollIntoView()` that will make each clicked tab to scroll to the center of the visible area, ensuring its copy is fully visible
1. In the storybook, go to the `Table of Contents > Default` component and enter mobile view.
2. Click the tabs and they need to scroll to the center of the visible area instead of not moving
https://github.com/user-attachments/assets/e6cd7cc3-3089-4d6f-a9cc-a21513fbcfc3

fix(toc): centering clicked tabs in mobile

---

packages/web-components/src/components/masthead/masthead-l1.ts

[JIRA](https://jsw.ibm.com/browse/ADCMS-7584)
This PR addresses multiple CTA highlighting in L1 components caused by anchor links pointing to sections within the page.
**Changed**
-  modifying the `_handleSelectedMenuItem`  function that sets the `active` attribute to stop propagating when the link `href` contains `#`

fix(masthead-l1): fix unwanted item highlighting

---

packages/styles/scss/components/card/_card.scss

Related Ticket(s)
[ADCMS-6623](https://jsw.ibm.com/browse/ADCMS-6623)
Description
It's difficult to see that cards are clickable rather than just having differently colored background when they display full-width. Add proper "gutter" space on the left and right sides of cards to suggest that they are clickable cards.
Changelog
A `margin-inline: $spacing-05` was added for small screen to add left and right space on the `content-group-cards` component.

feat(content-group-cards-item): add gutters for mobile

---

packages/web-components/src/components/masthead/masthead-composite.ts
packages/web-components/src/components/masthead/megamenu-category-heading.ts
packages/web-components/src/components/masthead/megamenu-heading.ts

none
In order to help the AEM team rebuild the masthead natively in AEM, I added shadow parts to the SVG icons so they can be targeted outside the shadow root and therefore styled accordingly.
New shadow parts added to the SVG icons

feat(masthead): adding shadow parts to svg arrow icons

---

packages/web-components/src/components/masthead/masthead-composite.ts

None - this is a work requested for the L0 work by Nishant and Neha
Adding a condition through an attribute to render the globe icon for the lang selector. 
By adding `has-language-selector` attribute to `c4d-masthead`, it'll display the globe icon:

fix(masthead): globe icon logic fixed to display

---

packages/web-components/src/components/masthead/masthead-composite.ts

none - this is a work for the new L0 that will live inside of AEM
Enabling the world icon and using the correct one

fix(masthead): enabling the icon and using the correct icon

---

packages/web-components/src/components/masthead/__stories__/masthead.stories.ts
packages/web-components/src/components/masthead/masthead-menu-button.ts

[Jira](https://jsw.ibm.com/browse/ADCMS-4525)
This PR hides the hamburger menu button when no L0 nav items are present
**Changed*
- Set the `hideButton` variable to `true` and display to none on the `masthead-menu-button` component when no `left-nav-menu`  components are found under `masthead-container`
- Added new story to facilitate testing

fix(masthead-menu-button): hide hamburger button when no nav menu items are present

---

packages/styles/scss/components/background-media/_background-media.scss

https://jsw.ibm.com/browse/ADCMS-6638
On mobile, the gradient overlay doesn’t appear, which makes most text illegible due to the background image.
Removed a media query that was preventing the gradient to display on mobile as well

fix(background-media): missing overlay in mobile resolutions

---

packages/styles/scss/components/pricing-table/_pricing-table.scss

https://jsw.ibm.com/browse/ADCMS-6628
The `Pricing Table` inherits its inner structure from the `Structured List component`. The latter has a built in logic to indicate mobile users that there's scrollable content to the right or to the left. 
This logic was not working due to some CSS constraints.
Added some new CSS rules to enable Overflow Hints as per Structured List component
https://github.com/user-attachments/assets/49e00d3c-0701-43d2-8d17-84adff8cd423

fix(pricing-table): enabling overflow hints in mobile

---

packages/web-components/src/components/carousel/carousel.ts

[ADCMS-6609](https://jsw.ibm.com/browse/ADCMS-6609)
The current implementation of JavaScript based touch swiping does not work consistently for left/right swipe navigation.
Increased the gesture-duration and short the distance swipe and now animation behavior is increased and better.

fix(carousel): gesture-duration-mobile

---

packages/styles/scss/components/structured-list/_structured-list.scss

https://jsw.ibm.com/browse/ADCMS-6634
Adjusting the column width in mobile so that the next column 'peeks out' from the right side of the screen, indicating there's more content to be scrolled.

feat(structured-list): column-width-mobile-6607

---

packages/styles/scss/components/masthead/_masthead-l1.scss

PR to fix l1 dropdown not appearing on IOS devices 
The component is not appearing because it has 0 width on iOS devices.
This PR forces full width on that component.

fix(masthead-l1): mobile dropdown with 0 width on iOS devices

---

packages/styles/scss/components/card-group/_card-group.scss
packages/web-components/src/components/card-group/card-group.ts

https://jsw.ibm.com/browse/ADCMS-8167
[In this ticket](https://jsw.ibm.com/browse/ADCMS-6599) we added inline gutters for the card group in mobile.
But we found out that it would only work correctly in ToC pages, since FW ones already have that gutter in mobile resulting in an ever bigger gutter. 
I added a logic that will check if `body` has the attribute of `data-fullwidthtemplate="true"` - if we're in a FW template, the gutters will not be applied
`  :not(:host(#{$c4d-prefix}-card-group.is-full-width-template)) {`
`@include breakpoint-down(md) {`
`padding-inline: $spacing-05;`
` }`

fix(card-group): incorrect mobile gutters for FW layout pages in AEM

---

packages/web-components/src/components/masthead/left-nav.ts

[Jira](https://jsw.ibm.com/browse/ADCMS-7864) 
Paleative fix for L0 navigation closing when from an iPhone, and selecting a category from the Products menu.
**New**
- Addedd overrde for the `_handleFocusOut` method comming form upstream codebase.

fix(left-nav): fix menu closing on iOS devices

---

packages/web-components/src/components/table-of-contents/table-of-contents.ts

[Jira](https://jsw.ibm.com/browse/ADCMS-6249)
PR to fix TOC pulling Widgets  fields as nav links on chrome based browsers
**Changed**
- TOC now ignores the input and select tags

fix(table-of-contents): ignore input and select tag names

---

packages/web-components/src/components/video-player/video-player.ts

[ADCMS-8313](https://jsw.ibm.com/browse/ADCMS-8313)
Adding a missing shadow-part for the video-player so the svg play icon can be styled from the AEM side.
**New**
Adding `part: 'play-video'` for the video-player component.

feat(video-player): adding player icon shadow part

---

packages/services/src/services/KalturaPlayer/KalturaPlayer.js
packages/web-components/src/components/video-player/__tests__/video-player-container.test.ts
packages/web-components/src/components/video-player/video-player-container.ts

All credits of this PR goes to @tweenn with his great help with https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/12273
https://jsw.ibm.com/browse/ADCMS-7731
Enabling the attribute `customVideoName=""` to allow the usage of custom titles overrides.
**Changed**
- Web-components / Video Player Container
- Get Player Options - Detect and extend the overriding properties used in the player container and overlay with player container
- Services / Kaltura Player
- Left a comment on a default property that IF change is planned, there should also be a lookout for the prop of same name in the above Get Player Options method

fix(video-player-container): enabling the usage of custom title override

---

packages/web-components/src/components/notice-choice/__stories__/notice-choice.stories.ts
packages/web-components/src/components/notice-choice/notice-choice.ts
packages/web-components/src/components/notice-choice/services.ts
packages/web-components/tests/snapshots/c4d-masthead-composite.md
packages/web-components/tests/snapshots/c4d-video-player.md

This section shows the specific product's legal links, terms, and conditions. Along with this, it collects users' consent regarding communication preferences.
**New**
- Notice & Choice is served annually once marketing permission is received 
**Changed**
**Removed**

Notice & Choice served annually once marketing permission is received

---

packages/styles/scss/components/video-player/_video-player.scss

Closes https://jsw.ibm.com/browse/ADCMS-7507
changing the display property in the Card in Card's parent container so that the video fills it in properly.
Before:
After:

fix(card-in-card): video to better fill parent container

---

packages/web-components/src/components/button-group/button-group.ts

[jira](https://jsw.ibm.com/browse/ADCMS-7379)
PR to remove the restrictions on the method that defines the child count on `button-group` 
The restrictions were filtering out valid components and causing the button group to misbehave.   
Before: 
(buttons on top of each other)
After:
(Buttons side by side)

fix(button-group): remove element selector restrictions

---

packages/web-components/src/components/card/card-footer.ts
packages/web-components/src/components/cta/defs.ts

https://jsw.ibm.com/browse/ADCMS-6380
Contact Module won't work if card-footer has a parent-href
this PR removes parent-href if the cta type is 'chat' or 'contact'
**New**
- New function in card-footer.ts that will remove parent-href if the cta type is 'chat' or 'contact'

fix(card): parent-href preventing CM variation from working

---

packages/web-components/src/components/notice-choice/__stories__/notice-choice.stories.ts
packages/web-components/src/components/notice-choice/notice-choice.ts
packages/web-components/src/components/notice-choice/services.ts

This section shows the specific product's legal links, terms, and conditions. Along with this, it collects users' consent regarding communication preferences.
**New**
- Notice & Choice is served annually once marketing permission is received 
**Changed**
**Removed**

Enahncement nc
